### ISSUE TITLE
How is this project different from GraphQL?

### ISSUE THREAD

**Issue by orefalo** [sinclairzx81/typebox#1]
http://graphql.org/ ?

**Comment by sinclairzx81** [comment]
Hi,

This project is more focused at being a run time type system that attempts to find parity with the TypeScript type system offering similar type checking functionality at runtime. graphQL on the other hand is a type system + query + projection library geared at letting users pick and choose the data they want over receive over REST-ful endpoints. 

More specifically, this library is geared towards structurally validating data as ```types``` and actually shares more in common with JSONSchema validation. In fact, one of the design goals of this library was to see how well the TypeScript type system could be expressed in JSONSchema v4. 

The primary motivation for this project is to offer some concise type validation for input / output messages sent and received over a network. Which may include REST-ful message exchange, however my main focus was offering operational RPC based message validation in line with technologies like SOAP / WSDL and to mirror some of the development time experience (authoring message types as classes, auto generating documentation, automatic type validation, serialization etc) of these platforms in a nodejs / typescript environment. However in C#, message contracts are derived from .NET reflection capabilities (specifically System.Type), typebox tries to emulate this.

The library itself does not contain any network related code and is intended to be "plugged in" to network libraries requiring this form of boundary validation. 

### The Problem
To give you a bit more insight, consider the following typescript code which is type checked at compile time.
```typescript
type TInput = { name: string }
type TOutput = { id: string }
const operation = (input: TInput): TOutput => { 
  return { id: "1" }
} 
```
However, when compiled, all the type information is lost.
```javascript 
const operation = function(input){
  return {id: "1" }
}
```
This is fine for most javascript (particularly if its compiled with typescript), but is undesirable at a network / io boundary where the caller might may pass anything at all over a network.

### The Solution
So typebox attempts to address this by encoding type information in JavaScript itself. The following code creates a example type safe "function" that validates its inputs and outputs based from the given typebox types where the types are used to define a function signature.
```typescript
const TypeSafeFunction = <T extends typebox.TBase<any>, U extends typebox.TBase<any>>(t: T, u: U, body: (input: typebox.Static<T>) => typebox.Static<U>): (input: typebox.Static<T>) => typebox.Static<U> => {
  return input => {
    // type check - input type.
    let check1 = typebox.check(t, input)
    if(!check1.success) throw Error("invalid input type.")
    let output = body(input)
    // type check - return type.
    let check2 = typebox.check(u, output)
    if(!check2.success)  throw Error("invalid output type.")
    return output
  }
}
```
which can now be used as...
```typescript
// unsafe
// type TInput = { name: string }
// type TOutput = { id: string }
// const operation = (input: TInput): TOutput => { 
//  return { id: "1" }
//} 

// safe
const TInput  = typebox.Object({ name: typebox.String() })
const TOutput  = typebox.Object({ id  : typebox.String() })
const operation = TypeSafeFunction (TInput, TOutput, input => {
  return {id: "1"}
})
operation({name: "dave"}) // ok
operation(1) // throws an error
```
and because the ```TInput``` and ```TOutput``` types are encoded as javascript objects, creating metadata for remote users on how to call the method is as straight forward as.
```javascript
let signature = {
   operation: "operation",
   input: TInput,
   output: TOutput
}
console.log(JSON.stringify(signature, null, 2))
```
which results in.
```json
{
  "operation": "operation",
  "input": {
    "kind": "object",
    "properties": {
      "name": {
        "kind": "string"
      }
    }
  },
  "output": {
    "kind": "object",
    "properties": {
      "id": {
        "kind": "string"
      }
    }
  }
}
```
Hope that helps.

**Comment by orefalo** [comment]
It does, you are writing a runtime type validator.

My point is: a GraphQL schema can also be used to validate user inputs. It's actually one of the main use cases.
   http://graphql.org/learn/validation/

Now it won't come out as a JSONSchemav4, and it won't have the glue to process XML/REST/andwhatnot, but GQL could help you define:

1. A type system based on a static schema (It's called the IDL format)
2. Complex types (there are custom user defined types for Date, URL, UUID, RegEx..etc)
3. Well, it comes with a bunch of tools already

Anyways, was just trying to save you the time.

Sincerely,

**Comment by sinclairzx81** [comment]
Thanks for the heads up!

Yes, I am aware of the functionality that graphQL provides and it isn't really the motivation for this project sorry (my clients don't speak IDL, and I'm not working exclusively over REST). 

I am only really interested in enabling better type introspection in JS, static type resolution (for typescript), data validation, and to allow for integration with existing services through the exchange of standards based formats (specifically JSONSchema and later XSD). In saying this, it would be possible to generate IDL from these types, so it's certainly worth thinking about!

Thanks!
