### ISSUE TITLE
Reduce unnecessary cloning in `Value.Convert`

### ISSUE THREAD

**Issue by hpeebles** [sinclairzx81/typebox#1002]
Hey!

While debugging an issue with converting union types I noticed that the input value is cloned for each subschema until a match is found. In my case the value is fairly large and there are many subschemas so this is adding a huge amount of overhead.

I've pushed a commit to my fork (https://github.com/hpeebles/typebox/commit/67968b07296fe86222f4111c70cdedc1dc85bf1e) which only clones if the input value is about to be modified which should improve performance significantly in cases like mine.

If you're happy with the idea behind this change I'd be happy to turn it into a PR and I can add tests which ensure that when calling `Value.Convert` the input value is never modified.

**Comment by sinclairzx81** [comment]
@hpeebles Hi, Thanks for taking a look into this optimization. 

Had a look through, but unfortunately; not sure I can take this one on. While I agree that the current union variant clone isn’t ideal, the benefit is that it remains localized to the union conversion logic, which is preferable. The proposed update, however, shifts the Clone logic from Union into the Object and Record conversion functions. This has the unintended effect of de-optimizing these types, as they would now undergo at least one Clone operation.

Consider the following

```typescript
const T = Type.Object({ x: Type.Number() })

// before update

const V1 = { x: '1' }

const R1 = Value.Convert(T, V1) // no clone

console.log(R1 === V1)          // true - references are the same

// after update

const V2 = { x: '1' }

const R2 = Value.Convert(T, V2) // cloned at object level

console.log(R2 === V2)          // false - references are not the same
```

---

That said, I’m definitely open to further optimizing the Convert function, but any changes should ensure that conversion logic remains self-contained within the function (i.e., avoiding external or propagated state tracking like hasBeenCloned). This helps keep the logic clean and straightforward, without introducing complex conditional branching across different conversion functions.

Unions indeed pose a unique challenge since the conversion must be tested against multiple variants. Given the mutable nature of Convert, a clone seems necessary per variant, but it might be worth exploring possible optimizations through schema introspection, which hasn’t been fully explored yet.

---

For your implementation tho, I could recommend the following:

1) Make `hasBeenCloned` a global variable (prefer this to additional argument passing)
2) Create a `value = ConditionalClone(value)` function that either returns the value (if hasBeenCloned === true) or performs a clone (if false). This function would also set hasBeenCloned to true on the first pass, thereby consolidating the cloning logic and limiting its impact on Record and Object conversions.

---

Once again, thanks for diving into this. I agree there’s room for optimization within the Value.* functions, but given the number of tweaks already made to ensure correctness, my preference is to keep the logic as simple and clear as possible. There’s also ongoing consideration for creating compiled versions of these functions, and it would be easier to approach that with straightforward, foundational logic.

Will close up this issue for now, but happy to discuss more on this thread

All the best!
S

**Comment by hpeebles** [comment]
Thanks for putting the time into that reply! And yes I completely agree with everything you said.

If I get time I think I'll have another stab at this and make sure I avoid any performance regressions while keeping everything simple.

**Comment by hpeebles** [comment]
Hey!

I've done another version which can be found here - https://github.com/hpeebles/typebox/commit/9ae49018e6eed73ab8deaad524a3524b84f95c7e

This commit replaces `hasBeenCloned` with `cloneOnWrite` which is always set to false other than in the `Union` case.

If you're happy with this approach I can turn it into a PR.
