### ISSUE TITLE
Typescript classes to typebox to ajv?

### ISSUE THREAD

**Issue by wysisoft** [sinclairzx81/typebox#1006]
I have an app that needs to have typescript classes for my entities to facilitate data transfer, I see in your workbench you have this. Good. I have some complex custom validations, and i'm not using javascript on the server side, so I need a tool that will spit out some codegen for the validations and i'll use GPT to convert from javascript to the server lang (C#). It looks like ajv is the only tool that will support this codegen with custom validations?

just want to double check.

**Comment by sinclairzx81** [comment]
@wysisoft Hiya,

> I have an app that needs to have typescript classes for my entities to facilitate data transfer, I see in your workbench you have this.

The Workbench project doesn't actually generate types from runtime constructs (like classes and functions), it only generates from TS static constructs `() => {}` and `new () => {}`  respectively. Keep in mind that both the Function and Constructor types provided by TypeBox are there to offer a semi formal way to structure RPC/IPC interfaces, but neither can be validated directly (instead you would extract Parameters and Return/Instance types and validate those on receipt of data on those interfaces)

If you are working with the Workbench / Codegen projects, I would recommend expressing types as `interface` definitions only and avoid Function and Constructor definitions. These would have the greater likelihood of being portable to C#. Also note that Intersect and Union types (Union especially) don't have good representations in C# due to differences between nominal and structural type systems. You should avoid using Union and Intersect unless you have infrastructure able to reconcile structural types under C#'s nominal type system.

> It looks like ajv is the only tool that will support this codegen with custom validations?

TypeBox supports non-compiled custom types (so you can write custom validators for custom data structures), but it doesn't support "compiled" custom types (where custom logic can be emitted as JIT evaluated code). The latter I believe Ajv has some internal infrastructure for (but I don't know all the details there)

If you are doing C# / JS interop work, cross language validation may be better achieved via Ajv + https://www.newtonsoft.com/jsonschema. You can still use TypeBox to create types JavaScript side (and generate C# structures from it (or vice versa)). As for GPT, I would probably discourage using something like GPT for code translation as the json schematics can be parsed into different structures relatively easily (and you have a lot more control doing that). 

Note that, C# Reflection is very good and can generate either Json Schema or TypeBox types from C# class definitions. In fact, if you are working through a translation layer between languages, C# reflection may prove the better "source of truth" as inherent limitations in nominal type systems (C#) may map easier onto structural type systems (where those limitations act as natural constraints preventing non-trivial mappings). Again, this mostly relates to Union and Intersection types that can't be naturally expressed in C#. You can avoid problems by just describing the DTO's in C# and generating schematics / TB types from there.

---

Will close off this issue for now, as there isn't much to action here, but if you have any other questions, feel free to ping on this thread.

Cheers
S



---

**Comment by wysisoft** [comment]
wait sorry I think the typescript -> typebox is a little incomplete, I don't see support for things like partials and unions, is there any talk of this or am I better off starting from the model?

**Comment by sinclairzx81** [comment]
> wait sorry I think the typescript -> typebox is a little incomplete, I don't see support for things like partials and unions, is there any talk of this or am I better off starting from the model?

@wysisoft If you are referring to TypeBox Codegen or Workbench projects, they do support Partial and Union structures

[Workbench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=Ly8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCi8vIEludGVyZmFjZQovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KZXhwb3J0IGludGVyZmFjZSBWZWN0b3IgewogIHg6IG51bWJlciwKICB5OiBudW1iZXIsCiAgejogbnVtYmVyCn0KLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCi8vIFBhcnRpYWwKLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCmV4cG9ydCB0eXBlIFBhcnRpYWxWZWN0b3IgPSBQYXJ0aWFsPFZlY3Rvcj4KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyBNYXBwZWQgUGFydGlhbAovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KZXhwb3J0IHR5cGUgTWFwcGVkUGFydGlhbCA9IHsKICBbSyBpbiBrZXlvZiBWZWN0b3JdPzogVmVjdG9yW0tdCn0KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyBJbnRlcnNlY3QKLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCmV4cG9ydCB0eXBlIEludGVyc2VjdCA9IFZlY3RvciAmIHsgdzogbnVtYmVyIH0KCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyBVbmlvbgovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KZXhwb3J0IHR5cGUgVW5pb24gPSBudW1iZXIgfCBzdHJpbmcgfCBib29sZWFuCgo%3D)

```typescript
// ---------------------------------------------------
// Interface
// ---------------------------------------------------
export interface Vector {
  x: number,
  y: number,
  z: number
}
// ---------------------------------------------------
// Partial
// ---------------------------------------------------
export type PartialVector = Partial<Vector>

// ---------------------------------------------------
// Mapped Partial
// ---------------------------------------------------
export type MappedPartial = {
  [K in keyof Vector]?: Vector[K]
}

// ---------------------------------------------------
// Intersect
// ---------------------------------------------------
export type Intersect = Vector & { w: number }

// ---------------------------------------------------
// Union
// ---------------------------------------------------
export type Union = number | string | boolean
```
... however they do not support is `class` or `function` JavaScript definitions. This is because `class` and `function` definitions are runtime constructs. The generators work on on static (non-JavaScript) constructs only, any type that can be expressed through the type system. If you need to represent `class` and `function` definitions, you can use the following static types.

[Workbench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=Ly8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCi8vIEZ1bmN0aW9uIChTdGF0aWMgT25seSkKLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCmV4cG9ydCB0eXBlIExvZyA9IChtZXNzYWdlOiBzdHJpbmcpID0%2BIHZvaWQKCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLyBDb25zdHJ1Y3RvciAoU3RhdGljIE9ubHkpCi8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQpleHBvcnQgdHlwZSBWZWN0b3IgPSBuZXcgKCkgPT4gewogIHg6IG51bWJlciwKICB5OiBudW1iZXIsCiAgejogbnVtYmVyLAogIGFkZChsZWZ0OiBWZWN0b3IsIHJpZ2h0OiBWZWN0b3IpOiBWZWN0b3IKICBzdWIobGVmdDogVmVjdG9yLCByaWdodDogVmVjdG9yKTogVmVjdG9yCiAgbXVsKGxlZnQ6IFZlY3RvciwgcmlnaHQ6IFZlY3Rvcik6IFZlY3RvcgogIGRvdChsZWZ0OiBWZWN0b3IsIHJpZ2h0OiBWZWN0b3IpOiBWZWN0b3IKfQoKCg%3D%3D)

```typescript
// ---------------------------------------------------
// Function (Static Only)
// ---------------------------------------------------
export type Log = (message: string) => void

// ---------------------------------------------------
// Constructor (Static Only)
// ---------------------------------------------------
export type Vector = new () => {
  x: number,
  y: number,
  z: number,
  add(left: Vector, right: Vector): Vector
  sub(left: Vector, right: Vector): Vector
  mul(left: Vector, right: Vector): Vector
  dot(left: Vector, right: Vector): Vector
}
```
I don't know specifically what you're building there, but if the goal is to leverage the CodeGen for generating cross language structures, you would implement those structures with TS `type` and `interface`, then generate the TypeBox types, then generate the C# types from the TypeBox types.

```
TypeScript -> TypeBox -> C# (Class POCO)
   |
   +--- Static Types Only
```
Bear in mind, this is only one possible way to approach things. In my experience, it's the Server Side language (C# in your case) that should be the source of truth. In this regard you would generate TypeBox types from C# Data Structures (which will be much simpler thing to manage)

```
C# (Class POCO) -> TypeBox 
```
You can achieve this using the [System.Reflection](https://learn.microsoft.com/en-us/dotnet/api/system.reflection?view=net-8.0) namespace.

Hope this helps
S

**Comment by wysisoft** [comment]
luckily I landed on my feet with the c# stuff, that's all fine. I think your project should replicate or just swallow AJV. AJV seems to have good support for custom keywords, and how custom keywords appear in codegen. Does typebox have anything similar?
