### ISSUE TITLE
When converting to union schema, skip cloning for subschemas which would never modify the input value

### ISSUE THREAD

**Issue by hpeebles** [sinclairzx81/typebox#1031]
Hey! (Again!)

In a lot of my use cases I'll have value which will either be an object or one of a few error string literals (eg. "NotAuthorized", or "NotFound", etc).

When calling `Value.Convert`, the potentially large object is cloned when checking each subschema, even if that subschema would never modify the input value, such as in the string literal cases.

I've just pushed a commit to my own branch which skips the clone step for subschemas which we know will not modify the input value. Please see [here](https://github.com/sinclairzx81/typebox/commit/22bab618e7f3ca120c698006d4a4b121e89abbb6).

Do you think this is a reasonable approach? If so I'd be happy to turn this into a PR.

**Comment by hpeebles** [comment]
I've just seen that the same "clone on each subschema" behaviour is happening within `Value.Default`, so maybe its worth moving this into some common location which can be used in both scenarios.

**Comment by hpeebles** [comment]
I guess I could always order my union type schemas such that the object subschemas are first, that way the match is found before reaching the subschemas for which cloning can be skipped.
But it still feels like this would be useful.

**Comment by sinclairzx81** [comment]
@hpeebles Hi,

The Clone function should already differentiate between Reference types (object, array) and Value types (number, string, boolean, etc). When cloning a Value type, the call to Clone is essentially a noop on FromValue that returns the value as is.

https://github.com/sinclairzx81/typebox/blob/master/src/value/clone/clone.ts#L63-L79

```typescript
function FromValue(value: ValueType): any {
  return value // noop
}
// ------------------------------------------------------------------
// Clone
// ------------------------------------------------------------------
/** Returns a clone of the given value */
export function Clone<T extends unknown>(value: T): T {
  if (IsArray(value)) return FromArray(value)
  if (IsDate(value)) return FromDate(value)
  if (IsTypedArray(value)) return FromTypedArray(value)
  if (IsMap(value)) return FromMap(value)
  if (IsSet(value)) return FromSet(value)
  if (IsObject(value)) return FromObject(value)
  if (IsValueType(value)) return FromValue(value) // value check here ...
  throw new Error('ValueClone: Unable to clone value')
}
```
This should mean that when performing a Convert and Default operations, the cost of calling Clone should only be the function call to FromValue + preceding checks. This should be faster than a Set lookup (I'd hope), but would be interesting to test.

Do you want to write a quick benchmark comparing either approach?

```typescript
console.time()
for(let i = 0; i < 100_000; i++) { // want to dial this quite high
  Value.Convert(T, ...) // with and without the Set checking
}
console.timeEnd()
```

As it stands tho, I don't think the update is something TypeBox could take on in it's current form (not too sure about the Set lookup), but if benchmarks do show better performance, I may be keen to investigate ways to bring on those optimizations in a more formal way (ideally without the Set). But to proceed would need performance testing and to weight the technical / maintenance cost.

Curious to see those benchmarks tho!
Cheers!
S

**Comment by hpeebles** [comment]
The issue in my use case is that the value I'm passing to `Value.Convert` is a large object. Then when it is converted to a union type it gets cloned for every subtype that it gets checked against, even if that subtype is a string literal or a number, etc.
So `Clone` is optimised to do nothing if the value passed in doesn't need to be cloned, but it is still cloning my large objects when checking against schema types which won't modify the input.

But I think I can work around this by always defining the large union variants first and simply not caring about the case where no match is found because that almost never happens.

**Comment by sinclairzx81** [comment]
@hpeebles Hiya,

>  Then when it is converted to a union type it gets cloned for every subtype that it gets checked against, even if that subtype is a string literal or a number, etc. So Clone is optimised to do nothing if the value passed in doesn't need to be cloned, but it is still cloning my large objects when checking against schema types which won't modify the input.

Hmmm, Union has proven challenging to get right. The Convert function was written to be a mutable conversion which would mutate the value passed (which was nice and fast as there was no cloning required), except problems occurred when dealing with unions, as mutation on each variant would overlap on top of the value. Multiple variants would Convert multiple times, leading to really unpredictable results.

The solution was simply to Clone in the Union case (meaning mutations affected the Clone not some shared mutable value). This problem was recently raised on the following issue (related to Default)

https://github.com/sinclairzx81/typebox/issues/993

with subsequent PR submitted here

https://github.com/sinclairzx81/typebox/pull/994

The rules are the same in Default and Convert cases where the mutability optimizations implemented for these functions do not naturally extend to Union (where the value could be one of many possible permutations of each variant). Because of this, I believe Clone is a requirement on a per variant basis to provide a safe and predictable result for these functions (at least I haven't found a better algorithm that would avoid the Clone. I'm yet to find an algorithm as optimal as just Clone (noting algorithms to handle Union differentiation have a cost also)

As it stands, I think the NOOP pass through for value types is reasonable, but there is a definite cost managing Object types inside Unions, as the Clone has proven difficult (if not impossible) to avoid. This said, I'm genuinely ok with the current performance / algorithms, but if there is options for going faster I am certainly happy to explore those, but any algorithm would need factor all possible structures while retaining separation of concern rules already present in the library (keeping Default, Convert, Clean, Transform functions independent). 

I might close up this issue for now as it sounds like you have a workaround for your case. But certainly happy to discuss more  if you have any thoughts on improving TypeBox Union algorithms. 

Cheers!
S
