### ISSUE TITLE
Type.Optional() with Type.Union() and Type.Undefined() breaks validations

### ISSUE THREAD

**Issue by raissarcl** [sinclairzx81/typebox#1032]
I came across this problem with the validations when trying to create some schemas with these types together while using Fastify and passing it to the routes. When you use **Optional** with an **Union** that includes the **Undefined** type, for example:

```
export const ExempleSchema= Type.Object({
  type: Type.Optional(Type.Union([Type.Number(), Type.Null(), Type.Undefined()])),
});


  fastify.post(
    "/test",
    {
      preHandler: [fastify.authenticate],
      schema: {
        body: ExempleSchema,
      },
    },
    ExampleController.test,
  );

```

I know it's redundant to type with both the Optional and Undefined types, but probably it shouldn't break the validations, every API call would return with either a 500 or 502 HTTP code, unless I removed the Type.Undefined(). Also, just to point out the TypeScript types with:

` const TypeTest = Static<typeof ExempleSchema>`

It creates the type normally.

**Comment by sinclairzx81** [comment]
@raissarcl Hi,

Unfortunately, Undefined() is part of an extended JavaScript type set (along with Function, Constructor, Symbol, Void, etc) whose types extend beyond that of Json Schema. Because the types are non-standard, you won't be able to use them with Fastify as it only supports Json Schema compatible types (via Ajv + fast-json-stringify) 

Information on Undefined and other JavaScript types are documented here:

https://github.com/sinclairzx81/typebox#types-javascript

---

When working with Fastify, it's best to limit types to those prefixed with `[Json]` doc comments. This means avoiding the use of Undefined() in your type definitions. While it is possible to work around this by overriding Fastify's Ajv implementation (via fastify.setValidationCompiler(...)) and using TypeBox's TypeCompiler (which supports a broader type set), it's probably not worth it in this case as Fastify primarily handles JSON payloads, and `undefined` cannot be represented in JSON (so you would never receive an `undefined` value)

Hope this helps
S

**Comment by raissarcl** [comment]
Thank you! I couldn't really find an answer for it while searching, but now it makes sense to be the framework's way of handling it.
