### ISSUE TITLE
`Value.Parse` fails for unions which require defaults and conversions

### ISSUE THREAD

**Issue by hpeebles** [sinclairzx81/typebox#1033]
Hey! Sorry to hassle you again!

I've just run into an issue where `Value.Parse` throws even though the input is valid.

The issue is that within `Value.Default`, for a union, it only returns the value with the defaults added if the `Check` step passes, but in my case the check would only pass after the `Convert` step, so the default fields do not get added, which in turn causes the `Check` after the `Convert` to also fail.

It seems like the default values need to be added within the `Convert` step, so that when looping over each union subtype, the defaults are added, then the conversion takes place, and only then does the check happen.

Minimal failing test:

```
it('Should Convert union which requires defaults and conversions', () => {
    const T = Type.Union([
      Type.Object({
        big: Type.BigInt(),
        optional: Type.Number({ default: 0 }),
      }),
      Type.Number()
    ])
    const X = Value.Parse(T, {
      big: "12345678901234567890",
    })
    Assert.IsEqual(X, { big: BigInt("12345678901234567890"), optional: 0 })
  })
```

If the `optional` field is added to the input then the test passes.

**Comment by hpeebles** [comment]
This fixes my use case -

`src/value/convert/convert.ts`
```
function FromObject(schema: TObject, references: TSchema[], value: any): unknown {
  if(!IsObject(value)) return value
  for(const propertyKey of Object.getOwnPropertyNames(schema.properties)) {
    const propertySchema = schema.properties[propertyKey];
    if(!HasPropertyKey(value, propertyKey)) {
      if (!HasPropertyKey(propertySchema, 'default')) {
        continue
      }
      const defaultValue = propertySchema.default;
      const clone = IsFunction(defaultValue) ? defaultValue() : Clone(defaultValue);
      (value as any)[propertyKey] = Visit(propertySchema, references, clone)
    } else {
      value[propertyKey] = Visit(propertySchema, references, value[propertyKey])
    }
  }
  return value
}
```

But this only applies the defaults for objects, so I don't think this is production ready code, I just wanted to check that this would make my failing case pass.

**Comment by sinclairzx81** [comment]
@hpeebles Hiya,

The problem here is due to ambiguities with the mismatched type on Union (where preceding Union ops (Default, Clean) are checking the validity of the String against the expected BigInt and discarding them when finding the String value). It's very difficult to implicitly reconcile this case on Unions internally, but you can explicitly work around this issue with Transforms.

```typescript
// Explicit handling conversions from String to BigInt
const StringBigInt = Type.Transform(Type.String())
  .Decode(value => BigInt(value))
  .Encode(value => value.toString())

const T = Type.Union([
  Type.Object({
    big: StringBigInt,
    optional: Type.Number({ default: 0 }),
  }), 
  Type.Number()
])

const R = Value.Default(T, { big: "12345678901234567890" })
//
// { big: '12345678901234567890', optional: 0 }
```
This works is because the `big` property is checked as a String value through all the Parse ops (so will pass all Union checks), with the Transform converting the String value into a BigInt as the last operation in Parse. Additionally, you can make the above safer by specifying pattern rules for the Transform.

```typescript
// Explicit handling conversions from String to BigInt
const StringBigInt = Type.Transform(Type.String({
  pattern: '^[1-9]\\d*$', // Ensure string matches a bigint
  default: '4321'         // Defaults supported here
}))
  .Decode(value => BigInt(value))
  .Encode(value => value.toString())

const T = Type.Union([
  Type.Object({
    big: StringBigInt,
    optional: Type.Number({ default: 0 }),
  }), 
  Type.Number()
])

const R = Value.Parse(T, { big: "123456789012345678901234567890" })

// { big: '123456789012345678901234567890', optional: 0 }
```
---

So the above should work, but partially agree it's not ideal (as a conversion from String to BigInt) should be possible here. The issue is fundamentally related to Union differentiation; but given the ambiguities that can arise from mismatched types, I don't believe there is a ideal solution to reconcile for these cases.

With respect to the workaround, I am somewhat reluctant to mix and match different Value operations together (for example having Convert access Default properties or vice versa) and had actually been hesitant to include Check in union differentiation. Another solution may be to run the Convert operation before the other operations, but get a sense this could open up the flood gates for a litany of other order dependent issues, so not keen to explore that (at least not at this time).

For the now, the Transform types should solve the problem in a moderately reasonable way.

Let me know if this helps
Cheers
S

**Comment by sinclairzx81** [comment]
@hpeebles Hi!

Hey, might close off this issue for now as I think the restructured code for `StringBigInt` should be a reasonable workaround. Feel free to ping on this thread if you had any follow up thoughts / comments tho. 

Cheers!
S
