### ISSUE TITLE
Types with default values are not seen properly using "Static"

### ISSUE THREAD

**Issue by Youssef93** [sinclairzx81/typebox#1035]
The simplest way for me to explain it is with an example

```
export const UserSchema = Type.Object({
  name: Type.String({
    description: 'name description',
  }),
  value1: Type.Optional(Type.Number({ default: 10 })),
  value2: Type.Optional(Type.Number()),
});

export type UserType = Static<typeof UserSchema>;
```
On the `UserType`, we should expect the output to be

```
name: string;
value1: number; // because it has a default, it will never be undefined
value2?: number;
```
`value1` should not have the `?` identified (aka should not be undefined) because it has a default value. But the compiler always shows `value1` as `value1?: number`

I tried adding `TypeSystemPolicy.ExactOptionalPropertyTypes = true;` but did not make any difference

**Comment by sinclairzx81** [comment]
@Youssef93 Hiya,

In TypeBox, the `default` annotation doesn't contribute to an inference result at all (via. Static). The reason for this is because the annotation may be treated as optional metadata in Json Schema validators, and as a result; some validators may not generate a value if the annotation is present. Because there is no way to know in advance how a validator will process a value, TypeBox cannot reasonably derive inference from the annotation.

As per documentation for `default`

https://json-schema.org/understanding-json-schema/reference/annotations

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn't required.

With the two main aspects being "This value is not used to fill in missing values during the validation process" and "The value of default should validate against the schema in which it resides, but that isn't required.".

---

As a general rule, TypeBox ignores keywords in schematics that:

- Are up for interpretation across different validators (the default annotation is one such case of this)
- Not representable in the TypeScript type system (TypeScript doesn't have a way to describe a default value)

Inference is primarily derived from required known schematics which are strictly defined, these are documented at the links below:

https://github.com/sinclairzx81/typebox#types-json

https://github.com/sinclairzx81/typebox#javascript-types

Hope this brings some insight. Will close up this issue for now as things are working as per design, but happy to field any additional questions on this thread.

Cheers!
S

**Comment by Youssef93** [comment]
For those who could stumble upon this thread, I created a workaround.

```
/**
 * Utility function to mark multiple attributes as required in a TypeBox schema.
 *
 * @param schema - The original schema to modify.
 * @param requiredKeys - An array of keys to mark as non-optional.
 * @returns - A new intersected schema with the selected attributes required.
 */
// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function setDefaultsOnStaticSchema<S extends TObject<TProperties>, K extends keyof S['properties'] & string>(
  schema: S,
  requiredKeys: K[],
) {
  // Omit the keys from the original schema
  const omittedSchema = Type.Omit(schema, requiredKeys);

  // Create a new object schema with all the required keys
  const requiredSchema = Type.Required(
    Type.Object(
      requiredKeys.reduce(
        (acc, key) => {
          acc[key] = schema.properties[key];
          return acc;
        },
        {} as Pick<S['properties'], K>,
      ),
    ),
  );

  // Return the intersected schema
  return Type.Intersect([omittedSchema, requiredSchema]);
}
```

Then your schema / types would be

```
export const UserSchema = Type.Object({
  name: Type.String({
    description: 'name description',
  }),
  email: Type.Optional(Type.String({ format: 'email' })),
  age: Type.Optional(Type.Number({ default: 10 })),
});

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const type = setDefaultsOnStaticSchema(UserSchema, ['age']);

export type UserType = Static<typeof type>;
```

Now `UserType` has `age` as a required attribute but the validator does not require it.
