### ISSUE TITLE
The inferred type of '' cannot be named without a reference to

### ISSUE THREAD

**Issue by Lilja** [sinclairzx81/typebox#104]
Hello! I'm trying out `typebox` with project references in typescript.

In `A` I'm defining 
```typescript
export const row = Type.Object({
    id: Type.String(),
    event: Type.String(),
    condition: valueType,
    value: Type.Number(),
    action: actionType,
    campaignId: Type.Array(Type.Number()),
    allCampaigns: Type.Boolean(),
    within: withinType,
})
export type Row = Static<typeof row>
```

And then in `B` which uses a project reference to `A`, i'm defining a row converter(related to firestore document storage):
```typescript
import * as fbAdmin from "firebase-admin";
import {
    Row,
} from "../../A/src/types"

export const RowConverter = {
    toFirestore: (data: Row) => data,
    fromFirestore: (
        snap: FirebaseFirestore.QueryDocumentSnapshot,
    ): Row => {
        return snap.data() as Row
    }
}
```

And i'm facing this error: 
```
src/converters.ts(9,14): error TS2742: The inferred type of 'RowConverter' cannot be named without a reference to '../../A/node_modules/@sinclair/typebox/typebox'. This is likely not portable. A type annotation is necessary.
```

Do you have an idea on how to proceed with this?

**Comment by sinclairzx81** [comment]
@Lilja Hi. I don't really use composite projects, so I'm not really the best person to ask about this. However, as far as I know, composite projects do treat each project as individual distinct packages. Based on this, you could try the following.

- Ensure TypeBox is npm installed on project `B`, 
- Ensure the variable `row` is exported from project `A`. 

Note that Project B will need both TypeBox installed and the declaration of the variable `row` in order to infer the type. If you only export the type `Row`, Project B can't infer it without know what `row` is. 

Outside of this, I provide much more assistance I'm afraid (this is very much a TypeScript / project configuration issue). If you're interested tho. Have a look at projects like [Nx](https://nx.dev/) or if you're brave, you could try [Hammer](https://github.com/sinclairzx81/hammer) which is something I wrote to handle cross linking dependencies. Both projects iron out some of the complexity around cross linking packages.

Hope that helps
S

**Comment by Lilja** [comment]
Thank you! I'll check out your examples and figure it out.
