### ISSUE TITLE
AOT TypeCompiler - Code does not return Errors function

### ISSUE THREAD

**Issue by peterlundberg** [sinclairzx81/typebox#1045]
In a recent project I could not use TypeBoxes validation in the front end web app due to CSP rules not allowing `unsafe-eval'`. To work around this I followed [TypeCompile docs](https://github.com/sinclairzx81/typebox?tab=readme-ov-file#typecompiler) and added a build step in our workspace to generate the validator as code instead. 

Note that even with language: 'typescript' I had to tweek the output to get something existing typescript code could import easily. That is fine but perhaps this issue and other docs could help others getting this to work.

```typescript
const analyticSchemaValidatorCode =
  '/* eslint-disable @typescript-eslint/ban-ts-comment */\n' +
  '/* eslint-disable @typescript-eslint/no-explicit-any */\n' +
  '// @ts-nocheck\n\n' +
  '// This code is generated from generate-typecheck.ts\n\n' +
  TypeCompiler.Code(AnalyticalViewConfigSchema, {
    language: 'typescript',
  }).replace('return function check', 'export default function check');
fs.writeFileSync(checkTargetFile, analyticSchemaValidatorCode);
```

However, the biggest problem is that I did not get the diagnostic errors for when check fails. Seams that `.Compile` and `.Code` are not functionally equivalent? Is there some way to get the `.Errors` functionality from AOT code that I have missed?

**Comment by sinclairzx81** [comment]
@peterlundberg Hi,

The AOT options for TypeBox are currently limited to Check functionality only. For errors, these are obtained via calls to `Value.Errors()` which uses dynamic property checking which are not compiled. The Errors() function is shared between TypeCompiler and Value.* operations.

### Content-Security

The recommendation for Content Security restricted environments is to simply use `Value.*` functions instead of the compiler. These functions are simpler to use, and do not require `eval` to work. They do however come at a performance cost, but are perfectly adequate for most browser level workloads.

### Experimental

If you do need high performance checking browser side while operating in a eval restricted context, you can try the following. This approach uses the compiler to generate Check code, which is then loaded via dynamic ESM import to a generated ObjectURL (avoiding explicit calls to `eval`). This approach works in Deno, it may also work in Browser environments that are behind content security restriction (but it would need testing)

```typescript
import { TypeCompiler, TypeCheck } from 'npm:@sinclair/typebox/compiler'
import { TSchema, Type } from 'npm:@sinclair/typebox'

/** 
 * Experimental workaround for content security restricted environments. Should work
 * in Deno and Browser environments. Other enviroments such as Node, Bun, Cloudflare
 * may have issues imported from instance ObjectURL.
 */
async function DynamicCompile<T extends TSchema>(schema: T, references: TSchema[] = []): Promise<TypeCheck<T>> {
  const code = `export default function() { ${TypeCompiler.Code(T)} }`
  const blob = new Blob([code])
  const url = URL.createObjectURL(blob)
  const mod = await import(url)
  const check = mod.default()
  URL.revokeObjectURL(url)
  return new TypeCheck(schema, references, check, code)
}

// ------------------------------------------------------------------
// Usage
// ------------------------------------------------------------------

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number(),
})

const C = await DynamicCompile(T)       // Compile

const R = C.Check({ x: 1, y: 2, z: 3 }) // true

const E = [...C.Errors({ x: 1 })]       // [...errors]
```

---

You can try the above, but overall the recommendation is simply to use Value.* operations when working in content security restricted environments.

Hope this helps
S

**Comment by peterlundberg** [comment]
It does, thank you.

Will go the Value route then. As you said in the browser it is rarely a
performance issue, just fiddely to use the right constuct in the right
environment.

The suggested workaround will probably get shut down by browsers sooner or
later as is still in effect dynamic eval. And for true high perf situations
the diagnostics errors are not that critical.

**Comment by sinclairzx81** [comment]
@peterlundberg Alright cool. Will close off this issue for now. 

Cheers!
S
