### ISSUE TITLE
How to solve circular dependencies?

### ISSUE THREAD

**Issue by nik-lampe** [sinclairzx81/typebox#106]
Hello,

I have some troubles with using circular dependencies in my types.

Let's say I have these two types: User and CourseInstance. A User has a Ref to CourseInstance and the CourseInstance has an array of Refs to User.

User.ts:
```
import { Static, Type } from '@sinclair/typebox'
import { CourseInstance } from './courseInstance'

const { Ref } = Type

export const User = Type.Object(
  {
    id: Type.Number(),
    uid: Type.String(),

    courseInstance: Type.Optional(Ref(CourseInstance)),

  },
  { $id: 'User' }
)

export type UserType = Static<typeof User>
```

CourseInstance.ts:
```
import { Static, Type } from '@sinclair/typebox'
import { User } from './user'

const { Ref } = Type

export const CourseInstance = Type.Object(
  {
    id: Type.Number(),
    uid: Type.String(),

    name: Type.String(),
    users: Type.Optional(Type.Array(Ref(User))),
    assets: Type.Optional(Type.Array(Ref(Asset))),
  },
  {
    $id: 'CourseInstance',
  }
)

export type CourseInstanceType = Static<typeof CourseInstance>
```

Compiling it with tsc does work, but running the compiled code does not. It throws 
`TypeError: Cannot read property '$id' of undefined`
Just like in #103 

Also I wanted to use ts-eager in development (which I prefer, because it's faster than ts-node by building it with esbuild as far as possible and only relying on ts-node where necessary) .
But this complains about 
`ReferenceError: Cannot access 'CourseInstance' before initialization`

I'm not sure if I messed up my tsconfig, or if I should try to avoid the dependency cycle. 

Here is my tsconfig:
```{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es2019",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "@custom/*": ["./src/*"]
    },
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true
  },
  "lib": ["esnext.asynciterable", "es2019"],
  "include": ["./src/**/*"]
}
```

Typescript Version: 4.4.3
Typebox Version: 0.20.5

**Comment by sinclairzx81** [comment]
@nik-lampe Hi. Creating recursive (or cyclic) schemas is possible in TypeBox, but with some caveats. Your mileage will vary depending on the capabilities of the validator (for example AJV currently has problems with multiple recursive schemas, which you can read it bit about here (https://github.com/ajv-validator/ajv/issues/1709)). 

This said, you can express your type with a combination generics and `Type.Rec(...)`. As follows..

```typescript
export const Asset = Type.Object({})

function CourseInstance<T extends TSchema>(item: T) {
    return Type.Object({
        id:     Type.Number(),
        users:  Type.Optional(Type.Array(item)),
        assets: Type.Optional(Type.Array(Asset)),
    })
}

// We define User as a Top level recursive Schema. We pass `Self` to the
// `CourseInstance(...)` type as a generic argument.
export const User = Type.Rec(Self => Type.Object({
    id:       Type.Number(),
    instance: Type.Optional(CourseInstance(Self))
}))
```
Which produces the following schema.
```
{
  "$ref": "#/definitions/self",
  "definitions": {
    "self": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "instance": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number"
            },
            "users": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/self"
              }
            },
            "assets": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "required": [
            "id"
          ]
        }
      },
      "required": [
        "id"
      ]
    }
  }
}
```
Have tested this in AJV `8.6.2`. Note that `Type.Rec(...)` is currently marked as `EXPERIMENTAL`, but I don't expect this signature to change. Also note that the inferred type for `Self` is currently `TAny`. 

As for `TypeError: Cannot read property '$id' of undefined`, would need to see the full schema. In #103, the problem was related to the bundler and not specifically TypeBox. I reference, I currently use https://github.com/sinclairzx81/hammer for bundling (which uses `esbuild` under the hood), and haven't experienced this problem. Have a go following the same series of suggested steps in #103 and see if you can replicate the same issue.

Hope that helps.
S

**Comment by sinclairzx81** [comment]
Will close off this issue. Feel free to reply if you run into any issues using the Type.Rec() type, or have general questions on this type.

Cheers
S
