### ISSUE TITLE
Default factory

### ISSUE THREAD

**Issue by orimay** [sinclairzx81/typebox#1100]
Some values may need a random default or current timestamp or something. Currently, even if I specify something like this:
```ts
export function schemaPlainDateTime(options?: StringOptions) {
  return Type.Transform(Type.String(options))
    .Decode(encoded => Temporal.PlainDateTime.from(encoded))
    .Encode(decoded => decoded.toJSON().slice(0, 19));
}

export function schemaPlainDateTimeDefaultNow() {
  return schemaPlainDateTime({
    get default() {
      // only called once :c
      return Temporal.Now.plainDateTimeISO().toJSON().slice(0, 19);
    },
  });
}
```

It only calls `default` once, and doesn't call it every time a new priority needs a default. Would've been awesome if we could have it.

Or, even better, it would've been super awesome if we had a separate `factory` option with proper `this` type so that the default value could rely on another existing property values

**Comment by sinclairzx81** [comment]
@orimay Hi,

It is currently not documented, but you can use set `default` to be a function. This will cause TypeBox to invoke the function to resolve a value on Create, and Default. The following shows usage (unfortunately my environment does have the Temporal API available, so I have used Date)


```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const NumericDateBase = Type.Number({
  // use a function to defer initialization of default value
  default: () => Date.now()
})
const NumericDate = Type.Transform(NumericDateBase)
  .Decode(value => new Date(value))
  .Encode(value => value.getTime())

setInterval(() => {
  console.log('----')
  console.log('created', Value.Create(NumericDate))
  console.log('default', Value.Default(NumericDate, undefined))
  console.log('decoded', Value.Decode(NumericDate, Value.Create(NumericDate)))
  console.log('encoded', Value.Encode(NumericDate, Value.Decode(NumericDate, Value.Create(NumericDate))))
}, 1000)
```

---

Just keep in mind, this functionality may be updated in future revisions. The reason is because applying functions to schematics means the `default` annotation is will lost on serialization (because functions do not serialize) and where non-serializable values applied to established Json Schema keywords is something TypeBox tries to avoid. 

In future, this functionality may be updated to use a special case `Default` schematic which would contain both function and serializable information about the default value being computed "IF" the value passed is a function.

```typescript
import { Default } from '@sinclair/typebox'

const NumericDateBase = Type.Number({
  // Future: Wrap Computed Defaults 
  default: Default(() => Date.now())
})
```

For now, the above functionality should be fine to use, just be mindful of the considerations being given applying functions to `default`, and for a possible future requirement to need to wrap the callback in future revisions.

Hope this helps
S

**Comment by orimay** [comment]
Amazing, thank you so much! Is there any chance it will be possible to calculate a value based on `this`? Or should we use Transform instead for such cases?

**Comment by sinclairzx81** [comment]
@orimay Hi,

> Amazing, thank you so much! Is there any chance it will be possible to calculate a value based on this? Or should we use Transform instead for such cases?

It won't be possible to provide a `this` context for value initialization on `default` (as value initialization is specific to Create which does not receive an existing / incoming value), so Transforms are probably the way to go.

If you need specific handling of Defaults / Transforms, you may need to create a Value / Parse Pipeline depending on your use case. It is possible to call a series of Value.* functions in sequence to achieve this. See the following URL for how you might approach structuring a pipeline (where the following is TypeBox's default Parse pipeline)

https://github.com/sinclairzx81/typebox/blob/master/src/value/parse/parse.ts#L41-L57

Will close up this issue for now as there should be enough infrastructure in TypeBox to achieve what you need. But if you have any follow on questions, feel free to ping on this thread.

All the best!
S
