### ISSUE TITLE
TypeScript typing error when using `@hookform/resolvers` typeboxResolver and typebox schema

### ISSUE THREAD

**Issue by char8x** [sinclairzx81/typebox#1129]
## Example

```tsx
import { useForm } from "react-hook-form";
import { typeboxResolver } from "@hookform/resolvers/typebox";
import { Type } from "@sinclair/typebox";

const schema = Type.Object({
  username: Type.String({ minLength: 1 }),
  password: Type.String({ minLength: 1 }),
});

const App = () => {
  const { register, handleSubmit } = useForm({
    resolver: typeboxResolver(schema),
  });

  return (
    <form onSubmit={handleSubmit((d) => console.log(d))}>
      <input {...register("username")} />
      <input type="password" {...register("password")} />
      <input type="submit" />
    </form>
  );
};
export default App;
```

## Typing Error

<img width="1241" alt="图片" src="https://github.com/user-attachments/assets/544d1d64-c2aa-4b69-9ca0-8798d170bdd2" />

```md
Argument of type 'TObject<{ username: TString; password: TString; }>' is not assignable to parameter of type 'TObject<TProperties> | TypeCheck<TObject<TProperties>>'.
  Type 'TObject<{ username: TString; password: TString; }>' is missing the following properties from type 'TypeCheck<TObject<TProperties>>': schema, references, checkFunc, code, and 3 more.ts(2345)
```

## Env

@sinclair/typebox 0.28 ~ 0.34
typescript 5.6.3
@hookform/resolvers 3.9.1
react-hook-form 7.54.2
react 18.3.1
next 14.2.20

## Temporary Workaround

fallback to `@sinclair/typebox@0.27.8` or comment with `@ts-ignore`

## Extra Question

What has changed since version 0.28 and why are people still using the old 0.27 version?

<img width="1183" alt="图片" src="https://github.com/user-attachments/assets/aa847191-28d4-47dc-b70c-c2ccba83f1d5" />

**Comment by sinclairzx81** [comment]
@char8x Hi,

Unfortunately, I am not a @hookform/resolvers developer so I can't provide much information regarding TypeBox usage with this library. Judging by the compiler output, it does looks like a version disparity to me. I guess the first thing I would  try is to ensure multiple versions are not installed (as this is generally not supported by TypeBox). You may need to match the version used by hookform tho.

I see that hookform configures TypeBox as a peer dependency for version 0.25.24 (which is quite old). You may be able to update to latest. But if not, it might be worth pinging hookform contributors to support dependency ranges as per other projects.

https://github.com/fastify/fastify-type-provider-typebox/blob/main/package.json#L20-L22

```json
  "peerDependencies": {
    "@sinclair/typebox": ">=0.26 <=0.34"
  },
```

---

> What has changed since version 0.28 and why are people still using the old 0.27 version?

TypeBox keeps a revision log at the following URL where I try to document updates and design rationales. See link.

https://github.com/sinclairzx81/typebox/tree/master/changelog

The reason TypeBox sees significant downloads of 0.27.x  is that version was used by the Jest test runner for a number of months. They've since upgraded to [0.33.x](https://github.com/jestjs/jest/blob/main/packages/jest-schemas/package.json#L22) but expect there is a long tail of applications still running nightly CI tasks (and downloads counts typically trail version releases by several months or more).

In terms of changes, 0.27.x should still largely be compatible with 0.34.x, but there has obviously been a lot more added to TypeBox since 0.27.x (as well as general bug fixes). If you only need a simple type builder + validation, 0.27.x (or 0.25.x) should be fine (but would recommend getting on the latest version if you can)

Hope this helps
S

**Comment by char8x** [comment]
@sinclairzx81 Thank you very much for your patient and detailed answer. 

After further investigation, I found  that I installed `prettier-eslint@16.3.0`, the dependency tree of `prettier-eslint` is as follows:

```md
prettier-eslint@16.3.0
    |--- pretty-format@29.7.0
            |--- '@jest/schemas': 29.6.3
                    |--- '@sinclair/typebox': 0.27.8
```

If I install another version of `@sinclair/typebox`(<0.27.8  ||  >0.27.8), it will cause `version disparity`, so TypeScript will have a typing error. If I specify `@sinclair/typebox@0.27.8` the error will disappear.

So the correct way to use `@sinclair/typebox` is to declare a version range in `peerDependencies`, such as `"@sinclair/typebox": ">=0.26 <=0.34"` instead of a specific version, just like [fastify/fastify-type-provider-typebox@main/package.json#L20-L22](https://github.com/fastify/fastify-type-provider-typebox/blob/main/package.json#L20-L22) did.

**Comment by sinclairzx81** [comment]
@char8x Hiya

> So the correct way to use @sinclair/typebox is to declare a version range in peerDependencies, such as "@sinclair/typebox": ">=0.26 <=0.34" instead of a specific version, just like [fastify/fastify-type-provider-typebox@main/package.json#L20-L22](https://github.com/fastify/fastify-type-provider-typebox/blob/main/package.json#L20-L22) did.

Ah cool :) It sounds like you found a solution here so will close off this issue for now. 

To be honest, I think the jury is still out on best way to handle cross referenced TypeBox dependencies, so I really should spend some time documenting guidelines for how to resolve  cases like this. Unfortunately I don't have much control over how downstream libraries consume TypeBox revisions, but the peerDependency approach used by Fastify seems to be best approach found thus far. I will give this some thought for future documentation.

Closing up for now, but if you any follow on questions, feel free to ping on this thread.
All the best!
S
