### ISSUE TITLE
Feature request: Type.StrictObject

### ISSUE THREAD

**Issue by leoyli-headsup** [sinclairzx81/typebox#114]
Hi, thank you for creating such useful library.

Based on JSONSchema spec ([ref](http://json-schema.org/understanding-json-schema/reference/object.html#additional-properties))

> The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword or match any of the regular expressions in the patternProperties keyword. By default any additional properties are allowed.

This behavior is not safe, I'd like my validator to fail the validation when additional props were provided but I feel it is tedious to write `{additionalProperty: false }` every single time. So I'm proposing to add a helper called `Type.StrictObject` for defining `Object` type with `additionalProperty: false` to strictly check objects.

I'm not sure if it is sounding though, as I can also wrap this library and repackage to my code.

**Comment by sinclairzx81** [comment]
@leoyli-headsup Hi, thanks for the suggestion. 

I do actually agree that under most circumstances, users would probably want `additionalProperties: false` as a default, however because TypeBox tries to align closely to JSON schema (being effectively a thin layer above it), it was decided that users should opt in to this constraint in the same way users would have to if editing JSON schema directly.

The decision to omit `additionalProperties: false` was largely informed by a lengthy discussion with one of the core JSON schema contributors; with the discussion itself focusing primarily on JSON schema architecture, schema composition and how constraints (such as `additionalProperties`) implicate schema composition. The takeaway from the discussion was that JSON schema constraints "should be additive only, never subtractive"; and that TypeBox would need to subtract constraints just to enable composite schemas (specifically intersection types through `allOf` and `unevaluatedProperties`). This would lead to significant complexity in TypeBox trying to reconcile constraints for composed schemas, with this complexity a direct result of violating the "additive constraints only" design principles in JSON schema.

The topic is a little complicated, but you can read those discussions [here](https://github.com/json-schema-org/json-schema-spec/issues/1087)

This said, omitting `additionalProperties: false` actually works closer to TypeScript than it might first appear. Consider the following examples where default TypeBox object schemas analog polymorphic assignment. Link [here](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRycAXMiAK4C2ARtADQHHK3lV2PPELs31QCAXwIEYlEAjDB0IZJADOYABQxM5DOgCUOZCPwEEspcgAmcMHGQBeXWWQBGBq3IAmZ72QBmZ6fIAWPRIFZCMQJW4WKOiYlgB6OOIAPRJTU2BpWTgAGwAFKHQAB2hpCAVRA3xFFXNLHQTkdABrZABaCllWsKUoSilgADcUdsL0bIBPanQoQoALYAQK6uVsEnInF2R3UPIfMwC9esT4YGzybrBe-tlkHoWwJbKVVfsNti2PXd8DoWC0TCOjSa5FGEymM3mCGQxSg1GACgUgwgQA)

```typescript
interface Foo {
    a: number,
    b: number,
    c: number
}

function test(foo: Foo) { }

const data = { a: 1, b: 2, c: 3, d: 4 } as const
                            //   ^ additionalProperties


test(data) // ok - non-constructive - polymorphic

test({ a: 1, b: 2, c: 3, d: 4 }) // fail: construction strict

test({ a: 1, b: 2, c: 3, d: 4 } as Foo) // ok: polymorphic permissive
```

Due to the above reasons, I don't think I can add a `Type.StrictObject(...)` function to TypeBox, mostly because it breaks composition which would require significant complexity to fix it. However, as you said, you can add this function yourself if you don't need such composition. The following creates a complete `StrictObject()` type using TypeBox generics.

```typescript
import { Type, Static, TProperties, ObjectKind, TObject, CustomOptions } from '@sinclair/typebox'

function StrictObject<T extends TProperties>(properties: T, options: CustomOptions = {}): TObject<T> {
    return { ...options, kind: ObjectKind, type: 'object', properties, additionalProperties: false }
}

const T = StrictObject({
    a: Type.Number(),
    b: Type.String(),
    c: Type.Boolean()
})

type T = Static<typeof T>
```
Anyway, hope this lends a bit of insight into some of the design considerations around `additionalProperties`
Cheers
S

**Comment by leoyli-headsup** [comment]
Yeah, that make sense. Thank you for the reference!

**Comment by truemoroz** [comment]
And now CustomOptions and ObjectKind are not exported from typebox. It'll be good to have StrictObject in this lib.

**Comment by sinclairzx81** [comment]
@truemoroz Hi, TypeBox has since standardized on `additionalProperties: false` for strict object assertion. This keeps the library just a thin layer above JSON Schema and avoids unintended constraints being applied to types.

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
}, { additionalProperties: false })
```
However it is possible to construct the `StrictObject` type a number of ways. The following is maybe the most straight forward.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjgPIBGAVhiTOWMRAHYDOOyVt9nAClAiZYwDGzgBfOADNBIOAHIAAm2AsSAGwLAoAehjoMlCAA8FAWABQVjCciwZAV3XMWeGFFIMadGAB5kOFsYDBYAE3FkASEMETEAPgAKMEFhYjEALhQcIVc2LO5fRjy4AF5ECQBKLK4fegD4xCs4OCgMGEcoNzRMADpC+mTU2PSORDheydzgVjGCMLDgVwINaLTRfJkVtgxJSqsJKysSWfhA8vxPegGYRIRmuBMaw16AOUcQSljEyqwH1GefXen2+vweAC9ARg3h8vlAfgd9tZLAZMCgyu4iKQ-KiMBBpCh4lYgA)
```typescript
import { Type, Static, ObjectOptions, TObject, TProperties } from '@sinclair/typebox'

export function StrictObject<T extends TProperties>(properties: T, options: ObjectOptions = {}): TObject<T> {
  return Type.Object(properties, { ...options, additionalProperties: false })
}

const T = StrictObject({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})

type T = Static<typeof T>
```
Hope that helps
S
