### ISSUE TITLE
help: Changes since 0.14 to 0.22 regarding union, null, and not-required properties

### ISSUE THREAD

**Issue by thatsnotright** [sinclairzx81/typebox#129]
We are upgrading, and have this helper defined:

```
export function NotRequired<T extends TSchema>(otherType: T): TOptional<TUnion<[TNull, T]>> {
  return Type.Optional(Type.Union([Type.Null(), otherType]))
}
```

which allowed the property to be missing, null, or the provided type.

Now I cannot get a schema generated that does not have the field as required, whereas before it used to be omitted from the 'required' array.

This
```
export const CONTAINER_TYPE = Type.Intersect([
  BASE_ENTITY,
  Type.Object({
    name: Type.String(),
    maxChildren: NotRequired(Type.Number()),
    isDefaultContainer: Type.Optional(Type.Boolean()),
    width: NotRequired(Type.Number()),
    layout: NotRequired(Type.String()),
    maxVolume: NotRequired(
      Type.Object({
        unit: EnumType(Volume),
        value: Type.Number(),
      })
    ),
    maxMass: NotRequired(
      Type.Object({
        unit: EnumType(Mass),
        value: Type.Number(),
      })
    ),
  }),
])
```

only works if I add an additional `Type.Optional` around the call to `NotRequired` even though it also has also a `Type.Optional` and inspecting the result includes the `Symbol('OptionalModifier')` as the TSchema `modifier` field.

I added some debug code to the library, and basically it comes down to Symbol('OptionalModifier') being different between the comparison in `Object()` for `exports.OptionalModifier` and the candidate's modifier.  Even though they're both visually identical.

The helper function we have above is declared in a common library package (we have a monorepo with npm workspaces), whereas adding the Type.Optional in the project directly works.  I assume this is some kind of issue with using Symbol between the node_module in the common package file, and the node_module in the server project?  I'm at a loss how to fix this, curious if you have any ideas what we may be doing that's now triggering this behavior?  Thank you!

**Comment by thatsnotright** [comment]
I assume this is the reason https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#shared_symbols_in_the_global_symbol_registry

(though we are using typebox in Node)

**Comment by sinclairzx81** [comment]
@thatsnotright Hi, the `Type.Optional(...)` modifier is actually the correct way to omit a property from the schemas `required` array. So for example, consider the `width` property defined on the `CONTAINER_TYPE` with and without the `Type.Optional(...)` modifier.

### Without Optional
```typescript
const CONTAINER_TYPE = Type.Object({
  width: Type.Union([Type.Null(), Type.Number()]) // expanded
})

type CONTAINER_TYPE = {
   width: null | number // must be either null | number
}

const CONTAINER_TYPE = {
  type: 'object',
  properties: {
     width: { anyOf: [{ type: 'string' }, { type: 'null' } ] }
  },
  required: ['width']
}
```

### With Optional
```typescript
const CONTAINER_TYPE = Type.Object({
  width: Type.Optional(Type.Union([Type.Null(), Type.Number()])) // expanded
})

type CONTAINER_TYPE = {
   width?: null | number  // must be either null | number | undefined
     // ^ - Note that the ? modifier added via Type.Optional(). Internally
     //     TypeBox will omit this property from the `required` array.
}

const CONTAINER_TYPE = {
  type: 'object',
  properties: {
     width: { anyOf: [{ type: 'string' }, { type: 'null' } ] }
  },
  required: [] // omitted
}
```
TypeBox version 0.14 is quite a few versions back, but I'm fairly certain this logic has been this way since the original versions of TypeBox.

### Symbols

TypeBox uses Symbol types for the `kind` and `modifier` properties primarily as these are non JSON serializable. They've been in for a while and should be supported in all major browsers and JavaScript runtimes (except for Internet Explorer). 

If you are using a monorepo, you will need to make sure all projects in your workspace reference the same version of TypeBox to avoid Symbol overlap.

### Intersect

TypeBox has updated the `Type.Intersect()` schema representation in recent revisions. It now mandates that the JSON Schema validator be supportive of draft `2019-09` (information [here](https://json-schema.org/draft/2019-09/release-notes.html) to leverage `unevaluatedProperties` with info [here](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.2.4). This shouldn't impact you if you're your not using this property.

Hope this helps.

**Comment by sinclairzx81** [comment]
@thatsnotright Just had a look at your incoming PR, thanks for that. Can you please verify first that each project in your workspace is taking the same dependency on TypeBox, you may need to flush out `node_modules` on each dependent project. This just to verify updating as a resolution to the issue. 

Let me have a think about using `Symbol.for(...)`. I think in scenarios where there are multiple versions of TypeBox installed, a `StringKind` should not equal `StringKind` if one originates from a different version. Although I can certainly see how this might help with updating to recent revisions in mono repository environments, so it's worth considering.

Let me know if fully updating TypeBox across your projects solves your issue first.
Cheers
S

**Comment by thatsnotright** [comment]
I had originally thought it may be related to incorrect versions and spent some time ensuring they were right. In the Docker container for the node app the version is all the same:

```
node@f1c3cc0e0a56:/usr/src/app$ find . -name typebox
./api/node_modules/@sinclair/typebox
./node_modules/@sinclair/typebox
./packages/common-api/node_modules/@sinclair/typebox

node@f1c3cc0e0a56:/usr/src/app$ grep version ./packages/common-api/node_modules/@sinclair/typebox/package.json
  "version": "0.22.1",
node@f1c3cc0e0a56:/usr/src/app$ grep version ./node_modules/@sinclair/typebox/package.json
  "version": "0.22.1",
node@f1c3cc0e0a56:/usr/src/app$ grep version ./api/node_modules/@sinclair/typebox/package.json
  "version": "0.22.1",
```

I am unsure why this is an issue for us after upgrading, the typebox source hasn't really changed much in this area.

I did find that if I move typebox to a top level dependency, npm only installs 1 copy which means the Symbol imported is always the same. It doesn't seem right that such a dependency should be pushed to the root package.json, though.  Undoing this change and rebuilding the Docker container results in the same situation, incompatible Symbol's.

It would be possible to create the symbols with the current package.json version, which would alleviate your concern over multiple versions of typebox needing to differentiate Symbol's.

**Comment by sinclairzx81** [comment]
@thatsnotright Hi, did you manage to resolve this issue? I think my preference at this stage is to keep on with existing `Symbol()` definitions (as I feel its better to highlight version disparities than suppress them). TypeBox's internals that relate to static resolution do change from version to version (usually to keep pace with enhancements with the TS compiler, sometimes at a frequency of 6 months), so a type created in one version may not be directly compatible with a type in another version. Symbols do provide an ideal mechanism to highlight such disparities.

The issue really sounds like you have multiple versions of TypeBox installed across each package in your repository (even if the package.json suggests otherwise). You can try a force update, or possibly just delete the yarn / package lock files and reinstall from scratch to pull the latest (as the lock may be sourcing different versions).

Let me know how you got on.

**Comment by sinclairzx81** [comment]
@thatsnotright Going to close off this issue. Feel free to re-open if you're still running into problems. I may actually consider the `Symbol.for('')` update in the near future, and even possibly using `string` over `symbol` as there are cases where encoding the `kind` on JSON can be used to remotely reconstruct TS types (which currently isn't possible due to Symbols being non JSON serializable).

For now will keep on with the current setup, but still interested to learn if you did find a workaround in your mono repository setup.

Many Thanks
S
