### ISSUE TITLE
Question on Type.Union - shouldn't it map to oneOf

### ISSUE THREAD

**Issue by maolimu** [sinclairzx81/typebox#142]
The type generated by Type.Union seems to be perfect, but I was wondering if the JSON schema should not actually be oneOf instead of anyOf.

anyOf seems to not accurately match the generated type.

**Comment by maolimu** [comment]
The question could be expanded to Type.Enum - which currently maps to anyOf but maybe oneOf would be more accurate. Not really relevant in this case, since only one property is involved, but still semantically more correct perhaps.

Well, since I mention Type.Enum ... it is confusing it does not map to JSON schema enum. 
And that one has to use KeyOf.

**Comment by sinclairzx81** [comment]
@maolimu Hi, see https://github.com/sinclairzx81/typebox/issues/37 for details on `oneOf` vs `anyOf`. 

Enum is currently expressed as a Union of Literals. This is a generalized schema representation, but not necessarily the most compact. The signature for Enum is a little wild, but you shouldn't need to use KeyOf to leverage it.

```typescript
enum Foo { A, B }

const T = Type.Enum(Foo)

type T = Static<typeof T> // T is Foo 
```
Hope that helps
S

**Comment by mmunte-impeo** [comment]
@sinclairzx81  thx for pointing to the oneOf vs anyOf. You are of course correct that unions map best to anyOf.

Turns out I have created a discriminating union: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions

The schema:
`    Type.Union([
        Type.Object({
            createType: Type.Literal('base64'),
            data: Type.String({ minLength: 5, contentEncoding: 'base64', examples: [tinyPdfBase64] }),
        }),
        Type.Object({
            createType: Type.Literal('reference'),
            archiveSystemReferenceId: Type.String({ minLength: 1, examples: ['some-foreign-key-in-archive'] }),
            processingError: Type.Union([Type.String({ examples: [null] }), Type.Null()]),
        }),
    ]),`

And later in Typescript:
`          switch (request.body.createType) {
                case 'base64':
                    ...
                    break;
                case 'reference':
                    ...
                    break;
          }`

While Typescript behaves correct - the schema and thus validation is not, as any possible property can be sent.

I guess this would be best solved by addition of a new Type.DiscriminatedUnion function? And for it to work properly, it is up to the user to ensure a literal with same property name but different values is created in each "branch".

Does this make sense?

**Comment by sinclairzx81** [comment]
@mmunte-impeo Hi, this implementation looks good to me. Discriminated unions are actually supported through inference of `Type.Union(...)` without the need for additional types. Quick example link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAgnAC8KYQDoA8iIBWGEjAAUCWXDgBrDgBMAXFbSZtAGWAwMUAl1MMVBgBKLEs4ADdfAFcMJxcMbXwoDgBzUyDZcgyZBSV4ACENLVd9IxNzMNt2R2cdDy8fPwZ84NCZK0iuGLidADkokBFvdMzs3OU4AGEi+L1DYzMLdpt7J2KE+u9ff0nWsM7u9e1kKLAuDFMAbVn+weGQo9uhqHSAXWys2XlFCeQZnQAquxgIoriocPkcJN3l8ZFQopxiIo4F5lKYIIYnPgiKQADxCTAQKgoAB8QUQYRYAHdPCQABbowzaKp2clLKxWEgEFgYRiBJzsjlWDEGbQHBL0ghQFRmACMAAZyUK4Px+HA6RBwt4nOK4MAWHBlMl2CkwkKRFAMARrABuM0Ue1cnmMFoC+3Cpni7QwCAAUXEkHYGHYxG25NV6s12oi0V5+rg7AGz3dcAtVtt9vIju5vIYuzdyyF43glwIOBEryKIrFsasEY1WqgOtr8cuibuUBw7eerxTaetdsLDuWWZko9hsiAA) and below where the `kind` property is the descriminator which is narrowed in the `switch` (which you have similar in your implementation)

```typescript
import { Type, Static } from '@sinclair/typebox'

const A = Type.Object({
  kind:  Type.Literal('A'),
  value: Type.String()
})
const B = Type.Object({
  kind:  Type.Literal('B'),
  value: Type.Number()
})
const C = Type.Object({
  kind:  Type.Literal('C'),
  value: Type.Tuple([Type.Number(), Type.Number()])
})

const T = Type.Union([A, B, C])

function test(obj: Static<typeof T>) {
  switch(obj.kind) {
    case 'A': {
      obj.value.charAt(10)      // hover: value is string
      break;
    }
    case 'B': {
      obj.value.toExponential() // hover: value is number
      break;
    }
    case 'C': {
      const [a, b] = obj.value  // hover: value is [number, number]
      break;
    }
  }
}
```
As for the schema representation, I have just added a spec to test that the validation is working as expected. You can view this test here https://github.com/sinclairzx81/typebox/blob/master/spec/schema/union.ts#L24-L30. Both of these validation checks will fail because neither of the schemas match the types specified on the union. This is the expected behavior. 

Note that `anyOf` will only pass validation if one of the schemas match any of the sub schemas, but it doesn't permit mixing and matching data from different sub schemas. From your applications standpoint, you can be assured the data you receive is one of the specified schemas (either `A` or `B` in this case), but you will need to narrow (using `switch` or `if` clauses) as you would usually for TypeScript to determine which.

So, everything looks ok with your implementation. Are you able to provide an repro where your see the validation pass when it should fail?

**Comment by mmunte-impeo** [comment]
@sinclairzx81 I will re-test. 

Maybe this was all just noise due to improper testing, I was under the impression that the schema  when used in Fastify was allowing properties of sub-schemas to be mixed. I will retest and come back here.

**Comment by sinclairzx81** [comment]
@mmunte-impeo Just be mindful that by default, TypeBox schemas do allow `additionalProperties` by default. If you're seeing additional properties being received on your Fastify server instance (which may corresponds to some of your other sub schemas), you can constrain each sub schema with the following.

```typescript
const A = Type.Object({
  kind:  Type.Literal('A'),
  value: Type.String()
}, { additionalProperties: false })

const B = Type.Object({
  kind:  Type.Literal('B'),
  value: Type.Number()
}, { additionalProperties: false })

const C = Type.Object({
  kind:  Type.Literal('C'),
  value: Type.Tuple([Type.Number(), Type.Number()])
}, { additionalProperties: false })
```

**Comment by sinclairzx81** [comment]
@mmunte-impeo Might close off this issue as `anyOf` is generally the best approximation of TS unions. But feel free to reply if you're still running into problems with the union validation.

Cheers!
S
