### ISSUE TITLE
How to declare ReadonlyArray

### ISSUE THREAD

**Issue by jonaskello** [sinclairzx81/typebox#157]
I want to make my whole type readonly. It works with `Type.Readonly()` for properties of an object, but I cannot make arrays readonly. I've tried this:

```ts
const Foo = Type.Readonly(Type.Array(Type.String()));
type Foo = Static<typeof Foo>;
```

The type of `Foo` is not `Array<string>` but I would like it to be `ReadonlyArray<string>`.

**Comment by sinclairzx81** [comment]
@jonaskello Hi. It's not possible to use object modifiers outside the context of object types. The `Type.Readonly(...)`, `Type.ReadonlyOptional(...)` and `Type.Optional(...)` modifiers analog the `?` (optional property) and `readonly` modifiers on TS interfaces and types. So for example.

```typescript
interface T {
   a?: string[]          // Type.Optional(Type.Array(Type.String()))
   readonly b: string[]  // Type.Readonly(Type.Array(Type.String()))
   readonly c?: string[] // Type.ReadonlyOptional(Type.Array(Type.String()))
}
// -----------------------------------------------------------------------------------------------------------
// Note: It isn't possible to express readonly and optional outside an interface in TypeScript either
// -----------------------------------------------------------------------------------------------------------

let a: string[]? // invalid syntax
let b: readonly string[] // invalid syntax
let c: readonly string[]? // invalid syntax

```
Also note that `readonly` doesn't protect against mutation of the array, it only protects against the reference of the array being changed, so for example.

```typescript
interface T {
   a?: string[]          
   readonly b: string[]  
   readonly c?: string[]
}
function test(value: T) {
  value.b.push('hello')  // ok
  value.c!.push('world') // ok
  value.b = []           // fail - Cannot assign to 'b' because it is a read-only property.
  value.c = []           // fail - Cannot assign to 'c' because it is a read-only property.
}
```
So, TypeScript doesn't really have a notion of readonly outside of an object interface / type. But it does have `const` and `as const` for fixed values (achieving a form of readonly) And for arrays specifically, TypeScript does support Tuple types.

```typescript
const A = ['hello', 'world'] as const // type A = ['hello', 'world']

// TypeScript
type A = [string, string]

// TypeBox
const A = Type.Tuple([
   Type.String(),
   Type.String()
])
```
Information on Tuple types can be found here. https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple. Information on const assertions can be found https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions.

Hope this is helpful
S

**Comment by jonaskello** [comment]
Thanks for the reply! Actually I'm not looking to decorate the array with a `readonly` modifier even though I can see how you would think that from my attempts :-). I'm looking to make it of the typescript built-in type  `ReadonlyArray` which is a type similar to `Array` but it has no mutation methods like `push()` etc.

Note that in your examples above, some of the syntax is actually [valid since of typescript 3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#improvements-for-readonlyarray-and-readonly-tuples).

```ts
let a: string[]? // invalid syntax
let b: readonly string[] // This is actually valid since of ts 3.4, it is the same as ReadonlyArray<string>
let c: readonly string[]? // invalid syntax
```

Also in this example you can decorate both the property and the array with `readonly` and you will not be able to push to the array as it is now of type `ReadonlyArray<T>`:

```ts
interface T {
   a?: readonly string[]          
   readonly b: readonly string[]  
   readonly c?: readonly string[]
}
function test(value: T) {
  value.b.push('hello')  // Property 'push' does not exist on type 'readonly string[]'.(2339)
  value.c!.push('world') // Property 'push' does not exist on type 'readonly string[]'.(2339)
  value.b = []           // fail - Cannot assign to 'b' because it is a read-only property.
  value.c = []           // fail - Cannot assign to 'c' because it is a read-only property.
}
```
Here is a [playground link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCrIN4Chm7gfgC5koI4ATAexABsBPZAZzClAHMBtAXV17+Ry5SFavWQAjYsKq0GzViE48BvaaIYIiJMjLHz23LAF8sMAK4gEYYNWSRmACgBucGmYjFUASkyCXbiAA6cUCABzNGAAsHAHJIiBoaShifZAB6NOQABShKUOgwBhjwqJjkKghGZBBKMGQIAA9gZmRbQvzkGLVZJhYDLhjAhwAmAGZRgE4vP1d3QIQAQjCI6JiAd0ooGnIU9MycvIKiksiyiqqausbmura6Dq6ddV6FJUGR8amZgODkAF5kNx+MCMsh4MAaMgALTIADCcBAl2QcEYjGAbBAdkonXEZXEEAQcAiKGAdWayO0FChz1CuXyUEKgW+cwQ-0BymBvFB4MhMPhiNqyNR6MxYGxMQQeIJRMYJLJVTglPI1J6tMODLoTJMQA) to verify the above example.

**Comment by jonaskello** [comment]
In the end I actually went with a `DeepReadonly` mapped type to make the typescript type generated from the schema fully immutable. Something like this:

```ts
const body = Type.Object({
  validationTokens: Type.Array(Type.String()),
});

type Body = DeepReadonly<Static<typeof body>>;
```

From the above the `Body` type will resolve to below.

```ts
type Body = {
  readonly validationTokens: readonly string[];
}
```
Note that both the property and array are now readonly so the array has no `push()` etc.

The utility type `DeepReadonly<T>` used above is declared as this:

```ts
type ImmutablePrimitive =
  | undefined
  | null
  | boolean
  | string
  | number
  | Function;

export type DeepReadonly<T> = T extends ImmutablePrimitive
  ? T
  : T extends Array<infer U>
  ? ReadonlyArray<DeepReadonly<U>>
  : T extends Map<infer K, infer V>
  ? ReadonlyMap<DeepReadonly<K>, DeepReadonly<V>>
  : T extends Set<infer M>
  ? ReadonlySet<DeepReadonly<T>>
  : {
      readonly [K in keyof T]: DeepReadonly<T[K]>;
    };
```

I think this approach makes the schema declaration more concise also since I can skip the readonly decorators there. I hope that helps anyone looking to make their type fully immutable, including arrays :-)

**Comment by SebastienGllmt** [comment]
I'm stuck on this issue as well. I'm trying to export Typebox definitions from my library, so telling everybody who consumes my library to wrap all their typebox usage with `DeepReadonly<Static<...>>` is not realistic.

Ideally, creating readonly array types is something that Typebox would support natively

**Comment by SebastienGllmt** [comment]
Actually, I just thought of a different workaround until this is supported at the typebox level: use Type.Unsafe`

```
Type.Unsafe<DeepReadonly<Static<typeof MyType>>>(MyType);
```

**Comment by SimenB** [comment]
@sinclairzx81 sorry to necro post (I can open up a new issue if you prefer), but is this something that could be changed? 😀 We usually use `ReadonlyArray` rather than `Array` to prevent accidental mutations (`sort` comes to mind). Usually this is fine since regular arrays are superset of readonly ones, so we can pass data from typebox into functions that expect readonly variants. But if we use the types we get back from typebox, we cannot then pass the readonly variants into it (without copying the array frist, so it becomes muatable).

**Comment by sinclairzx81** [comment]
@SimenB Hi!

> sorry to necro post (I can open up a new issue if you prefer), but is this something that could be changed?

Ah. It's all good! Here is fine :)

> We usually use ReadonlyArray rather than Array to prevent accidental mutations (sort comes to mind). Usually this is fine since regular arrays are superset of readonly ones, so we can pass data from typebox into functions that expect readonly variants. But if we use the types we get back from typebox, we cannot then pass the readonly variants into it (without copying the array frist, so it becomes muatable).

Ah, I had been meaning to look into this for the new Script feature in V1 (where I aim to eventually parse full `.d.ts` definitions). As such, I've gone ahead and published a new `Type.Immutable()` modifier type on 1.0.36 which should support the `readonly T[]` type inference. This is up on NPM now.

[Immutable Documentation](https://sinclairzx81.github.io/typebox/#/docs/type/immutable)

[Immutable Reference Link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgehrgFonmXW32PPPb6AlVAIYATCADsANkgCCUKAKQAeBAD44ANWAC4ASRAgArjAHFxqJcp6Mu1m7faUA3pThwAxmIDO8KXAC8iIgA6XQMjE1QACmQ0QJk5JCiggDl9EGJUKAiAShzqF3dRLzgAIT8AmJDDY1NEmIR9MBqAbWjUQIBlGChgUQBzbIAacraUtIzsgF1c5zhCNDgff1aOoxhgVwU51AgMBdU4OlmiBbKoQREJJDhRVPSoJom8o-nSpaDOgTWNrZ2S-cOtiVTucxJI4E0vN0+kMbmMoI8AL6WOwo1HcQ6VMKmODADzDADyaDkMGgcAi7Vc3TAMCyyLR9PpjhmgMWwxWn3WmyIvyk-3oLOBwlBV1hdweT0BrzZHy+XLQv2KfOe6ClZyFl3BkJ6vRhtwyjxmBSKDgWQ1KCLKywpVJgEQABhLjqy1RcwaKMuLmcdVSCNRCutrdXDHi5Di5w3AAD4zMMRuAAamYcBdwrgEGIHgyADdUEI4AI8ZjqmYVDjRLMABa4txiGCoMgwGZ22lIukM9u2SxF8IJuD8dVgjCkgAK2CJa1QHjbHZnHCZLkBCEt71WnJ+u1LB35xyX-iccYPh6PR9jKY1ZAAXMnfW69fcJgBuGbHl+v0P0FxnsFIK-u+8PuBnzfYCD1jAAvK8vxFO8HifED4LjQ5W3yTx4F3aVKWAal7X3cMoLgS9rwHaC4XFCN8J-a4YJDcMIKI10SLFGiEWbYDDiNNCr2WBB8WIAArVBXBgBRcIQ2MXEI7j+wYpQggQbtTFkuo4nkJS2gQUY7mUbS4IQrc40oqSb0UbiVJMuTNIyHSgJA8S4Do7iFJLOSzLUwINLvay9P0hELCRQ5Z0C+xDnaJA9FQANXDgABRBtUFEIQPCvAB1bRh2nIKgvnZUTn8CJ8L-B4sjges6wSvF8uMqjSKmOAAH5ZigfR0CvDABHETMvReMoIkK2rj1K+LErJArqOKhqumauBWvazqF2OABhHrRpq4rBvKslqqY4qjwmpqWswWbUC69AABEer6naj3W4berGl89qmmaOuOw1ULgE0pDNIYFqGc6LTeGJrSw20HQjAU8pW7aSrijbKuIraPVqx6Dral6gMlC77oG2HbqhpHxsap7DvR8HFuWqrLphsrbsR+8roPFHppJubw0Bc68qpnGaYqrndqJ1GjqbFsgA)

```typescript
import Type from 'typebox'

// ------------------------------------------------------
// ReadonlyArray<T> Via Immutable<T>
// ------------------------------------------------------
{
  const A = Type.Immutable(Type.Array(Type.Number()))

  const B = Type.Immutable(Type.Tuple([Type.String(), Type.Number()]))

  type A = Type.Static<typeof A>  // type A = readonly number[]

  type B = Type.Static<typeof B>  // type B = readonly [string, number]
}
// ------------------------------------------------------
// Immutable is TypeOperator (Script)
// ------------------------------------------------------
{
  type A = Type.Static<typeof A>  // type A = readonly number[]

  type B = Type.Static<typeof B>  // type B = readonly [string, number]

  const { A, B } = Type.Script(`

  type A = readonly number[]

  type B = readonly [string, number]
  //       |
  //       +--- readonly observed as Immutable<T> in this context
  `)
}

// ------------------------------------------------------
// Immutable + Readonly for Properties
// ------------------------------------------------------
{
  type T = Type.Static<typeof T>  // type T = {
                                  //   readonly x: readonly number[];
                                  //   readonly y: number[]; 
                                  //   z: readonly number[];
                                  // }

  const T = Type.Script(`{
    readonly x: readonly number[]
    readonly y: number[]
    z: readonly number[]
  }`)             // const T: Type.TObject<{
                  //     x: Type.TReadonly<Type.TImmutable<Type.TArray<Type.TNumber>>>;
                  //     y: Type.TReadonly<Type.TArray<Type.TNumber>>;
                  //     z: Type.TImmutable<Type.TArray<Type.TNumber>>;
                  // }>
}
// ------------------------------------------------------
// Symmetric Extends: WIP
// ------------------------------------------------------
{
  type A = (readonly number[]) extends (readonly number[]) ? true : false
  type B = (number[])          extends (readonly number[]) ? true : false
  type C = (readonly number[]) extends ( number[])         ? true : false
  type D = (number[])          extends (number[])          ? true : false

  const { A, B, C, D } = Type.Script(`
    type A = (readonly number[]) extends (readonly number[]) ? true : false
    type B = (number[])          extends (readonly number[]) ? true : false
    type C = (readonly number[]) extends ( number[])         ? true : false
    type D = (number[])          extends (number[])          ? true : false
  `)
}
```

This type had been a quite challenging to implement under the V0 infrastructure, but the V1 infrastructure makes it a bit more approachable. I've gone with the name Immutable for now which loosely correlates to the TypeScript [TypeOperator](https://ts-ast-viewer.com/#code/C4TwDgpgBAglC8UBOECGATA9gOwDYimwFcBbAIwiQG0BdIA) AST Node. I decided to go with a modifier vs adding a ReadonlyArray and ReadonlyTuple type, mostly because the Immutable only contributes to inference (which puts it inline with the existing Readonly and Optional modifiers).

I will need to do a bit more work on the Extends checks (last example) to support Tuple, but I think the Immutable type does make sense to support the readonly array inference side of things. Will do more work on the syntax side over the next few weeks, but the Type.Immutable(T) function should be ok to use now.

Let me know if this helps!
Cheers!
S

**Comment by sinclairzx81** [comment]
@SimenB Hi, Just an update here

## ReadonlyType(T)

I've done a bit more work here and added a new type analogous to TypeScript's `Readonly<T>` named Type.ReadonlyType(T). 

The naming is somewhat unfortunate as Type.Readonly(T) is reserved to make object properties `readonly`, but where the type itself functions somewhat similar to Type.Partial(T) where it applies a the Type.Readonly(T) modifier mapping to each immediate sub property.

[Documentation](https://sinclairzx81.github.io/typebox/#/docs/type/readonly-type) | [Example](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgehrgFkBDMNAEzgEEBnALjgDecKKiZsIAOwA2SOAG0A0nGAS4Aa1RIIGRHAC6-BIr1wAvtQDGk7vARwAvIiIA6AEqjx0pMjQAKH6jOAPLEAFaoFjC+QnCxcfF0cIRouo4ClLFkhi4AcgCuIMSoUL4AlAA08VXVNbVxibEiYpIycFlwEgVFUADcGXBI2WjO+YXFZZV1U9OxDcIeLbKDHV3FfbEAXkOBo91lMwd1c02erVsrY72UpqWlh-cPCfTmtPTMrKgcPIYAkiAgeRgTGIUlQAB4EAg8mBQWC5M4EXoAHxIyzWeAAZQcTmG7maXgC-hcUJhqF8chmiWS6CxjhOi3k-QCI1WJQqjw5cDmnUu5SZuVZE05j25rL5sWZu3Gd2FD1FvMoeluspV1USemoiXe7C4fEQfwBQJB4IQnCgUCYSDBCOcKLREhsXGxzLxp28RCJwzNFqQvkp9GpTrpCy8F26cg1EoFl32qumlFu-TjVU1bxYOu+iClUDgAFo4DkIBAwPbHQAhZ0uV2LQmSwXK2pUohwCuOHndShAA)

```typescript
// Mapped As: { readonly [K in keyof T ]: T[K] }

const T = Type.ReadonlyType(Type.Object({           // type T = {
  x: Type.Number(),                                 //   readonly x: number;
  y: Type.Number(),                                 //   readonly y: number;
  z: Type.Number()                                  //   readonly z: number;
}))                                                 // }

// Mapped As: TImmutable<TTuple<[...]>>

const S = Type.ReadonlyType(Type.Tuple([            // type S = readonly [
  Type.Number(),                                    //   number,
  Type.Number(),                                    //   number,
  Type.Number()                                     //   number,
]))                                                 // ]

// Mapped As: TImmutable<TArray<...>>

const A = Type.ReadonlyType(Type.Array(            // type A = readonly number[]
  Type.Number()                                   
))
                               

// Mapped As: TNumber - Noop

const B = Type.ReadonlyType(Type.Number())         // type B = number
```

---

## Programmable Readonly | Mapped Types

The Type.ReadonlyType(T) type explcitly implements the TypeScript mapping behaviors for `Readonly<T>` so should be fine for most cases, however there is still some work to do to get Array | Tuple readonly mapping working inline with TS mapped types (programmable)

[Reference](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAKlC8UDaBGANFATBgzAXQCgCB6YqARwFcIBnYASwHsA7ALigAtGB3KAE0a1YAZX4RgEAE4Bbes2jAOAQ2BQlUUJCiNIklY0lQaXSgBs+UAEbQlYMKfoQ+JMtw4RmG91DBK908SlYKHoaNU8-PRAAfgJNaAANACUIJQFmUxAAHhgAPgQoAG8oSVT0zOQAaRDPAGsIEEYAM1g8dhgkSrwoAF8ieKgkgH0ABgLkspZMnPyoOfmFxaWoUg1waGGxxFK0qZBkdCxcbv71waGUAuKd8v3Omqh6xpaYNthO7p651YHhy8RCgRlsCQaCwSsyHMbntkAAPdjMSjSaySN44KAAHyglyxmAA3EDwUTiUtVgtoRl9iN2CgCST6SSyfMKRUUOx8YSGVyQUyoZNKVh2Dg6dzRaTIfMAHTSzliuWrPpEIA)

```typescript
type T = [1, 2, 3]

// question: how does TS determine that a type operator should be applied
// when the parameter T is an array?
type XReadonly<T> = { readonly [K in keyof T]: T[K] }

type R_0 = XReadonly<T>                       // type R_0 = readonly [1, 2, 3] 

type R_1 = { readonly [K in keyof T]: T[K] }  // type R_1 = {
                                              //   readonly [x: number]: 3 | 1 | 2;
                                              //     readonly 0: 1;
                                              //     readonly 1: 2;
                                              //     readonly 2: 3;
                                              //     ...
                                              // }
```

Where TB currently only supports the` R_1` inference result when mapped.

[Reference](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgYwgDsBneBOAXkSIDoBlGqYGBgAKPAG0AjABo4AJhkBmALp4AlNTpN4AJQD6E9pzS9+gkQG9EcAL4yABpaioAhgBMGAGyRwxAaTjA9HAA1qhIEBiISgBciH5KNnbqlIRocHoGHMjGPDDOMMA0ADypqBHp+gB8cDW1NQD09XClFZlw5pR1Xd09vX21jbVObp7eAAyxEgDcnf1z872DNcPu9F5wErGyMwu7e0twK6NysQo7exf9g9bUQA)

```typescript
const T = Type.Script('[1, 2, 3]')

const R_1 = Type.Script({ T }, `{ readonly [K in keyof T]: T[K] }`)

type R_1 = Type.Static<typeof R_1>        // type R_1 = {
                                          //   readonly 0: 1;
                                          //   readonly 1: 2;
                                          //   readonly 2: 3;
                                          // }
```

.... but where calling the `Readonly<T>` built-in can produce the `R_0` result.

[Reference](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgYwgDsBneBOAXkSIDoBlGqYGBgAKPAG0AjABo4AJhkBmALp4AlNTpN4AJQD6ABnac0vfoJEBvRHAC+MgAbbUAQwAmDADZIAPAgB89qpwAPTBcCDOYGiucABuwM5wTm6eSMhowgjqlIRoSQZG6ai8MM4wwDTeuagQGPn6fnBNzS1NoXDV9UZQLu70XnCSMvJwykA)

```typescript
const T = Type.Script('[1, 2, 3]')

const R_0 = Type.Script({ T }, `Readonly<T>`) // mapped via ReadonlyType(T)

type R_0 = Type.Static<typeof R_0>            // type R_0 = readonly [1, 2, 3]
```

Will do some work to line up the mapped / programmable side next year.

---

Again, hope this helps, ReadonlyType(T) is available on 1.0.49
Cheers!
S

**Comment by SimenB** [comment]
I missed your post last month somehow and stumbled across `immutable` now. It's awesome, exactly what i wanted! Thank you! 😀

`ReadonlyType` is also great! Really nice to wrap whole objects rather than doing `Readonly` on every field 👍

Question - is there any reason to use `Type.Immutable` over `Type.ReadonlyType` (typechecking perf or otherwise)?

**Comment by sinclairzx81** [comment]
@SimenB Hi!

> Is there any reason to use Type.Immutable over Type.ReadonlyType (typechecking perf or otherwise)?

I would probably opt for Immutable for now, will go into a bit of detail regarding the differences between each, but at a high level,

- Immutable(T) - New Modifier similar to Optional / Readonly (applied to Array types)
- ReadonlyType(T) - Computed type similar to Partial (but assigns Readonly instead of Optional)

---

### Type.Immutable(T)

Type.Immutable is essentially a new kind of modifier (like Optional / Readonly) that assigns an `~immutable` flag to a type (used for inference only). It should be fast to apply as well as to infer. In terms of functionality, Type.Immutable flag only applies to Array and Tuple like structures; and where Type.Immutable is used to imply exterior immutability vs the interior immutability already specified by Type.Readonly.

The following shows the distinction between Type.Immutable and Type.Readonly (as it applies to properties)

```typescript
import Type from 'typebox'

const A = Type.Array(Type.Number())

const T = Type.Object({
  x: Type.Readonly(Type.Immutable(A)),
  y: Type.Readonly(A),
  z: Type.Immutable(A),
})

type T = Type.Static<typeof T>  // type T = {
                                //   readonly x: readonly number[];
                                //   readonly y: number[];
                                //   z: readonly number[];
                                // }
```

If choosing between Type.ReadonlyType(T) and Type.Immutable(T), Type.Immutable(T) is probably the way to go as it involves no additional computation of the type (as it only assigns the `~immutable` flag). 

You may wish to wrap it in an exterior type like the following 

```typescript
import Type from 'typebox'

// use this to emulate the ReadonlyArray<T> TS structure
export function ReadonlyArray<Type extends Type.TSchema>(type: Type): Type.TImmutable<Type.TArray<Type>> {
  return Type.Immutable(Type.Array(type))
}
```
I may include `Type.ReadonlyArray(T)` in the next revision (which would be implemented as above). Aliased types like this currently fall outside any particular category in TB, so wanted to give it some more thought before including as part of the library (also with some consideration to the TS definition of ReadonlyArray which is modelled as a base for Array)


---

### Type.ReadonlyType(T)

The Type.ReadonlyType (which may be renamed to ReadonlyObject next revision), is the same as TypeScript's `Readonly<T>` utility type and should have the same runtime/inference performance as Partial. 

It is implements the mapped type logic as follows ...

```typescript
type Partial<T> = { [P in keyof T]?: T[P]; }            // Type.Partial(T)

type Readonly<T> = { readonly [P in keyof T]: T[P]; }   // Type.ReadonlyType(T)
```

Type.ReadonlyType is a computable type so has some runtime overhead (the same as Partial), but also has some additional mapping rules when applying to Object and Array types.

#### When applied to Object

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Array(Type.Number())
})

// Applies a ~readonly modifier to each property (does not make interior values immutable)

const S = Type.ReadonlyType(T)

type S = Type.Static<typeof S>  // type S = {
                                //   readonly x: number;
                                //   readonly y: number[];
                                // }
```

#### When applied to Array | Tuple

```typescript
const T = Type.Array(Type.Number())

// Applies an ~immutable modifier if the exterior type is a Array

const S = Type.ReadonlyType(T)

type S = Type.Static<typeof S>  // type S = readonly number[]
```

The mapping behaviors are based on the same rules as the TS utility type. and where TS has some special handling for the generic / mapped Array, Tuple cases where rather than mapping for each element (which would apply Readonly in the object case), instead applies an exterior Immutable modifier (or TypeOperator)

```typescript
type T = [1, 2, 3, 4, 5]

type ReadonlyType<T> = { readonly  [K in keyof T]: T[K] } // ReadonlyType(T)

type S = ReadonlyType<T>                                  // type S = readonly [1, 2, 3, 4, 5]
                                                          //          ^
                                                          //          TypeOperator | Immutable(T)


```

---

There's actually quite a bit of complexity and depth to Immutable and ReadonlyType (more than I expected) with some interesting compiler behaviors TB is trying to replicate. I may apply some additional updates in the next few revisions to ReadonlyType (probably just to rename to ReadonlyObject), but the Immutable(T) should be good to use now (and recommend wrapping it as a ReadonlyArray for now as per example)

If using ReadonlyType, just be mindful of the rename in the next minor revision :)

Hope this helps! :)
S

**Comment by SimenB** [comment]
Thanks for the detailed answer! Just landed the update using the new immutability helpers and it greatly helped. Even caught a bug where we mutated an array 😀 

---

> You may wish to wrap it in an exterior type like the following
> 
> ```ts
> import Type from 'typebox'
> 
> // use this to emulate the ReadonlyArray<T> TS structure
> export function ReadonlyArray<Type extends Type.TSchema>(type: Type): Type.TImmutable<Type.TArray<Type>> {
>   return Type.Immutable(Type.Array(type))
> }
>```
> I may include `Type.ReadonlyArray(T)` in the next revision (which would be implemented as above). Aliased types like this currently fall outside any particular category in TB, so wanted to give it some more thought before including as part of the library (also with some consideration to the TS definition of ReadonlyArray which is modelled as a base for Array)

Haha yeah, we ended up adding some helpers 🙂 

```ts
export const ReadonlyObject = <Properties extends TProperties>(
  properties: Properties,
) => Type.ReadonlyType(Type.Object(properties));

export const ReadonlyInterface = <
  Heritage extends TSchema[],
  Properties extends TProperties,
>(
  heritage: [...Heritage],
  properties: Properties,
) => Type.ReadonlyType(Type.Interface(heritage, properties));

export const ReadonlyArray = <Type extends TSchema>(items: Type) =>
  Type.Immutable(Type.Array(items));
```
