### ISSUE TITLE
Question: How to refer to a TypeScript type?

### ISSUE THREAD

**Issue by Mahi** [sinclairzx81/typebox#158]
Say I have a type:
```ts
type Identifier = string;
```
How would I use this with a typebox type?
```ts
const Foo = Type.Object({
    id: ???,
    name: Type.String(),
    ...
});
```

**Comment by Mahi** [comment]
I figured out another way for my own types:
```ts
const IdentifierSchema = Type.String();
const Identifier = Static<typeof IdentifierSchema>;
```
But is there another way if the type is not under my control, but comes from an external source?

**Comment by sinclairzx81** [comment]
@Mahi Hi, Unfortunately, there isn't really a way to bring in imported pure TS interfaces into TypeBox (unless you're importing TypeBox types). You will need to reconstruct the type as a TypeBox type. This is due to pure TS types having no associated runtime information (like a schema).

Fortunately, TypeScript is structurally typed, so it is possible to replicate the imported type as a TypeBox type (as you've done). So long as the TypeBox type matches that of the imported type, things will be structurally correct. For example.

```typescript
import { Type, Static } from '@sinclair/typebox'

interface Foo { // Some Interface you might import from a remote library
   a: number,
   b: string,
   c: boolean
}
const Foo = Type.Object({ // This is your typebox type that matches the remote type
   a: Type.Number(),
   b: Type.String(),
   c: Type.Boolean()
})


// This function expects a type of foo
function test(foo: Static<typeof Foo>) {

}

// This object is typed to the remote interface Foo
const foo: Foo = {
    a: 1,
    b: 'hello',
    c: false
}

// This is allowed because Static<typeof Foo> and Foo are structurally equivalent. 
test(foo)
```
Duplication of the imported type can be annoying, so it is recommended to only use TypeBox to type data you expect to receive over the wire. If you expect to receive the imported `type`, then duplication of the imported type is the only way to handle things in TypeBox.

Hope that helps
S
