### ISSUE TITLE
How to `ref` a schema that was not defined by typebox?

### ISSUE THREAD

**Issue by rubenferreira97** [sinclairzx81/typebox#167]
Hi, currently I am trying to use typebox to build schemas for [fastify-multipart](https://github.com/fastify/fastify-multipart).

However I can't find a way to define the following docs ref: 

```ts
const opts = {
  attachFieldsToBody: true,
  sharedSchemaId: '#mySharedSchema'
}
fastify.register(require('fastify-multipart'), opts)

fastify.post('/upload/files', {
  schema: {
    body: {
      type: 'object',
      required: ['myField'],
      properties: {
        // field that uses the shared schema
        myField: { $ref: '#mySharedSchema'}, // ⬅️ How to build this schema???
        // or another field that uses the shared schema
        myFiles: { type: 'array', items: fastify.getSchema('mySharedSchema') },
        // or a field that doesn't use the shared schema
        hello: {
          properties: {
            value: { 
              type: 'string',
              enum: ['male']
            }
          }
        }
      }
    }
  }
}, function (req, reply) {
  console.log({ body: req.body })
  reply.send('done')
})
```
`fastify-multipart` generates a default shared schema with a specified `sharedSchemaId`. I want to ref that id on my schema.

**Comment by sinclairzx81** [comment]
@rubenferreira97 Hi, You should be able to do something like the following. (Note, I've omitted any schema registrations on Fastify in the example below (you'll have to refer to the Fastify documentation for how to correctly register schemas). Also the call to `fastify.getSchema('mySharedSchema')` should be unnecessary as you should be able to `Type.Ref(...)` the shared schema once it's registered.

TypeScript Example Link [Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUKEiw4AMQItiVVNVr0GVZatTSp-fnAC0Z8xctXrN23cuHjuEgAsMIAo9P2fvv7akSCHYVPBcCKAwAEzgAXhRhADoAeREAKwwSGAAKBCk4AqoICAAuBMxE-CgOAHNsgEosfIKRCLK0CqrahqbyHCQAEmAosoYQVFxwyKjnNw8GCnq4Izh2CBgMMpAAV1CWTBJgNTgAAyGok7gjuEiqDEjOaKlA4NCAIQgo9XiOjBT0zI5PIFODjBTADBcEblP4AJQwVGykwi0UazVBqHBXAwLHaSQAglAoARUNlfol4YjkdN6miQW4uFxSjDEgBVdjAYLZADa6JB5IAMsANsSuNkxgRsQx6uiALoy8gyrz+FWqnxeACi4gI4GxyrVBsNZmeQRC8B0KiO30UuitDWeFr0iUgKgAPEhmh8vmV8ERSK6hJgIFQ4F7UAA+KTkcPi-jbMBMghRfhUYDYlgMfrNFiudwEMrAkFib2hz6oZrkKM4KjbTjEYJwbKRACOOEiCdQS0LptCSAZTJwYIhUMHmLTOIocRuGGbiWL5YKzXbXFQiRYGHYUXFUWCGGlUfqQA)

```typescript
import { Type, Static } from '@sinclair/typebox'
import Fastify from 'fastify'

// ------------------------------------------------------------
// Schema
// ------------------------------------------------------------
const Shared = Type.Object({
   foo: Type.String(),
   bar: Type.String(),
}, { $id: 'mySharedSchema' }) // note: must specify `$id` if referenced

const Body = Type.Object({
   myField: Type.Ref(Shared),
   myFiles: Type.Array(Type.Ref(Shared)),
   hello: Type.Union([
      Type.Literal('male')
   ])
})

// ------------------------------------------------------------
// Example
// ------------------------------------------------------------

const fastify = Fastify()

fastify.post<{ 
  Body: Static<typeof Body>
}>('/upload/files', {
  schema: {
    body: Body
  }
}, function (req, reply) {
  const { hello, myField, myFiles } = req.body
  
  reply.send('done')
})
```

Hope that helps
S

**Comment by rubenferreira97** [comment]
@sinclairzx81 
If I understood correctly, with this approach I am defining a new shared schema and not utilizing the already defined schema from `fastify-multipart`. If `fastify-multipart` changes their schema implementation, I will have an outdated schema. Not to say that two different schemas would be defined that could create inconsistencies.

Even if that might work, I don't think it should be the correct approach for this problem.

**Comment by sinclairzx81** [comment]
@rubenferreira97 I'm not familiar with `fastify-multipart`, so can't be of too much more assistance on the use of this library specifically, however.... 

In order to reference another schema through TypeBox, you will need to create the referenced schema in TypeBox with an `$id`. By doing this, TypeBox can infer both the structure of your surrounding properties, as well as the schema being referenced. But you could try...

TypeScript Example Link [Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAMQIYGcbAGYE84ahEOAcg1XWyIChRJY4BvOAFSzAFMAaOAZRiXQDGXJgFUAdgGsxEAO5i4AX1z5CRAAIpgYgQBskwKAHoYrNgCMIADyqUBEMWlxlMOALyJn2ABQBKSpUNDOABaULDwiMio6JjYgKCAOQgYNjgYAAt+XAgdHVktAHM4FHSIAFcdABM4GWgJYog4PLEi1DgscqIoVPi4MFRNFrgANyQdYGqAKW4AeQSeAXS2ECQ4LT69AVSIDGZTACErNNMULl6OsrgBJHkAA1RbuAG2Oi0YRozUpDAwfF-gfipEzsOBeARlKDdMQwHQ4XplSTSOQ+GrpYCLGrAXJwNhiJBmHRA0xrMQYF64rZpRpoLE6Gp1AB0cF6sVZbPZMX8dgc8EOlTce3YDJmZgAVmwBDAvPRKHA5SAsAhgGwqgAuBhwAAk3Qw6qIAGIFdxMt1KtxFsskEQlG0EVJZPI2qJEQ6OLL5YqsWwUOqWEKAIKQpBYLykGnYBkFNgwc1LFZeIhGk1sM0WlZEFG2l1yJ4oZjie3It1yuBLXIQX2mBniYD2LwAbXdJcFbAZABlgCkoGMEytCRmmwBdPwKPwsjkTyecwJwACiliQ4EJ46nq9X-jD5CwDMgaAAPIx3XysOrePx0XvgWwdnBjwA+SgKO8JwxlMB5JCVQwYL0oIhcGU5RQNMkHVQCSwsfl1WPd0FEfLgMARSVa3kLxugARy4bp3ywFFwO5RxGDLPIuAVJUVUqUjPUJPMlHcDCGUgrB3XdbDYQZFBcUqBNKnsNgB1HSggA)

```typescript
import Fastify from 'fastify'
import { Type, Static, TUnknown } from '@sinclair/typebox'

const fastify = Fastify()

// -------------------------------------------------------
// Note that following should work so long as you're 
// passing valid JSON Schema in place of TypeBox types, 
// you can `as` assert into the appropriate type (currently 
// unknown) which will enable type inference to still work. 
// -------------------------------------------------------

const Body = Type.Object({
   myField: { $ref: '#mySharedSchema'} as unknown as TUnknown,
   myFiles: Type.Array(fastify.getSchema('mySharedSchema') as unknown as TUnknown),
   hello: Type.Union([
      Type.Literal('male')
   ])
})

// -------------------------------------------------------
// Example
// -------------------------------------------------------

fastify.post<{ 
  Body: Static<typeof Body>
}>('/upload/files', {
  schema: {
    body: Body
  }
}, function (req, reply) {
  const { hello, myField, myFiles } = req.body
  
  reply.send('done')
})
```
But this is quite messy. However, It might be possible to create a custom type around this to make usage a bit more clean and get inference for what ever type `fastify.getSchema('mySharedSchema')` should return.

**Comment by sinclairzx81** [comment]
@rubenferreira97 Hi, might close off this issue. Feel free to ping a reply if you have any other questions.

Cheers!
S
