### ISSUE TITLE
TypeScript Linter Error: Property '$ref' is missing in type 'TIntersect<[TObject<

### ISSUE THREAD

**Issue by SimonPiscitelli** [sinclairzx81/typebox#171]
I have

```ts
// entity.schema.ts
export const EntitySchema = Type.Object({
    id: Type.String({ format: "uuid" }),
    created_at: Type.String({ format: "date-time" }),
    updated_at: Type.String({ format: "date-time" }),
    name: Type.String(),
    fca_number: Type.Union([Type.Null(), Type.String()]),
    contact_name: Type.Union([Type.Null(), Type.String()]),
    contact_email: Type.Union([Type.Null(), Type.String()]),
    contact_number: Type.Union([Type.Null(), Type.String()]),
});

// upsert-entity-request.schema.ts
export const UpsertEntityRequest = Type.Omit(EntitySchema, ["updated_at", "created_at"])
```

In Type.Omit() I get the following error:

```
Argument of type 'TIntersect<[TObject<{ id: TString; created_at: TString; updated_at: TString; }>, TObject<{ name: TString; fca_number: TUnion<[TNull, TString]>; contact_name: TUnion<...>; contact_email: TUnion<...>; contact_number: TUnion<...>; }>]>' is not assignable to parameter of type 'TObject<TProperties> | TRef<TObject<TProperties>>'.
  Property '$ref' is missing in type 'TIntersect<[TObject<{ id: TString; created_at: TString; updated_at: TString; }>, TObject<{ name: TString; fca_number: TUnion<[TNull, TString]>; contact_name: TUnion<...>; contact_email: TUnion<...>; contact_number: TUnion<...>; }>]>' but required in type 'TRef<TObject<TProperties>>'.ts(2345)
typebox.d.ts(150, 5): '$ref' is declared here.
```

**Comment by SimonPiscitelli** [comment]
Also, in this case. How could I alter the interface for `id` and make it optional?

**Comment by sinclairzx81** [comment]
@SimonPiscitelli Hi, Have tested your schema and don't seem to seeing any type errors. See modified schema below for `Type.Optional(...)` on the `id`.

TypeScript Link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsACh+-OBnbEhAOhYkAFhhAFVMFrIzjIsOCQjsW8AKLLgQ3Fp0E4AXhTDVAeREArDBIYAAoEWTgIuGAAEwAuT0wfMGJLAi5gtET8KA4Ac1DqaF0YeIAiAFdymNKKAEpanHk4b2TgVK5wyJIoDCIMaIB9InjMjFVsvIKqIuG4Uui+gFpiEAwa8gbOiPKwBZh+oZKEsYn2fKRpqGKyvYxl0DW6rC24dgJVka9T-M2ZSOoSAQBuxyiARBgoJ9EgBVdhtdjBADao1UADlylx0g1juMYDkzsFagBdX7-CzKAhBYHvDBQsaw+FIlHozGEnAo76EknPP5dSyEKkuYBcOmqBmWJleFlY9lfPGTYmkvkUqkgsEQ0XihHIqUYmU4zmKnkbADcslkTR2LAhMEWShUqEWPQAjuUMNZ1M5dPpDDJjKZ4OTrHBoWBrbA7A6AEoYV3u+AeFHeEAOYKRhyoJzaXQ4REVXZ9QZEUo4UrdXr7IswUok80yIMQLhjLgQfIAKVw3lR6nlZ2AVFQwVD4Zg6aEMbj1hwIMxOAATPU600IOUYGBVyx4mE5AoIqUhJhSmUIP5AtWeU092BaJhYMB3UfEBbd5FStUt8--q-LsVHxUqtEJafl+cwHmsZTWPiuSlMBkTkBeL57m8qyPtul5fvuwh-pBeQwTuX7wbBe5UICwKguCUCoURr4EOwqDeFQj6ItR-xoYhIGgVhZQzlweHoSBhH4RxT5CcJnGHhBvbQSxcEyUS1GCfxczkgKMDUihH6if8pS0fRjHxMxWlfmxYl7mBf48Xx7H-Ip1mRCZpmYRJcw4WcVlieQckKQhGEqZSalCrxmlKXuukMUxMkRA5YlOeBcyWZFFA+cJ0XCbF2FSe5wmeUZETyUZtm+fy-lkeqlHBXZOl0eFBmJalHHpdxepZRxhUpYlZlcS5mWJTlIVwPlSl9S+bVzC6VQ9IBtVGaUyFrMl36kWqFFATNfmqjSq1KWWxWCrowpbexO0qmpy0Qi1g0KOQQA)

```typescript
import { Type, Static } from '@sinclair/typebox'
// entity.schema.ts
export const EntitySchema = Type.Object({
    id: Type.Optional(Type.String({ format: "uuid" })), // Optional
    created_at: Type.String({ format: "date-time" }),
    updated_at: Type.String({ format: "date-time" }),
    name: Type.String(),
    fca_number: Type.Union([Type.Null(), Type.String()]),
    contact_name: Type.Union([Type.Null(), Type.String()]),
    contact_email: Type.Union([Type.Null(), Type.String()]),
    contact_number: Type.Union([Type.Null(), Type.String()]),
});

// upsert-entity-request.schema.ts
export const UpsertEntityRequest = Type.Omit(EntitySchema, ["updated_at", "created_at"])

console.log(JSON.stringify(UpsertEntityRequest, null, 2))

// outputs: {
//   "type": "object",
//   "properties": {
//     "id": {
//       "format": "uuid",
//       "type": "string"
//     },
//     "name": {
//       "type": "string"
//     },
//     "fca_number": {
//       "anyOf": [
//         {
//           "type": "null"
//         },
//         {
//           "type": "string"
//         }
//       ]
//     },
//     "contact_name": {
//       "anyOf": [
//         {
//           "type": "null"
//         },
//         {
//           "type": "string"
//         }
//       ]
//     },
//     "contact_email": {
//       "anyOf": [
//         {
//           "type": "null"
//         },
//         {
//           "type": "string"
//         }
//       ]
//     },
//     "contact_number": {
//       "anyOf": [
//         {
//           "type": "null"
//         },
//         {
//           "type": "string"
//         }
//       ]
//     }
//   },
//   "required": [
//     "name",
//     "fca_number",
//     "contact_name",
//     "contact_email",
//     "contact_number"
//   ]
// }
```

I would recommend first checking that you're using `strict` mode in TypeScript. Also I see that some of the Type errors are reporting `Type.Intersect()` and `Type.Ref()` (which I don't see in your example). Currently there is a limitation in TypeBox were you cannot `Type.Omit()` or `Type.Pick()` from a intersected object (which seems to be the actual error here). This is due to the current JSON schema representation that makes composing from intersections difficult. This functionality will be changing in future versions of TypeBox, but it is worth mentioning in case this is your issue.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@SimonPiscitelli Hi, might close off this issue. Currently it's not possible to compose intersected types as hinted by the error you're seeing (which is also a design decision of the current implementation of TypeBox, so technically not a bug). But as mentioned this will be changing in next release but is not a bug in the current.

If you're still running into problems, feel free to comment on this thread. But generally the current way of approaching intersected types is to only intersect types that do not require future composition, this partially relates to some JSON schema constraints around `allOf` and `unevaluatedProperties`.

```typescript
const A = Type.Object({
   a: Type.String(),
   b: Type.String()
})
const B = Type.Object({
  c: Type.String(),
  d: Type.String()
})

const PartialA = Type.Partial(A)
const PartialB = Type.Partial(B)

// Note: Intersections should final composition as it is not possible
// to compose schemas once they have been intersected.
const Upsert = Type.Intersect([A, B])
const PartialUpsert = Type.Intersect([PartialA, PartialB])
```

Hope this helps
S
