### ISSUE TITLE
Partial Record of Literal Union

### ISSUE THREAD

**Issue by jjarthur** [sinclairzx81/typebox#183]
With TS types, we can have a list of optional keys with the below type:
```typescript
type T = Partial<Record<'k1' | 'k2', string>>;
const T0: T = { k1: '' };         // succeeds
const T1: T = { k2: '' };         // succeeds
const T2: T = { k1: '', k2: '' }; // succeeds
const T3: T = { k3: '' };         // fails
```

Is it possible to achieve this using typebox?
```typescript
const Keys = Type.Union([Type.Literal('k1'), Type.Literal('k2')]);
const T0 = Type.Partial(Type.Record(Keys, Type.String())); // fails because object is expected
const T1 = Type.Partial(Type.Object(Type.Record(Keys, Type.String()))); // TypeError: Cannot create property 'modifier' on symbol 'Symbol(RecordKind)'
```

**Comment by sinclairzx81** [comment]
@jjarthur Hi. TypeBox currently only supports `Type.Object(...)` as a parameter of `Type.Partial(...)`, `Type.Required(...)`, `Type.Pick(...)` and `Type.Omit(...)`. This is due to `Type.Record(...)` being expressed with JSON Schema `patternProperties`. (so it is difficult to reconcile these utility types as they are being expressed with regular expressions, and don't have any standard look up as would be the case for objects expressed with defined `properties`)

The `TRecord<TUnion<TLiteral[]>, TSchema>` representation may be possible in future releases however (there is currently some considerations for this on https://github.com/sinclairzx81/typebox/issues/176).

**Comment by jjarthur** [comment]
Amazing @sinclairzx81! Thank you.
