### ISSUE TITLE
`Intersect` doesn't work with `Union` in 0.24

### ISSUE THREAD

**Issue by SimenB** [sinclairzx81/typebox#187]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAbgBQQjL0iw4tCNQrweAE1QBlWgAsMIRnAC8KTgDoAktRgYoFDLRgAKANpC4+zAYDyXAFZXbSIwBEALmcMAwAlDEYFGXpUGzQXZRgoGgBzGwBKdJx0gBpHYIMAVWpgGXt4kPcvaxskAFEANwxTIIqDROTqNKzsdIBdXKEBgSA

This works fine with 0.23.5

**Comment by SimenB** [comment]
>I will be revisiting this particular type composition again once the 0.24.x release has settled down

Could you post a comment in this thread when you've done so? The code became slightly less readable than the `Intersection` usage 🙂

**Comment by sinclairzx81** [comment]
> Could you post a comment in this thread when you've done so? The code became slightly less readable than the Intersection usage

Hey sure thing! 🙂Also glad the above solution worked out ok. I'll note, it's been a little bit challenging to find ways to advance TypeBox while avoiding breaking changes. The `Type.Unsafe()` function was partially written to allow a little bit of flexibility to refine some of the library internals while providing somewhat tenable fallbacks for when things didn't quite line up, but I'll admit, the Intersect change was quite the significant one (but does actually set up TypeBox for more advanced composition in later releases!)

At this stage, I expect the update to resolve union intersect will be ready on the next `minor` release of the library (so, `0.25.x`), but will be sure to notify on this thread (and changelog) when things are ready to go. Note, usually it takes a few months to prepare these releases (in between other work), so expect a little bit of delay getting this functionality back in.

For the time being, I'll be recommending the following fallback (same as above) until this form of composition is re-enabled.

```typescript
import { Type, Kind, Static, TSchema, SchemaOptions, IntersectReduce, IntersectEvaluate } from '@sinclair/typebox'

// --------------------------------------------------------------------------------------
// IntersectSchemaArray<T> Candidate TypeBox utility type
// --------------------------------------------------------------------------------------

export type IntersectSchemaArray<T extends TSchema[]> = IntersectReduce<unknown, IntersectEvaluate<T, []>>

// --------------------------------------------------------------------------------------
// TIntersectAllOf<T> (unevaluatedProperties requires draft 2019-09)
// --------------------------------------------------------------------------------------

export type TIntersectAllOf<T extends TSchema[]> = ReturnType<typeof IntersectAllOf<T>>

export interface IntersectAllOfOptions extends SchemaOptions { unevaluatedProperties?: boolean }

export const IntersectAllOf= <T extends TSchema[]>( allOf: [...T], options: IntersectAllOfOptions = {}) => 
  Type.Unsafe<IntersectSchemaArray<T>>({ ...options, [Kind]: 'IntersectAllOf', allOf })

// --------------------------------------------------------------------------------------
// Usage
// --------------------------------------------------------------------------------------

const T = IntersectAllOf([
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.Number() })
])

type T = Static<typeof T>
```

All the best!
S

**Comment by sinclairzx81** [comment]
@SimenB Hi, just an update on this.

Hey, I'm just about to roll through a `0.25.0` minor revision as there's been a need to update the schema representations for Extended types (this to allow for the addition of a new `Type.Date()` type). But unfortunately this revision doesn't include the Intersection of Union resolution that I'd hoped for in the `0.25.0` release.

The PR for Type.Date() can be found here https://github.com/sinclairzx81/typebox/pull/271

## Updates on Intersected Unions

I'm actually still really in the process of figuring out how best to express intersected unions appropriately in the library, but have starting to consider the idea of having to implement some form of normative type evaluation that matches TS inference behaviors for aliased intersections and unions. Ultimately, the goal is still to return to the previous `pre-0.24.0` representation (via `allOf`), but with the ability of being able to compose intersections and unions across all current and future utility types such as `Type.Partial()`. This was partially made possible in `0.24.0` update, but came at cost of losing the `allOf` representation.

At this stage, the focus has been on looking into a `Type.Normalize()` Type that will evaluate intersections and unions to a normalized `TObject`. Once normalized, the type becomes immediately composable with all the current utility types (`Type.Partial()`, `Type.Required()`, `Type.Pick()`, `Type.Omit()` and `Type.KeyOf()`) as well as providing inroads to being able to tackle the Intersected Union problem.

### Intersect Normalization

```typescript
const A = Type.Object({ a: Type.Number() })

const B = Type.Object({ b: Type.Number() })

const C = Type.Intersect([A, B]) // to be expressed as `allOf`

const N = Type.Normalize(C)      // const N = Type.Object({
                                 //    a: Type.Number(),
                                 //    b: Type.String()
                                 // })
```

### Union Normalization

```typescript
const A = Type.Object({ type: Type.Literal('A') })

const B = Type.Object({ type: Type.Literal('B') })

const C = Type.Union([A, B])     // to be expressed as `anyOf`

const N = Type.Normalize(C)      // const C = Type.Object({
                                 //   type: Type.Union([ Type.Literal('A'), Type.Literal('B') ])
                                 // }) 
```

### Intersected Unions

The envisioned steps to produce an intersected union are shown below. The `Type.Normalize()` function would be implemented internal to `Type.Intersect()`, but showing it's explicit usage here for reference

```typescript
const A = Type.Union([
   Type.Object({
      type: Type.Literal('A1'),
	  a1:   Type.String()
   }),
   Type.Object({
      type: Type.Literal('A1'),
	  a2:   Type.String()
   })
])

const B = Type.Union([
   Type.Object({
      type: Type.Literal('B1'),
	  b1: Type.String()
   }),
   Type.Object({
      type: Type.Literal('B1'),
	  b2:   Type.String()
   })
])

const NA = Type.Normalize(A)       // const NA = Type.Object({
                                   //    type: Type.Union([Type.Literal('A1'), Type.Literal('A2')])
                                   //    a1: Type.Optional(Type.String()),
                                   //    a2: Type.Optional(Type.String())
                                   // })

const NB = Type.Normalize(B)       // const NB = Type.Object({
                                   //    type: Type.Union([Type.Literal('B1'), Type.Literal('B2')])
                                   //    b1: Type.Optional(Type.String()),
                                   //    b2: Type.Optional(Type.String())
                                   // })
							 
const C = Type.Intersect([NA, NB]) // const C = {
                                   //	allOf: [{            <-- normalized A
                                   //      type: 'object',
                                   //      required: ['type'],
                                   //      properties: {
                                   //         type: {
                                   //            anyOf: [
                                   //              { const: 'A1' },
                                   //              { const: 'A2' }
                                   //            ]
                                   //         },
                                   //         a1: { type: 'string' },
                                   //         a2: { type: 'string' }
                                   //      }								   
                                   //   }, {                 <-- normalized B
                                   //      type: 'object',
                                   //      required: ['type'],
                                   //      properties: {
                                   //         type: {
                                   //            anyOf: [
                                   //              { const: 'B1' },
                                   //              { const: 'B2' }
                                   //            ]
                                   //         },
                                   //         b1: { type: 'string' },
                                   //         b2: { type: 'string' }
                                   //      }								   
                                   //   }]
                                   // }       
```

Hope that gives you a bit of an update on where things are at with this particular issue. The `0.24.0` release turned out to be quite a large undertaking that I've been slowly chipping away at over the past few months, so most of the efforts have been going into stabilizing the `0.24.x` additions (mostly for the new Compiler and Value APIs)

Apologies for the delay in getting this functionality solved. I do anticipate the `Type.Normalize()` to be ready either late this year, or early next, with the work to upgrade TypeBox's internals to use this API internally sometime after. Will try and aim for the `0.26.x` revision.

Cheers!
S

**Comment by SimenB** [comment]
Thanks for the in-depth update! Looking forward to it 🙂

**Comment by sinclairzx81** [comment]
@SimenB Hi!

Hey, I've got some good news to report on this issue. After much research into reconciling JSON Schema `allOf` with TypeScript intersection type inference (as well as retaining support for intersections + utility types), I finally have a workable solution to bring back the `anyOf` schema representation on 0.26.0. There is currently a development package published on NPM for integrators to test before release (sometime next week), you can test the functionality by installing the following version (any feedback most welcome)

```
$ npm i @sinclair/typebox@0.26.0-dev
```
I've also prepared some release notes on 0.26.0 at the link below (it's a very significant revision for the TypeBox project)

https://github.com/sinclairzx81/typebox/blob/next/changelog/0.26.0.md

So just on this issue, it actually turned out to be a VERY difficult problem to solve (with the solution essentially requiring a re-implementation of the TS type system on top of the TS type system, as well as implementing some of TS type system at runtime in the most compact implementation I can achieve while still remaining maintainable (24kb minified)). That said, having this issue finally solved actually brings TypeBox very close to an official 1.0 release (at long last)

In all, I'm pleased to say, the original code snippet posted with this issue should finally work again as expected! 

```typescript
import { Type, Static } from '@sinclair/typebox'

export const bodySchema = Type.Intersect([                // const bodySchema = {
  Type.Object({ ID: Type.Readonly(Type.String()) }),      //   type: 'object',
  Type.Union([Type.Object({ Event: Type.String() })]),    //   allOf: [{
]);                                                       //       type: 'object',
                                                          //     required: ['ID'],
                                                          //     properties: {
                                                          //       ID: { type: 'string' }
                                                          //     }
                                                          //   }, {
                                                          //     type: 'object',
                                                          //     required: ['Event'],
                                                          //     properties: {
                                                          //        Event: { type: 'string' }
                                                          //     }
                                                          //   }]
                                                          // }

type T = Static<typeof bodySchema>                        // type T = {
                                                          //   readonly ID: string;
                                                          // } & {
                                                          //   Event: string;
                                                          // }
```
Thanks for your patience on this one, Intersections in TypeBox have long been a difficult thing to get right (particularly aligning semantics between TS and JSON schema), but I do think the solution implemented on 0.26.0 should be very stable moving into the future. On the next release ill will be aiming for Runtime Mapped types (which I think might be feasible in the TS compiler), possible support for [JSON Type Definition](https://github.com/sinclairzx81/typebox/tree/next/example/typedef) and an official 1.0 sometime later in the year.

Cheers!
S

**Comment by SimenB** [comment]
Ah nice! I'll check it out Monday 👍

**Comment by SimenB** [comment]
Played around with it, and it works for our use cases 👍

**Comment by sinclairzx81** [comment]
@SimenB Hey, no problem, thanks for taking a look! :) 

Am aiming to publish out to NPM a bit later this week (likely Wednesday / Thursday). Just wrapping up on some integration and performance benchmarks prior to the release, so once these have been done, 0.26.0 should be good to go!

Thanks again, and all the best! :)
S

**Comment by sinclairzx81** [comment]
Hi @SimenB, 

Hope you're doing well. Hey, I wasn't sure the best way to reach out so pinging on this old issue. I wanted to notify you of a fairly significant update to TypeBox that is looking to introduce ESM + Common JS dual publishing support in the next minor revision (0.32.0). These updates are very significant and constitute a major push to get TypeBox to a 1.0.0 RC. As such, I have been trying to reach out to integrators to ask them to quickly review this revision prior to publishing, this just to help ensure things go smoothly. 

It's possible to install the development version with the following.

```bash
$ npm install @sinclair/typebox@0.32.0-dev-20 # or latest tagged dev revision on npm
```
I have prepared a changelog detailing the updates which you can find [here](https://github.com/sinclairzx81/typebox/blob/index/changelog/0.32.0.md).  I don't anticipate there being many significant breaking changes, but am hesitant about publishing the revision without giving integrators the opportunity to test first, particularly given the size of the update.

---

If you are able to give this revision a quick test / review, these are the things I'm very mindful of:
1) Ensure Common JS works fine as per previous revisions (with special attention given to Jest)
2) Ensure ESM can be resolved via `module` configuration in `package.json` (or `.mjs`)
3) Ensure TypeScript can resolve types correctly (CJS and ESNext configurations)
4) Ensure the package redistributable itself is acceptable (npm link [here](https://www.npmjs.com/package/@sinclair/typebox/v/0.32.0-dev-20?activeTab=code))
  4.1) Files: 47 > 912 (due to modularization of the type system + dual publishing)
  4.2) Size: 536kB > 1.36MB

---

On item 4), I am very keen to get some feedback on the way TypeBox is configured for dual publishing. Given the nature of the updates (modularization of the type system), this has resulted in an explosion of modules which are duplicated for the Common JS and ESM builds. I'm not certain of the accepted best practice here, and there isn't a lot of information out there on how to correctly dual publish /w types, but have implemented a technique referred to as `package-json-redirects` which is documented at the following URL

https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main/examples/node_modules/package-json-redirects

If you are able to take a look at the package and offer any feedback there, that would be very helpful. I'd be more than happy to make any amendments to the package prior to publishing if you notice anything that could be improved upon or changed.

---

I am aiming to get this revision out within the next few weeks (or sooner if there's good end user feedback). Hoping you're able to take a look and help give the green light to this revision.

Many Thanks
S

**Comment by SimenB** [comment]
Hey! 👋 Currently on vacation, but I can test when I'm back home next week 👍

**Comment by sinclairzx81** [comment]
@SimenB Hi! Thanks for getting back to me on this!

Anytime next week would be amazing! :) At this stage, I'm currently still pushing out npm `dev` revisions, but should have things relatively stable by the end of next week (so this would be the best time to start testing things out).

Any help with testing, package review or general feedback would be hugely appreciated this side. The updates for 0.32.0 are vast, but still aiming for backwards compatibility as much as possible, so if you spot anything out of place, please let me know.

Look forward to hearing back
Many thanks!
S

**Comment by sinclairzx81** [comment]
Hi @SimenB !

Hey, going to look at pushing out the 0.32.0 revision today. I think the changes here should be ok, and haven't seemed to have had any issues with CJS since upgrading the package to also support ESM. Importing the package natively across Node CJS and ESM environments and versions seems fine, but still mindful of bundlers and other auxiliary tooling correctly resolving for the package. From what I've been able to test, Everything seems to be working ok, but will be keeping an eye out for any issues post publish.

Still happy to get some feedback on this revision when you have some time. It's certainly a big update this one, and do want to make sure the package in moving in the right direction as gauged by long term users of the library, so do hope to hear back :)

All the best!
S

**Comment by SimenB** [comment]
Oh, I forgot about this 😅 I can test tomorrow (in about 12-14 hours), but looking at the manifest (without running any code) it looks correct to me 👍

**Comment by SimenB** [comment]
Can confirm `0.32.0` and `0.32.1` both works great for both ESM and CJS in Jest 👍

**Comment by sinclairzx81** [comment]
Hi @SimenB!

Hey, Thank you so much! I'm so happy to hear the new version is working ok !! (*phew*)

This was actually the first attempt I've had a go at dual publishing, so had been very mindful to avoid some of the pitfalls. So far, things seem to have gone well, but did have a small WebPack related issue https://github.com/sinclairzx81/typebox/issues/699 appear today (which I thought was quite interesting), but other than this, the deployment seems to have gone quite smoothly. Will be keeping an eye out for any tooling issues over the next while.

Btw, I highly recommend the [example-subpath-exports-ts-compat](https://github.com/andrewbranch/example-subpath-exports-ts-compat/) repository as an excellent resource for approaching dual publishing + types. There's several good approaches documented here, and can confirm, the [package-json-redirect](https://github.com/andrewbranch/example-subpath-exports-ts-compat/tree/main/examples/node_modules/package-json-redirects) technique appears to work very well, particularly to ensure type resolution continues to operate for developers who configure `tsconfig.json` with legacy `moduleResolution: 'node'`. I don't think I'd ever have been able to figure this out without the help of this repo :) 

Again, thank you so much for giving things a test. Hoping you have a great holiday and new years!
All the best!
S
