### ISSUE TITLE
Nesting Unions in Intersects doesn't work after upgrade from 0.23.5 -> 0.24.10

### ISSUE THREAD

**Issue by joemckenney** [sinclairzx81/typebox#194]
Upon upgrading typebox in our repo from [0.23.5 -> 0.24.10](https://renovatebot.com/diffs/npm/@sinclair%2ftypebox/0.23.5/0.24.10) the following nested types no longer work.  It seems like our `TObject` properties aren't being inferred as `TProperties`?  Here is a trivialized example/reproduction: 

```
const User = Type.Object({
  name: Type.String(),
});

const Workspace = Type.Object({
  id: Type.String(),
});

const Environment = Type.Object({
  name: Type.String(),
});

/*
0.23.5:  Worked
0.24.10: Broken w/ Error
  [tsserver 2739] [E] Type 'TUnion<[TObject<{ id: TString; }>, TObject<{ name: TString; }>]>' is missing the following properties from 
  type 'TObject<TProperties>': type, properties
*/
const test = Type.Intersect([User, Type.Union([Workspace, Environment])]);

```

**Comment by sinclairzx81** [comment]
@joemckenney Hi! This is a temporary limitation and breaking change in `0.24.0`. This change was due to a fairly significant restructure to support better composition elsewhere (e.g. `Intersect` can now be passed to `Pick`, `Omit`, `Partial`, `Required` and `KeyOf`) and to define minimal subset of JSON Schema 6 for the development of a runtime type checker.

There are plans to re-enable this functionality once the `0.24.0` release settles down a bit. For the time being, there are two workarounds options you can use if you need this form of composition.

## Option 1) Intersect first then Union

The following produces a structurally equivalent type by taking the intersection of `User & T` then applying the union at the top level.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAqiwxQ4AXhTCAdAHkRAKwwkYACgSy4cdgRAYAXLsx78UDgHMLASiyy5L4A3LLyispwAOrQANYsYAQkGNquGIYmZpbWMrbAACYuaG4e3n4BMkGhcjIKSvAAouwAbnyKjuzwOsXpRqbmVjZ2Ds5p7jCe7D7+gSFhtRHwyKk9eirswIoWANpDYwCSnRrqA9tqGjgxUPGJyQC6M7m2q4cwx1k751A4Ta207B0YA9ZMCakJMChUvgiKQADzgjAQKgoAB8834-DgCMhOkGMgxtkJ9kcLmUky81QJlAAZIhZATCXACqSJt5KZignAAD5wPEMokjFnk9kUOC0nL82zE0Zktn0jm+IA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const User = Type.Object({
  name: Type.String(),
});

const Workspace = Type.Object({
  id: Type.String(),
});

const Environment = Type.Object({
  name: Type.String(),
});

const T = Type.Union([
   Type.Intersect([User, Workspace]),
   Type.Intersect([User, Environment])
])

type T = Static<typeof T>

// type T = ({
//     name: string;
// } & {
//     id: string;
// }) | ({
//     name: string;
// } & {
//     name: string;
// })
```
## Option 2) Implement pre 0.24.0 Intersect using Type.Unsafe

The following re-implements the pre 0.24.0 schema representation using `Type.Unsafe()`. This allows for unions to be used inside intersections.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgE4CSAdjBlAM4YkwBKGAJgFcS2OM1YcuMAKIA3AgBtBRDHAC+cAGZQIIOAHIAAu2BMSCgsCgB6GOgwAjCAA99AWABQn69bgBaAMCg4JDQsPCIyKiw718AGQwAcwISVHE2Tm4AHmQAPjgACkEmDHklFX4ABR1MWGAMdjgoDABHQSsGuH4oAk14ACYABgBGAE4-QdGASlj-aPmFxaWIz08MZ0hYODtMMRYMqUoaOgBBKB7UHLh11iZ+RopqWgIAbQBdfIBePYlM3gFhBgssUANZMCAAdyYjH2km4ckUylYORw71yuVWHnWm3gpgkmhSqgSyVS6ThMAA8mBiBAmI0kMVSoiKtUILViA0APwALjgTggCgwBCY6kx2Og8BItPY8GJKTSsL+cG+VxuGDuDyOzzRBUUCgpml5LwAdKbkG8cGyaXTeXLSYqpFTrY1vgg1FNlfk0JhjQBVOm9IFkv5a07nAiXPK5ApIU3Gq3AaU4PUG9QzDxSunwX2cKDKlD2Y0UhwAKykMc8cDgTAIIAwvO9GGN+CgpkSBSmWE87oA3JifHNlkPhyOQrNpM5a2BBbNR3P50tMZmZXAAOrQEHsMCE-ONoul8sIStwYD8BuFlttjtdjy9pfS+DSJiyKy0ussXeF4tl7gVjxVms63PH1LyYdtO27KY+y8DMHxQfM7QVX5yxeHM2HIQt-UTJgChedcoE3bcRBwJ8Xx0Jh3xgN4pmo6DPB2VRkHzfAiFILIGIgTQUAxGCBwY+DXVmKsANres4BlVswOggcNAAMkKI8PAHYSTzPcSYEkxJpN8DQAB9ECE4TALEiS220tMgA)

```typescript
import { Type, Static, TSchema, IntersectReduce, IntersectEvaluate } from '@sinclair/typebox'

// --------------------------------------------------------------------------------------
// LegacyIntersect<T> (unevaluatedProperties requires draft 2019-09)
// --------------------------------------------------------------------------------------

export type IntersectSchemaArray<T extends TSchema[]> = IntersectReduce<unknown, IntersectEvaluate<T, []>>

export interface LegacyIntersectOptions { unevaluatedProperties?: boolean }

export const LegacyIntersect = <T extends TSchema[]>(allOf: [...T], options: LegacyIntersectOptions = {}) => Type.Unsafe<IntersectSchemaArray<T>>({ ...options, allOf })
const User = Type.Object({
  name: Type.String(),
});

// --------------------------------------------------------------------------------------
// Example
// --------------------------------------------------------------------------------------

const Workspace = Type.Object({
  id: Type.String(),
});

const Environment = Type.Object({
  name: Type.String(),
});

const T = LegacyIntersect([User, Type.Union([Workspace, Environment])]);

type T = Static<typeof T>

// type T = {
//     name: string;
// } & ({
//     id: string;
// } | {
//     name: string;
// })
```
Hope this helps!
S

**Comment by sinclairzx81** [comment]
@joemckenney Will close off this issue as this change was noted as breaking in the changelog for 0.24.0. As mentioned though, will revisit enabling intersecting unions in future, but for now will be recommending the `Type.Unsafe<T>(...)` implementation until the 0.24.0 release settles down.

Thanks for reporting. Please feel free to response on this thread if you have any questions on the above.
Cheers
S
