### ISSUE TITLE
TypeCompiler default Values not set

### ISSUE THREAD

**Issue by semoal** [sinclairzx81/typebox#203]
I'm using this `Type.Object` for my search requests, before with ajvPlugin automatically was setting up default values and we're not required inside the query params, now with the new compiler it is.

```ts
const DEFAULT_PAGINATION = Type.Object({
  limit: Type.Number({ default: 10 }),
  page: Type.Number({ default: 0 }),
});
```

# Crash:

```bash
TypeBoxValidationError: [['/page', 'Expected number'], ['/limit', 'Expected number']]
    at /Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/@fastify+type-provider-typebox@2.1.0_gwkzdqyjv2peluqydwem4oisyq/node_modules/@fastify/type-provider-typebox/dist/index.js:22:15
    at validateParam (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.2.0/node_modules/fastify/lib/validation.js:79:36)
    at validate (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.2.0/node_modules/fastify/lib/validation.js:96:17)
    at preValidationCallback (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.2.0/node_modules/fastify/lib/handleRequest.js:90:18)
    at next (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.2.0/node_modules/fastify/lib/hooks.js:168:7)
    at handleResolve (/Users/sergiomoreno/Projects/bridge-monorepo/node_modules/.pnpm/fastify@4.2.0/node_modules/fastify/lib/hooks.js:185:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      schema: { default: 0, type: 'number', [Symbol(TypeBox.Kind)]: 'Number' },
      path: '/page',
      value: undefined,
      message: 'Expected number'
    },
    {
      schema: { default: 10, type: 'number', [Symbol(TypeBox.Kind)]: 'Number' },
      path: '/limit',
      value: undefined,
      message: 'Expected number'
    }
  ]
}

```

**Comment by sinclairzx81** [comment]
@semoal Hi. Thanks for trying out the new compiler! :) Yes, this functionality is actually intended. The compiler only produces routines to check the value; 
but not change or mutate the value. This is inline with the JSON Schema meaning of `default`. See link and quote below.

https://json-schema.org/understanding-json-schema/reference/generic.html

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn’t required.

TypeBox does however offer a new `Value` namespace that uses `default` to instantiate and cast values. This namespace can also be used by clients. See documentation at link below.

https://github.com/sinclairzx81/typebox#Values

I guess as additional functionality like auto value initialization is above and beyond the type compiler itself, it may be a good addition to the TypeBox Type Provider project instead (which could implement this functionality to keep inline with Fastify)

Note though, there can be a performance cost auto initializing, so implementation should support opt in (as this functionality does go a bit outside spec definitions). But best for the Fastify team to review.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@semoal Hi

> If that functionality could be enabled with an option flag, would be amazing.

It might be worth submitting an quick issue on the https://github.com/fastify/fastify-type-provider-typebox project for this functionality. This project is actually external to Fastify, but the Type Provider package offers slightly tighter integration. Just drop an issue on that project and feel free to link back to this issue. The Fastify team can review there (ill keep an eye on it also)

> Also, another question I've tried to pass the number parameters but I get Expected a number, is this intended?

I think this might be due to Fastify passing strings for `query` parameters, but the compiler is checking specifically for numbers. Again, I'm not sure what default conversions Fastify does in this respect, but if Fastify does automatically map numeric strings to numbers for expected number types, this could also be a good thing to consider including on the Type Provider as a separate issue.

In the interim thought, you can try specifying the `DEFAULT_PAGINATION` type with the following properties (and custom `NumericString` type)

```typescript
const NumericString = Type.RegEx(/^(0|[1-9][0-9]*)$/)

const DEFAULT_PAGINATION = Type.Object({
  limit: NumericString,
  page: NumericString
});
```
Or optionally if you expect some of these query parameters to be optional.
```typescript
const NumericString = Type.RegEx(/^(0|[1-9][0-9]*)$/)

const DEFAULT_PAGINATION = Type.Object({
  limit: Type.Optional(NumericString),
  page:  Type.Optional(NumericString)
})
```
Unfortunately, this does mean you will likely need to manually parse these parameters as integers via `parseInt(req.query.limit)`, but the regex should provide some protections against invalid numeric strings.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@semoal Hey, will close off this issue and track things over at https://github.com/fastify/fastify-type-provider-typebox/issues/25

Cheers! :)
S
