### ISSUE TITLE
Type.Intersect with Refs

### ISSUE THREAD

**Issue by cjsewell** [sinclairzx81/typebox#206]
Pre 0.24 it was possible to use Intersect with refs:

```typescript
export const BaseSchema = Type.Object({
        prop1: Type.String(),
        prop2: Type.String(),
    },
    {
        $id: 'baseSchema',
    },
);

export const ExtendedSchema = Type.Intersect(
    [
        Type.Ref(BaseSchema),
        Type.Object({
            prop3: Type.String(),
            prop4: Type.String(),
        }),
    ],
    {
        title: 'extendedSchema',
        $id: 'extendedSchema',
    },
);
```

Now that Intersect only accepts TObject, how can we achieve a similar result?

**Comment by sinclairzx81** [comment]
@cjsewell Hi! Unfortunately, there is no way to directly compose for intersections of `TRef<TObject>` in the 0.24.0 release. This is a known breaking change (see changelog) and a consequence of some fairly broad internal structural changes to TypeBox. There plans to re-enable these kinds of intersections in future releases, but that work is not going to be ready for quite some time.

However 0.24.0 provides some other options.

#### IntersectAllOf

Because the 0.24.0 release handles Object intersection manually (which is the reason why `Type.Intersect` is constrained to types of `TObject` only). The 0.24.0 release instead provides ways reimplement user defined types, including reimplementing pre-0.24.0 schemas. The following is the current recommendation for intersection via `allOf` (i.e. pre-0.24.0)

```typescript
import { Type, Kind, Static, TSchema, SchemaOptions, IntersectReduce, IntersectEvaluate } from '@sinclair/typebox'

// --------------------------------------------------------------------------------------
// TIntersectAllOf<T> (unevaluatedProperties requires draft 2019-09)
// --------------------------------------------------------------------------------------

export type IntersectSchemaArray<T extends TSchema[]> = IntersectReduce<unknown, IntersectEvaluate<T, []>>

export type TIntersectAllOf<T extends TSchema[]> = ReturnType<typeof IntersectAllOf<T>>

export interface IntersectAllOfOptions extends SchemaOptions { unevaluatedProperties?: boolean }

export const IntersectAllOf = <T extends TSchema[]>(allOf: [...T], options: IntersectAllOfOptions = {}) =>
  Type.Unsafe<IntersectSchemaArray<T>>({ ...options, [Kind]: 'IntersectAllOf', allOf })


// --------------------------------------------------------------------------------------
// Example
// --------------------------------------------------------------------------------------

export const BaseSchema = Type.Object({
        prop1: Type.String(),
        prop2: Type.String(),
    },
    {
        $id: 'baseSchema',
    },
);

export const ExtendedSchema = IntersectAllOf(
    [
        Type.Ref(BaseSchema),
        Type.Object({
            prop3: Type.String(),
            prop4: Type.String(),
        }),
    ],
    {
        title: 'extendedSchema',
        $id: 'extendedSchema',
    },
);

type ExtendedSchema = Static<typeof ExtendedSchema>
```
#### Remove Type.Ref

Alternatively, you can remove the `Type.Ref(...)` from `ExtendedSchema`. This is generally inline with TypeBox moving forward (where each composited type yields a brand new type). This is generally ok if you do not intend to publish your schemas (as intersection of large objects results in increasingly larger output schemas)

```typescript
export const BaseSchema = Type.Object({
        prop1: Type.String(),
        prop2: Type.String(),
    },
    {
        $id: 'baseSchema',
    },
);

export const ExtendedSchema = Type.Intersect(
    [
        BaseSchema,
        Type.Object({
            prop3: Type.String(),
            prop4: Type.String(),
        }),
    ],
    {
        title: 'extendedSchema',
        $id: 'extendedSchema',
    },
);
```
Hope this helps
S

**Comment by cjsewell** [comment]
@sinclairzx81 thank you so much for your response.

I had initially removed the ref, and tried that approach, but I use typebox with [fastify-swagger](https://github.com/fastify/fastify-swagger) and generate client docs with [redoc](https://github.com/Redocly/redoc) and then client libraries with [openapi-generator](https://github.com/OpenAPITools/openapi-generator) in multiple languages from swagger.  
This resulted in a huge swagger json and a lot of redundant properties in the client libraries.

Your `IntersectAllOf` implementation is exactly what I was after and generates the same result as the old `Intersect`

Thanks again!

**Comment by sinclairzx81** [comment]
All good :) Will close off this issue for now. 

All the best!
S
