### ISSUE TITLE
Suggestion: More functionality support to Compiler

### ISSUE THREAD

**Issue by mooyoul** [sinclairzx81/typebox#213]
Hello there. 
I've been exploring better validation implementations and just realized that Typebox now provides built-in compiler for basic validation purposes.
It was awesome on first impression, and just realized it can be better.

### 1. Give more context about errors

Developers can read which value was failed validation by reading path field, why validation was failed by reading message field. which schema was used for validation. but currently there's no easy way to distinguish validation errors.

For example, I'm currently writing a webapp using React and I want to display customized validation text if validation was failed. There's a field that can be failed due to missing value, does not satisfy minLength/maxLength, etc. but validation errors cannot be distinguished - I don't know which rule (or keyword) was failed validation. Also it can be used for i18n purposes.

I think it would be okay by introducing a new field - `rule` (or `keyword`) - to `ValueError` interface.

### 2. Handle default value

Currently Typebox Compiler ignores `default` keyword and It would be great if compiler can handle default value.

I think Typebox Compiler a big potential - It's fast, It's simple, and It's small (This is super critical for modern SPAs - Compare bundle size between [ajv](https://bundlephobia.com/package/ajv@8.11.0) and [Typebox](https://bundlephobia.com/package/@sinclair/typebox@0.24.22))

### A letter

Congratulations for more popularity. I'm really happy that Developer Communities (e.g. fasitfy) show more interests about TypeBox. also Thank you for maintaining this awesome project. I've been used Typebox over 2 yrs in production, It has been foundation for our APIs. It successfully elimated a lot of manual works (e.g. writing validation logics, generating SDKs) and gave high productivity to our team. I'm still remember back day when I opened a PR regarding variadic tuple types :) You made it!

**Comment by sinclairzx81** [comment]
Hi @mooyoul! Good to hear from you! Also thank you for the kind words :) Yeah TypeBox gets a few downloads these days, but still managing to find ways to evolve the project over time. I'm glad to hear you're getting some good use out of the lib, and especially for server and API work (something I'm very interested in too).

> Hey side note, if you're interested in the server side of things, I've actually been putting together a small [service framework](https://github.com/sinclairzx81/sidewinder) on the side just to get some better insights into how TypeBox can be better  integrated into downstream web service infrastructure. A lot of the new functionality in the `0.24.x` release (compiler included) was informed by the work being done on this project. Would be keen to get your thoughts! [TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AAmGA7sAHa1QD0AxhIzFAIbswSAWABQoSLERwA6hgBGAZQjsA1hhgKMUAG7B2WXASKlKNekxasKW7VuFjw0eElmLlamAGEANsAzccfEJicipaBmYtDl9-QVFRVlY4AFpUtPSMzKzsnNy8nISkzy4efhhClPyq6pra9PiRTkYKeGLuPgE4AF4UdAwAOjbSgQAKBFE4SbhrHS0ALkQJqeWSXmpqEgW0TH6AMQBXRgFgLhGAbW2BgDl9kDktEYBKABpenZu7h8eAXVfL-o+9ygT0eS0m2FE2FBIgqdTh8IRyQqmh0eiwIyuEFo0MSlUR+IJWQaTRa0xsaO6cEY9Bk8iUqnUKN0+hGQw6MGhohmzIGIHUAAssSNVusSK8RuwYtwAJLUV68V5yR7dAB8ixEy1xyymgCBSbX6vXanVguBag36o36wAopIAAUjtcDAvD4IAocBGvAWjFuQMVnu9WmhmqSFsNFsmxo1UzNlrDk1t9sOwAAjvssJK-AEzNxgHg-FATdHlhGg2H4za4HyYILqFTeHy4Ew8FooBga0ZiE1huVI5NEgXWP3tYAYUjt5ZbMH2UEYDcYTagLZrvFdAAMvZ8oMvB0WTePJ9PeHAANRwORwSGckS4wnXm8VHwZ+AYrEYV4AIUIdBmOKSN9-+OJXCkumsSUtSdC0m4DJeFKMCsiU7KvCQn5zIk-Rof0JAXiS8AthQ+zePAPS8HQvDAPAwHcP07C8N43jCmsGyvAAjMx35FrGHHmmGEbRqGnGcXx2plnAToAOa3LErpLm6lbVgsLRQEwonyn666+lS-pQGxur8bpeoVDpumccJslYrW9aNs2rZBMYnbsgZ4YOXAwm4fh8DACua5AsuQA)

## 1. Give more context about errors

Yes! I've actually been given this some thought, but likely won't be ready till the next release. To support i18n, my current thinking is that the `ValueError` object should include additional `code` and `params` properties. This should allow users to localize the core validation messages generated by TypeBox, but also allow custom error messages to override the core messages if necessary. The following is the high level idea.

### Example

```typescript
import { Value, ValueError } from '@sinclair/typebox/value'

export enum ValueErrorType { // exported enum from '@sinclair/typebox/value'
  NumberMinimum = 100,
  NumberMaximum = 200
}

const T = Type.Object({
  x: Type.Number({ minimum: 32, errorMessage: '사용자 정의 오류 메시지' }),
  y: Type.Number({ maximum: 32 })
})                                                 

const errors = [...Value.Errors(T, {  // const errors = [{
  x: 16,                              //   type: 100,
  y: 64                               //   params: [32],
})]                                   //   schema: { type: 'number', minimum: 32, errorMessage: '사용자 정의 오류 메시지' },
                                      //   path: '/x',
                                      //   value: 16,
                                      //   message: 'Expected number to be greater or equal to 32'
                                      // }, {
                                      //   type: 200,
                                      //   params: [32],
                                      //   schema: { type: 'number', maximum: 32 },
                                      //   path: '/y',
                                      //   value: 64,
                                      //   message: 'Expected number to be less or equal to 32'
                                      // }]
									  

// -----------------------------------------------------------------------
// Localization
// -----------------------------------------------------------------------
export function LocalizeMessage(error: ValueError) {
  if((error as any).errorMessage) return (error as any).errorMessage
  switch(error.type) {
    ValueErrorType.NumberMinimum: return `예상 숫자는 ${error.params[0]}보다 크거나 같을 것으로 예상됩니다. ${error.value}를 받았습니다.`
    ValueErrorType.NumberMaximum: return `${error.params[0]}보다 작거나 같을 것으로 예상되는 숫자. ${error.value}받았습니다.`
    ...
  }
}
	
const localized = errors.map(error => ({...error, message: LocalizeMessage(error) }))
```
I may also consider setting up a separate project similar to https://www.npmjs.com/package/ajv-i18n where users can map errors via local codes, maybe something like.
```typescript
import { Locale } from '@sinclair/typebox-locale'

const errors = [...Locale('FR-fr', Value.Error(T, {...})]
```
## 2. Handle default value

Ah, not handling `default` was actually by design. I decided to leave this out of the compiler for performance reasons, but also based on the semantic definition of `default` described at the link below.

https://json-schema.org/understanding-json-schema/reference/generic.html

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value. However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value. The value of default should validate against the schema in which it resides, but that isn’t required.

Instead, TypeBox has a slightly different interpretation to AJV in this respect. Rather than providing options to `useDefault` inside the compiler itself, TypeBox instead provides a separate `Value` API which uses default for generative values. The following is the basic usage which is partially inspired by C# [default value expressions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default).

```typescript
import { Value } from '@sinclair/typebox/value'

const T = Type.Object({
  x: Type.Number({ default: 1 })
  y: Type.Number({ default: 2 })
})

// -----------------------------------------------------------------------------------
// Value.Create(...) will create values from types and use `default` if specified
// -----------------------------------------------------------------------------------

const A = Value.Create(T)                // const A = { x: 1, y: 2 }

// -----------------------------------------------------------------------------------
// Value.Cast(...) will fill in missing values and and truncate if necessary
// -----------------------------------------------------------------------------------

const B = Value.Cast(T, { x: 3 })        // const B = { x: 3, y, 2 }

const C = Value.Cast(T, { z: 4 })        // const C = { x: 1, y, 2 }
```

The `Value.Cast(...)` function is an immutable operation and always produces a new value. I felt this design was slightly more flexible as `Value.Cast(...)` can be useful for non-validation purposes (such as data migration), but also allows one to express Ajv `{ useDefault }` functionality in the following way...

```typescript
// -----------------------------------------------------------------------------------
// Creates a { useDefault } like validator
// -----------------------------------------------------------------------------------

function createValidator<T extends TSchema>(schema: T) {
    const C = TypeCompiler.Compile(Type.Partial(T)) // Accept partial objects of T
    return (value: unknown): Static<typeof T> | undefined => {
       if(!C.Check(value)) return undefined // or throw
       return Value.Cast(T, value) // fill in missing values
    }
}

const C = createValidator(Type.Object({
  x: Type.Number({ default: 1 })
  y: Type.Number({ default: 2 })
}))

const A = TC({ x: 100 })                        // const A = { x: 100, y: 2 }
```
## TypeCompiler and Ajv

There's been quite a bit of interest in the new TypeCompiler (which is great!), but should provision the new compiler is still very new and I think for most server cases, using Ajv will likely be the better option for many projects. The compiler itself was mostly written to help accelerate Web Socket message throughput in some of the applications I write (so quite niche) and make applications start faster (AJV can be a little slow when you have many large schemas to compile). However, overall Ajv does provide a wealth configurations and supports the full JSON schema spec so may be the preference for the short term.

At this stage, the TypeCompiler and Value API's are offered in a useable first release state. I plan to enhance functionality and performance over the next few releases (with the next immediate thing being localization support). I'm always very keen to get community feedback on ways to make the TypeBox (and now it's compiler) better / faster and more lightweight. 

Thanks for getting in touch! Also yeah, I still remember your AWESOME variadic tuple PR from a few years back! That really made a huge difference to reducing a lot of the complexity in TypeBox's inference logic. Still hugely appreciative of that PR :)

All the best!
S

**Comment by sinclairzx81** [comment]
@mooyoul Hi. Have just pushed an update on `0.24.23` that includes a new `type` property that can be used to localize error messages. An example of mapping error messages to French can be viewed below (note that the dependent property on `ArrayMinItems` can be obtained from the `schema` property passed on the error.

```typescript
import { ValueErrorType } from '@sinclair/typebox/error'

const errors = [...C.Errors({...})].map(error => {
  // optional override if users pass an errorMessage on the schema
  if(error.schema.errorMessage) return { ...error, message: error.schema.errorMessage } 
  switch(error.type) {
    case ValueErrorType.ArrayMinItems: 
      return { ...error, message: `Attendu au moins ${error.schema.minItems} éléments`}
    case ValueErrorType.Boolean: 
      return { ...error, message: 'Booléen attendu' }
    case ValueErrorType.String: 
      return { ...error, message: 'Chaîne attendue' }
    case ValueErrorType.Number: 
      return { ...error, message: 'Nombre attendu' }
    // ... 
    default: 
      return error
})
```
The following is the full list of mappable errors. I imagine a full set of locales could be implemented in an external library similar to https://www.npmjs.com/package/ajv-i18n. May look into this in future (but could use some help setting them all up)
```typescript
// -------------------------------------------------------------------
// ValueErrorType
// -------------------------------------------------------------------

export enum ValueErrorType {
  Array,
  ArrayMinItems,
  ArrayMaxItems,
  ArrayUniqueItems,
  Boolean,
  Function,
  Integer,
  IntegerMultipleOf,
  IntegerExclusiveMinimum,
  IntegerExclusiveMaximum,
  IntegerMinimum,
  IntegerMaximum,
  Literal,
  Null,
  Number,
  NumberMultipleOf,
  NumberExclusiveMinimum,
  NumberExclusiveMaximum,
  NumberMinumum,
  NumberMaximum,
  Object,
  ObjectMinProperties,
  ObjectMaxProperties,
  ObjectAdditionalProperties,
  Promise,
  RecordKeyNumeric,
  RecordKeyString,
  String,
  StringMinLength,
  StringMaxLength,
  StringPattern,
  TupleZeroLength,
  TupleLength,
  Undefined,
  Union,
  Uint8Array,
  Uint8ArrayMinByteLength,
  Uint8ArrayMaxByteLength,
  Void,
}
```

**Comment by sinclairzx81** [comment]
@mooyoul I think ill close off this issue as the errors now include a mappable `type` property. I may look at a `i18n` translation library in future, but for now I think TypeBox should be offering enough to realize that functionality down the road.

On the `default` value functionality, im fairly happy with the current design as users integrating TypeBox should be able to implement this functionality via `Value.Cast(T, ...)`. This is similar to AJV `{ useDefault }` but requires one to explicitly code the logic for it (which I tend to prefer explicit over implicit where-ever possible)

Thanks again for your suggestions and kind words. Hoping to get TypeBox to a version 1.0 one of these days, and every suggestion bit of feedback helps!

All the best!
S
