### ISSUE TITLE
Value API support for Deno

### ISSUE THREAD

**Issue by AndresPrez** [sinclairzx81/typebox#216]
The Value API and I think anything not exported from  the `src/typebox.ts` file cannot be imported in deno at the moment.

Could it be easily possible do so?

**Comment by sinclairzx81** [comment]
@AndresPrez Hi. Unfortunately only `src/typebox.ts` is supported in Deno at this stage. I haven't yet found a way to provide support for Deno that wouldn't either require duplication of the codebase, porting the codebase to Deno, or setting up an elaborate build process (i.e automating a Deno branch) to make Deno work. 

### The Problem

The problem mostly stems from Deno requiring module imports with the `.ts` specifier. The `.ts` specifier happens to be invalid from a TypeScript standpoint (as TS files are imported with a `.js` specifier in ESM), but necessary for Deno to be able to resolve modules over HTTP. Because there is currently friction between TypeScript and Deno in this regard, it has the unfortunate consequence pushing these problems back on library authors. I don't believe this is correct as Deno shouldn't need special handling due to a proprietary TS import scheme, even though the issue partially rests with an inability to configure the TypeScript compiler for this use case.

Some options I've considered:

- Propose that TypeScript support a `moduleResolution: 'deno'` flag that permits `.ts` specifiers. This is very unlikely as it rests under their stated non-goals. However there is an open issue https://github.com/microsoft/TypeScript/issues/37582 which may permit some more options.
- Propose Deno resolve either `.ts` or `.js` when importing files over HTTP with no specifier. This is likely untenable from Deno's standpoint as it would require potentially two HTTP requests for a single import, as well as lead to potentially ambiguous imports (for example if both `.ts` and `.js` files exist at the import endpoint)
- Ask `deno.land` to interpret modules imported with no-specifier as `.ts` imports and automatically 302 redirect to the `.ts` module. This might be possible as I believe Deno's module resolver does support 302 redirect.
- Publish via `esm.sh`. However it's unclear how `esm.sh` would handle sourcing necessary `.d.ts` files required for type inference.

I am actually very interested in providing these additional API's to Deno, but at this stage, it's just not clear on how best to proceed. Would be open to community thoughts around this, so will leave this issue open for discussion. 

Cheers
S

**Comment by sinclairzx81** [comment]
https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937

**Comment by sinclairzx81** [comment]
https://github.com/denoland/deno/discussions/9569

**Comment by nayeemrmn** [comment]
@AndresPrez This works:
```ts
import value from "https://esm.sh/@sinclair/typebox@0.24.27/value";
const { Value } = value;

console.log(Value.Create);
```

The following is _supposed_ to work, but the named exports are for some reason borked on both esm.sh and skypack:
```ts
import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value";

console.log(Value.Create);
```

**Comment by nayeemrmn** [comment]
Correction: the following works:
```ts
import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value/value";

console.log(Value.Create);
```

**Comment by sinclairzx81** [comment]
@nayeemrmn Thanks for this. Just to extend to a couple of other imports.

```typescript
import { Type, Static } from "https://esm.sh/@sinclair/typebox@0.24.27";
import { TypeCompiler } from "https://esm.sh/@sinclair/typebox@0.24.27/compiler/compiler";
import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value/value";

const T = Type.Object({
    x: Type.Number(),
    y: Type.Number(),
    z: Type.Number()
})

type T = Static<typeof T>

const instance = Value.Create(T)

const C = TypeCompiler.Compile(T)

console.log(C.Check(instance)) // true
```

**Comment by sinclairzx81** [comment]
Related issue to `esm.sh` exports

https://github.com/ije/esm.sh/issues/389

**Comment by sinclairzx81** [comment]
@AndresPrez Hey, I think moving forward `esm.sh` seems a pretty great option. It should be fine to use import scheme suggested by @nayeemrmn if you need this functionality today, however I will properly update the documentation inline with `esm.sh` once https://github.com/ije/esm.sh/issues/389 has been resolved.

Once resolved, this should mean imports can be changed from...

```typescript
// today
import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value/value"

// future
import { Value } from "https://esm.sh/@sinclair/typebox@0.24.27/value" // correct
```
### deno.land/x/

I will keep pushing tagged versions to `deno.land/x/` on each new release for existing users. I had briefly spoken to a few in Deno community around the idea of 302 redirect for non-specifier TS imports; and from my understanding this functionality was being considered, but should be considered tentative to the point of potentially not happening at all. I guess my view on this is that the ideal solution would be to have TS allow compilation with the `.ts` specifier (as an opt in) and that this solution would be best as it wouldn't require deno.land to introduce undue complexity on their side, but we'll see how things pan out.

For now, `esm.sh` looks like the best way. Will update and close off this issue once https://github.com/ije/esm.sh/issues/389 has been resolved.

Cheers
S

**Comment by sinclairzx81** [comment]
@AndresPrez Hi, have tested the following imports today, and they should be working ok. Had some problems importing the TypeCompiler, but this seems to have resolved itself. Import links are below.

```typescript
import { Conditional } from 'https://esm.sh/@sinclair/typebox/conditional'
import { TypeCompiler } from 'https://esm.sh/@sinclair/typebox/compiler'
import { TypeGuard } from 'https://esm.sh/@sinclair/typebox/guard'
import { Value } from 'https://esm.sh/@sinclair/typebox/value'
import { Type, Static } from 'https://esm.sh/@sinclair/typebox'
```
Have updated the documentation inline with the `esm` import and will recommend this for the foreseeable future. Are you able to test these imports your side to confirm things are ok. Will look to close off this issue within the next day or so.

Cheers
S

**Comment by sinclairzx81** [comment]
@AndresPrez Hey will close off this issue for now. Feel free to reply on this thread if you run into any problems. 

Cheers

**Comment by AndresPrez** [comment]
Thanks @sinclairzx81 sounds good. Btw yes, esm.sh works great.

**Comment by PkmX** [comment]
There seems to a gotcha that `https://esm.sh/@sinclair/typebox`, `https://esm.sh/@sinclair/typebox/value`, `https://esm.sh/@sinclair/typebox/compiler` all package their own instance of `TypeRegistry`. So `Value.Check` won't be able to find the custom type you registered via `TypeRegistry.Set(...)`.

**Comment by sinclairzx81** [comment]
@PkmX Hi! This is a good find. 

It might be worth pinging the `esm.sh` project about this https://github.com/esm-dev/esm.sh as this looks like a bug. It's true that the `Value` and `TypeCompiler` modules import the `TypeRegistry`, but they should be importing from the same path (meaning Deno should instance the module once only)

Did you want to submit an issue?

**Comment by PkmX** [comment]
A quick search seems to find quite a few similar issues, such as esm-dev/esm.sh#16.

**Comment by sinclairzx81** [comment]
@PkmX I've submitted an issue https://github.com/esm-dev/esm.sh/issues/741 so will see how things go.

There's not much I can do on the TypeBox side to resolve the issue, but the expectation here is that esm.sh should generate cache-able import paths (such that the `typebox.ts` module is observed once, irrespective of submodule import), but not to sure of the technicalities around this.

Will keep an eye on this.

**Comment by PkmX** [comment]
For the record, I ended up switching to import from `https://deno.land/x/typebox` and manually adding the `.ts` extension redirect via import maps, which works correctly with a single shared `TypeRegistry`, at least for now.
