### ISSUE TITLE
Support for TS `extends`

### ISSUE THREAD

**Issue by satvik-s** [sinclairzx81/typebox#217]
Not a major/important thing but wondering if supporting some syntactic sugar equivalent to the TS `extends` keyword has been thought of?

example: if I have the following type in TS
```typescript
interface BaseType {
  ab: number;
}

interface FinalType extends BaseType {
  cd: string;
}
```

to create something similar in typebox, I think there are two approaches. 

Approach 1
```typescript
const BaseType = {
  ab: Type.Number(),
};

const FinalType = Type.Object({
  cd: Type.String(),
  ...BaseType,
});
```

Approach 2
```typescript
const BaseType = Type.Object({
  ab: Type.Number(),
});

const FinalType = Type.Intersect([
  BaseType,
  Type.Object({
    cd: Type.String(),
  })
]);
```

Is there any other approach that might be better than the above two? In either case, is it worth adding the support for something like the following:

```typescript
const BaseType = Type.Object({
  ab: Type.Number(),
});

const FinalType = Type.Extends(BaseType, Type.Object({
  cd: Type.String(),
}));
```

**Comment by sinclairzx81** [comment]
@satvik-s Hi! Yes, `Type.Extends(...)` had been considered previously, however I felt it was better to express class inheritance through type intersection (as per Approach 2). There are a few reasons for this, but one of the main ones is that type intersection generally provides a more flexible way to structurally compose types while still enabling one to express class like inheritance. Consider the following.

```typescript
{
  class A { a: number = 0 }
  class B extends A { b: number = 0 }
}
{
  type A = { a: number }
  type B = { b: number } & A // B is the same as B extends A
}
```
The other reason is due to some future plans to possible enable conditional type mapping in the library, in this respect, the `extends` function is somewhat reserved for future use to enable the following.

```typescript
type T = string extends number ? true : false // type T = false
//              ^ reserved
```
TypeBox currently provides experimental support for conditional type mapping, however I'm looking for ways to reduce the code overhead before making this functionality standard (replicating TypeScript equivalence checks at runtime can be fairly involved). But you can try it out here.

[TypeScript Link Here](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYWwDg9gTgLgBAbzgYQgOwCbBsdBDAGzgF84AzKCEOAcgAEBnYNAYwL2CgHoYBPMAKYAjCAA8uLdFhz4CNAFChIsRHAAq-ASXKVq9Jq3acemkaIXzJaBvDVwAvCinZcaQgDoAoqJgDMDAAo4Li44Kxt1B3UAGWwBKEIAHjJCBgEAPnk4dU13AGUYKGYAcwCASgAaLJzBdwA5AFcQIXjyquyNWtjfBIIAwoaBSurOgXdu+MIAlII0svkyoA)

```typescript
import { Conditional } from '@sinclair/typebox/conditional'
import { Type } from '@sinclair/typebox'

const T = Conditional.Extends( // const T = TLiteral<false>
  Type.String(),
  Type.Number(),
  Type.Literal(true),
  Type.Literal(false)
)
```
### Implementing Extends with Generics

Moving forward, the recommendation for creating specialized types will be to either use [Generic](https://github.com/sinclairzx81/typebox#generic-types) types, or [Unsafe](https://github.com/sinclairzx81/typebox#unsafe-types) types. The `Extends` function can be safely expressed via Generic functions.

[TypeScript Link Here](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgPIBGAVhifAL5wBmUEIcA5AAIDOwAHYkANgWBQA9DHQYqEAB5cAUMowLIsVgFdhxCILgBRBTAyCAJnwA8AIQJ8McdWct8U1OgxwARDFGAANwwLZ1NzKw9aehgAPgAKKgcMAC44e0ccC38gkLS-AOCLAEpEZTg4KAwYbShDNEwAOgBJQTMoRwZ4gG0kzLhswpCAXWLlRlUSAz54AEE4AF4UWUbPGPikAjSGjEb8AMEAc3jSxjHlKcEZ9MXjcLd42fIVta6kKm2V-aFj0+LzmSYFC3fBEUjWQEYCAsdKxOCSSSIOBbOAzA6HODMABkSI+qJg6MxQA)


```typescript
import { Type, Static, TObject } from '@sinclair/typebox'

export function Extends<Base extends TObject, Derived extends TObject>(base: Base, derived: Derived) {
  return Type.Intersect([base, derived])
}

const A = Type.Object({ a: Type.String() })

const B = Extends(A, Type.Object({ b: Type.String() }))

type T = Static<typeof B> // { a: string } & { b: string }
```
Hope this helps!
S

**Comment by satvik-s** [comment]
Thanks for the clarification!

Understand the reasoning now and will close out the issue.
