### ISSUE TITLE
Convert Type.Union to array

### ISSUE THREAD

**Issue by rasmusrim** [sinclairzx81/typebox#237]
Would it be possible to have an easy way to convert a Type.Union to an array? 
For example:

```
const urgencyKeyArray = Type.Union([
  Type.Literal("notSet"),
  Type.Literal("resuscitation"),
  Type.Literal("urgent"),
  Type.Literal("lessUrgent"),
  Type.Literal("notUrgent"),
]).ToArray();

```

I know I can do

`UrgencyKey.anyOf.map((l) => l.const);`

It would just be nice to have a shorthand.

**Comment by sinclairzx81** [comment]
@rasmusrim Hi

The way you've mapped the const values is the intended way (as you're reading out values directly from the structure of a known underlying schema). Utility functions to extract certain data structures are best implemented outside of TypeBox as there could be a myriad of ways to express unions, and the `ToArray()` you described would only work for literals.

For example...

### OK
```typescript
const T= Type.Union([
  Type.Literal("notSet"),
  Type.Literal("resuscitation"),
  Type.Literal("urgent"),
  Type.Literal("lessUrgent"),
  Type.Literal("notUrgent"),
])
// This works for unions of literals
const values = T.anyOf.map((l) => l.const);
```
### FAIL
```typescript
const T= Type.Union([
  Type.Object({ x: Type.Number() }),
  Type.Object({ y: Type.Number() }),
])
// But fails for unions of objects
const values = T.anyOf.map((l) => l.const); // const will be undefined
```
It's because of this variability that a generalized `ToArray()` cannot be added to TypeBox. The `UrgencyKey.anyOf.map((l) => l.const);` mapping you have is fairly concise and readable. In terms of a utility like library to extract certain values from schemas, such a utility library should really target the JSON schema specification rather than TypeBox (as utils written for the JSON schema spec would be able extract values from TypeBox types, as these are based on the spec). 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@rasmusrim Will close off this issue as schema utility functions of this sort are considered out of scope.

Thanks for the suggestion tho.
S
