### ISSUE TITLE
feat: stricter version of "Cast"

### ISSUE THREAD

**Issue by jayalfredprufrock** [sinclairzx81/typebox#242]
Out of the gate, I'd just like to say this library is probably the most well designed and maintained (by a single person) I've come across in quite some time. Many thanks for this wonderful package, that I have a feeling will become the cornerstone of many more in the future. Now on to my self-serving interests :)

I'm in the process of replacing a large API that previously used hand-written json schemas (with derived typescript interfaces) and AJV for validation. 99% of the json schemas were only enforcing basic types and required/optional properties, making the whole setup overly complicated. Typebox (and accompanying compiler) is coming so close to fully replicating previous behavior while being a significantly better dev experience. That said, I have come across a few limitations that feel like they could be solved without bloating its intentionally limited/focused scope. 

This particular "feature" request has to do with the current "Cast" behavior. Originally I was looking for a way to replicate AJV's basic coercion rules and at first glance, "Cast" seemed to do exactly what I needed. But as I recently learned, it actually goes further than AJV's coercion rules and uses "Create" to produce values when a strict cast is not possible. The behavior that I would love to have is for "Cast" (with perhaps an explicit "strict" option or a new "Coerce" function) that behaved in the exact same way when a value could be "reasonably converted" and simply throw when it can't (instead of using "Create" to produce a new value).

**Comment by sinclairzx81** [comment]
@jayalfredprufrock Hi, thanks :) Glad you like the library! :)

Yeah, quite a few people have mentioned that they would like to use Value.Cast() for request validation (using it as an alternative Ajv's coercion rules). Originally, Value.Cast() was implemented to assist with data migrations and envisioned more as a non-optimized utility than something to be used in validation pipelines. But given the interest, I have been thinking of ways to allow Cast to be used in this way.

My preference would be to not make Cast() configurable in this way if possible; as Cast() should always produce a schema correct value (the same as Create()). Also I tend to prefer explicit logic over implicit for things of this nature. But maybe something like the following could work?

```typescript
// return true if no create is invoked but coercion checks succeed.
if(Value.Castable(schema, value)) { 
   return Value.Cast(schema, value)
} else {
   throw Error('Cannot cast schema')
}
```
In this respect, Castable() would act as kind of Check(), but where checking factors coercion rules implemented by Cast(). 

### Coercion Rules

Currently, string, number and boolean coercion is automatic for Cast() under the rule of "should always retain as much information from the original value as possible", however implementing this functionality as the default has resulted in some technicalities elsewhere which I'd like to mitigate if possible. In the next release of TB, Cast() may actually require configuration to opt into coercion rather than it being the default, so any design for Castable() or similar would also need to factor potential for configuration in this sense.

Happy to discuss more!
Cheers
S

**Comment by jayalfredprufrock** [comment]
Yeah I think the API you propose would be perfectly acceptable and open up the door for other use cases beyond data migrations. Really appreciate the discussion! I'll go ahead and close this since it sounds like such a feature is already on your radar.
