### ISSUE TITLE
feat: Flag to allow UnsafeType in Compiler

### ISSUE THREAD

**Issue by jayalfredprufrock** [sinclairzx81/typebox#243]
I was disappointed to find the lack of support for string enums. I'm pretty sure they've been a part of the official JSON schema spec for a while (don't quote me on that) but at the very least they are supported by most openapi doc and code generators so their use is fairly ubiquitous. Coming across https://github.com/sinclairzx81/typebox/pull/172 , I understand why the decision was made and was happy to find the workaround using UnsafeType. What I didn't realize is that its use entirely prevents using the Compiler. (The docs sort of hint at it, but make it sound more like a recommendation than a requirement). 

Anyways, would you consider a flag that would allow the unsafe type to essentially skip validation? My main reason for needing the "enum" type is actually more for generating docs and API clients and less about validation. Pulling in AJV to handle this one discrepancy would be unfortunate, especially because the increased Typebox compilation speed is definitely noticeable in a large NestJs application I'm working on.

Additionally, allowing a custom validator to be registered for UnsafeTypes would be incredibly powerful and truly provide a path for those looking to go all in on Typebox without requiring you to deviate from the specs and/or your vision for the library.

**Comment by sinclairzx81** [comment]
@jayalfredprufrock Hi. Yes, currently the TypeCompiler is limited to types where the structure of the schema is known in advance (essentially the standard subset listed [here](https://github.com/sinclairzx81/typebox#types-standard)). However there are plans to enable unsafe types in both Value.Check() and TypeCheck.Check() validation paths.

> Anyways, would you consider a flag that would allow the unsafe type to essentially skip validation?

I think it's probably better to provide a mechanism to validate unsafe types rather than ignore them outright, so wouldn't be keen on adding the option to skip them. Unfortunately unsafe type validation is still a fair way off (though it is being considered for the next minor release 0.25.x), For the time being I would recommend keeping on with Ajv if you need to express schemas with unsafe types. (despite the downshift in compilation performance)

Initial thoughts on Unsafe type validation were briefly drafted https://github.com/sinclairzx81/typebox/issues/244#issuecomment-1246501728, however there is still quite a bit of design work to do as unsafe types would need to integrate into Value.Create() and Value.Cast() in some capacity.

Open to ideas and thoughts on the design of this functionality!
Cheers
S

**Comment by jayalfredprufrock** [comment]
Glad to know such a feature is still being considered! We can continue discussion in #244. Thanks!
