### ISSUE TITLE
Compatibility with Cloudflare Workers

### ISSUE THREAD

**Issue by unvented** [sinclairzx81/typebox#253]
I'd like to use TypeBox in Cloudflare Workers, but i keep getting the below error.

```
Unhandled Promise Rejection: EvalError: Code generation from strings disallowed for this context
```

Is there any way to work around this?

**Comment by sinclairzx81** [comment]
@unvented Hi.

You can use `Value.Check(T, value)` instead of compiling with the TypeCompiler. The `Value.Check(T, value)` function will carry out the same runtime checks as the compiled version, however it uses dynamic type checking; which means you will lose out on the performance optimizations you get through compilation (but is relatively still quite fast to use)

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
   x: Type.Number(),
   y: Type.Number(),
   z: Type.Number()
})

const value = { x: 1, y: 2, z: 3 }

if(!Value.Check(T, value)) {
  const errors = [...Value.Errors(T, value)]
  console.log(errors)
}
```

Alternatively, if you want to retain the performance, you can inspect the compiled validation routine with the `TypeCheck.Code()`. To use this, you will need to precompile the schemas first as a build step. 

```typescript
const T = Type.Object({
   x: Type.Number(),
   y: Type.Number(),
   z: Type.Number()
})

const C = TypeCompiler.Compile(T)

console.log(C.Code()) // use this code to validate
```

Hope that helps
S

**Comment by unvented** [comment]
@sinclairzx81 thank you so much <3
