### ISSUE TITLE
Equivalent usage of JSON.validate on deno

### ISSUE THREAD

**Issue by luislve17** [sinclairzx81/typebox#254]
First of all, amazing work on _typebox_  and its documentation. Looking forward to work with this in production env 💪🏻 
Currently using deno 1.25, and was wondering how I'm suppose to validate a recently-created and casted type with my JSON `value` as in the example provided:
```ts
function receive(value: T) {                         // ... as a Type
  if(JSON.validate(T, value)) {                      // ... as a Schema 
    // ok...
  }
}
```

```ts
> JSON.validate()
Uncaught TypeError: JSON.validate is not a function
    at <anonymous>:2:6
> 
```

Thanks in advance

**Comment by sinclairzx81** [comment]
@luislve17 Hi, `JSON.validate(...)` is just a stand-in for "insert your validator here". TypeBox is based on the JSON Schema specification, so any JSON Schema validator should work, however have a read over the following.

https://github.com/sinclairzx81/typebox#ajv
https://github.com/sinclairzx81/typebox#typecheck-compiler
https://github.com/sinclairzx81/typebox#check

Hope this helps.
S

**Comment by luislve17** [comment]
Nice, I definitely will.
Thank you!

**Comment by jtlapp** [comment]
> `JSON.validate(...)` is just a stand-in for "insert your validator here"

It would be helpful to state this the docs so we're not off googling and searching this repo for where the heck this method comes from.

**Comment by ehaynes99** [comment]
`JSON.validate` isn't valid... anywhere. You can't even monkey patch `JSON` safely because it's not a regular object, so this is a poor example. Having to scroll all the way down to the [typecheck](https://github.com/sinclairzx81/typebox#typecheck) section to see any actual use for the library really limits the curb appeal. The "Usage" section should contain at least a basic example of parsing a JSON string and parsing a js Object.
