### ISSUE TITLE
Question: Comments on static types

### ISSUE THREAD

**Issue by jsbrain** [sinclairzx81/typebox#260]
I was wondering if you think there is a way to have property comments reflected on the `Static<>` type, e.g.:

```ts
const testSchema2 = {
  /** This is some property. */
  someProp: 'test',
};
type TestType2 = typeof testSchema2;
export const testObj2: TestType2 = {
  someProp: 'test'
};
```

So when I "normally" infer a type from an object, I will receive the comments in the intellisense like so:

<img width="343" alt="Screen Shot 2022-10-14 at 10 24 37" src="https://user-images.githubusercontent.com/20225909/195799490-6b0f4f00-f643-46e5-9489-289eb48a660f.png">

But when I do it as a typebox schema:

```ts
const testSchema = Type.Object({
  /** This is some property. */
  someProp: Type.String(),
});
type TestType = Static<typeof testSchema>;
export const testObj: TestType = {
  someProp: 'test',
};
```

And in the inferred type, the comments aren't present anymore:

<img width="579" alt="Screen Shot 2022-10-14 at 10 24 49" src="https://user-images.githubusercontent.com/20225909/195799627-824ac036-80d4-4cc3-a2ef-eb111707a5d0.png">

Any idea if this would be possible?

**Comment by sinclairzx81** [comment]
@jsbrain Hi. I have looked into this before https://github.com/sinclairzx81/typebox/issues/150#issuecomment-1030143472, but didn't find a good approach to make it work. TypeScript is actually able to create mapped objects types where each property retains the properties doc comment, but this only really works for really simple cases.

The issue getting this to work in TypeBox most stems from needing to decompose a object into 4 separate object types, `readonly`, `readonly-optional`, `optional` and `required`. These 4 types are then intersected together to produce the correct output type. This decomposition strategy enables TypeBox to inference properties modifiers correctly `Type.Optional()`, `Type.Readonly()`, etc, but because of the decomposition, the comments applied to the each property are lost.

So, I don't think this is possible (at least not without introducing a fair amount of additional complexity / compute overhead to the current strategy). However the code to handle this inference logic can be found [here](https://github.com/sinclairzx81/typebox/blob/master/src/typebox.ts#L291-L301) if you want to experiment. I should also note that this inference strategy dates back to the very early versions of TypeBox, and there may be alternative approaches possible today...

**Comment by jsbrain** [comment]
Thank you @sinclairzx81 for this detailed explanation, I already expected something like that ...
I might actually look into this at some point and see if there is a solution and get back to you if I find anything.
Will close this for now.
