### ISSUE TITLE
Type.Optional + default value should generate a non optional type

### ISSUE THREAD

**Issue by celio-rodrigues-ib** [sinclairzx81/typebox#279]
Consider the following enum:
```
enum MyEnum {
  ONE = 'one',
  TWO = 'two',
}
```

And the following typebox:
```
const myType = Type.Enum(MyEnum, {
  default: MyEnum.ONE,
})
const mySchema = Type.Object({
   myNum: Type.Optional(myType)
})
```

It will generate the following json schema:
```
const schema = {
   type: 'object',
   properties: {
      myNum: {
         type: 'string',
         enum: ['one', 'two'],
         default: 'one'
      }
   },
   required: []
}
```

And it should generate the following type:
```
type schemaType = {
   myNum: MyEnum
}
```

But it is generating myNum as optional:
```
type schemaType = {
   myNum: MyEnum | undefined
}
```

If the client doesn't send `myNum` value, it will be populated with the default value mentioned in the schema, so it won't be undefined in any scenario.

Awesome joob with Typebox, it's amazing!! :)

**Comment by sinclairzx81** [comment]
@celio-rodrigues-ib Hey, might close off this issue as I think TypeBox is working to spec here. 

Feel free to reply on this thread if you have any follow up queries or suggestions on the `default` property. Note, the current design is largely informed by the quote from the JSON Schema reference guide (above) so do need to largely align to that, but open to reviewing ideas around how to improve TypeBox to better accommodate varying validator configurations in future, so always happy to discuss ideas and suggestions from the community. 

For now though, will close off this issue.

All the best!
S

**Comment by celio-rodrigues-ib** [comment]
I understand your point, so if I know that the validator will fill the default value as you said in your example:
```
// Write the type this way if you know the validator will use defaults
const T = Type.Object({
   x: Type.Number({ default: 1 }),
   y: Type.Number({ default: 2 }),
   z: Type.Number({ default: 3 })
})
```

It will generate a correct type (non optional), but request will fail because the property is now required in the schema (so I'll need to send it everytime, what makes default useless here).

Isn't it possible to add an optional configuration to `Type.Optional(..., { hasDefaultValue: true })` or maybe create a new `Type.OptionalWithDefault()`, so we can decide if the type is going to be optional or not, based on our server configuration? So, in that case, it will generate an optional property in the schema, but it won't be optional in the typings.

Because if we can't, the type won't reflect 100% of the reality and we would need to add a property validation in the code to ensure it isn't undefined.

**Comment by sinclairzx81** [comment]
Hi,

> It will generate a correct type (non optional), but request will fail because the property is now required in the schema (so I'll need to send it everytime, what makes default useless here).

Hmmm, are you sure the request will fail? I would expect validators that support patching defaults values on validate to automatically include these values if they are not defined. So for example.

```typescript
const T = Type.Object({
  x: Type.Number({ default: 1 }),
  y: Type.Number({ default: 2 }),
  z: Type.Number({ default: 3 })
})

// { x: 4, y, 4 } > [validate with defaults] -> { x: 4, y: 4, z: 3 }

// { x: 4, y, 4 } > [validate without defaults] -> error: missing required property 'z'
```
It would be good to check this (note: I'm not very familiar with how Ajv handles patching default on validation)

> Isn't it possible to add an optional configuration to Type.Optional(..., { hasDefaultValue: true }) or maybe create a new Type.OptionalWithDefault(), so we can decide if the type is going to be optional or not, based on our server configuration?

TypeBox only supports options that are part of the JSON schema specification. Because `hasDefaultValue` would be outside the specification, tying conditional inference to it wouldn't be feasible (both in terms of providing standard compliant code hints, and technically because it would need to push TS inference limits really hard). See [here](https://github.com/sinclairzx81/typebox/blob/master/src/typebox.ts#L312-L324) for the current logic handling `optional`, `readonly` and `readonly-optional` inference, it's quite complex.

In saying this, TypeBox does actually let you specify non standard options on the schemas, it's just you would need to implement your own custom logic to use it. So something like the following is supported.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQMoGMAWBTEBDAGjlRjxmHSOQE8xs4BfOAMyghDgHIABAZ2AB26ADZ5gUAPQxa2AEYQAHpwCwAKFCRYiFDIDiAVzxQAJoxZsOPfkNHipM+QokBzQyZXrw0eAEEAVgBu5uxceIEeahIScAC0cfEJiUnJKanJkdEAwvq8MCEYOPhwmexgwMLYUBmxabV19YlqatgKmvDM+kLkEAJw6KXl2AA8yHAtMNgCxrwoBbh4AHwAFLxY8wBcKACUm0sBeML62JudANYCEADuAltwALwLcPuH9MAzJGQUI4+IanBRcAASvMwHA8nAwEZyAc4MBmHBMHheAARbDMPD6YQwABqByOvCIEBgOCglze9FWhTwf36AlycHwYDopjucCWNDoBiMxgAdMgAPKyPzYdAwFZrfC3ABkUrglPmPMRKLRGKxuJeMzuWrBUCOtwA-Do6DyAApQ4AHcVU26bZB-AElATMYCuKD0fxBMnEuA5bCo9GYmC8Gk9elhIKsgTYS5wD1LJC+-2qoObGC6+gMLb2rIDCpwL2YBl4JnYYx-N0wfRQXrhnn9cCDJaM5lZ1QMJqqAENbs99Kd6IAUQUeHAFWqvYnvY7tPpo1ZHOwPMFwtF8bgfzgm4UtpkPIAcvoQLJKmvjCrA5sAIyMLYEDeb6g740Ho8npBngNYzYAJhvd9Um6bgAXk+i4vseUCnueX5wAAzDeagMEQSBKkmgbqviqbpghqjVDy+HTqG8BrOgpz3H0ubYOyrZqDO8DPEc5FINucDXu2uHqMwSwkacex4tgWy3AgHaAXR2gKEQ1BEEBZisgx9AAhAZExHASK8IepYQmQaxlgBgH6QZhn6QCAB6+qIUAA)

```typescript
import { TSchema, Static, Type } from '@sinclair/typebox'
import { TypeGuard } from '@sinclair/typebox/guard'
import Ajv from 'ajv'

// ----------------------------------------------------
// Custom Schema Compiler
// ----------------------------------------------------

export function compile<T extends TSchema>(schema: T): (value: unknown) => value is Static<T>  {
 // Remap to partial if hasDefaultValues, otherwise schema
 const mapped = (TypeGuard.TObject(schema) && schema.hasDefaultValues === true) ? Type.Partial(schema) : T
 // Configure Ajv with useDefaults
 const ajv = new Ajv({ useDefaults: true })
 // Compile with mapped
 return ajv.compile(mapped)
}

// ----------------------------------------------------
// Example
// ----------------------------------------------------

const T = Type.Object({ 
    x: Type.Number({ default: 1 }),
    y: Type.Number({ default: 2 }),
    z: Type.Number({ default: 3 })
}, { hasDefaultValues: true })

// ...

const check = compile(T)

const value = { x: 1 }

if(check(value)) {

   const { x, y, z } = value // ok - assumed patched
                       // ^?
}
```
So, the above can be refactored into something a bit more concise and integrated into your existing validation pipeline, it's just that TypeBox can't really assume too much of that pipeline and how it works (opting instead for schema mapping to get around disparities in non-standard validation behaviors). Schema mapping in this way is quite common though, here's another example from an [issue](https://github.com/sinclairzx81/typebox/issues/278) submitted yesterday using similar techniques to remap for deep partial)

Maybe just have a quick check to see what Ajv does in terms of patching default values, it it requires properties to be defined as optional, then you can use the `compile()` example above to get alignment to what you expect. I think given that there are many ways to interpret "patching default values", that does suggest there isn't too much TypeBox could do to align to each approach. 

Usually in cases like this, I find it's usually best stick to the specification !! :D

Let me know how you go with testing Ajv defaults
Cheers
S

**Comment by sinclairzx81** [comment]
Can confirm that Ajv will patch non-existent default values without needing to define them as optional.

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'
import Ajv from 'ajv'

export function compile<T extends TSchema>(schema: T): (value: unknown) => value is Static<T>  {
 const ajv = new Ajv({ useDefaults: true })
 return ajv.compile(schema)
}

const T = Type.Object({ 
    x: Type.Number({ default: 1 }),
    y: Type.Number({ default: 2 }),
    z: Type.Number({ default: 3 })
}) // not optional

// ...

const check = compile(T)

const value = { x: 1 }

if(check(value)) {
  
   console.log(value) // { x: 1, y: 2, z: 3 } - ok
}
```

**Comment by celio-rodrigues-ib** [comment]
Thank you for your answer @sinclairzx81 .

I found that AJV was correctly patching.

The issue was because I was using a reference to another schema:
```
const withDefault = Type.Number({ default: 1 })

Type.Ref(withDefault)
```

But AJV was still requiring for the property, so I found that I needed to add the default value again inside the reference:
```
const withDefault = Type.Number({ default: 1 })

Type.Ref(withDefault, {
   default: 1
})
```

Then it stopped complaining about missing the property value.
