### ISSUE TITLE
Type inference breaks when preHandler is defined

### ISSUE THREAD

**Issue by s1gtrap** [sinclairzx81/typebox#284]
I've been finding this library quite pleasant but I'm also using `@fastify/bearer-auth` and they seem to be in conflict as
```typescript
  fastify.post('/api/v1/reports', {
    schema: {
      body: Type.Object({
        stopId: Type.String(),
      }),
    },
    //preHandler: fastify.verifyBearerAuth,
  }, async (request, reply) => {
    if (!stops[request.body.stopId] === null) // ...
    // ...
  });
```
works fine until you uncoment the line with `preHandler`, in which case you get:
```
src/server.ts:127:15 - error TS18046: 'request.body' is of type 'unknown'.

127     if (stops[request.body.stopId] === null) {
                  ~~~~~~~~~~~~
```
I'm not sure what's happening here, are you not able to set preHandlers on top of schema validation? Is this even a typebox issue? Either way it's quite sad having to opt out of this but I'd have to choose authentication over static schema inference.

**Comment by sinclairzx81** [comment]
@s1gtrap Hi. This isn't a TypeBox issue, but perhaps the following will work?

```typescript
fastify.post('/api/v1/reports', {
  schema: {
    body: Type.Object({
      stopId: Type.String(),
    }),
  },
  preHandler: (request, reply) => fastify.verifyBearerAuth(request, reply) 
}, async (request, reply) => {
  const { stopId } = request.body
})
```
I believe the issue here is that the signature for `verifyBearerAuth` probably doesn't match the signature for `preHandler` (which you've configured for a TypeProvider). Because these signatures are different, when you assign the callback with `preHandler: fastify.verifyBearerAuth` it confuses TypeScript and breaks the provider inference logic (as the function generics are different). The workaround I believe is to explicitly write the `preHandler` callback in a way TypeScript can understand.

```typescript
preHandler: (request, reply) => fastify.verifyBearerAuth(request, reply)
//           |                                            |
//           |                                            +-- Request<..., TypeProviderDefault>
//           |
//           +--- Request<..., TypeProviderTypeBox>
```
Hope this helps.
S

**Comment by sinclairzx81** [comment]
Will close off this issue as it's unrelated to TypeBox.
