### ISSUE TITLE
Should Type.Record<Type.String(), ...> use additionalProperties?

### ISSUE THREAD

**Issue by smiley-uriux** [sinclairzx81/typebox#285]
Presently something like `Type.Record<Type.String(), Type.Number()>` uses `patternProperties` with a regular expression to match any string, though it looks like the deprecated type `Type.Dict()` used `additionalProperties` presumaby to support string unions.

While technically the `patternProperties` approach provides equivalent validation and enables an extra feature, semantically it's not really the same and is often treated differently in libraries that consume JSON schema for reasons beyond validation (i.e. API and doc generators, human readable error extractors, etc.). In general, these libraries don't make a special case for regular expressions like `^.*$` since that is just one of several regex expressions that could be mapped to "any string". 

Ideally Typebox would use `patternProperties` for the string literal union case and use `additionalProperties` for the simple string key case. Not sure if altering the output dynamically like that is something that would be messy or incompatible with the library. I realize I can achieve the behavior I want using `Type.Unsafe()` which is great. I only wanted to point out that I find the current behavior a little awkward since I would never hand craft a JSON schema to use `patternProperties` with a regex to represent any string when `additionalProperties` does a much better job of capturing the intent.

**Comment by smiley-uriux** [comment]
On a side note, could the string union literal case be handled with
```
{
    type: "string",
    enum: ["dog", "cat"]
}
```

I realize you steered away from using enum so you could capture unions of arbitrary types, however in this particularly case, only unions of string literals make sense, and again, consumers of JSON schema generally handle the `enum` keyword gracefully.

**Comment by sinclairzx81** [comment]
@smiley-uriux Hi, thanks for the suggestions and insights! 

### Records with additionalProperties

It's not currently documented anywhere, but TypeBox recently added a fallback for the `additionalProperties` representation of `Dict<T>`. It's possible to construct a `Dict<T>` in the following way.

```typescript
function Dict<T extends TSchema>(schema: T): TUnsafe<Record<string, Static<T>>> {
  return Type.Object({}, { additionalProperties: schema })
}

const T = Dict(Type.Number())
Value.Check(T, { x: 1, y: 2 })   // true
Value.Check(T, { x: 1, y: 'z' }) // false
```

### Should Record use additionalProperties by default?

I do think `patternProperties` is the better fit `Record<K, T>` mostly because it allows for user defined regular expressions for keys. 

```typescript
type T = Record<`prefix_${string}`, number>

const T = Type.Record(Type.RegEx(/prefix_.*/), Type.Number())
```

### String Enum

I still get a lot of questions about supporting `enum` for string literals, so will be looking into it again next year. To support them (and other representations), TypeBox really needs a more sophisticated composition framework running behind it. At this stage, the library only really wants to deal with one representation for "union like things" and adding multiple ways to express the same thing (i.e. `anyOf` vs `enum`) just adds too much complexity (and I'm not too keen on supporting complexity like that without having some framework in place to make maintaining tenable).

However, the following is the high level thinking to support string enum.  

```typescript
// Detect for idealized schema representation if possible.
//
const T = Type.Union([                               // const T = { enum: ['A', 'B'] }
  Type.Literal('A'),
  Type.Literal('B')
])
// Map idealized representation to compositional normative form
//
const N = Type.Normalize(T)                          // const K = {
                                                     //   "anyOf": [
                                                     //     { "type": "string", "const": "A" },
                                                     //     { "type": "string", "const": "B" },
                                                     //   ]
                                                     // }

// Only compose with normative form
//
const B = Type.Record(N, Type.String())              // const B = {  
                                                     //  "type": "object",
                                                     //  "properties": {
                                                     //     "A": { "type": "number" },
                                                     //     "B": { "type": "number" },
                                                     //  },
                                                     //  "required": ["A", "B"]
                                                     // }
```
The current types provided by TypeBox are all considered "Normative" or "Identity" for that representation, so much of the work involved would be developing a way to map the idealized representations into the normative form for composition (I'm sure some of this crosses over with Group/Category theory!). There's quite a bit of thinking going into this at the moment, but I don't expect things to be ready in TypeBox before 2nd quarter next year. However some of this work may emerge as a prototype in [this](https://github.com/sinclairzx81/sidewinder) project first.

Hope this helps! 
S

**Comment by sinclairzx81** [comment]
@smiley-uriux Might close up this issue as I'm pretty keen to keep `patternProperties` for `Record`. But let me know if the `additionalProperties` option describe above helps. Happy to discuss enhancing this functionality somewhat (mostly through providing an equivalent TS type to support structures like.

```typescript
const T = Type.Object({
   x: Type.Number(),
   y: Type.Number()
}, {
   additionalProperties: Type.String()
})

type T = Static<typeof T> // type T = { x: number, y: number } & { [key: string]: string } ?
```

Cheers
S

**Comment by smiley-uriux** [comment]
As always, I really appreciate your thoughtful and detailed responses! Your Dict example is also appreciated and exactly what I figured I would do to support my use cases.

Your reasoning for leveraging `patternProperties` is fair, although I generally leverage Typebox as my source of truth so the fact that `Type.Record(Type.RegEx(/prefix_.*/), Type.Number())` is inferred as `Record<string, number>` isn't particularly useful if the intent is to work with a type like `Record<'prefix_${string}', number>`.
