### ISSUE TITLE
Add a parse or ensure method to compiled schemas

### ISSUE THREAD

**Issue by dbartholomae** [sinclairzx81/typebox#289]
Hi there!

A very common pattern when using validation is to simply parse a value and throw an error if it has the wrong format, e.g.

```ts
const C = TypeCompiler.Compile(Type.Object({
  name: Type.String(),
  email: Type.String({ format: 'email' }),
}))

function loadUserFromDb(id: string) {
  const user: unknown = await database.loadUser(id);
  return C.ensure(user);
}
```

Would you be interested in a PR adding this? The `ensure` itself is quite simple (it checks whether the input is valid, if it is, returns it, and if it is not, throws an error with all the validation errors in it). For that, an [`AggregateError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError) might be a good choice.

The benefit is that in places where we do not expect problems, e.g. when reading from the database, we can easily sprinkle in some type safety and early errors. This often requires really fast validation as well, which speaks for Typebox.

**Comment by sinclairzx81** [comment]
@dbartholomae Hi, thanks for the suggestion!

At this stage, I'm currently holding back on adding a specific built in TypeBox `.Assert()` (or `ensure`) function to throw errors on validation failure. There's a couple of reasons for this...

The first is that before TypeBox implements an assert, there ideally needs to be some work done to build a default error formatter. This formatter would accept an iterator of `ValueError` and produce a "standardish" human readable message to be used on thrown validation exceptions. This is on my list of things to do, but has some crossover with i18n requirements I'd like to meet.

The second is that it's currently possible to use `.Check()` and `.Errors()` to construct user defined assertion functions that throw  errors specific to the object or component where the type error occurred. This is quite nice for seeing where something has faulted rather than checking stack traces; and has been my current approach for error handling. For an example of this consider the link below.

https://github.com/sinclairzx81/typebox/blob/collections/src/collections/map.ts#L37-L51

Let me add a suggestion tag and revisit when TypeBox gets a error formatter. However, at this stage I am leaning a bit more towards just providing the error formatter, as `.Assert()` would just be a convenience function for both `.Check()` and `.Errors()`. Will give this some thought.

Thanks again!
S

**Comment by sinclairzx81** [comment]
@dbartholomae Hi, I think I might close this issue as it's fairly unlikely TypeBox will get a `Parse` or `Assert` function. 

### Parse or Assert

So, the reason for not including these functions is due to them already being constructable with a combination of `Check()` and `Errors()` and that there is often many different ways one might want to implement these functions (for example implementing an Assert for a HTTP server might require different logic to a simple value assertion). 

For example, consider [this](https://github.com/sinclairzx81/typebox/issues/328) particular issue, where there is a optimization consideration where only authenticated users see value diagnostic errors (which is far outside the scope of TypeBox and more into the realms of integration). But from this, the desire to want to validate in this way does promote the idea one can attain higher performance by not adopting "one size fits all" methods. Also I feel keeping `.Check()` and `.Errors()` distinct promotes the idea that through experimentation (and other factors) this can lead to higher performance in some cases, even if it comes at a marginal DX cost by not combining them into a single `.Assert()` like function.

### Error Reporting

In terms of error reporting, I'm quite keen to keep errors open an mappable through `ValueError` and not be too opinionated on how errors should be formatted (of which there is quite a bit of room for interpretation here also). For now, the `ValueError` should provide enough information to construct i18n translations as well as other custom error message formats. And from this, it should be possible for external implementers provide translations and formats though external packages (or implemented as part of their projects)

### Recommendation

For now, the recommended approaches for including Parse and Assert like functionality to applications is shown below.

#### Dynamic

Performs Dynamic Type Checking via the Value module.

```typescript
import { Value } from '@sinclair/typebox/value'

function Assert<T extends TSchema>(schema: T, value: unknown) {
  if(Value.Check(schema, value)) return
  const first = Value.Errors(schema, value).next()!.value
  throw new Error(first.message)
}
```
#### Compiled

Performs JIT optimized Type Checking via the TypeCompiler module.

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'

function CompileAssert<T extends TSchema>(schema: T) {
  const C = TypeCompiler.Compile(schema)
  return (value: unknown) => {
    if(C.Check(value)) return
    const first = C.Errors(value).next()!.value
    throw new Error(first.message)
  }
}
```
#### Re-Export

Creates a custom compiler that returns a custom type check with a `.Parse()` function.

```typescript
import { TypeCompiler, TypeCheck } from '@sinclair/typebox/compiler'
import { Type, Static, TSchema } from '@sinclair/typebox'

export class CustomTypeCheck<T extends TSchema> {
  constructor(private readonly check: TypeCheck<T>) {}
  public Code(): string {
    return this.check.Code()
  }
  public Check(value: unknown): value is Static<T> {
    return this.check.Check(value)
  }
  public Errors(value: unknown) {
    return this.check.Errors(value)
  }
  public Parse(value: unknown): Static<T> {
    if(this.check.Check(value)) return value
    const first = this.check.Errors(value).next()!.value
    throw new Error(first.message)
  }
}

export namespace CustomCompiler {
  export function Compile<T extends TSchema>(schema: T): CustomTypeCheck<T> {
     return new CustomTypeCheck(TypeCompiler.Compile(schema))
  }
}

const C = CustomCompiler.Compile(Type.String())

const S = C.Parse('hello world')
```

Thanks for the suggestion though (it is worth thinking about), and certainly happy to discuss more on this thread. But for now, will close off this issue.
All the best!
S

**Comment by Lonli-Lokli** [comment]
@sinclairzx81 I would like to know if your custom approaches could create a new object from the value? That's because I might want to get value with just those properties

```
const C = CustomCompiler.Compile(Type.Object({str: Type.String()))

const S = C.Parse({str: "str", "dontNeedThis": "value")
```
