### ISSUE TITLE
querystring/page Expected number

### ISSUE THREAD

**Issue by patilanz** [sinclairzx81/typebox#305]
querystring/page Expected number error:

```js
schema: {
	querystring: Type.Object({
		page: Type.Number(),
	})
}
```

the url i'm calling is /route?page=1

If I change the type to String() it works.

**Comment by sinclairzx81** [comment]
@patilanz Hi, 

This issue is related to Fastify where it I don't think it automatically coerces strings as numbers (as query strings are received as strings read from the URL). You may be able to configure Ajv to coerce values for you, have a read of https://ajv.js.org/coercion.html; but this may be better submitted on the Fastify project.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@patilanz Will close off this issue for now, but if you have any questions, feel free to reply on this thread.

Cheers
S
