### ISSUE TITLE
Incorrect type for object when additionalProperties is set to True

### ISSUE THREAD

**Issue by inabhi9** [sinclairzx81/typebox#311]
Hi,

I'm not sure if it's an issue or expected behaviour. When I set `additionalProperties: true` like in eg:

```ts
const body = Type.Object({
  name: Type.String(),
  email: Type.String({ format: 'email' }),
}, {additionalProperties: true})

type TBody = Static<typeof body>
```

Produces following type

```ts
type TBody = {
   name: string,
   email: string
}
```

However considering the `additionalProperties` it should also include `{[k: string]: any}`, shouldn't it?
Schema is generated correctly and works as expected with fastify.

**Comment by sinclairzx81** [comment]
@inabhi9 Hi!

Yeah, this is expected behavior. TypeBox follows TypeScript's structural semantics where `{[x: string]: any}` is implied in polymorphic assignment contexts (or assignment of values that cannot be proven at the time of construction); and is actually the default (so, `additionalProperties: true` is the default and where `additionalProperties: false` is used to constrain). TypeScript has some interesting rules around this.

Consider the following..

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4TAUCUBJAdgFwKYCcAzAQwGMcUxErqbokkBLbfYs0AFVAG8lRQAPAFygMAVwC2AI3wAaXqACewsVPxIAvvQKiMJLAwD2GULgDOWABQA3IgBtROYewCU3TRQi0v3uqgCi-ETiAA625Kg+kV70JEbmoDb2OKAAvNwCwgCMMorCAEw5OgDWGAYA7hgA+sF4BsH4WEqgAMyg6qCoRAAmXQz6RnagNXUNCvRmlokOrqjBBrYK4gZ4wQAWDCSgRKamDADmGOI42MIGReM45hZcGaDZuaAFoMWlFdW19XiNwq3qM2DmPAbLBbHb7Q7HLDCYgMWxAA)

```typescript
// --------------------------------------------------
// Interface
// --------------------------------------------------

interface T {
  x: number,
  y: number
}

function test(value: T) {}

// --------------------------------------------------
// Example
// --------------------------------------------------

const value = { x: 1, y: 2, unknown_property: 3 } // additional property

test(value) // polymorphic assignment: ok

test({ x: 1, y: 2, unknown_property: 3 }) // strict assignment: fail
```
But can be written as a structural assignment with the following.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4TAUCUBJAdgFwKYCcAzAQwGMcUxErqbokBLbfYs0AFVAG8lRfQAPAFygMAVwC2AI3wAaHnwCewsVPxIAvkiQFRGElnoB7DKFwBnLAB4AaqBz9cGACZn2APgAUANyIAbUTjC1gCUXJoUELRR0XSoAKL8ROIADr7kqDGZUVokxhagPv44oAC8XALCAIwyoEqgAEw1ugDWGIYA7hgA+sl4hsn4WHUAzKDh5ljefgGhqMmGvgrihnjJABb0JKBEZmb0AOYY4jjYwobNWhMenBWg1bXCjaAtbZ09fQN4Q8Kj6rNgFjwon0ojwflA80Wy1WGy2Oz2h2Op1A5y0QA)

```typescript
// --------------------------------------------------
// Interface
// --------------------------------------------------
interface T {
    x: number,
    y: number
}

function test<V extends T>(value: V) {}

// --------------------------------------------------
// Example
// --------------------------------------------------

const value = { x: 1, y: 2, unknown_property: 3 }

test(value) // polymorphic assignment: ok

test({ x: 1, y: 2, unknown_property: 3 }) // structural polymorphic assignment: ok
```
So, TypeBox aligns to these semantics rather than augmenting types with `{[x: string]: any}` as these are the default semantics in TypeScript. However, there are some future considerations being planned for the following.....

```typescript
const T = Type.Object({
  x: Type.Number(),
  y: Type.Number()
}, {
  additionalProperties: Type.String()
})
// maps to....
type T = {
  x: number,
  y: number
} & {
  [key: string]: string
}
```
But at this stage, the following results in a non-reconcilable type in TypeScript.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/PTAEFpK6dv4TAUCUBJAdgFwKYCcAzAQwGMcUxErqbokksBPABx1ABVQBeUAbyVCgAHgC5QGAK4BbAEb4ANANCMxk2fiQBfUADI+SgNoYiUnGIDOWPAEsMAcwC6Fq7btb6BCRhJZrAewxQXEsACgA3IgAbCTMOAEo+TXpUWlS05FQAUSETZkjyFPSi2noSAMtQCOi2Hl5hMQBGeWUxACZmrwBrDD8AdwwAfWY8P1Y8JjEAcgBmSdBtemCscKiYhNRmP0jGKT88ZgALaxJQInNzazsMU2wxYmtIxZxQutFQJpbQdtAunv6hkZjCagGZzTTrMCWGw+U7nS7XHC3UD3R4UUAAQTwdmkiKwoD8BCCLDYk1eqmkcjwAG5PmpKTTfn1BsNRvhgVDXDTNHNrOZxH48WcLlciDJ8kE-KBmEQ8CYcLg8PjCUxWCD2JMAHRowTsYkgsniCn4GkqQ3qak-DDdJkA1njU0c+xcnl8nqCuEisVsLCSlUkupGOXOGz2JygR12Z1a1CCQQABUBbMYIKELtAtjKUmlvi9oF61iwB3TGAAJjghOH4UQsBI8Dho2BY7HdarJnT8Gm3bDhcZcz6ia2I5MgA)

```typescript
// --------------------------------------------------
// Interface
// --------------------------------------------------

type T = {
  x: number,
  y: number
} & {
  [name: string]: string
}

function test(value: T) {}

// --------------------------------------------------
// Example
// --------------------------------------------------

const value = { x: 1, y: 2, unknown_property: '3' } 

test(value) // polymorphic assignment: fail

test({ x: 1, y: 2, unknown_property: '3' }) // strict assignment: fail

// Argument of type '{ x: number; y: number; unknown_property: string; }' is not assignable to parameter of type 'T'.
//   Type '{ x: number; y: number; unknown_property: string; }' is not assignable to type '{ [name: string]: string; }'.
//     Property 'x' is incompatible with index signature.
//       Type 'number' is not assignable to type 'string'
```
For now, augmenting a inferred type with `{[key: string]: any}` for `additionalProperties: true` (which is the default) is not feasible as it does not naturally extend to the above use case. 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@inabhi9 Will close off this issue for now. But if you do have any follow up questions, please feel free to reply on this thread.

Cheers!
S

**Comment by inabhi9** [comment]
Thank you for the detailed explanation!

I understand your point and I think without compromising on consistency, it wouldn't be possible.
I hope TS will allow such  compatibility in future!

Best,

**Comment by npdev453** [comment]
@sinclairzx81, seen thing problem not for first time especially in any JSONSchema + TS related things. 
Is there related issue in TypeScript repo? (maybe you push it some or at least link it together)

**Comment by npdev453** [comment]
@sinclairzx81 

https://github.com/horiuchi/dtsgenerator/issues/525#issuecomment-1652834099

What about? [TS Sandbox](https://www.typescriptlang.org/play?ts=5.2.2#code/PTAEFpK6dv4TAUCUBJAdgFwKYCcAzAQwGMcUxErqbokksBPABx1ABVQBeUAbyVCgA2hiIBbHAC5QAZyx4AlhgDmAXWkBXDAGsMAewDuGANygkAX1AAyPgNAAPaRg1iARvgA0dxk5fu8FmZIBFokWAp6GKC4cgAUAG5EADYaUhwAlHzm9Ki0efnIqACi9uLMSeS5BdW09CSRcqCJKWw8vA7SAIweoD6gAEw9WrqGGAD6zHh6rHhM0gDkAMzzoJZI9RiNrtKcbY7dvZL92Qw4cc2p6fQxWLHtjqAHfYOgw-pGE1MzAF5zoEsrcyZIA)

```ts
// --------------------------------------------------
// Interface
// --------------------------------------------------

type T = {
  [name: string]: unknown; 
} & {
  x: number,
  y: number
} 

function test(value: T) {}

// --------------------------------------------------
// Example
// --------------------------------------------------

const value = { x: 1, y: 2, unknown_property: '3' } 
const b: T = {x:1, y:2}

test(value)  // no errors

test({ x: 1, y: 2, unknown_property: '3' })  // no errors
```
