### ISSUE TITLE
Check and Error methods raising error and not returning anything

### ISSUE THREAD

**Issue by irg1008** [sinclairzx81/typebox#314]
I am using Typebox with fastify-typebox-provider for type checking the body and response on requests.

The problem happens when I call Value.check or when compiling the schema, then checking an object against Check or Error methods, status 400 is automatically risen.
I can't catch it no matter how and when trying to type the response for error 400, 500 server error is risen instead.

The next snippets returns a 400 response:

```typescript
  app.post('/register', {
    schema: {
      body: registerData.schema,
    },
    preHandler: app.authHandler([app.authMethods.notLogged]),
    handler: async (req, res) => {
      registerData.Check(req.body); // Raises 400 error with format { statusCode: 400, error: "", message: "" }
     // ...
   }
```

When trying to type the response, a serialization error rises and throws 500 server error. This is normal because It doesn't know how to map from the typebox error to the one declared by mine.

The problem is when I try to get the error to map them my self, I can't because the 400 status is automatically returned and the functions return nothing.

```typescript
  Check: function (check: Static<typeof this.schema>) {
    const valid = Value.Check(this.schema, check); // This raises 400 automatically
    console.log(valid); // Not reaching
  }
```

**Comment by sinclairzx81** [comment]
@irg1008 Hi,

This issue seems like it might be more Fastify related than TypeBox. However, as a test, what happens if you pass the schema to TypeBox Value or Compiler directly (without implicating Fastify)? Note: TypeBox will throw a compile error if the schematic/type being compiled doesn't conform to TypeBox's specification for a type (so it would be good to just rule that out if there is something wrong with the schema)

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { Type } from '@sinclair/typebox'

const T = Type.Object({...}) // <- replace with your schema here
const C = TypeCompiler.Compile(T) // <- should throw if there is something wrong with the type.
```

Btw, The Fastify type provider package provides a validation compiler plugin that internally compiles and validates TypeBox types for you. This means you shouldn't need to use the `Value` and `TypeCompiler` modules at all (as they are handled by the plugin). Have you considered trying the following?

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYCEIA82YAKUEAbsACYZQA0K62eAagIYA2lLM0AwhOMDbU4AXzgAzEiDgByAALiWAZxjBxqAPQwGAWjAlyVKDu2YARnhkBYAFChIsRPUyiJU2XKXAAdgGM2LMBQWgwWuNZ24NDwAGLKqupu-LKKKmqoEbYaGnAA8qTUUJQYSnAwABYYcHFpiQCCAFJMcL78YILC4tBllc6MuGUMLW0dULat3ioS8elwALzVM+oAFACUAHRKGDCsHBRcvCNCUMsE-buc3FB8AsertrapCajrAO7AFWfEZMVQADxnHD4BjfQzUAB8a3WAHNtssZBoZHQELY4HAlL5KiAWAAuRCotFwACOAFdqKgVEVvNC8Wd1rkzAArDC+GDLFE2QmE3C0hjrADKMCp0LWNAJXNQvMwAqFPhFqzFnK5cAAXlKMDLhWtxaJ7kqRLYRHRllAMETVvNwfilRMpkhcHRUHQVa4FqaietSeTDasgA) [Documentation Here](https://github.com/fastify/fastify-type-provider-typebox#type-compiler)

```typescript
import { TypeBoxTypeProvider, TypeBoxValidatorCompiler } from '@fastify/type-provider-typebox'
import { Type } from '@sinclair/typebox'
import Fastify from 'fastify'

// Overrides the Fastify AJV compiler for the TypeBox type compiler
const fastify = Fastify().setValidatorCompiler(TypeBoxValidatorCompiler)

fastify.withTypeProvider<TypeBoxTypeProvider>().get('/', {
  schema: {
    querystring: Type.Object({
      x: Type.String(),
      y: Type.String(),
      z: Type.String()
    })
  }
}, (req) => {
  const { x, y, z } = req.query
})
```
Let me know if that helps
Cheers
S

**Comment by irg1008** [comment]
Wow, I wasn't aware of that, neat feature!

What I meant is that I wasn't able to type custom response errors when validation error was risen.
I use a errorHandler now to map the validation error and fastify-sensible for consistent typing and response. So I think that is enough to cover error handling.

I have to give it to you man, this plugin is awesome!

Pd: I am opening another issue relating to "email" format not being recognised:
email: "example@mail.com"

Response
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "body/email Unknown string format 'email'"
}
```

Other formats work great. Anyway will open the issue if you don't mind.

**Comment by irg1008** [comment]
Okay I see you spoke about it in #304. It's a little weird to have autocomplete for the formats but not actually have them implemented. Can we open a PR to implement them? Or maybe another package?

**Comment by sinclairzx81** [comment]
@irg1008 Hi, 

> Okay I see you spoke about it in https://github.com/sinclairzx81/typebox/issues/304. It's a little weird to have autocomplete for the formats but not actually have them implemented. Can we open a PR to implement them? Or maybe another package?

TypeBox somewhat follows Ajv's approach of considering formats as a separate thing (with `ajv-formats` being an install-able auxiliary package for Ajv). At this stage, TypeBox has no such auxiliary package (yet), but there is a reference example you can use in your project which ports the Ajv formats over to TypeBox. You can find this below.

https://github.com/sinclairzx81/typebox/blob/master/example/formats/additional.ts

Copying file this into your project, You should be able to configure with the following

```typescript
import { AdditionalFormats } from './path/to/additional.ts'

AdditionalFormats.Configure() // configures formats

const T = Type.String({ format: 'email' })

Value.Check(T, 'dave@domain.com') // true
```
Hope that helps!
S

**Comment by sinclairzx81** [comment]
@irg1008 Hi, might close off this issue as it's somewhat related to Fastify and/or the Provider. If you have any follow up questions on configuring formats, feel free to reply on this thread. Note that TypeBox may get some built in formats at a later time, but for now they need to be manually configured.

Cheers
S
