### ISSUE TITLE
suggestion: add static type check to the 'default' option.

### ISSUE THREAD

**Issue by wuchangming** [sinclairzx81/typebox#316]
``` ts
Type.Boolean({
    default: 'string', // Now I can set any types value, i think it can only receive boolean will be better.
    title: 'isDisable'
})
```

**Comment by sinclairzx81** [comment]
@wuchangming Hi, thanks for the suggestion

At this stage, I'm keeping the `default` property fairly open. The reason is there's a few cases where users may need a bit of flexibility here. For example creating lazy default values....

```typescript
const Timestamp = Type.Integer({
   default: () => Date.now() // default value is obtained via function 
                             // call invoked from infrastructure used to 
                             // initialize the value.
})
```
As of current the TypeBox's `Value.Create()` function doesn't understand functions for the default value, but other infrastructure users may setup around the type may (for example JSON schema utility libraries external to TypeBox). For now, I'm keeping options open around the default property, but at the cost of users needing to be a bit mindful to specify a correct default value for the type. 

Hope that brings a bit of insight into why `default` is currently typed as `any`. 
Cheers!
S

**Comment by sinclairzx81** [comment]
@wuchangming Hi, thanks again for the suggestion, but might close this one off for now.

I think at this stage, changing the `default` value from `any` may prove a breaking change for some users, but may review in a subsequent version of TypeBox. Again I can't assume too much from JSON Schema tooling that may need to read the default value, and where the default may either be a function (as per example) or contain additional metadata used by the tooling to produce a value. Ideally the `default` should equal the expected type, but there are edge cases where this may not always be true.

A possible better alternative to `any` might be to change the type to `unknown` (requiring implementers to appropriately test the value before use), but will review in a subsequent release.

Thanks again
S
