### ISSUE TITLE
Indirect recursion example

### ISSUE THREAD

**Issue by claudiuandrei** [sinclairzx81/typebox#320]
I'm trying to out how to do the following recursive pattern:

```typescript
Profile = { ..., student: Student, coach: Coach },
Student = { ..., profile: Profile, coach: Coach },
Coach = { ..., profile: Profile, students: Type.Array(Student) }
```

I'm not sure if this is possible, and yes, how would it be the best way to go about it?

**Comment by sinclairzx81** [comment]
@claudiuandrei Hi,

TypeBox doesn't support mutually recursive or cyclic referenced data structures as part of it's type system. There's a few reasons for this, but the first is that in order for the above data to validate, the validator may need to do a potentially infinite recursive check (i.e. `student.profile.student.profile...`), also TypeScript inference also tends towards infinity when computing the type for similar reasons. 

> Note: There are possible solutions to the later which I've been investigating (and potentially the former through reference caching during the validation pass), but in general these forms of structures are usually best to avoid, particularly when validating JSON data which doesn't support cyclic referencing when stringified.

### Cyclic Data Example

The reference between the Student and Profile types can be boiled down to the following example if expressed as actual JS data.

```typescript
const data: any = { data: null }
data.data = data     // introduce cyclic reference
JSON.stringify(data) // TypeError: Converting circular structure to JSON
```

### TypeBox Expression

While cyclic data structures cannot be constructed through the TypeBox API (or leverage TS inference as other types), you can construct them explicitly through `Type.Unsafe()`. The following is an example of how this might look.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZ-fnAC0K1WvUbNW7TvmKAshAAmGLgC48MAK4n2MPcp1PnLrbIzjIsOBxgYoVAQkGJY2GHaIsnBwJBBBABYWAMJxJPFYUXBgtFTAXBgWAAo5eRiy5O6e0PCx7Czw+GERALwowgB0AKp1BFQYADyNtjAAfAAUCJlCmBYMECIAVhgkMAwZMtEAJMBGs0Phq+vR2RCYsMAYLBaTG9ExqYmIcJtQGFSzKQkMFEd3J7n5a7PV7vRjFCAAjDfcg4BRZWgifL0eL+ApwepNGDtf6ldoY4bYkr5dokzKUO4UylU6k02l0+lwcoASlkDlc7I5uhkcMMJnMcHBkLZnJFosqXngvn8gWCAqJIRu0ViCWSD1++IOFn2dnK4uq9zq8EFpTgrTQmC6PT6-WN+XGirg0zRc0Wy0OmW2uzB8rWmROZ2Il2umSVDyBLzeHwe0N+0Q1dnDIL21mGMbgcJOiIwyNRFhxxPjWPzGDxKYOJPaZOZrO5ilF9Y5Dl5plVCWFDY7XI8Ep8dmlQRCnzSkVuxaK8vVZbsV1CwwA2gBdXUybv62r1OBD+KmtoW7osXoDLf2qbCWbzJYrX23T1Rr6-f3+QMzh3HeWJyPeiGlGMh9FTmAX0dM9GAIKAoAIVA1h8PwQCAiNQQYbVVgoCgqxkcgWTkWtHE7PCNAcZBLnsHD8LItRZCoKxOGICB2EdYixgANwILgrDRfAiFIfonQhTcHhGJkR2iFi2JLYt2mVNJS0xFg5wABgXQlvwLADJIeGThjkgBGJSpO3OECHYIx0QgOA6LgCtyiAA)

```typescript
import { Type, Static } from '@sinclair/typebox'

// -------------------------------------------------------
// Model: Student
// -------------------------------------------------------
export interface Student {
  coach: Coach,
  profile: Profile
}
export const Student = Type.Unsafe<Student>({
  type: 'object',
  $id: 'Student',
  properties: {
    coach: { $ref: 'Coach' },
    profile: { $ref: 'Profile' }, // problem here: student.profile.student.profile...
  }                                                                 
})

// -------------------------------------------------------
// Model: Profile
// -------------------------------------------------------
export interface Profile {
  coach: Coach,
  student: Student
}
export const Profile = Type.Unsafe<Profile>({
  type: 'object',
  $id: 'Profile',
  properties: {
    coach: { $ref: 'Coach' },
    student: { $ref: 'Student' }, // problem here: profile.student.profile.student...
  }
})

// -------------------------------------------------------
// Model: Coach
// -------------------------------------------------------
export interface Coach {
  profile: Profile,
  students: Student[]
}
export const Coach = Type.Unsafe<Coach>({
  type: 'object',
  $id: 'Coach',
  properties: {
    profile: { $ref: 'Profile' },
    students: { type: 'array', items: { $ref: 'Student' } }
  }
})

// -------------------------------------------------------
// Test
// -------------------------------------------------------
function test(value: Static<typeof Coach>) {
  value.profile.coach.students[0].profile.student.coach.students[1].coach // and so on ...
}
```
Just note that the TypeBox type compiler won't support the above types, so your best bet would be to try validate with Ajv (which may internally cache for the observed reference to terminate recursion). You would need to run Ajv to test for this (I'm not familiar with the Ajv internals for this case)

### Alternative Approach

As a alternative, have you considered specifying an `Id` for the properties instead of the direct references?

```typescript
export const Student = Type.Object({
    coachId: Type.String(),
    profileId: Type.String()                                                           
})
```
This is a fairly common way to represent referential data in a way that mitigates cyclic referencing. It's very serializable and can be validated trivially.

Hope this helps!
S

**Comment by claudiuandrei** [comment]
Thank you so much @sinclairzx81 !

I use the nested structure for defining the relationships for reading only and I only need to describe the type, so your example is perfect. I use a similar approach as your alternative option for writing.

Would `Value.check` work on the first example, or it will be affected by the infinite recursion like `TypeCompiler.compile`?

**Comment by sinclairzx81** [comment]
@claudiuandrei Hi, 

Both `Value.Check` and `TypeCompiler.Compile` cannot support `Type.Unsafe` types (by default). Note, the unsafe type is mostly used to express valid JSON Schema which falls outside the standard schematics constructed by the TypeBox functions (see [readme](https://github.com/sinclairzx81/typebox#types-standard) tables for the standard schematics). For example, Unsafe types are usually used in tandem with OpenAPI (which extends JSON Schema) and where the unsafe type can be used to express custom schematics, however it can also be used in fallback scenarios like this where either TypeScript or Validation logic can't be naturally expressed otherwise.

On this, I would recommend trying Ajv first to see if you can get the type validating without hitting infinite recursion (as the custom schematics defined above should be valid JSON schema)

### Alternative Approach | Manual Validation

In the instance Ajv fails to validate, TypeBox does allow you to implement the type checking manually with custom types. This is handled through the `TypeSystem` module where you can construct the type + validation logic. If you implement the type checking logic this way, you will be able to leverage the `TypeCompiler` and `Value` modules to validate for you, but at the cost of having to implement the checking yourself. See below.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYGELmAGwyjgF84AzKXOAcgAEBnYAOwGN8BDYKAehnQwAjCAA8erXGAJEaAWABQoSLEQoBAZVQMYGEKQpU99Jm07c+A4WIZadIOYvDR4SNJgA0cdTA4xgrfUpqYxZ2Ll5+TCsHBR4eOABaJOSU1LT0jMys2PjvAFcAEwxmGBzErIrKqoyFDBFleBYdKHIOVgwvGELilwU4OAk2gAsALjgcYfc+uDAqcmkxgAU56QUSBQlmbU7ukrgAXjVMTW1dADosKAxfDDcMAB58opKAPgAKGieemk83iDA-BAtp4AG4cfB5DAASgOL0Q0yuXSgzDgMCgkLgcVREAKEDGQPwqDgiLyyNR6I6AEkAGJwMEQjrABhwDhwbS7UryEhQhRlar8gXZeRY5YQeaEPmCqXS2r1ZxwJpEVrtOCi8UdBDTQasUbjCCTabs54wMZfEprDZA7Zq6QHI4YE52C5XG53e42wjvGgejA-OB-AHAK2g8GQmH7OGa+T9ElktEYrEwHF4uAEomxlHxqm0+kYpksmYrCVcnnySXSivVMoTHXlyv1zKyhoKkpKtodGtDeHRwtihaqosYKY9o09BimrrGgDaAF0LfJNttO3a7o7zpdrjo3Z2vZ2-QHAcC6aGMGMOMxUOHIwiMEjMxTMfEk7j8cxCcTb6T7xiaceGQrmVZbUhjWUs6wbCCUjKZAMG0cDIMg3kFyteBkBXAQzgAeUEAArDBWBgN4kEfOAAHcCHwMjoAAazI4AYC7AA1E8LiGfDaPPAp7RwPBCCgC5JFWHtgLGTs3ihYd+lHEoJw5cTh1ApDIg6NDDm8Xx-HuZSxRQF4kMtLZ4CwdDMB4qQ+IE3iMDeZAwPkLBWPYoitX1HUxiQHgACpPOxXE4E8+ISEktlJx6dzMW83yIH8wLFPkIA)

```typescript
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { TypeSystem } from '@sinclair/typebox/system'
import { Type, Static } from '@sinclair/typebox'

// -------------------------------------------------------
// Student
// -------------------------------------------------------
export interface Student {
  coach: Coach,
  profile: Profile
}
const Student = TypeSystem.CreateType<Student>('Student', (options, value) => {
  return true // todo: only return true IF value is a student
})

// -------------------------------------------------------
// Profile
// -------------------------------------------------------
export interface Profile {
  coach: Coach,
  student: Student
}
const Profile = TypeSystem.CreateType<Profile>('Profile', (options, value) => {
  return true // todo: only return true IF value is a profile
})

// -------------------------------------------------------
// Coach
// -------------------------------------------------------
export interface Coach {
  profile: Profile,
  students: Student[]
}
const Coach = TypeSystem.CreateType<Coach>('Coach', (options, value: any) => {
  return true // todo: only return true IF value is a coach
})

// -------------------------------------------------------
// Test
// -------------------------------------------------------

const T = Type.Object({  // will work with Value.Check and TypeCompiler.Compile
  coach: Coach(),
  student: Student(),

})

type T = Static<typeof T>


const C = TypeCompiler.Compile(T)

C.Check({
  coach: { /** todo */ },
  student: { /** todo */ }
})

```
In the above, you are free to implement any logic for each type, but i think to validate without hitting recursion issues, you will need to cache the references and check them to terminate recursion. 

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@claudiuandrei Hi, might close this one off as cyclic / mutual recursive structures are generally not supported.

If you have any questions on the unsafe type ajv implementation, or custom type implementation, please feel free to reply on this thread. Certainly happy to discuss more. I think having a good reference implementation in place to handle the custom mutual recursive type / value validation using `CreateType` may serve as reference documentation in future, so somewhat interested to dig a bit deeper on a reference implementation.

All the best!

**Comment by claudiuandrei** [comment]
@sinclairzx81 Thank you so much for the help, and thanks for building a great library!
