### ISSUE TITLE
move `this.Create` and `this.Clone` to root

### ISSUE THREAD

**Issue by unvented** [sinclairzx81/typebox#332]
Could you please move `this.Create` and `this.Clone` functions out of the `TypeBox` class and call them with `Create()` and `Clone()` from the within type constructors?

That would allow us to re-export the type constructors individually, e.g.:

```ts
export const types = {
  string: Type.String
}
```

To make this possible, the type constructor functions **must not** call `this`.

I currently re-export them like this:

```ts
const polyfill = {
  Create<T>(schema: Omit<T, 'static' | 'params'>): T {
    return schema as any
  },

  Clone(value: any): any {
    const isObject = (object: any): object is Record<string | symbol, any> => typeof object === 'object' && object !== null && !Array.isArray(object)
    const isArray = (object: any): object is any[] => typeof object === 'object' && object !== null && Array.isArray(object)
    if (isObject(value)) {
      return Object.keys(value).reduce(
        (acc, key) => ({
          ...acc,
          [key]: this.Clone(value[key]),
        }),
        Object.getOwnPropertySymbols(value).reduce(
          (acc, key: any) => ({
            ...acc,
            [key]: this.Clone(value[key]),
          }),
          {},
        ),
      )
    } else if (isArray(value)) {
      return value.map((item: any) => this.Clone(item))
    } else {
      return value
    }
  }
}

export const types = {
  string: Type.String.bind(polyfill)
}
```

Another way would be to export all the type constructor functions individually. However this would require the most work and would probably be the less convenient option.

I'd love if you solve this. Thanks.

**Comment by sinclairzx81** [comment]
@unvented Hi, thanks for the suggestion.

I do actually want to do a little bit of refactoring on the TypeBuilder, but do largely need to keep on with the current design in the short to medium term. There's a few considerations around the current setup (mostly as it relates to system / framework integrations), but also for some historical / design rationales. But am planning to overhaul the `TypeBuilder` at some point into the future.

Isn't something like this possible now tho?

```typescript
import { Type, Static, TProperties, TSchema } from '@sinclair/typebox'

export const string  = Type.String()
export const number  = Type.Number()
export const boolean = Type.Boolean()
export const object  = <T extends TProperties>(properties: T) => Type.Object(properties)
export const array   = <T extends TSchema>(items: T) => Type.Array(items)

const T = object({
  s: string,
  n: number,
  b: boolean,
  o: object({ x: number, y: number }),
  a: array(boolean)
})

type T = Static<typeof T>
```

**Comment by unvented** [comment]
Re-exporting each type constructor is possible, but that makes it impossible to declare names like `null`, `undefined` and other reserved words.

I totally understand your point here, but wouldn't it be possible on your end to export them individually under capitalized names? That would also make our code bundles much smaller.

**Comment by sinclairzx81** [comment]
@unvented Hi, sorry mate. I meant to respond to this a bit sooner, but was sidetracked by a couple of things (one of which partially related to this issue). But let me try and give some insights into why things are currently expressed the way they are, with an overview of the TypeBuilder and a couple of scenarios where `Create` and `Clone` are used.

## TypeBuilder

The class is imagined as a fairly low level set of intrinsic types. It's expressed as a class both to allow integrators to extend with higher order types, but also to hard encode the intrinsic type set, essentially making the intrinsics inseparable (and thus reliable for higher order type composition)

The following is the intrinsic set (with all other types largely optional and a candidate to move to separate functions)

- `unsafe` (note: all types including intrinsics can technically be expressed as this type)
- `any`
- `unknown`
- `string`
- `number`
- `boolean`
- `null`
- `undefined`
- `function`
- `constructor`
- `T[]`
- `[...T]`
- `Record<typeof any, T>`
- `T | U`
- `T & U`

> Note: All other types are considered non-intrinsic and thus optional (but still need to be supported)

### Create()

The `Create(...)` function was added to the `TypeBuilder` inline with considerations as to how users may want to extend the intrinsic set, as well offer integration points when embedding the type system in application infrastructure. This is probably best expressed as a code example.

#### Extend

The following extends the TypeBuilder into an ApplicationTypeBuilder and implements a custom `Foo` type (along with defining the type through the new `TypeSystem` module). Note that the `Create` function provides a convenient way to omit the `static` facade type.

```typescript
import { TypeSystem } from '@sinclair/typebox/system'
import { TypeBuilder, Static, TSchema, Kind } from '@sinclair/typebox'

TypeSystem.CreateType('Foo', (_, value) => Array.isArray(value) && 
   value[0] === 0 && 
   value[1] === 1 && 
   value[2] === 2
)

interface TFoo extends TSchema {
  [Kind]: 'Foo',
  static: [0, 1, 2]
}

export class ApplicationTypeBuilder extends TypeBuilder {
  public Foo(): TFoo {
     return this.Create({ [Kind]: 'Foo' }) // omit static as it's valueless
  }
}

export const Type = new ApplicationTypeBuilder()
```

#### Intercept for Auto Registration

Because the `Create` function is called once per type, it can be used for things like auto type registration. The following extends the TypeBuilder with a `Check` function. It internally keeps a `reference` Map which will be added to for every schema passed that has an `$id`

```typescript
import { TypeBuilder, TSchema, Static } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

export class ApplicationTypeBuilder extends TypeBuilder {
  private references = new Map<string, TSchema>()

  public Check<T extends TSchema>(schema: T, value: unknown): value is Static<T> {
    return Value.Check(schema, [...this.references.values()], value)
  }
  protected override Create(schema: any): any { // intercept
    if('$id' in schema) this.references.set(schema.$id, schema)
    return super.Create(schema)
  }
}

const Type = new ApplicationTypeBuilder()

// Usage: Auto Referencing Now Works

const Vector = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
}, { $id: 'Vector' })

const Vertex = Type.Object({
  position: Type.Ref(Vector), // { $ref: 'Vector' }
  normal: Type.Ref(Vector)  // { $ref: 'Vector' }
}, { $id: 'Vertex' })

const R = Type.Check(Vertex, { 
  position: { x: 1, y: 2, z: 3 },
  normal: { x: 1, y: 2, z: 3 },
})
```
### Clone()

This function is somewhat annoying and needs refactoring (it's a candidate to move elsewhere), but it's purpose is to help ensure composited types are treated as immutable internal to the TypeBuilder.

I have considered pulling `ValueClone` from the `value` modules, but as a design constraint (and due to some [historical reasons](https://github.com/sinclairzx81/typebox/tree/typebox-legacy-v2#usage)), the `typebox.ts` file must be kept a standalone script. Except from a prior era

>Typebox is written as a portable single file that can be copied into any TypeScript project. Copy the ./src/typebox.ts file into your project and you're all setup.

### Imports

There are some considerations to support the following in future.

```typescript
import Type, { Static } from '@sinclair/typebox'
```

## Note on Bundle Size

Although TypeBox splits modules at the `class` or `namespace (iife)` level (as opposed to the `function` level), it's still pretty good in terms of bundle size. These are the current measurements when compared to other libraries.

https://bundlephobia.com/package/@sinclair/typebox@0.25.24

## Summary

I hope this provides some justification for `Create` and `Clone` and addresses a couple of other things. I do agree that these methods are somewhat clunky (and can probably be expressed in other ways), but for the purposes of keeping things non-breaking, I do need to keep on with the current design in the short to medium term. 

Again, sorry for the late reply. But certainly happy to discuss this in more depth. Historically, getting a design up and working in TypeBox specifically for the purposes of integration as been a difficult ongoing moving target, with the `Create` and `Clone` functions used to iron over a couple of integrator usecases. Discussing integration / extension requirements does help steer the library though (so always in hearing things out), although actioning changes is typically slowly and carefully (and strategically) carried out over the long term.

All the best!
S

**Comment by unvented** [comment]
@sinclairzx81 can we have a follow up chat on Discord on this topic?

**Comment by sinclairzx81** [comment]
@unvented Do you have link?

**Comment by unvented** [comment]
@sinclairzx81, sent you a friend request!

**Comment by sinclairzx81** [comment]
@unvented Haven't received it, handle is "sinclair", profile picture is the same as my github profile picture (also, not much of a discord user I'm afraid, but can usually be found in the TypeScript discord)
