### ISSUE TITLE
Type.Buffer()

### ISSUE THREAD

**Issue by sayem314** [sinclairzx81/typebox#386]
This is my code for defining the return type as a buffer on fastify web framework but unfortunately `.Buffer` does not exists on lib so how can I describe it?

```ts
export const MovieStreamParams = {
  headers: API_HEADERS,
  params: Type.Object({
    id: Type.String(),
  }),
  response: {
    200: Type.Buffer(), // non-existent
    206: Type.Buffer(), // non-existent
  },
  ...SCHEMA_SECURITY,
};
```

**Comment by sinclairzx81** [comment]
@sayem314 Hi,

This is more a question for Fastify. But to specify a typed `Buffer` response, you can use `Type.Uint8Array()`. This works because the NodeJS `Buffer` type internally extends the `Uint8Array`. Quick example below.

### Example

```typescript
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import Fastify from 'fastify'

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>()

fastify.get('/', {
  schema: {
    response: {
      200: Type.Uint8Array() // or Type.Unsafe<Buffer>({}) will also work
    }
  }
}, (_, res) => {
  const body = Buffer.from('hello world')
  res.status(200).send(body) // must be Uint8Array or Buffer
})

// You can test with this
async function httpTest() {
  const body = await fastify.inject().get('/').then(res => res.body)
  console.log(body) // "hello world"
}
httpTest()
```
Just be mindful here though. I don't think Fastify will runtime check the `Buffer` response type, so specifying a `Uint8Array` type here is merely for the benefit of static type checking (not runtime checking). Also note, Binary encoded data cannot be expressed using the JSON Schema specification. As such, the `Type.Uint8Array()` type is implemented as a non-standard type in TypeBox, and is only designed to work with the TypeBox `TypeCompiler` (although it would be possible to configure Ajv to also validate this type using custom type configurations)

Hope this helps
S

**Comment by sinclairzx81** [comment]
@sayem314 Hey, might close off this issue as the above example should work ok for static type checking.

All the best!
S

**Comment by sayem314** [comment]
Thank you. I will try that.
