### ISSUE TITLE
Feature Request: Create or patch object with default value only

### ISSUE THREAD

**Issue by joshuaavalon** [sinclairzx81/typebox#394]
# Problem

Usually, for a configuration object, I would like to patch the object with default value if user does not provide one.

```ts
// Design 1
const schema = Type.Object({
  foo: Type.String({ default: "." }),
  bar: Type.Number()
});

const Config = Static<typeof schema>;
```

Currently, if I use the design 1, I will have some problems. If I use `Value.Create` or `Value.Cast`, it will also patch `bar` which is not I wanted.

```ts
// Design 2
const schema = Type.Object({
  foo: Type.Optional(Type.String()),
  bar: Type.Number()
});

const Config = Static<typeof schema>;
```

If I use the design 2, I have to patch all the value manually which is hard for nested values and I have to create another schema and type to verify the patched version.

# Solution

I have read #279 which seems AJV has `withDefault` to solve this problem. However, If I use AJV, it defeats the purpose of using Typebox.

It would be nice if `Value.Create` and `Value.Cast` or a new function be able to create or path with default values only.

**Comment by sinclairzx81** [comment]
@joshuaavalon Hi. 

It wouldn't be possible to implement the above functionality in the `Create` or `Cast` functions. This is because the schema (Design 1) specifies that `bar` is a required property. So omitting `bar` in the initialized value would mean the returned value is mismatched to the type. Consider the following if implementing this proposal for `Create`.

### Example

```typescript
// Design 1
const schema = Type.Object({
  foo: Type.String({ default: "." }),
  bar: Type.Number()
})

const value = Value.Create(schema)           // const value = { foo: '.' } - with bar omitted
const check = Value.Check(schema, value)     // const check = false        - value mismatched (error)
```
The rules around TypeBox value initialization are that the return value "MUST" match the target schema or throw an Error. At this stage I'm reluctant to implement any additional logic for value initialization that would construct values mismatched to expected type as it's just too difficult to maintain without a formal specification for how this should work for all cases.

Recently however, TypeBox introduced a `Value.Convert` function that performs hard coded value coercion. This function returns `unknown` for the resulting type as the value may or may not be valid to the expected type (and thus should be checked). There are some considerations around making Convert programmable (see issue https://github.com/sinclairzx81/typebox/issues/343), but in terms of supporting default value initialization in the way you describe, this would either need to be implemented outside of TypeBox (through schema introspection) or through a programmable conversion pass implemented by way of `Value.Convert`.

Note, the programmable Convert functionality isn't likely to be ready for some time, so constructing the value through introspection is currently the only option.

### Using Ajv

> I have read https://github.com/sinclairzx81/typebox/issues/279 which seems AJV has withDefault to solve this problem. However, If I use AJV, it defeats the purpose of using Typebox.

Just keep in mind, TypeBox is written specifically to integrate with Ajv (as well as any other JSON schema validator). If you need Ajv's default value initialization, it's perfectly ok to use Ajv for validation and initialization, and TypeBox to construct your types + inference.

Happy to discuss this a bit more, but not sure if there's anything specific that can be implemented at this stage. I would recommend taking a look at some of the comments on https://github.com/sinclairzx81/typebox/issues/343. If TypeBox were to implement default value initialization in the way you describe, it would likely be through future enhancements to `Convert`.

Cheers!
S

**Comment by joshuaavalon** [comment]
@sinclairzx81 Thanks for the long answer.

> The rules around TypeBox value initialization are that the return value "MUST" match the target schema or throw an Error. At this stage I'm reluctant to implement any additional logic for value initialization that would construct values mismatched to expected type as it's just too difficult to maintain without a formal specification for how this should work for all cases.

I do not know TypeBox must return a value that match the schema.

But I think you misunderstand what I mean in the example. I mean if you have a function to create or patch default values, I can merge it with user input. If user input does not have the required value and there is no default value set, then it should fail the checking.
```ts
const schema = Type.Object({
  foo: Type.String({ default: "." }),
  bar: Type.Number()
});

const Config = Static<typeof schema>;

const value = Value.Create(schema);           // const value = { foo: '.' } - with bar omitted

const userInput1 = { bar: 1 };
const check1 = Value.Check(merge(value, userInput1), value) // Good to go

const userInput2 = {};
const check2 = Value.Check(merge(value, userInput1), value) // Bad, user should check their input
```

Currently, `Create` and `Cast` both try to create value even though there is no default value set which defeats the purpose of checking user input.

> Just keep in mind, TypeBox is written specifically to integrate with Ajv (as well as any other JSON schema validator). If you need Ajv's default value initialization, it's perfectly ok to use Ajv for validation and initialization, and TypeBox to construct your types + inference.

It will be a bit difficult because I use `TypeRegistry` for custom type.

**Comment by sinclairzx81** [comment]
@joshuaavalon Hi!

Yeah, this seems very similar to `Convert` in the respect that:

1) The value is initialized from schematics
2) The value may produce an invalid result.
3) The value must be checked.

Similar requirements have been requested by users of the Fastify framework, specifically to have default values initialized for  HTTP headers, querystrings and params. So I would like to offer this functionality in some capacity, but am apprehensive about hardcoding a solution at this stage.

### Future Plans

Rather than implementing a specific function for this (or changing `Create` and `Cast` which have very specific requirements for value initialization) The following is a high level view of what's being considered for `Value.Convert` in subsequent revisions.

```typescript
import { Value, Defaults, Coerce } from '@sinclair/typebox/value'

// user defined assertion pipeline
function pipeline<T extends TSchema(schema: T, value: unknown): Static<T> {
  const value1 = Value.Convert(T, value, Defaults)       // create with defaults only
  const value2 = Value.Convert(T, value1, Coerce)        // apply coercions
  const value3 = Value.Cast(T, value2)                   // cast any remaining values
  if(!Value.Check(T, value3)) {                          // assert valid (optional post-cast)
    throw Error(Value.Errors(T, value3).First().message)
  } else {
    return value3                                        // return
  }
}
```
The changes to `Convert` will require this function to accept a implementation of `interface Conversion` which will handle the logic to remap a value into some target shape. The intent here is to allow users to specify custom logic for custom cases, and setup user defined assert / parse / transform pipelines for incoming values. This is generally a better approach to hardcoding a `Value.Default()` or similar function as it allows (and encourages) users to swap the defacto implementation out if the defacto logic doesn't quite fit some requirement. It also frees TypeBox to implement a variety of additional transforms (for example codecs for msgpack/cbor/xml/etc) and potentially explore the high performance data encoding.

There a little bit of thinking going into this atm (and to make the API palatable for users). But I don't anticipate there will be much in the way of changes here for a good few months (at a minimum). But am open to discussions to gather up all the requirements necessary for this feature.

Open to thoughts :)

**Comment by joshuaavalon** [comment]
@sinclairzx81 I will look forward to `Convert`.
