### ISSUE TITLE
Representation of Record<stringunion> support

### ISSUE THREAD

**Issue by AWare** [sinclairzx81/typebox#404]
I'm trying to upgrade a codebase from 0.25 to latest.

This codebase makes heavy use of the StringUnion helper as defined in https://github.com/sinclairzx81/typebox/issues/174#issuecomment-1134944761

When used as the key for a Type.Record, the latest version gives an `Invalid Record Key` error. Looking at the readme and https://github.com/sinclairzx81/typebox/issues/234 it seems there is now a new StringUnion implementation that doesn't support use as a Record key by design. 

We're using this pattern extensively, so I'd really like to find a pattern I can replace the StringUnion implementation with.

Also, could you consider making StringUnion a first class type in typebox and allowing it to be composed with Record?

**Comment by sinclairzx81** [comment]
@AWare Hi,

Running TB version 0.28.2, Type.Record() does support `TUnion<TLiteral<string>[]>` keys

```typescript
const R = Type.Record(Type.Union([  // {
  Type.Literal('a'),                //    type: 'object',
  Type.Literal('b')                 //    properties: {
]), Type.String())                  //      a: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
                                    //      b: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' }
                                    //    },
                                    //    required: [ 'a', 'b' ],
                                    //    [Symbol(TypeBox.Hint)]: 'Record',
                                    //    [Symbol(TypeBox.Kind)]: 'Object'
                                    // }
```

A first class `StringUnion` type is still out of reach at this time. The reason for this is due to ongoing efforts to compose JSON schema around the current TB schema representations, and introducing multiple representations for `union` is just too far reaching and complicated to maintain (at least for now). There is some incentive to provide a `StringUnion` at some point in future (with particular note to the recent `TemplateLiteral` type) but for now, I need to keep a singular representation for Union.

### Revised StringUnion

The following is a revised implementation of `StringUnion` with added `StringUnionKey` which maps the `StringUnion` into a `Union<TLiteral<string>[]>` (so it can be passed as a key to Record). This implementation has been built against TB 0.28.2 (latest)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GlgB2AJjsgMoDGAFhiAIakCqBwEBpAchgG4ZSkAZYDD50ANjgCCAZ2l94AXzgAzKBBBwA5AAFphCmLrAoAehjoMAIwgAPTQFgAUE5Mm4AWk9fvP33-8BgUF+Lm5kMFCEAObMrAQoFtKhHsGpaekZnk5OGDaQsHDmmCjhkQQxLGy4GKgAPMhwuSLE0iUR0bFsAHxwALwojTbNRK3k7eWdBLWEynx4PQD8KJO1CE5wcADaAJJwhHAA1jUQyngAugBcKEIiUOK1MnKwtbg7ZzjS41FdXU4KPVdkFxeFBso5lABXAgUGBxOClDqVAjVOoNJoYFptMoVOK1OgEVA-AAUn2xk0BAEpAQiJkiUfUemtHBsoBgYBCoPE0JgAHSTElfSY8jEQkA8+hgIliYSiMR9HrcjA8m6yqUyu5iClauB0Vr41B-MG5fLwQi3ZR0CgYLGI3FooYYkZwUnRTZnPpbM49dGY8jUWh0RDrLb4YiXLQ0nFsBzM50wOiwihXI6oE4oYMikBXTY83PIM6G8FQmFwyMre3DVou8purpE7jiCEYaTZ3M8-NUm20u2M4Mstkc+JITahojhzRlpGaHCZq4NsRN1pKXU6gk60aTnuF5KZXd7vfJRjSOhRDA7-cXy8BMEUNifAb9TdsImbTSSadaABCH80AGFNGcFIbMBIFwK4cC3gQ94NP0SCzlsWjvjgmjfsh-5wO8WxkKgIDWGIRKKp+tg8qOFLjk+BCaHACg3ne8C4B6FEogRQGgWx7EbOBkHQR6TIcfxAmCQJ4EbPqADyyjZn2QkybJbEiRsSDcTAVxvh+RQYKp1ZRB+mzYbhED4YRxGkeOKoalRChYNJcm2TJCmIBBdGqahhQWFpXy6fpeEERYRE2CRhBEGRqnmeIlnWbGdnRYJDlKc5Wj-jgGkediXk4T5xkBaZoXquF1E2TFRUgQp7yFcVxUKXpGWGb5mD+YFxAhVokwxhV7XAeBNHOI4ylwAASh6io8v1GC3lARBErgpAWDykZEtqHHgXxHXtQpKVaBAlgAFZjTA07lattkKWAaiYLAwDNlcK1HUVDlwJI11uZgqXROlBlGX5JlBc1E6edRkW3ZVbggZ+T0bZo2nvZlX3ZT95H-VZh1A0J92-uD7laFDODVR9dUYA1OURojyMo8JIMA6TZNLRTrIAI4QsYGBENmiE-q5f5UWVUXU7JVXebVWU8gAEmav2jeNRAHTzvOoxTuMw-V31NeOYk7XtbWy3zbjdUAA)

```typescript
import { Type, Kind, TSchema, TUnion, TNever, TLiteral, Assert } from '@sinclair/typebox'

// -------------------------------------------------------------------------
// StringUnion Types
// -------------------------------------------------------------------------

export type TStringUnionKey<T extends TStringUnion> = T extends TStringUnion<infer K> ? TUnion<{
  [I in keyof K]: TLiteral<Assert<K[I], string>>
}> : TNever

function StringUnionKey<T extends TStringUnion<any>>(stringUnion: T): TStringUnionKey<T> {
  return Type.Union(stringUnion.enum.map(literal => Type.Literal(literal))) as any
}

export interface TStringUnion<T extends string[] = []> extends TSchema {
  [Kind]: 'StringUnion'
  static: keyof T
  enum: [...T]
}
function StringUnion<T extends string[]>(values: [...T]): TStringUnion<T> {
    return { [Kind]: 'StringUnion', enum: values } as any as TStringUnion<T>
}

// -------------------------------------------------------------------------
// Usage
// -------------------------------------------------------------------------

const T = StringUnion(['A', 'B', 'C'])          // const T = { enum: [ 'A', 'B', 'C' ], [Symbol(TypeBox.Kind)]: 'StringUnion' }

const K = StringUnionKey(T)                     // const T = {
                                                //   anyOf: [
                                                //    { const: 'A', type: 'string', [Symbol(TypeBox.Kind)]: 'Literal' },
                                                //    { const: 'B', type: 'string', [Symbol(TypeBox.Kind)]: 'Literal' },
                                                //    { const: 'C', type: 'string', [Symbol(TypeBox.Kind)]: 'Literal' }
                                                //   ],
                                                //   [Symbol(TypeBox.Kind)]: 'Union'
                                                // }

const R = Type.Record(K, Type.String())         // {
                                                //   type: 'object',
                                                //   properties: {
                                                //     A: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
                                                //     B: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' },
                                                //     C: { type: 'string', [Symbol(TypeBox.Kind)]: 'String' }
                                                //   },
                                                //   required: [ 'A', 'B', 'C' ],
                                                //   [Symbol(TypeBox.Hint)]: 'Record',
                                                //   [Symbol(TypeBox.Kind)]: 'Object'
                                                // }

```
Let me know if this helps
Cheers
S

**Comment by sinclairzx81** [comment]
@AWare Hi, Might close this one out as there isn't likely to be a `StringUnion` in the near future. 

With respect to Type.Record() throwing `Invalid Key`, if you can provide an repro of the issue, I'm happy to take a deeper look. The implementation of Type.Record() has changed in recent revisions, but the keys it accepts shouldn't have changed, so if you can provide the repro, can re-open this issue and dig a bit further.

For now, consider the revised `StringUnion` example above. This has been tested on the latest version, and will allow you to remap the key into the union structure expected by `Type.Record()`

Cheers
S

**Comment by AWare** [comment]
@sinclairzx81 sorry for not getting back to you, I've just got back from some leave and will give this a shot.
thanks
alex
