### ISSUE TITLE
Partial for a ref does not produce the right type

### ISSUE THREAD

**Issue by noamokman** [sinclairzx81/typebox#411]
Hey,
I have an issue with `Type.Partial` when used in conjunction with `Type.Ref`.
I recreated the issue in the following test that I think explains the issue:
```ts
{
  const A = Type.Object({ type: Type.Literal("A") });
  const Ref = Type.Ref(A, { $id: "Ref" });

  Expect(Ref).ToInfer<{
    type: "A";
  }>();

  const P = Type.Partial(Ref);

  Expect(P).ToInfer<{
    type?: "A" | undefined;
  }>();
}
```
This fails and from the type hints we can see that the partial didn't take effect.
![image](https://user-images.githubusercontent.com/6004557/233927873-2c636556-2b38-4107-be80-b55b7002f389.png)

I hope the issue is clear, 
Let me know if you need anything else 🙂

**Comment by sinclairzx81** [comment]
@noamokman Hi, Thanks for reporting.

Ah, this is actually intentional. TypeBox is internally stateless, and doesn't track any `$id` references for types, so it's unable to dereference the target type to apply a Partial to it. Because it can't dereference types, the default behavior is to just map `TPartial<TRef<T>>` to `TRef<T>` (with no partial applied). Consider the following values for `R` and partial `P`. Note that in order to make `T` partial, it needs it needs to be able to dereference `T` by way of `R` (which currently isn't possible)

```typescript
const T = Type.Object({ x: Type.Number() }, { $id: 'T' })

const R = Type.Ref(T)         // const R = { $ref: 'T' }

const P = Type.Partial(R)     // const P = { $ref: 'T' } // can't dereference `T`, so just return R
```
This is a known limitation in TypeBox, and applies to using `TRef` with `Partial`, `Required`, `Pick`, `Omit` and `KeyOf`. The current logic interprets `TRef` as a kind immutable (or unreachable) reference that cannot be mapped. So when when applying a Partial to a Ref, TypeBox just returns the Ref with no Partial applied (making the static type correct).

Another alternative approach may be to `throw` for `TRef` composition (in which case the return type would be `TNever`), This is being considered for later revisions. 

### Workaround

In most cases, you can just apply the Partial to the target type if you have access to it, but in other cases you may only have access to the `TRef`. TypeBox is unopinionated here and can't really assume too much as to how users will use `TRef` (as there are runtime / stateful considerations that TypeBox can't predict for all cases). But with this in mind, it is possible to implement type dereferencing using the following. 

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjmpgOICuBUAJubiQBYYgHkBKGAZjszYcA8mGIQAdgGc4AXzi8oEEHADkAASnAJJADYFgUAPQx0GAEYQAHqoCwAKAdGjcALTuPnr95++--gPcnFx5eDCgMHQwpAC4UKAISAGs4Agl6OAARcL4UMylgt0DiktLihwwrSFg4CQIQaLBEjDhQnKiZBAc4OErq+FNMFGyI3gAeZF6rGEj6GWRBdgIAPjgAXhQpmfT50LHtMKg8VYB+YZzx3FW45G64EkkpeFH2kmj12owAdzgAWQIwGMnlBtABzJisJbLAAUAEo7n1oPBeNQdOIJK0+BMtrN5osODCpJCODccBAxMBHnF8QRROiZBsELJYTc9shVl17D0ei8Ih0AHRSDAwaFEoQEfkAEmA9AAhDgxUtYT1nHgYNAWpMCDJeZE3ncecLqFAMRQMPzQqLiZw4OT6cruXBVTwYMbTWzlndZAiqkiFKiSOishdsZVtnMUDTCdabizzqMJhyDT1gLxoWaaHR6PzkJbFRxYcrOY7uanobLdQKWNqreKpaNC3AYCwlD8AKJQJRQaEAAwAwmkJBB4PQLnBpRlVJKEPmJRPZKoe-CuSW4BFXSbg6NoZW3lJ+aDhbWlvW+LDZcrtfGseynSEMCRjVoAG6akY3z0r7nyDC6IWIZNuXXN04FnVJ5nfcZ2UA70V1g2DCjKJDkKQwo2yseowF0DBEJQvD8J8BwHAeaR4EmD4zX5YRzAAKwfEUkCsG4zH5AA5agQHMcI4TkHAkAnOJVGQVQ5AdO8UGIx54C4ABGD42j5PcLT4dMcEQccZUE2SROZVc9MdZ05NcVZbnsEinlaAAmeS+FeaJlLTWS+I0+gtMsnSxP01dnWs4zWhkyTSNaABmGzDj1ezLS4SznIEtQuGCjyvP051Qr86LAosrgABYwrs-couC2LNPi7KkuS7yQly9LgqIsypLgAAFCiWMauhiAIXRoQUiL90g7rssbCqS1VUdRibCAUGoujAzGRibnYzjwjkT8HEGFpmo2fAiFIMZ1ogXgmtWYaTuS1V1qaj5GJOOIJA4rijgAHzgVFR14bQMAyWQgA)

```typescript
import { Type, Static, TypeGuard, TSchema, TRef, SchemaOptions } from '@sinclair/typebox'

// --------------------------------------------------------------------
// References: Track and Deref Types
// --------------------------------------------------------------------
export namespace References {
  export type TDeref<T extends TSchema> = T extends TRef<infer S> ? TDeref<S> : T
  const references = new Map<string, TSchema>()
  export function Ref<T extends TSchema>(schema: T, options: SchemaOptions = {}): TRef<T> {
    references.set(schema.$id!, schema)  // Store T as reference
    return Type.Ref(schema, options)     // Return TRef<T>
  }
  export function Deref<T extends TSchema>(schema: T): TDeref<T> {
     if(TypeGuard.TRef(schema)) {
       if(!references.has(schema.$ref)) throw Error(`Cannot deref $id '${schema.$id}'`)
       return Deref(references.get(schema.$ref)!) as TDeref<T> // Recursive TDeref<T>
     } else {
       return schema as TDeref<T>
     }
  }
}

// --------------------------------------------------------------------
// Example: Replace Type.Ref for References.Ref
// --------------------------------------------------------------------
const T  = Type.Object({ x: Type.Number() }, { $id: 'T' })   // T
const R1 = References.Ref(T,  { $id: 'R1' })                 // R1 -> T
const R2 = References.Ref(R1, { $id: 'R2' })                 // R2 -> R1
const R3 = References.Ref(R2, { $id: 'R3' })                 // R3 -> R2
const R4 = References.Ref(R3, { $id: 'R4' })                 // R4 -> R3

const P = Type.Partial(References.Deref(R4))                 // deref to TObject<{ x: TNumber }>

type P = Static<typeof P>                                    // type P = { x?: number | undefined }
```
Note, some attempts were made in 0.26.0 to internally implement the above, however given the myriad of ways users may need to ref / deref, it was decided this is probably best left out of the library (but there may be some utility types to handle this setup in later releases). It's a complicated problem to solve internal to TypeBox, with the above example the recommended approach for now.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@noamokman Hi, might close off this issue as the inference should be working as expected (at least with the current design). I may look at returning a `TNever` for mapping operations on `TRef` + runtime `throw` in future. but for now I'm quite happy with the `TRef<T>` -> `T` unmapped return value (but could probably put some documentation up around this)

I'm open to ideas on providing some auxiliary `References` implementation (as above). As mentioned, there's been some thinking that has gone into this, with the following the high level thoughts of what this `References` container should do (at this stage)

```typescript
const R: TRef<T> = References.Ref(T) // Store T, Return TRef<T>

const T: TSchema = References.Deref(R) // Deref T via R

const S: TSchema[] = References.Resolve(T) // For T, Deref all internal references

// Compilers

const C = TypeCompiler.Compile(T, [...S])  // Compile T with dependent S references

const c = ajv.addSchema(S).compile(T) // Similar usage for Ajv
```
Am open to thoughts, but will close up this issue for now.
All the best!
S
