### ISSUE TITLE
Revisit #427

### ISSUE THREAD

**Issue by russell-dot-js** [sinclairzx81/typebox#428]
Hi @sinclairzx81,

No way to reopen #427 but I think there was a misunderstanding in my question.

Not looking for anything at runtime or any codegen... typescript is used for developer sanity and knowing that if something compiles it should behave as expected, not for any runtime functionality.

For example, ajv exposes a generic type called JSONSchemaType:
```
type User = {
  id: string;
  firstName: string;
}

// to assign a JSON schema to schema, it must be a valid json schema for User, defining id and firstName as strings.
let schema: JSONSchemaType<User>;
```

Here's an overly simplified example of the **type** I'm looking for (calling out type specifically here to avoid confusion that any runtime behavior is expected):
```
type SchemaOf<T> = TSchema & { static: T };
// good
const foo: SchemaOf<string> = Type.String();
// bad
const bar: SchemaOf<string> = Type.Number();

// good
const baz: SchemaOf<{ hello: 'there' }> = Type.Object({
  hello: Type.Literal('there'),
});
// bad
const bae: SchemaOf<{ hello: 'there' }> = Type.Object({
  hello: Type.Literal('where'),
});
```

This example works, but the devil is in the details. Any reason why the library can't ship a battle-tested type for you that you can use to enforce that a given TSchema is a schema for a given type?

**Comment by sinclairzx81** [comment]
@russell-dot-js Hi, sorry about that, I thought you meant deriving types at runtime. Let me go into a bit of detail on this `SchemaOf<T>` type.

### SchemaOf

You can implement `SchemaOf` explicitly using the following (where each raw TS type is mapped to it's TSchema analog), the following is a quick of example of how to achieve this.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQHYGcCuUCmAaOAFUMzABt8iB5AIwCscBjGAwgQSigEMBPVgZRhRgqAOasAcphA0cUVgCEIECl1STMZMpJwA3OXAC+cAGZQIIOAHIAAuhGMyXYFAD0MHmBw0IADysAsABQwTi+kLBwHl5w-IwAFjggXFQmJOQ4AEo4ACaYjDgAPIRwYTA4qDnocJioANaoEADuqADaALoAfHAAvESlvuWV1a0iJgYAMgQAdLNjBpntcAD8cK1xicmphROdM7MbSSlppBTZeQWFmZ1LAFxr7aHh0PDROLEJR6npFHB--8UBkMqjV6o0Wh1un00FhcMUfkVDlsThlzvkioROlinhFXp53kjjrQGMx-n9AWUKiDsoxoDlCnUcDwICY4Go+KCGs1UFjetR6EwYIUkK0ANJwERwRnM1mEdr3QnbQhirpGTo4l5RfEfTbHDjcHhk8klSnDTngnl8mHYDH63iFRUmYpY9UhIKuVxwACyXDA1UI-C1MREMAgbKICiIhKI0w1kTeOq+TpNgyp1VqXJaULgwT+KeBI3mUDgUzgs2mRbgixWieRCMKrVL5cW3Vuuf6pupTDpDKZLLZqA5GYt3VWjuJgudbaCeaBabgdp4hUrAFVR7W9Zx7Wu4NPZ53qughCJRH9VgHj2Jd+38-PUNJZMWa4QpDIDHuO6mzT4VDg1M+lF-f8P1vM17y0MlzykCCQIkPQ5GCYIPRQXwuHAChggTEo+kdYV2y4e4f1UdR2xoe4j2EMQ8HbRh7nvN95HbHI6M0Mh2xwe5WgARgIAAmAgAGZHhnUwWIYjp21Ee4EHbP5fDEx9qJEv4eAUuQlLJAAvNSoHbQxgkMTogA)

```typescript
import { Ensure, TTuple, TObject, TArray, TString, TNumber, TBoolean, TNull, TNever } from '@sinclair/typebox'

export type SchemaOfTupleReduce<T extends unknown[]> = T extends [infer L, ...infer R] ? [SchemaOf<L>, ...SchemaOfTupleReduce<R>] : []
export type SchemaOfTuple      <T extends unknown[]> = Ensure<TTuple<SchemaOfTupleReduce<T>>>
export type SchemaOfObject     <T extends Record<keyof any, unknown>> = TObject<{ [K in keyof T]: SchemaOf<T[K]> }>
export type SchemaOfArray      <T extends unknown> = Ensure<TArray<SchemaOf<T>>>

// Maps TS type into a TB TSchema T.
export type SchemaOf<T extends unknown> = 
  T extends [infer L, ...infer R] ? SchemaOfTuple<[L, ...R]> :
  T extends Record<keyof any, unknown> ? SchemaOfObject<T>:
  T extends Array<infer U> ? SchemaOfArray<U> :
  T extends string  ? TString :
  T extends number  ? TNumber :
  T extends boolean ? TBoolean :
  T extends null    ? TNull :
  TNever

// Example
type T = SchemaOf<{
  a: boolean,
  b: string,
  c: number,
  d: null
  e: [1, 2, 3]
  f: number[]
  g: {
    x: number,
    y: number,
    z: number
  }
}>
```
The above will support the following.

```typescript
// good
const A: SchemaOf<string> = Type.String()

// bad
const B: SchemaOf<string> = Type.Number()
```
However, this can be directly expressed as the following without mapping.
```typescript
// good
const A: TString = Type.String()

// bad
const B: TString = Type.Number()
```

### Why is SchemaOf omitted from the library?

> This example works, but the devil is in the details. Any reason why the library can't ship a battle-tested type for you that you can use to enforce that a given TSchema is a schema for a given type?

The reason TB doesn't implement `SchemaOf` by default is that ambiguities can exist for certain types (for example intersect and union) where it's not possible to correctly map the TS representation to the equivalent JSON Schema representation. This is due to limitations in TS not being able to decompose types into their constituent internal representations). This is a fairly complicated topic (the devil is in the details), but consider the following examples. 

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4FEB2AzgK5TYrLFgA25yA8gEYBWGAxjDsgIJRQCGqLgGUYUYPgDmXAHLEQjDFC4AhCBFr98s4tWqyMANyVwAvnABmUCCDgByAAKEJbav2BQA9DHQZGEAA87AFgAKDCMAMhYOB9MOGE2AAsMEH56C0oaDAAlDAATYjYMAB5kOEiYDHx8wjhifABrfAgAd3wAbQBdAD44AF4UCoCqmrqOiQsTABkcADoFyZMcrrgAfjgOxJS0jJLpnvmF7dT0zKpaPMLikpye1YAuTa6IqOh4OIwE5NOMrNo4ICgWVhqNavUmi12t0+oMCCQyGV-qUTrtztkrkVSsgerjXtEPr5vjszkxWBwgYCQZVquC8mxoPkSo0MKgIBY4FohBDmm18LiBigyewYCUkB0ANJwCRwFlsjnILpPVFnMqS3pmHr496xIkqjK8ASoSlU8o0sY8qH8wXw0jYw2CEr6ixlXFa8KhTyeOAAWX4YDqyGEuviEhgEE5KBUKBVKDm2pin2JvxdZpGtLqDV57VhcDCgLTYPGSygcFmcAWcxLcBW62TaORJQ65crKz6D3zQ3NdPYjOZrPZnPw3KzVr6G2dwo4ro7oQLoIzcAdqBK1YAquP62dlyUN3BZ-Pu3VCGIJJJARsg6epPvO4XF-h5IpS3XkHIFCYD130xb-BoMFor5qP+gFfveFqPnolKXnIUFgTIRhKGEYRengAT8OAtBhEm5SDM6YqdvwTx-po2idowTwnuIUhYJ2bBPI+H7KJ2+QMbo1CdhgTwdAAjDgABMOAAMwvHOlhsUx3SdpITwIJ2gIBBJz60WJgKoEpSgqZSABeGlQJ2phhKY7rIZ63rIEkwB1K00CNHUihsPwxCEF8QZwBAjAuVAxh1GGSguRSnx1PwdRGPw1DEPwVT5O5LAiiGGDWSk+BwGkYBgGeOCMMQ8BWXArTWDehA-GkCXxqEDJEPA3DKiVqoIIpcCMc+5gAGSIOpcBUWexmCmgmBzFOMAABRyapcCNf1GBzO+z7DQAlFpQKdVNcyiNRkgLUZ82mahlaxJZvl1DAKRwAyfDxcVJIJVlOUHV8SZpRlN55QVEBSOVlUnnAKi1SSewNXpbUdZR16SL1gyrQAkvgVRQAFI0dPJKC+INcUcKNE1PKts1KAtOCmItyOrUNmMraj61nvjZg7aEXS0yh3r7Sdr22fZ7BOS5Z02JAzhVBUhjhZFVTHadfnw-FIWxeShKYHUw2EBGJ1fE9Z7SnU51kBwtNffAADCf0pmKjXNUowMIJ13VSBDKMDXrPMQHzGDDUj40k+jI1IJNqO41A1OE0tBao6TSDkwNlNSP7tP00AA)

```typescript
// This works because TS observes intersected types as evaluated object types when mapping, but is wrong schema type.
const A: SchemaOf<{x: number} & {y: string}> = Type.Object({
    x: Type.Number(),
    y: Type.String()
})

// ... this is the correct schema type, but the type mapping is wrong.
const B: SchemaOf<{x: number} & {y: string}> = Type.Intersect([
    Type.Object({ x: Type.Number(), }),
    Type.Object({ y: Type.String(), })
])

// ... this works because composite evaluates the intersect as object types (so the mapping is correct)
const C: SchemaOf<{x: number} & {y: string}> = Type.Composite([
    Type.Object({ x: Type.Number(), }),
    Type.Object({ y: Type.String(), })
])
```
TypeBox tries to express schematics as analogs to type representations internal to the TypeScript compiler (i.e. how the compiler would observe an intersection as a tree of AST nodes). TypeBox does this for the purposes of computed types; but because the TypeScript language doesn't permit access to internal AST representations through type mapping (instead exposing intersections as evaluated types), it's difficult to reconcile the exact schematic intended by the user.

This aspect of TypeBox is a ongoing area of research, but given some of the limitations in TS, this functionality is left outside the library and left for users to experiment with in user space (as per `SchemaOf` example). The project is open to including reference implementations provided by users as part of the [examples](https://github.com/sinclairzx81/typebox/tree/master/example), but can't be made standard functionality until some of these edge cases are identified, documented, and tested.

The SchemaOf example is a basic reference implementation that handles objects, tuples and arrays, but not union and intersection. Have a go experimenting and extending this type. I can include in the `examples` if you want to submit via PR, but without solutions to union and intersect (and other types like record), I can't include as standard.

Hope this helps
S

**Comment by russell-dot-js** [comment]
It is 1:30 in the morning here in California but I didn’t want to close out the week without thanking you for taking the time for this in-depth and wizard level response. I will be hacking away with this ASAP.

To help me contribute to your repo, and the examples, can you recommend any documentation on the difference between Intercept and Composite? I’m struggling to find a use case where Intercept is preferable. Composite seems to always produce the desired effect (and has the added benefit of being able to control additionalProperties) but maintaining Intercept seems to add a lot of complexity so I imagine there must be some underlying value I’m failing to grok

**Comment by sinclairzx81** [comment]
> can you recommend any documentation on the difference between Intercept and Composite

At a high level, the Composite type will evaluate an array of `TObject[]` to be `TObject`. This is different from `TIntersect` which will simply return the `allOf: [...]` representation. For example.

```typescript
const T = Type.Intersect([                 // const T = {
  Type.Object({ x: Type.Number() }),       //   allOf: [{
  Type.Object({ y: Type.Number() }),       //     type: 'object',
])                                         //     required: ['x'],
                                           //     properties: {
                                           //       x: { type: 'number' }
                                           //     }
                                           //   }, {
                                           //     type: 'object',
                                           //     required: ['y'],
                                           //     properties: {
                                           //       y: { type: 'number' }
                                           //     }
                                           //   }]
                                           // }

const T = Type.Composite([                 // const T = {
  Type.Object({ x: Type.Number() }),       //   type: 'object',
  Type.Object({ y: Type.Number() }),       //   required: ['x', 'y'],
])                                         //   properties: {
                                           //     x: { type: 'number' },
                                           //     y: { type: 'number' }
                                           //   }
                                           // }
```
Previous to 0.26.0, TypeBox actually implemented Intersect using the Composite representation. Because Intersect is now implemented by way of `allOf: [...]` (which is correct), the Composite type was primarily added as a fallback for users who needed the flat Object representation.

However in addition, the Composite type is currently serving as provisional infrastructure for a possible future mapped type. Where the Composite type is would be analogous to the following TS mapped type (which evaluates the intersection)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UoG8oA8BcUB2BXAtgEYQBOUAvlAGQpQhZ5GkUCwAUO6JFAKIK0BtANJQAltigBrCCAD2AM1gBdLDGFKKUAPRaoXaH0SpMOAsRIAaOgzPNKOqBABuAQwA2uF8AgATKAGNZfDBZAGdRbyA)

```typescript
type T =  { x: number } & { y: number }

type E = { [K in keyof T]: T[K] } // type E = { x: number, y: number } // evaluated composite
```
The Composite type may be renamed to a more general Mapped type in future revisions of TypeBox, but only if there is a way to express mapped types as a runtime construct that can statically infer. This currently doesn't seem possible in TS.

For now, the preference for expressing intersected types would be using `Type.Intersect`, as there is liable to be a little bit of churn in future with respect to Composite. 

Hope this helps
S

**Comment by sinclairzx81** [comment]
@russell-dot-js Going to close this one off for now also. The `SchemaOf` isn't likely to be a standard feature library (as it's possible to just use the `TSchema` types as they are now). Additional mappings will be something that will need to be done at a higher level abstraction, but could potentially look at including an `example` of this mapping at a later time, the project is open to PR's in this respect.

But for now, will close.
Cheers
S
