### ISSUE TITLE
Any plans to allow multiple TypeSystem instances?

### ISSUE THREAD

**Issue by pastelmind** [sinclairzx81/typebox#442]
I tried adding custom string formats (i.e. `isURL()` using [validator.js](https://github.com/validatorjs/validator.js)), but discovered that `TypeSystem.Format()` and `TypeSystem.Type()` modify the global registries (`TypeRegistry`, `FormatRegistry`). This could cause problems if I import another package that also adds its own types and formats using the same names.

```ts
TypeSystem.Format('url', (value) => isURL(value));
// Error: Duplicate string format 'url' detected
```

Perhaps this could be solved if users could create their own `TypeSystem` instances and customize them instead. Is this feasible?

**Comment by sinclairzx81** [comment]
@pastelmind Hi!

> Perhaps this could be solved if users could create their own TypeSystem instances and customize them instead. Is this feasible?

Um, maybe. The reason for them being modular / singleton-ish is so they can act as a shared registry for the `value`, `compiler` and `system` modules. The singleton approach was reasoned about as there should only be one definition of a format or type defined within an application, and by keeping the registries singleton, it means overriding an existing format would result in overriding that format / type across the entire application. This ensures a single assertion for any given type or format across an entire application (which is desirable I think, as there should only be really be one definition for `email`, `url`, `uuid4`, etc)

If working through the `TypeSystem` module, I do actually implement checks for duplicate definitions [here](https://github.com/sinclairzx81/typebox/blob/master/src/system/system.ts#L59-L69). This would be the most ideal way to define both types and formats (vs calling into the registries directly), however I keep the registries fairly open in  `typebox.ts` as there are scenarios where users may need more control over the registration of new formats (inclusive of having the ability to override them). Examples of which may include extending the type builders. See [here](https://github.com/sinclairzx81/typebox/blob/master/example/typedef/typedef.ts#L177-L189) where the registries are used to implement the JSON Type Definition specification, and where careful naming is used to avoid overlap.

In terms of providing instance registries (as you suggest), perhaps...but this would require passing the registries into the compiler and type checkers (which I'm not sure would provide much benefit for 99% of cases), The following would be how that looks.

```typescript
const typeRegistry = new TypeRegistry()
const formatRegistry = new FormatRegister()

Value.Check(T, value, { typeRegistry, formatRegistry })
TypeCompiler.Compile(T, { typeRegistry, formatRegistry })
```
In all, this is probably not something I'd be willing to implement (at least at this time). Generally I tend to avoid singleton patterns in software (as singletons today tend to be multi instance tomorrow), it's just that the pattern has proven to be particularly apt for the TB registries. I'd first need to see significant problems caused by the pattern to justify making a change.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@pastelmind Heya, will close of this issue for now as there's no immediate plans to change the current setup, but may revisit in future.

All the best!
S

**Comment by denis-ilchishin** [comment]
@sinclairzx81 Thank you for your work!

I've been trying to build a custom type system on top of typebox, and for my use case it is essential to have different logic for server and client (web mostly), while sharing the same code base (basically custom server/client contract/interface type system). And obviously I don't want to include server-only code to client's bundle. Right now the only way to do that, is to import schema and validation logic separately, something like:

```TS
// client.ts
import 'package/client-types' // which imports Typebox and populates TypeRegistry for client
import { Type } from 'package/type'


// server.ts
import 'package/server-types' // which imports Typebox and populate TypeRegistry for server
import { Type } from 'package/type'
````

It would be so much better, if I can provide separate instances of these registries and completely isolate usage of typebox, and not worry about other libraries register a type or format with the same key, or something like that.
