### ISSUE TITLE
Check passes while Errors returns an error in this Type.Any scenario

### ISSUE THREAD

**Issue by jtlapp** [sinclairzx81/typebox#451]
I found a scenario where `Check` returns `true` despite `Errors` returning an error. When I run this:

```ts
import { Type } from '@sinclair/typebox';
import { Value } from '@sinclair/typebox/value';

const schema = Type.Object({
  int: Type.Integer(),
  whatever: Type.Any(),
});

const value = { int: 1 };

console.log('check', Value.Check(schema, value));
console.log('errors', ...Value.Errors(schema, value));
```

I get this:

```
check true
errors {
  type: 39,
  schema: { [Symbol(TypeBox.Kind)]: 'Any' },
  path: '/whatever',
  value: undefined,
  message: 'Expected required property'
}
```

I don't know what the correct behavior should be. Is `undefined` a valid `Any` property?

(version 0.28.13)

**Comment by sinclairzx81** [comment]
@jtlapp Hi, thanks for reporting! This is a good catch!

So, the correct behavior here should be that the property key is required (so the error reporting was correct, just not the validation, eek). I've quickly pushed a fix for this on `0.28.14` to resolve the issue and implemented tests to capture this particular case. You can review the PR on https://github.com/sinclairzx81/typebox/pull/452. The issue was limited to `any` and `unknown` where there was a fall through case on object key assertions. Other types undergo more exhaustive checks so are not implicated, but the `any` fall through case is certainly an interesting one.

Again, thanks for reporting!
Cheers
S

**Comment by jtlapp** [comment]
Gosh you're quick. Thanks so much. I have the new version working.

**Comment by sinclairzx81** [comment]
@jtlapp Hey all good! :) Will close this one off for now
