### ISSUE TITLE
How to implement types with refined static types AND runtime value checking

### ISSUE THREAD

**Issue by chrisui** [sinclairzx81/typebox#461]
Sorry if this has been answered somewhere but I'm struggling between `TypeSystem.Type` and `Type.Unsafe`. I'm trying to implement a `StringEnum` like defined [here](https://github.com/sinclairzx81/typebox#unsafe-types) but quickly realised that `Unsafe` types would fail when passed through `Value.check`. So then I moved over to try and use `TypeSystem.Type` but then quickly realised I've lost the ability to refine the type based on the options inputted.

Eg. 

```ts
type StringEnumOptions = { type: 'string'; enum: string[] }

export const SpecialStringEnum = TypeSystem.Type<string, StringEnumOptions>(
  'StringEnum',
  (options, value) => typeof value === 'string' && options.enum.includes(value)
)

export const StringEnum = <T extends string[]>(values: [...T]) => {
  return SpecialStringEnum({ enum: values, type: 'string' })
}
```

```ts
describe('StringEnum', () => {
  it('allows definition', () => {
    const Key = StringEnum(['NOA', 'OTHER'])
  })

  it('will have a sensible inferred static type', () => {
    const Key = StringEnum(['NOA', 'OTHER'])
    type Key = Static<typeof Key>

    // @ts-expect-error type check expected string
    const a: Key = 1

    // @ts-expect-error type check exepcted NOA or OTHER
    const b: Key = 'test'

    // success
    const c: Key = 'NOA'
  })

  it('will validate', () => {
    const Key = StringEnum(['NOA', 'OTHER'])
    expect(Value.Check(Key, 'NOA')).toBe(true)
    expect(Value.Check(Key, 'SOME_OTHER')).toBe(false)
    expect(Value.Check(Key, 0)).toBe(false)
    expect(Value.Check(Key, undefined)).toBe(false)
    expect(Value.Check(Key, {})).toBe(false)
  })
})
```

I've seen examples of doing this with type asserting `as TUnsafe<T>` but this feels a bit undesirable. Maybe this is THE solution for now though?

Thinking a bit further...

What if instead you had a third parameter on `TypeSystem.Type` which was a `constructor` function which would allow the creation of the underlying type to be created in such a way it could be made generic?

**Comment by sinclairzx81** [comment]
@chrisui Hi, thanks for submitting. 

Ah, There's actually a few ways to approach custom types in TypeBox, Currently only the `TypeSystem.Type` is formally documented, but as you've seen, is currently a bit leaky in terms of specifying generics (I will address this in later revisions as type registration and configuration using the `TypeSystem` is the preference in the future), However in the interim you can get a bit more "low level" and register types via the `TypeRegistry` directly. This provides more control over generics and inference, but with a slightly different setup.

### TypeRegistry

Rather than using the `TypeSystem.Set` function, you can call `TypeRegistry.Set` directly and just pass it a validator function. Using this approach means you will need to define a formal `TStringEnum` (as with other types) with an explicit `Kind`. Note the registry name (i.e. `StringEnum` must match the `Kind` specified via `TStringEnum`'s factory function). If both line up, then validation will work.

This should give you maximum control over the generics as it uses the same setup as TB standard types.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgaWAOwCYBo4GUYCGMwAxjgCq4kAWApiARQJ5i0BKtA5sAM4xRM4AXzgAzKBBBwA5AAEe6EgBsCwKAHoYLWgCMIAD2kBYAFCny2jtz4CAdLlowAPJX7pOAUTQBXEAD4ACml8KHcvX2kcAJ4aekY4ADcCJW9aAEo4AF4-RFM4OChHbyg0OC1WCFFE5NSszMyZG3dpOAAyVrgYugZbWh8QW0UUjFoeAKSU9NMhNNNafUhYOHQYWihRAhJaOFdQtE9+lzh51cweTrd9gG0AXSyLvc5bnJO+jHPKWIZck3yr1EwNwAXDIQmF+pE4Op1HAQN4+LCiDQClxeKtChgytoAIR5C5EUgg8hXfo6NY3PHlWgg6RNfbGX7HfpE6ZzBbQeAkCBoBFg-bhKQNI6vM4PdzPcY1UYgq62OXkG5pIl8g6+Fw5bI-fKFGDFUpIf7oDDA0GXVUgSFUml0ziQvq+EETVLnEQED4qgXq1lmExUuAAeTAxG55wa+AJJCcVMqAaDwBDflMXJ58EDwZ59w9-QCV2kAEFIdIAEKFgDC0kVQA)

```typescript
import { Kind, Static, TSchema, TypeRegistry } from '@sinclair/typebox'

TypeRegistry.Set<TStringEnum>('StringEnum', (schema, value) => {
  return typeof value === 'string' && schema.enum.includes(value)
})
export interface TStringEnum<T extends string[] = string[]> extends TSchema {
  [Kind]: 'StringEnum', // must match registered type!
  static: T[number]
  type: 'string'
  enum: T
}
export const StringEnum = <T extends string[]>(values: [...T]): TStringEnum<T> => {
  return { [Kind]: 'StringEnum', type: 'string', enum: values } as TStringEnum<T>
}

type Options = Static<typeof Options>
const Options = StringEnum(['A', 'B', 'C'])
```
I'm actually open to suggestions on how to improve TypeBox custom types. There's been several iterations of this over the years, but nothing formal or cohesive to make the process easier for users. The `TypeSystem` module was the first steps towards defining a actual system for type construction. If you've got some ideas to improve things (above the additional generics), let me know.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@chrisui Heya,

Will close this one off for now, will look to enhance the `TypeSystem.Set` to support more complex generic types in later revisions (but will require a minor semver update and some design changes to support). Should show up on `0.29.0`.

Happy to discuss more if you have any follow on questions (or suggestions) for the `TypeRegistry` implementation provided.
Cheers
S
