### ISSUE TITLE
Feature request: support `Type.Rest` like behaviour within objects

### ISSUE THREAD

**Issue by chrisui** [sinclairzx81/typebox#466]
I think a missing type for full compatibility with typescript is the usage of object spread syntax which acts like a true [extends function](https://github.com/sinclairzx81/typebox/issues/12) and is _not_ an intersection.

Eg. Consider the following:

```
const a = { x: 1 }
const b = { x: '1' }
const c = { ...a, ...b }

type C = typeof c // { x: string }
type T = typeof a & typeof b // { x: never }
```

The inferred type of `c` is not `typeof a & typeof b` but rather the property `x` is spread and _overrides_. This is the behaviour of `Object.extends()` in zod and is desired functionality for typebox.

`Type.Rest()`-esque idea for API:

```
const T1 = Type.Object({ x: Type.String() })
const T2 = Type.Object({
  x: Type.Number(),
  ...Type.Rest(T1)
})

type T2 = Static<typeof T2> // { x: string }
```

"Shallow merge" idea for API:

```
const T1 = Type.Object({ x: Type.String() })
const T2 = Type.Object({ x: Type.Number() })
const T3 = Type.Merge([T1, T2])

type T3 = Static<typeof T3> // { x: number }
```

_order matters_

my 2c is that `Type.Merge` seems simplest in every way while appearing more terse here

**Comment by sinclairzx81** [comment]
@chrisui Hi, thanks for the suggestion.

Unfortunately I don't think I can implement this for `Rest` as property spread syntax isn't supported in TypeScript (sadly). There's actually a lot of detail around this, but can't really implement this functionality without diverging from TS semantics (with the semantics tied to non-order dependent intersection). There's a bit of detail below if you're interested.

### Rest

TypeScript doesn't support rest property types, only intersection.

```typescript
type X = { x: number }
type Y = { y: number }
type T = { ...X, ...Y } // syntax error (use X & Y)

```
Rest is specifically used for some niche scenarios using tuple concatenation with TS compiler transforms. 

[Compiler TypeScript Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=Ly8gRWRpdCBUeXBlcyBIZXJlDQoNCnR5cGUgQSA9IFsxLCAyLCAzXQ0KdHlwZSBCID0gWzQsIDUsIDZdDQp0eXBlIFQgPSBbLi4uQSwgLi4uQl0NCg%3D%3D)
```typescript
type A = [1, 2, 3]
type B = [4, 5, 6]
type T = [...A, ...B] // [1, 2, 3, 4, 5, 6]
```
I agree though that `Rest` applied to object compositing would be nice. It's just that it falls outside the language. You can do this tho.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQw2hGoV4ADTgBeFJwB0AeS4ArDLRgAKJLwBcCzIoByAVxBcMUbQEoct0eMlwAmnKMYV6zTr2G0YwBlGCgaAHM7B2EnCXhkD0CvVQ0tXThWVhQU3wAefxQQsOpwnAA+DKymSWE4OEUGqUUwQkxYYAwKABpa+obXZtbrGA7uuGFsWyA)

```typescript
const X = Type.Object({ x: Type.Number() })
const Y = Type.Object({ x: Type.String() })
const T = Type.Object({ // TObject<{ x: TString }>
  ...X.properties,
  ...Y.properties, 
})
```

### Merge | Composite

Merge is actually implemented with `Type.Composite`. However keep in mind the resulting type for property `x` would be `never` (as per your example) as property intersection of `string` and `number` isn't possible. TypeBox follows TypeScript's rules for intersection here (both for `Composite` and `Intersect`) but with `Composite` producing an evaluated `TObject` schematic (and where `Intersect` would produce the `allOf` representation). However, the resulting types `A` and `B` below should be equivalent (irrespective of order)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQw1qzgAJCADcMUOAEE4ACmoQYWDNMb0Arow0ATOIwooA8lwBWGWjACUw2hGoV4SgLwpOAOgDCRJBUGsoA2nARkVFRYnDOru5wXgjCEWiYPpY2dspIvABc3hkAcrogXHLK9jj2ADQx4hEcmIUARBDWtjCt9alFGJmdOXmF6QMAyjBQNADmVTXRsRFQGACOuiwYhoWhrbytALq1wgfV0ecXl1cRS3BghJiwwBgUhSlC159fF7cRBYh9b5Az6-SI6ejmPA7QHA2HnUFRJDNDBtahlCpQVo4Y4fOF4hpXJGcNpuabUGZY7Aw-FwhFwA7UmnA0FU3FM2mNHCM9lfWKspwuNxwABCSX6PgAktQNFAKF0wkDYvEhaLkn0xoNsjBcnB-hrSuVKtVsHUCU1iXB2kNuvUIurfFl5SNxZMyXNjWdIrdwZCdu9TjzmZzzS1LR0tT04NzA1c6St1pttnBwnssUdozGfsHIvcII8YM9XgC2ZmQdmov8kK1ka1Uei5JSM6WzdFWc3ednsPV3u2yxdkW1w11I03e3G1hsVkndvt0yXe-Dy3cHnICy83qP23SIqm3paaySprNG-OFy2om2z1nW5vm7cGaer3A+UA)

```typescript
// Hover A (note evaluated as TObject)
const A = Type.Composite([              // const A = {
  Type.Object({ x: Type.Number() }),    //   type: "object", 
  Type.Object({ x: Type.String() })     //   required: ["x"],
])                                      //   properties: {
                                        //     x: {
                                        //       allOf: [
                                        //         { type: "number" },
                                        //         { type: "string" }
                                        //       ]
                                        //     }
                                        //   }
                                        // }

const B = Type.Intersect([              // const B = {
  Type.Object({ x: Type.Number() }),    //   type: "object",   
  Type.Object({ x: Type.String() })     //   allOf: [{
])                                      //     type: "object", 
                                        //       required: [ "x" ],
                                        //       properties: {
                                        //         x: { "type": "number" }
                                        //       }
                                        //     }, {
                                        //       type: "object", 
                                        //       required: ["x"],
                                        //       properties: {
                                        //         "x": { "type": "string" }
                                        //       }
                                        //     }
                                        //   ]
                                        // }
```
### Order Dependence and Extends

Order dependent property types (as per your example) isn't really supported in TypeScript (where TS will just produce intersections for any property keys that overlap). This is generally ok....but it does allow one to inadvertently produce an illogical `TNever` schematic if properties overlap with varying types. TypeBox is permissive of this because TypeScript is. However, considering something like `extends`, the production of an illogical `extends` isn't possible as the compiler will assert for overlapping properties of varying types.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgQTgG8BYAKDjhAC44kBXAWwCM05yBfc0SWRFNFlxwAQnFCokAEwDOBYnAD0iuAEkBGHHgDkI7f2zQowbDAA2AT3EhJs-qk3Dt+bQDpylGnBkwoyAOaUQcEhocpBACoWYMByEOhwYFAQMbBW2iD6mMYGEIxgmDAIzGbA7mQcoVXVNeHBUTFw2j5+SP76CHJIEPCYMjII-kiYJXgwEHAw0ToMLGhuHuRLZMtAA)

```typescript
export interface A {
  x: number 
}
export interface B extends A { // Interface 'B' incorrectly extends interface 'A'.
  x: string                    //   Types of property 'x' are incompatible.
}                              //     Type 'string' is not assignable to type 'number'.
```
Because of the above, we assume TypeScript interface `extends` performs subsequent `never` check and raises this as a diagnostic. This behavior is inline with classes also where properties and method signatures need to conform to the base (and where evaluated `never` is interpreted as a derived type breaking contract with the base). There's probably a bit more going on here specifically, but this is TypeBox's (or specifically my) interpretation.

### Summary

There's a lot of detail to consider here, but I can't implement much over what's already implemented. TypeBox composition needs to stay super aligned to the semantics of TypeScript (as close as I can get them anyway). In future, I would like to support more novel cases (like allowing users to write order dependent types through programmable mapping). But much of this comes down to being able to express certain constructs through type programmability (this is an ongoing thing for TypeBox :))

Hope this brings some insights!
Cheers
S

**Comment by chrisui** [comment]
This is great thank you. Understood. For my use case I can just wrap up [your example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAGnAC8KYQDoA8iIBWGEjAAUScQC4tmbQDkAriBEYopgJQV38xcrgBNDRsMPUNjMwtrNFt8KA4Acw8vWR8leGQg6JD9IxNzOH5+FBzwgB5IlFiEigA+AqKeZVk4OG02lW0wWkxYYAwWLGbWtv9O7tdifpxZcm85GSFMFCD8IlJSxYwIKhQaoA) as a utility, thank you.

**Comment by chrisui** [comment]
Related ask, any idea why [this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgPIBGAVhifAL5wBmUEIcA5AAIDOwAHYkANgWBQA9DHQYqEAB5cAsACg1JCIL7wAGnAC8KWQDpqdBgAokCgFzHMJgHIBXEFQxRLASjiNvGlo6cACahg4YZrT0MNZwdhEm+FBCAOY+fgHqqpra8MjhaI7mMXGSkiglDAA8NvbIyWl+AHxw5XBiOmpwcCZ9uiZg7JiwwBh8WN29fSGDw57E4zhq-mqBeXAAsp6pGOHVBRgKMBiCACZ8cADalNEM5FUwALrNllNXAII4AEJP9Wq+AytBBTKAYGAuKCCRKPaxTHp9EwfOYQEaLCbw6Ymb4otFjDGqHqrVSMNY5IL5ABM4W2UF2liuuhwISeWTUMkwKHC+CIpGqHIwEBYKGa7NkKGpRh5xBI-NkQolzSAA) doesn't correctly infer the correct types?
