### ISSUE TITLE
[Feature Request] Add support for creating oneOf schema

### ISSUE THREAD

**Issue by climba03003** [sinclairzx81/typebox#48]
Currently, I we can create `anyOf` and `allOf` schema with `Union` and `Intersect`. However, we are missing the `oneOf` schema.

Note. `OneOf` typing should be the same as `anyOf`.
For example:

```TS
const T = Type.Either([
  Type.String(),
  Type.Number()
])

type T = string | number

const T = {
  oneOf: [
    { type: 'string' },
    { type: 'number" }
  ]
}
```

**Comment by sinclairzx81** [comment]
@climba03003 Hi, thanks for the suggestion!

Yeah, I've been pondering a use case for `oneOf` for quite a while, and historically the `Type.Union(...)` has flipped between `anyOf` and `oneOf` behind the scenes several times in the past. See (https://github.com/sinclairzx81/typebox/issues/37) for the most recent update of `anyOf`. I did like the previous rationale there.

As for adding a `Type.Either(...)`, I guess it would need to bring functional value above and beyond what `Type.Union()` already provides, as well as being inline with the expectations of someone already familiar with the TS type system (i.e. structural typing, union discrimination). Also, TypeScript doesn't really have a notion of `Either` in the traditional sense (with Either usually meaning `left` or `right` values, not a set of possible values as is the case with unions). (Haskell definition of Either [here](https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Either.html)).

```typescript
// Possible API for Either which mandates on two types. But note that 'oneOf' isn't constrained
// to two possible options. Restricting to two types would be an artificial constraint.

type T = Type.Either(Type.String(), Type.Number()) // string | number
```
I'm not too sure about having two ways to approach the same problem. I think the expectation from the programmer creating a `Type.Either()` or `Type.Union()` is that the resulting type be `union` and the validation should just work. There is also a disconnect there with respect to having to remember a `Type.Either()` is just an alias for `oneOf` and `Type.Union()` is just an alias for `anyOf`, as well as needing to know the subtle differences between them. I had considered creating `Type.AnyOf()`, `Type.AllOf()`, `Type.OneOf()` in the past, but have felt it's better to align the API to TypeScript and capture the semantics of TypeScript in JSON schema rather than provide a full spectrum of JSON schema capabilities (if TypeScript had no direct analog). So, the goal for this project has primarily been to express TypeScript as JSON schema, but not necessarily to capture all of the JSON schema specification.

Still, I'm very open to discussing this more. If you can provide some use cases where `oneOf` would be the preference over `anyOf` I would be more than happy to discuss how to best provide that functionality. (perhaps as an option on the `Type.Union()`). I'm actually very open to discussing the pros and cons of `oneOf` vs `anyOf` with respect to `Type.Union()`. 

Thanks Again!
S

**Comment by climba03003** [comment]
I use this module mostly in `fastify`, `oneOf` fit most of the situation more than `anyOf`. For example, I have a base object then extends with some extra property. I need the input put to match exact one of the extended object only, but not at least one of them.

```TS
interface Base {
  metaType: 'string' | 'number'
  meta: string | number
}

interface StringMeta extends Base {
  metaType: 'string'
  meta: string
}

interface NumberMeta extends Base {
  metaType: 'number'
  meta: number
}
```

TypeScript can achieve `oneOf` but I think it is too complicated to compute the correct type in here, so I would rather concatenate the type with or.
```TS
const T = Type.Either([
  Type.String(),
  Type.Number()
])

T extends string ? string : number
T extends <first type> ? <first type> : T extends ........ : <last type>
```

Another solution maybe provide a options to choose using `oneOf` or `anyOf`. Default value can be the current `anyOf`.

**Comment by sinclairzx81** [comment]
@climba03003 Interesting mention to the conditional types, and you're right, those are a kind of `either`! 

Um, let me have a think about it. I guess in the example presented, the closest approximation would look something like the following in TypeBox.

```typescript
const Base = Type.Object({
  metaType: Type.Union([Type.Literal('string'), Type.Literal('number')]),
  meta: Type.Union([Type.String(), Type.Number()])
})
const StringMeta = Type.Intersect([Base, Type.Object({ metaType: Type.Literal('string'), meta: Type.String() })])
const NumberMeta = Type.Intersect([Base, Type.Object({ metaType: Type.Literal('number'), meta: Type.Number() })])

function test(base: Static<typeof Base>) {
    switch(base.metaType) { // note: unable to discriminate on base.
        case 'string': /* Base */ break;
        case 'number': /* Base */ break;
    }
}
```
But this loses the ability to have TS discriminate the `Base` type. However, it would be possible to re-express those types as follows which retains TS's ability to discriminate on the `Base` type.

```typescript
// typescript
interface StringMeta { metaType: 'string', meta: string }
interface NumberMeta { metaType: 'number', meta: number }
type Base = StringMeta | NumberMeta

// typebox
const StringMeta = Type.Object({ metaType: Type.Literal('string'), meta: Type.String() })
const NumberMeta = Type.Object({ metaType: Type.Literal('number'), meta: Type.Number() })
const Base = Type.Union([StringMeta, NumberMeta])

function test(base: Static<typeof Base>) {
    switch(base.metaType) {
        case 'string': /* StringMeta */ break;
        case 'number': /* NumberMeta */ break;
    }
}
```
I guess im trying to understand the scenario where the former would be preferred over the latter, as the same would be true for just writing these types out using `interface` and `type` keywords. Also, adding in the `oneOf` wouldn't help to discriminate the type in the underlying schema, so not sure how `oneOf` would necessarily help here.

I have added a quick test for this [here](https://github.com/sinclairzx81/typebox/blob/master/spec/schema/union.ts#L38-L55) that shows the schema discrimination that matches the expectations of TypeScript, with the first example in this reply more or less expressible with TypeBox today (outside of adding a `Type.Extends(...)`).

**Comment by sinclairzx81** [comment]
@climba03003 Ill leave this issue open for a week or so. Still open to discussing the implementation of `oneOf`, just not sure it provides any new functionality above the current `anyOf` when contrasted with the capabilities of TypeScript and some of the runtime aspects (at least what's been discussed so far). But not too sure... would you be able fork TypeBox and implement the `Type.Either(..)`?. A reference implementation might be good to discuss.

Cheers mate

**Comment by climba03003** [comment]
I will be a little bit busy on the next week. You can close the issue first and when I get time on it. I will re-open this issue later on and we can discuss further on it.

**Comment by sinclairzx81** [comment]
@climba03003 Ok mate. Will close off the issue for now.

Thanks for the suggestion though :) I will give it some more thought over time. 

S

**Comment by sinclairzx81** [comment]
@Mazay98 Hi. At this stage. TypeBox won't be implementing the `oneOf` schema as part of the core. The `anyOf` schema is the closest approximation to a TypeScript structural union type, and `oneOf` is only really useful if your union types have a discriminator field to prevent multiple subschemas matching. Note also that discriminator fields are not mandatory requirement for TypeScript unions, so TypeBox opts for the `anyOf` representation for this reason.

In saying this you can implement `OneOf` using `Type.Unsafe()` if you need it.

[TypeScript Link Here](https://www.typescriptlang.org/play?ssl=24&ssc=26&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgE6U10DyYxEAdgM5wC+cAMygQQcAOQABLsA4kANgWBQA9DHQYARhAAeYgLAAoQ8uVwAtBctXrN23fsPHD46eYcMzAS-NPff-wHWhoYY2pCwggCusuwccG4eAgA8yHChMBgcACY8FNS0BADaALoAfAAUnIkAXHCFAHSNyMU4EGzAnFy1jAWssTwAvIi8AJSIhnBwUBgwkVBxaJj1AKrcBAIYSQiFANJwMnAA1hioEAIoxd2ExCQpu2W8hRyRIBoYUGXlSI31bf2t7k8fBGhl4wQMJh8gWhMNh3gAotoCOA5BhagA5CAZOAwGhwAAGakw+LgYGEmFgqDgBBIMB4BHpcCywC4xBiTJZJCgoBkRGg9RQVBZ+y43gIUwwAEdIkpaJl4G8SARIlwMPtzqdInAqAQAG5qmAAdwgcFZUEitLmBDkcipUpluut8px6h47lZGCycG8MmkWQNeKqnhwWSI4txRDgdBg+R4IGgAYIcSqpsiGi4+ToOFxasdcmAoZg0G8huANol4XgAmtqrg5Qw+riuIgkQA5lQowmcTrk+5U+nM+Lo7GQRDTLCJ5PfOCSJ14ABBOBDRYYerMDQAKwwtK+LswtRX9QAMsAMlBreUxPOxCMcHnImiUOp6vhuRxW+UxqNDLPuPAAEJLk+SzrluO5IESj6HieZ4XmI-43ne1oPgez7oi8bxQJ+wI-nOcAAMJAYeoHbjAu6QahSwwe8cH4YhcD3lBz7-hAECokm2HfkYBi-qyKBAQknjlIU844P+OD4cUo6GJB-FDPgRCkEkkFnCgpRAA)

```typescript
import { Type, Static, TSchema, SchemaOptions } from '@sinclair/typebox'

// ----------------------------------------------------------------------------
// OneOf
// ----------------------------------------------------------------------------

export function OneOf<T extends TSchema[]>(oneOf: [...T], options: SchemaOptions = {}) {
  return Type.Unsafe<{[K in keyof T]: Static<T[K]>}[number]>({ ...options, oneOf })
}

// ----------------------------------------------------------------------------
// Example: Note the `type` property acts as a distinct discriminator. This is
// a requirement because if you have two structurally equivalent types nested 
// inside the oneOf, data that matches more than one subschema, the validator
// will report false (even though more than one subschema matches)
// ----------------------------------------------------------------------------

const A = Type.Object({ type: Type.Literal('A'), value: Type.String() })
const B = Type.Object({ type: Type.Literal('B'), value: Type.Number() })
const C = Type.Object({ type: Type.Literal('C'), value: Type.Boolean() })

const T = OneOf([A, B, C])

type T = Static<typeof T>
```

Hope this helps!
S

**Comment by bytenik** [comment]
Hi @sinclairzx81, we're hitting hard into this issue here at my work.

oneOf is the appropriate schema type for us -- our JSON schema is validated by ajv, and also, is used by libraries like JSON Forms which paints a form based on the schema. AnyOf and OneOf produce wildly different forms because of the different semantics.

I'm familiar with the unsafe mechanism you presented as a workaround. However, it doesn't support TransformKind, which we do also use heavily.

I just spent a few hours trying to work around this, writing the following code:

```

type UnionDecodeStatic<T extends TSchema[]> = {
    [K in keyof T]: T[K] extends TSchema ? StaticDecode<T[K], T[K]['params']> : never;
}[number];

type UnionEncodeStatic<T extends TSchema[]> = {
    [K in keyof T]: T[K] extends TSchema ? StaticEncode<T[K], T[K]['params']> : never;
}[number];

export interface TUnionOneOf<T extends TSchema[]> extends TSchema {
    [Kind]: 'UnionOneOf';
    static: UnionDecodeStatic<T>; // { [K in keyof T]: UnionStatic<T, T[K]['params']> }[number];
    [TransformKind]: //TransformOptions<UnionStatic<T, []>, UnionDecodeStatic<T, []>>;
    {
        Decode: TransformFunction<UnionDecodeStatic<T>, UnionEncodeStatic<T>>;
        Encode: TransformFunction<UnionEncodeStatic<T>, UnionDecodeStatic<T>>;
    };
    oneOf: T;
}

export function UnionOneOf<T extends TSchema[]>(oneOf: [...T], options: SchemaOptions = {}): TUnionOneOf<T> {
    function UnionOneOfCheck(schema: TUnionOneOf<TSchema[]>, value: unknown) {
        return 1 === schema.oneOf.reduce((acc: number, schema: any) => (Value.Check(schema, value) ? acc + 1 : acc), 0);
    }

    function UnionOneOfEncode(value: UnionDecodeStatic<T>): UnionEncodeStatic<T> {
        // Try to encode with each schema in the union until one succeeds
        for (const schema of oneOf) {
            try {
                if (Value.Check(schema, value)) {
                    // If the schema has a transform, use it to encode
                    if (TransformKind in schema) {
                        return (schema as any)[TransformKind].encode(value);
                    }
                    return value as UnionEncodeStatic<T>;
                }
            } catch {
                // Continue to next schema if this one fails
                continue;
            }
        }
        // If no schema matches, return the value as-is
        return value as UnionEncodeStatic<T>;
    }

    function UnionOneOfDecode(value: UnionEncodeStatic<T>): UnionDecodeStatic<T> {
        // Try to decode with each schema in the union until one succeeds
        for (const schema of oneOf) {
            try {
                // If the schema has a transform, use it to decode
                if (TransformKind in schema) {
                    const decoded = (schema as any)[TransformKind].decode(value);
                    if (Value.Check(schema, decoded)) {
                        return decoded as UnionDecodeStatic<T>;
                    }
                } else {
                    // If no transform, check if the value matches the schema directly
                    if (Value.Check(schema, value)) {
                        return value as UnionDecodeStatic<T>;
                    }
                }
            } catch {
                // Continue to next schema if this one fails
                continue;
            }
        }
        // If no schema can decode, return the value as-is
        return value as UnionDecodeStatic<T>;
    }

    if (!TypeRegistry.Has('UnionOneOf')) TypeRegistry.Set('UnionOneOf', UnionOneOfCheck);

    const res: TUnionOneOf<T> = {
        ...options,
        [Kind]: 'UnionOneOf',
        static: undefined as any, // This will be inferred by TypeScript
        params: [],
        oneOf,
        [TransformKind]: {
            Encode: UnionOneOfEncode,
            Decode: UnionOneOfDecode,
        },
    };

    const deleteThingsFromMe: MarkOptional<typeof res, 'static' | 'params'> = res;
    delete deleteThingsFromMe.static;
    delete deleteThingsFromMe.params;

    return res;
}
```

However, this still doesn't work correctly with refs. When a visitor for an Encode hits into this union type, it has to do a Value.Check on each union item. The problem there is that the Visit function you've got doesn't pass references into the Default case, and so any refs found underneath are unable to be dereferenced and it blows up.

I'm at a total loss for how to work around this without a change within the library. I'd prefer to see OneOf support natively, but if not, perhaps passing references into the Default function and then adding a second nullable argument to Encode and Decode that take in the reference array, so that I could manually support it? i.e. `IsTransform(schema) ? schema[TransformKind].Encode(value) : value;` -> `IsTransform(schema) ? schema[TransformKind].Encode(value, references) : value;`

**Comment by sinclairzx81** [comment]
@bytenik Hi,

I have been giving a lot of thought recently to including `oneOf` under a `ExclusiveUnion`, `ExclusiveOr` or `UnionXor` type, but I am not sure I want to go ahead with it just yet. An XOR type falls outside the semantics of TypeScript, and thus far, it hasn't been clear how to model it. 

This said, the imagined API would look like this

```typescript
// Builder
const T = Type.UnionXor([   // const T = { oneOf: [{ const: 1 }, { const: 2 }, { const: 3 }] }
   Type.Literal(1),
   Type.Literal(2),
   Type.Literal(3),
])
// Syntax
const S = Syntax(`1 ^ 2 ^ 3`)
```
And have the following inference rules

```typescript
// Union
Syntax(`1 | 2 | 3`)      // type is: 1 | 2 | 3
Syntax(`1 | 2 | 3 | 1`)  // type is: 1 | 2 | 3

// UnionXor
Syntax(`1 ^ 2 ^ 3`)      // type is: 1 | 2 | 3
Syntax(`1 ^ 2 ^ 3 ^ 1`)  // type is: 2 | 3
                         // -------------------------
                         //   : 1 xor 1 = never
						 //     : never | 2 | 3 | never 
						 //     : 2 | 3
```

---

The challenge with oneOf is that TypeBox would need to detect that two sub schemas may cancel out (O^2). This is because if a value matched more than one sub schema, the result is always `false`. While it is technically feasible to model for literal cases, it's far less obvious what to do when XOR operands are subsets of one another, consider

```typescript
// Union
Syntax('1 | 2 | number | null') // type is: number | null

// UnionXor
Syntax(`1 ^ 2 ^ number | null`) // type is: !(1 | 2) & (number | null)

                         // TypeScript Model
                         // -------------------------
                         //   : 1 xor number = never
						 //   : 2 xor number = never
						 //     : never | never | number | null
						 //     : number | null <-- incorrect - (cannot accept 1 or 2)
```
It is the above that is preventing me from implementing `oneOf`. I think my reasoning is correct that `1 ^ 2 ^ number` would require TypeBox to transform `1` and `2` to negated types + disjoint union which just isn't possible in TypeScript. 

TypeBox only selects a subset of Json Schema to express the semantics of TypeScript, so introducing additional semantics for `Xor` and `Not` is only going to cause long term semantic issues for TypeBox. But I think if TypeScript added support for negated types (minimum), support for oneOf could be achieved through transformation.

This TS negated types suggestion is still open from 2015

https://github.com/microsoft/TypeScript/issues/4196 

---

With all this said, I am interested in including  `oneOf` support, but in other ways....

TypeBox will be introducing `oneOf` validation support in the next version (+ additional JSON Schema keyword validators). The TypeBox type builder still won't be able to create a `oneOf` for the reasons mentioned, but I am moving TypeBox to a state where it can begin reason about `XOR` and `NOT` in a more formal way.  I may consider a `oneOf` to `anyOf` transformation inside `Value.*` for the purposes of XOR enumeration, but probably won't see this before the end of the year.

TypeBox-Next should be ready mid September (very soon), it's a big release.

I hope this brings some insight
Cheers
S

**Comment by bytenik** [comment]
@sinclairzx81 - In my use case, I'm totally happy with a regular TS union as the output. My own hackaround does work for me other than with transformers.
Would you consider implementing the optional parameter I mentioned so that I could use my custom solution?

Right now, the only thing I've managed to do is to use `Type.Union` (`anyOf`) and add a custom property to it, `x-really-oneof` and when I find one of those, I replace its parent with a `oneOf` in the generated schema before giving it to ajv or to forms. But its a massive hack.

**Comment by bytenik** [comment]
@sinclairzx81 - wanted to make sure you saw my last message. Thanks!

**Comment by sinclairzx81** [comment]
@bytenik Hi, sorry, have been across a few projects of late.

> In my use case, I'm totally happy with a regular TS union as the output. My own hackaround does work for me other than with transformers. Would you consider implementing the optional parameter I mentioned so that I could use my custom solution?

Unfortunately, I can't really add anything internal to TypeBox that is unrecognized by the JSON Schema specification (if talking about `x-really-oneof` property to transform `anyOf` to `oneOf` in decode pipelines). Of the custom things that have been added to TypeBox over the years, I am forever looking for ways to remove them just to keep TypeBox operating within the constraints of the JSON Schema specification. With this in mind, custom options or internal logic tied to those options is very much a no go zone.

As mentioned though, I am looking for ways to provide better support for `oneOf` and other keywords. The next version of TypeBox (due sometime in September (tentative)) will be able to compile and check the vast majority of the JSON Schema specification (2020-12), and accept raw schematics (meaning you can use pass `oneOf` schematics to the validators and they will validate under the semantics of the JSON Schema specification). This is a significant step for TypeBox and puts the validators on par with Ajv, but the work was mostly done to open future doors for "full spec aware" value processing (as it relates to Transform/Decode/Parse). It's been a big undertaking to get the infrastructure in place, but should provide a lot of options to improve Decode and other Value.* functions.

So, the first point of call will be to get the new validators ready and published, followed by subsequent work (beginning next year) to look at overhauling Value.* to enumerate using specifically JSON Schema keywords (meaning `oneOf` will naturally work with Decode). In the meantime, workarounds will be required.

With all this said. I am open to community API design suggestions just so long as they can be added while keeping TypeBox on spec, so if you would like to follow up on this thread once the new version is out, I would be very keen to discuss ideas on how to improve Value.* under the new validation infrastructure.

Hope this brings some insight
Cheers
S
