### ISSUE TITLE
React app triggers unsafe-eval when strict CSP is used

### ISSUE THREAD

**Issue by imsuvesh** [sinclairzx81/typebox#480]
Hi,
I am trying to use Typebox to validate types in my react web app, we have strict guidelines regarding CSP policy, and when I use TypeValidation in final build files, I get 
![image](https://github.com/sinclairzx81/typebox/assets/14920241/013875fa-8bea-442b-a256-75ebc74bac4b)

After going through the code I found this part is triggering the issue.
![image](https://github.com/sinclairzx81/typebox/assets/14920241/47ebfd2b-1d37-4e8e-a4c5-12847f4cea49)

Mentioned in [‎src/compiler/compiler.ts](https://github.com/sinclairzx81/typebox/blob/3b6c9849bf962abfa6898bc06bff44fbcd1d3262/src/compiler/compiler.ts#L523)

Can you recommend what would be the possible solution for this? Adding unsafe-eval in script-src is not recommended.

**Comment by sinclairzx81** [comment]
@imsuvesh Hi, thanks for bringing this up, I really should put some documentation in place for these cases.

If a Content-Security-Policy (CSP) is configured for the environment, the TypeCompiler requires that the `unsafe-eval` directive is specified for `scriptSrc`. This is because the compiled JavaScript string needs to be evaluated on the runtime before use. While this does provide best performance, it will cause problems in restrictive environments. Essentially, If you're running code in a such an environment, the recommendation is to use `Value.Check` rather than modify your CSP policy.

### Value.Check

You can use the `Value` module instead to perform the same type checking as the compiler. This runs much slower than the compiler check, but is safe to use in CSP restrictive environments. It's performance is comparable to common JavaScript validators such as Zod, Yup, Joi.

```typescript
import { Value } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number(),
})

// Replace TypeCompiler / TypeCheck with Value.Check
const R = Value.Check(T, { x: 1, y: 2, z: 3 })

// Errors also available on this module.
const E = Value.Errors(T, { x: 1 }).First()
```
I'm forever hopeful to see more options for sandboxed content-security-policy configured evaluation in JavaScript in future. Unfortunately, today you do need to trade high performance. Possibly https://github.com/tc39/proposal-shadowrealm may provide some options in future.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
@imsuvesh Hi,

Will close off this issue as `Value.Check` is the alternative to use in CSP restrictive environments. Additionally, you can also use TypeBox with Ajv which may provide additional checking options based on the JSON Schema specification.

```typescript
import Ajv from 'ajv'

const T = Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number(),
})

const ajv = new Ajv()

const R = ajv.validate(T, { x: 1, y: 2, z: 3 })
```
Cheers!
S
