### ISSUE TITLE
support for "deprecated" 

### ISSUE THREAD

**Issue by mahendraHegde** [sinclairzx81/typebox#496]
I want to be able to mark a property as "deprecated", [jsonschema supports is available]( https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3), how do i achieve the same with typebox?

**Comment by sinclairzx81** [comment]
@mahendraHegde Hi,

TypeBox only currently supports schematics for Draft 06/07, with newer keywords (like `deprecated`) only available on Draft 2019 (so the TypeBox validators don't support it yet). That said, if you're using Ajv AND using with the 2019 spec ....

```typescript
import ajv from 'ajv/dist/2019'
```
...you can specify the `deprecated` keyword on existing types (it's just the property type hints are not defined due to them being on a different spec)

```typescript
const T = Type.Object({
  x: Type.String({ deprecated: true }) // 2019 keywords are supported (just not represented as options)
})
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@mahendraHegde Heya, will close up this issue for now, but recommend taking a look at the Ajv validator for 2019 support for `deprecated`. As above, just pass the keyword on schema options on any given type, that should be enough to express the schematics as you need :)

All the best!
S
