### ISSUE TITLE
Partial doesn't work correctly for recursive types

### ISSUE THREAD

**Issue by pqnet** [sinclairzx81/typebox#506]
Tested with Typescript 5.1.6 and Typebox 0.29.6

This does not work:
```
const Node = Type.Recursive(This  => Type.Object({
    name: Type.String(),
    next: Type.Partial(This),
}))
// this is equivalent to type Node = { name: string; next: Node } instead of type Node = { name: string; next: Partial<Node> }
type Node = Static<typeof Node>
const n: Node = {
    name: 'hello',
    next: {} // error, missing properties 
}
```

**Comment by sinclairzx81** [comment]
@pqnet Hi,

Unfortunately, TypeBox doesn't support `Partial` on the reference types `TRef` and `TThis`. The reason is due to `Partial` requiring a full schematic to map from, and where `TRef` and `TThis` both are just references containing only a `$ref` identifier. 

### Problem

Consider the following for the `TRef` case.

```typescript
const T = Type.Object({ x: Type.String() }, { $id: 'T' })

const P = Type.Partial(T)   // ok - T contains all the information needed to map

// ---

const R = Type.Ref(T)       // const R = { $ref: 'T' }

const E = Type.Partial(R)   // fail - unable to dereference T
```
Note: TypeBox doesn't track internal `$id` references (and is largely stateless). This means that it cannot auto dereference schematics on it's own (which is required for all utility types). While there are ways to handle dereferencing for `TRef` externally (which is a topic unto itself), the `TThis` type is somewhat more challenging as there is no schema to dereference (as the schema is still being constructed at the time you call `Type.Partial(This)`. 

### Workaround

The following is a workaround for the type you posted which moves the interior partial type into it's own type `InnerNode` and applies the `Partial` directly to a non-referenced object type. Take note of the generated schema.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAku3YYoAOQgATDHAC8KYQDoAShhIBXKGwBuGABTIAFsBZGAfCcymACgSwwARcLmYA8iIAVlYwTgiycHDsBCAYAFy+GKb4UBwA5k4AlFhJKRjiMFluHmUy5MVNsvKKynA6+kbZplGxJPFIyXD8-HAKSvCdBsaJMsmp6TVmeYUlOMObo8NCmFkMEDFxDPULldVwahraetib98PbyWC0mMEYLFlzjQ+-f79PYaLTKIcr-cH-QGbXYghjKfLsArSeYQ1EPKEUU5o7HJDEaKpfME41EY5IAEmAun2yAADCcicTwaS4DD9od+jB6SjGRDmS8IG9iB9CdyeZCxn9gSKxbyJf9WYx4YVkTKmXKHuQsaqAer7viLnNtX9mZsyVAMFRqXSRmMADwAWkdjpQ7hYDKNuN1m3I7o9zJ9oo9nvuAaD90Bmt9RsBDHNAEdrHwMLoGFkANpR7UYhjArlhra6nPnFX54PJAC6mdV2wDshhKG6+CIpFtMIgVA6ty8QA)

```typescript
const InnerNode = Type.Recursive(This => Type.Partial(Type.Object({
  name: Type.String(),
  next: This,
})))

const Node = Type.Object({    // const Node = {
  name: Type.String(),        //   type: 'object',
  next: InnerNode,            //   properties: {
})                            //     name: {
                              //       type: 'string'
                              //     },
                              //     next: {
                              //       $id: 'T0',
                              //       type: 'object',
                              //       properties: {
                              //         name: {
                              //           type: 'string'
                              //         },
                              //         next: {
                              //           $ref: 'T0' // <----- This
                              //         }
                              //       }
                              //     }
                              //   },
                              //   'required': [
                              //     'name',
                              //     'next'
                              //   ]
                              // }

type T = Static<typeof Node>
```
I am interested in providing some form of auto dereference support for utility types in future, however previous attempts to implement haven't been very successful (and have required considerable state tracking internal to TypeBox). As a result, TB currently keeps type deref an external implementation concern, and this will likely need to be the case for the foreseeable future.

I hope this brings a little bit of insight into this aspect of the library. Will close off this issue for now as resolution to internal dereferencing is currently non-actionable, but may investigate again once other parts of the library have finalized (closer to a 1.0 release)

All the best!
S
