### ISSUE TITLE
Causing issues with latest Ajv

### ISSUE THREAD

**Issue by rhlsthrm** [sinclairzx81/typebox#52]
The new version of Ajv (v7) enables strict mode by default. This seems to break validation using typebox with these errors:

```
Error: strict mode: unknown keyword: "kind"
4128
      at Object.checkStrictMode (/root/node_modules/ajv/lib/compile/validate/index.ts:197:28)
4129
      at Object.checkUnknownRules (/root/node_modules/ajv/lib/compile/util.ts:27:22)
4130
      at checkKeywords (/root/node_modules/ajv/lib/compile/validate/index.ts:129:3)
4131
      at Object.validateFunctionCode (/root/node_modules/ajv/lib/compile/validate/index.ts:15:5)
4132
      at Ajv.compileSchema (/root/node_modules/ajv/lib/compile/index.ts:151:5)
4133
      at Ajv._compileSchemaEnv (/root/node_modules/ajv/lib/core.ts:659:24)
4134
      at Ajv.compile (/root/node_modules/ajv/lib/core.ts:323:34)
```

Is there some keyword being added to the schema for certain types under the hood?

**Comment by sinclairzx81** [comment]
@rhlsthrm Hi. TypeBox the adds `kind` and `modifier` properties to schema objects to assist with type inference. Previously, Ajv would accept unknown properties on the underlying schema, but this has since changed in Ajv 7 where they now default to `strict` and disallow unknown properties. 

Unfortunately, there is no way to remove the `kind` and `modifer` properties on TypeBox schemas as they are central to the conditional mapping TypeBox does. You can read a bit more about the issue [here](https://github.com/sinclairzx81/typebox/issues/51). The following is the current recommended options for enabling TypeBox with Ajv.

### Option A) Configure Ajv

A full example is located [here](https://github.com/sinclairzx81/typebox#Validation). But the minimum amount of work required is adding the following lines.
```typescript
ajv.addKeyword('kind')
ajv.addKeyword('modifier')
```

### Option B)  Type.Strict()

There exists the function on TypeBox called `Type.Strict()` that will omit the `kind` and `modifier` properties from the underlying schema. Information on this function can be found [here](https://github.com/sinclairzx81/typebox#Strict). This function was added in response to Ajv 7's decision to disallow unknown properties by default and to give users some options. Example of anticipated usage is as follows.

```typescript
const T = Type.Object({
   name: Type.String(),
})
const validate = ajv.compile(Type.Strict(T))
```

Hope this helps.

**Comment by rhlsthrm** [comment]
Thank you @sinclairzx81 this is helpful!
