### ISSUE TITLE
Separate Enum and Union

### ISSUE THREAD

**Issue by fvckDesa** [sinclairzx81/typebox#537]
My propose is to separate enum from union

TEnum have a different kind from "Union" like "Enum" and it's json schema is like this:
```json
{ 
  "type": ["number", "string"],
  "enum": [ "a", "b", "c" ]
}
```

**Comment by sinclairzx81** [comment]
@fvckDesa Hi,

Unfortunately TypeBox requires that all union-like data structures be expressed via `anyOf` representation. The reason for this is due to the sophistication involved in supporting multiple forms of union during type inference and type composition (where TB would need to accommodate a secondary inference paths specifically for the `enum` representation, which is fairly untenable given the complexity involved in appropriately handling union). This may change in future, but isn't planned for in the near to mid term. 

You can however implement `enum` representations using custom types. The following example implements `enum` for `string[]` and `number[]`, but you could extend this implementation to support TS `enum` also.

https://github.com/sinclairzx81/typebox/blob/master/examples/prototypes/union-enum.ts

```typescript
import { TypeRegistry, Kind, TSchema, SchemaOptions } from '@sinclair/typebox'

// -------------------------------------------------------------------------------------
// TUnionEnum
// -------------------------------------------------------------------------------------
export interface TUnionEnum<T extends (string | number)[]> extends TSchema {
  [Kind]: 'UnionEnum'
  static: T[number]
  enum: T
}
// -------------------------------------------------------------------------------------
// UnionEnum
// -------------------------------------------------------------------------------------
/** `[Experimental]` Creates a Union type with a `enum` schema representation  */
export function UnionEnum<T extends (string | number)[]>(values: [...T], options: SchemaOptions = {}) {
  function UnionEnumCheck(schema: TUnionEnum<(string | number)[]>, value: unknown) {
    return (typeof value === 'string' || typeof value === 'number') && schema.enum.includes(value)
  }
  if (!TypeRegistry.Has('UnionEnum')) TypeRegistry.Set('UnionEnum', UnionEnumCheck)
  return { ...options, [Kind]: 'UnionEnum', enum: values } as TUnionEnum<T>
}
```
These examples are offered for developers to use and extend, and are the recommended way to express structures above Json Schema subset used by TypeBox.

Hope this helps!
S

**Comment by sinclairzx81** [comment]
Will close off this issue for now, but have added the `suggestion` tag to review at a later point in time.

All the best!
S
