### ISSUE TITLE
add `Type.Json`

### ISSUE THREAD

**Issue by ivanhofer** [sinclairzx81/typebox#547]
I would like to have built in schema for a `Json` structure.

The `TypeScript` type would look like this:

```ts
type JsonArray = Json[]

type JsonObject = {
	[K in string]?: Json
}

type JsonPrimitive = boolean | null | number | string

export type Json = JsonArray | JsonObject | JsonPrimitive
```

We have tried to use `Type.Recursive` to build this using `typebox` but we get the error: `Type instantiation is excessively deep and possibly infinite.`

We currently have a workaround that makes nested objects possible for our current data structure, but we will probably hit a limitation soon:

```ts
const JSONValue1 = Type.Union([Type.String(), Type.Number(), Type.Boolean(), Type.Null()])
const JSONArray1 = Type.Array(JSONValue1)
const JSONObject1 = Type.Record(Type.String(), Type.Union([JSONArray1, JSONValue1]))

const JSONValue2 = Type.Union([JSONValue1, JSONObject1])
const JSONArray2 = Type.Array(JSONValue2)
const JSONObject2 = Type.Record(Type.String(), Type.Union([JSONValue2, JSONArray2]))

const JSONValue3 = Type.Union([JSONValue2, JSONObject2])
const JSONArray3 = Type.Array(JSONValue3)
const JSONObject3 = Type.Record(Type.String(), Type.Union([JSONValue3, JSONArray3]))

const JSONValue4 = Type.Union([JSONValue3, JSONObject3])
const JSONArray4 = Type.Array(JSONValue4)
const JSONObject4 = Type.Record(Type.String(), Type.Union([JSONValue4, JSONArray4]))

export type JSONObject = Static<typeof JSONObject>
export const JSONObject = JSONObject4

export type JSON = Static<typeof JSON>
export const JSON = Type.Union([JSONObject4, JSONValue4, JSONArray4])
```

So my question: is it possible to have a `Json` schema in `typebox`?

**Comment by sinclairzx81** [comment]
@ivanhofer Hi,

It is possible to express the schematics for this type, however TypeBox will struggle with type inference as the union variants contain self referential `this`. The following would be one way to express the schematics for this type.

```typescript
const JsonRecord = <T extends TSchema>(schema: T) => Type.Record(Type.String(), schema)
const JsonArray = <T extends TSchema>(schema: T) => Type.Array(schema)
const JsonBoolean = Type.Boolean()
const JsonNull = Type.Null()
const JsonNumber = Type.Number()
const JsonString = Type.String()
const Json = Type.Recursive(This => Type.Union([
  JsonRecord(This), // problem: self referential this
  JsonArray(This),  // problem: self referential this
  JsonBoolean,
  JsonNull,
  JsonNumber,
  JsonString
]), { $id: 'Json' })
```
### Problem

The problem comes down to the self referential `this` contained within the Union for the Array and Record types. Removing the Union and only showing the Array, the problem becomes a bit more clear.
```typescript
const T = Type.Recursive(This => Type.Array(This)) 

type T = T[] // infinite self referential this
```
Using Static to infer the T type would result in a "Type instantiation is excessively deep and possibly infinite". So while the schematic is representable, the inferred type is not.

### Solution

As Json data is essentially an `any` or `unknown` type. You can use either Type.Any() or Type.Unknown() to express arbitrary Json data (on the assumption the data was obtained via JSON.parse()). But if you want to express the type using those Json TS types, you can express the type in the following way.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZQzHABSLCOwCCUKAVRwAvMtXsA2gF15ww2oBKGEtAAm+xHGMBrDKgBccFjCgcAOamPipqFHD8-HAkfCQArjxQcFAYVBipnBhwAO4AFhjscPFs7IFwtvZQDgA8fgFlOGHsAHwWis34DeUG9UHt2c0AcvEgIhnO7KPjUANW7ABCEBBcGARFBmIra+xzw4lckweyGOKQsHAKg0bOsnBwAD7zmtq6d4-zlY7vT53+-TJ7r8jCMxhkfvMltt1hD9lwuLJZPZ2H55s40JgAHQAVRRBHSNWaLQAFBiMJj1OxUMSAJQ0xEyK4oZz4IikGpXCBUeYtSLRJnIZx9MofKZg5JPLardYfZovHSyoxfaqig5AA)

```typescript
import { Type, Static } from '@sinclair/typebox'

type JsonArray = Json[]
type JsonRecord = { [key: string]: Json } // circular reference when using Record<string, Json>
type JsonString = string
type JsonNumber = number
type JsonBoolean = boolean
type JsonNull = null
export type Json = 
  | JsonArray 
  | JsonRecord
  | JsonString
  | JsonNumber
  | JsonBoolean
  | JsonNull

const Json = Type.Unsafe<Json>(Type.Any())

type T = Static<typeof Json> // type T = string | number | boolean | JsonArray | JsonRecord | null
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@ivanhofer Heya,

Just going over the original issue request, it's very unlikely TypeBox will get a `Type.Json()` type as this type is already facilitated by `Type.Any()` and `Type.Unknown()`, both of which can be used directly to express any representable Json data structure, or wrapped in a `Type.Unsafe<T>(Type.Any())`  (as above) to allow that data structure to be expressed as specific TS types (without instantiation issues) if that's something you need to do.

Will close off this issue for now, but if you have any follow up questions, feel free to reply on this thread. 
All the best!
S
