### ISSUE TITLE
Creating single member Enum models produces `never` type in typescript after 0.31.9

### ISSUE THREAD

**Issue by steevsachs** [sinclairzx81/typebox#574]
After the 0.31.9 release, creating an Enum model using a single-item enum emits type `never`

This is possibly related to this change https://github.com/sinclairzx81/typebox/commit/2b83dc6ad26bd20e3f0ff3991b8ac487bbfc61dc#diff-48d9d15b6ff26128831ab393f0c39d25718e8105791d624de0383781ee231e21R345

Repro: https://codesandbox.io/s/typebox-0-31-10-issue-repro-77t32k

Can you please advise if this is expected?

**Comment by steevsachs** [comment]
(Updated original issue report; I realized in playing with my repro that I had it misdiagnosed originally)

**Comment by sinclairzx81** [comment]
@steevsachs Hi, thanks for reporting. Yes, this looks like a bug. 

Have published an updated version on 0.31.11 that should resolve this issue, however there is an unresolved outstanding issue that relates specifically to empty enums which cannot be resolved at this time. 

### Issue

The issue is specific to mapping empty `enum T {}` to `TNever` as TypeScript will infer `T[keyof T]` as `string` for the empty enum case, resulting in `enum T {}` giving inference as `TLiteral<string>` (despite correctly runtime mapping as `TNever`) 

The following is the inference behavior for Enum as of Revision 0.31.11.

### Empty Enum (Bug)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgDLAwZQEA2cAvnAGZQQhwDkAAgM7AAdiXoFgUAPQx0GAEYQAHtwCwAKHUYhAVy4BRHSACCiJupIQh-eEYBcKKjTr0APNajCA5gD44AXhRZADoDXQAKUOMASjg4SUk4CysbfxQAOQwAN1o4AFo4IjgobSFiEAx1GUw4EwD8IlIXKowIVhrfWM6u7p74uGaa1PcvWPySqAx+CHpsgBMUXDhgfn5tDCA)

```typescript
import { Type, Static, TLiteral } from '@sinclair/typebox'

enum EnumA {}
const A: TLiteral<string> = Type.Enum(EnumA)    // const A = TNever - at runtime
type A = Static<typeof A>                       // type A = string  - unresolved TS issue
```

### Empty Object (OK)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsgHIYBuGUcAvnAGZQQhwDkAAgM7AA7EgBsCwKAHoY6DACMIAD04BYAFBqSEAb3gBBAFwoqtegF4UMgHQBRAQFcQACgQMAlHAkS4m7XrjnKGjo1aUw4XX88QmISAB5QjAhmcIA+OHSMjy8E8MiBIKggA)

```typescript
import { Type, Static, TNever } from '@sinclair/typebox'

const A: TNever = Type.Enum({})                 // const A = TNever
type A = Static<typeof A>                       // type A = never
```
There's not much I can do about the empty enum mapping bug at this time, but will investigate a few approaches to see if it's possible to get both object pattern and enum pattern lined up better in later revisions.

Let me know if this 0.31.11 works ok for you.
Cheers
S

**Comment by sinclairzx81** [comment]
@steevsachs Hiya

Just published 0.31.12 which should also resolve the above empty enum issue. Will leave this issue open for a day to give you some time to test (this enum update has been challenging, so hoping the 0.31.12 update resolves any remaining issues).

Let me know how you go.
All the best
S

**Comment by steevsachs** [comment]
Thank you so much for the prompt and thorough responses, I really appreciate it! I can confirm this resolves the issues we were encountering.

**Comment by webberwang** [comment]
I'm getting `Type instantiation is excessively deep and possibly infinite` when the enum contains past certain number of properties. `Type.Enum(SomeEnum)`. Will try to reproduce

**Comment by sinclairzx81** [comment]
@webberwang Hi, thanks for reporting.

Yeah, this might be a difficult one to resolve. I am able to reproduce the issue this side (with the problem related to enum union expansion implemented on 0.31.9), but to solve, it may require TB to revert to the previous implementation (pre `0.31.9`) but I'll do some digging.

The `0.31.9` update was to enable enums to compose as unions, unfortunately, it looks as though scalability of the type may render these updates infeasible. So will likely need to revert. 

Would recommend keeping with 0.31.8 for the time being.

**Comment by sinclairzx81** [comment]
@dippi Heya, just a heads up on the enum changes for 0.31.9. I may need to revert these updates back to the previous `TEnum` implementation (as the implementations has hit some scalability issues). Unfortunately this would mean enums would no longer be able to compose as Record keys.

Will be spending some time reverting changes there, but if you wanted to take a quick look against 0.31.13 (current) to see if there's a way to optimize the inference, that would be good (as I'm very keen to keep the implementation if possible). However given the opaque nature of TS enums, I'm thinking typical strategies for optimization may not work in this instance (relates specifically to enum union expansion)

**Comment by sinclairzx81** [comment]
@webberwang @steevsachs Hiya

Hey, have reverted these `enum` updates back to 0.31.8 and deferred the implementation of 0.31.9 until I've had a chance to review optimizing for large enums. Updated version is 0.31.14. 

```
$ npm install @sinclair/typebox@latest
```

@webberwang Are you able to quickly test that 0.31.14 is working ok for your large enums?

@steevsachs Sorry about the back and forth on this, but it would be good to test your implementation is ok with these reverted changes also.

Apologies for inconvenience.

**Comment by steevsachs** [comment]
Apologies for the delay, I can confirm 0.31.14 is passing our checks.  

Thanks for all your work on this, and for doing due diligence as you go along!

**Comment by sinclairzx81** [comment]
@steevsachs Awesome thank you! :)

**Comment by sinclairzx81** [comment]
@webberwang Hiya,

Hey might close off this issue. The Enum implementation has been reverted to 0.31.8 so things should be working as before, but if you spot anything out of place, feel free to reply on this thread or just submit a new issue.

All the best
S

**Comment by webberwang** [comment]
@sinclairzx81 thanks for taking a look! can confirm `0.31.14` is working for enum with large number of members
