### ISSUE TITLE
Type.Enum documentability 

### ISSUE THREAD

**Issue by npdev453** [sinclairzx81/typebox#618]
Currently working on totally documentation module in pair with TypeBox and Nominal Types and stuck with a new problem:

Can't find properly way (DRY) how to document each field of Enum with title, description
I think about to store Enum as union but seems like unclear here
```ts
Type.Union([ 
   Type.Literal('PHOTON', {description: "particle"} ),
   Type.Literal('NEUTRON', {description: "particle"} )
])   
```

Repro:
```ts
enum ALPHA = {
    PHOTON = 'PHOTON',
    NEUTRON = 'NEUTRON' 
}

TypeBox.Enum(ALPHA)
/*
 export const ALPHA = {
  anyOf: [
    {
      const: 'PHOTON',
      type: 'string'
    },
    {
      const: 'NEUTRON',
      type: 'string'
    }
  ],
  $id: 'ALPHA'
}
*/
```

```ts
// For ex: 
const documentation = `
       ${input.anyOf.map( field => ` ${field.const} // ${field.description} ` ).join('\n')
`
```

**Comment by sinclairzx81** [comment]
@npdev453 Hi,

Unfortunately, there's no way to add additional metadata for `Type.Enum` values. This is because TypeScript has no way to encode extra data for `enum` that's available at runtime.

Note that both Type.Enum() and Type.Union([Literal]) produce the same schematic, but the difference is, Type.Union([Literal]) will allow you specify metadata (`description`) on each value (by assigning it to the literal (as you are)). If this is something you need (and you have control over the schema creation) I'd recommend the Type.Union([Literal]) approach in pretty much all cases.

```typescript
const T = Type.Union([
  Type.Literal('PHOTON', { description: 'Particle' }),
  Type.Literal('NEUTRON', { description: 'Particle' })
])

console.log(T)
// {
//   anyOf: [
//     {
//       description: 'Particle',
//       const: 'PHOTON',
//       type: 'string',
//       [Symbol(TypeBox.Kind)]: 'Literal'
//     },
//     {
//       description: 'Particle',
//       const: 'NEUTRON',
//       type: 'string',
//       [Symbol(TypeBox.Kind)]: 'Literal'
//     }
//   ],
//   [Symbol(TypeBox.Kind)]: 'Union'
// }
```
If handling both Type.Enum() and Type.Union([Literal]), just be sure to treat the `description` field as optional when producing documentation views.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@npdev453 Hiya,

Might close off this issue as there isn't anything actionable to enable metadata on `enum`. I would recommend using the Union([Literal]) representation if you need to encode metadata for each variant as this generally provides the most flexibility.

All the best
S
