### ISSUE TITLE
Date type prblem

### ISSUE THREAD

**Issue by freeseamew** [sinclairzx81/typebox#620]
Currently, typebox is being used in a project using fastify and prisma.

When defining fastify’s json schema using typebox

In the case of datet type defined as Type.Date(), the following error occurs saying that the type is incorrect.

Below is the error content.

```
{
   "level":50,
   "time":1696733542463,
   "pid":63349,
   "hostname":"MacBook-Pro",
   "err":{
      "type":"FastifyError",
      "message":"Failed building the serialization schema for POST: /articles, due to error schema is invalid: data/properties/createdAt/type must be equal to one of the allowed values",
      "stack":"FastifyError: Failed building the serialization schema for POST: /articles, due to error schema is invalid: data/properties/createdAt/type must be equal to one of the allowed values\n    at Boot.<anonymous> (/Users/gimgeun-yeong/Works/Project/NodeJs/MY_WORKS/slog-fastify-prisma-typescript/node_modules/fastify/lib/route.js:384:21)\n    at Object.onceWrapper (node:events:627:28)\n    at Boot.emit (node:events:525:35)\n    at Boot.emit (node:domain:489:12)\n    at /Users/gimgeun-yeong/Works/Project/NodeJs/MY_WORKS/slog-fastify-prisma-typescript/node_modules/avvio/boot.js:160:12\n    at /Users/gimgeun-yeong/Works/Project/NodeJs/MY_WORKS/slog-fastify-prisma-typescript/node_modules/avvio/plugin.js:275:7\n    at done (/Users/gimgeun-yeong/Works/Project/NodeJs/MY_WORKS/slog-fastify-prisma-typescript/node_modules/avvio/plugin.js:200:5)\n    at check (/Users/gimgeun-yeong/Works/Project/NodeJs/MY_WORKS/slog-fastify-prisma-typescript/node_modules/avvio/plugin.js:224:9)\n    at node:internal/process/task_queues:140:7\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)",
      "code":"FST_ERR_SCH_SERIALIZATION_BUILD",
      "name":"FastifyError",
      "statusCode":500
   },
   "msg":"Failed building the serialization schema for POST: /articles, due to error schema is invalid: data/properties/createdAt/type must be equal to one of the allowed values"
}
```

For reference, this problem did not exist in several versions below.

Please check this part.

**Comment by sinclairzx81** [comment]
@freeseamew Hi,

When using Fastify, you should use

```typescript
const T = Type.String({ format: 'datetime' }) // ✔ - use this 

const T = Type.Date()                         // ✘ - not this
```

The reason is because Type.Date() represents an actual JavaScript `Date` value, and these values cannot be serialized to Json. The Date type is actually documented under extended JavaScript types.

https://github.com/sinclairzx81/typebox#javascript-types

> TypeBox provides an extended type set that can be used to create schematics for common JavaScript constructs. These types can not be used with any standard Json Schema validator; but can be used to frame schematics for interfaces that may receive Json validated data. JavaScript types are prefixed with the [JavaScript] jsdoc comment for convenience. The following table lists the supported types.

Note: The TypeBox TypeCompiler and Value modules can validate this type, but the schema representation of the type is unknown to Json Schema and Ajv (which is why you see the `FST_ERR_SCH_SERIALIZATION_BUILD` error)

```typescript
const T = Type.Date() // { type: 'Date', [Symbol(TypeBox.Kind)]: 'Date' } - not valid Json Schema
```

### Recommendation

If working with Dates in Fastify, because you can only transmit a Date as either a Number (timestamp) or String (iso8601), you can use TypeBox Transforms to convert the encoded date into JavaScript date objects. This means your schema remains compliant with the Json Schema specification while still getting an intended JavaScript Date object (however you will need to Decode the value manually)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChQkWIjgA1AlwCuGCtVr1mbTjz6DhY8fwBuazdLnho8AGIEWxKqh11GVF29S3ZEgh2VzgAESIMZFAtAF4UYQA6ZCgCEKpoEAAKNExE-CgOAHMspAyoECIALkYAE0jiEAwGCgBKVtk4OESwjCDajCyrDTiAPjh2DAB3cMih6wx2zu6AUU4IAfmRuFjx4c1EmAgASVwAeQLirKWZQODQgCENj3jcjESzkQArPphS5a6JCgGEitRqERgURiWABcHUYHqkLBs0h0SasnIHVuMmcrmA7muiUgrgAPEhlk9aqgavgiKQSUJMBAqHBKahRhjRlkGPwGDgEMsWCQABYYSo1AUyLpdMRUmpsmFS6XAliQEIYCWwroAJgADLr5c9YeRliaZOQcFlgQBHHAq1o7caSwH3eCy1AARh2cBtiXd0oDgaDAf4-Dg7q98SQQJBSJqrkK7CKOHhiIwyITxQoyyCITdz213tUIx6fQ2gwVPow1r9zwdcFD4YL3ujwNB4MiKYR7ZRWjNmNkg+xQA)

```typescript
import { Type, Static } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'
import Fastify from 'fastify'

// Transforms a ISO8601 encoded Date String into a JavaScript Date object
const DateTime = Type.Transform(Type.String({ format: 'datetime' }))
  .Decode(value => new Date(value))
  .Encode(value => value.toISOString())

const Body = Type.Object({
    created: DateTime,
    updated: DateTime
})

Fastify().post<{ 
  Body: Static<typeof Body>
}>('/', {
  schema: {
    body: Body,
    response: {
      200: Body
    }
  }
}, (req, res) => {
  const body1 = req.body                      // body1 = { created: string, updated: string }
  const body2 = Value.Decode(Body, req.body)  // body2 = { created: Date, updated: Date }
})

```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@freeseamew Hi,

Will close off this issue as there is nothing to action in TypeBox. But consider the example above as this is generally the direction TypeBox needs to go in order to handle non-standard Json Schema types. Also, have a quick read over the 0.30.0 release notes , as these document some of the schema changes around non-standard types (as this was documented as a breaking change)

https://github.com/sinclairzx81/typebox/blob/master/changelog/0.30.0.md#Extended-Type-Representation-Change

All the best!
S

**Comment by freeseamew** [comment]
The answer was very helpful. I think the problem will be solved if you modify the code based on your response.

However, in the case of the previous version of the type box, there was no problem when I set Date and string as a union as follows to process the Date type received from prisma, but I was wondering why this method was an error in the current version, so I made an inquiry. I did.

```
createdAt: Type.Union([Type.Date(), Type.String() ])
```

Thank you again for your reply.
