### ISSUE TITLE
Pick from Intersect 

### ISSUE THREAD

**Issue by simon-tannai** [sinclairzx81/typebox#623]
Hello 👋

I have an issue when I'm trying to Pick from an Intersect schema. 

First, I define a schema:
```typescript
export const defaultDbSchema = Type.Object({
  ID: Type.String(),
  createdAt: Type.Number(),
  updatedAt: Type.Number(),
});
```

Then, I'm creating another schema by using Intersect:
```typescript
export const userDbSchema = Type.Intersect([
  defaultDbSchema,
  Type.Object({
    email: Type.String(),
    firstName: Type.Optional(Type.String({ minLength: 1, maxLength: 150 })),
    lastName: Type.Optional(Type.String({ minLength: 1, maxLength: 150 })),
  }),
]);
```

Finaly, I'm creating a simple schema by picking the `email` from `userDbSchema` and creating a TypeScript's type:
```typescript
export const userRegistrationPayloadSchema = Type.Pick(userDbSchema, ['email']);
export type UserRegistrationPayloadType = Static<typeof userRegistrationPayloadSchema>;
```

The point is `userRegistrationPayloadSchema` looks like that:
```JSON
{
  "type": "object",
  "allOf": [
    {
      "type": "object",
      "properties": {}
    },
    {
      "type": "object",
      "properties": {
        "email": {
          "format": "email",
          "type": "string"
        }
      },
      "required": [
        "email"
      ]
    }
  ]
}
```

The first entry of `allOf` array is and empty object. 
The result is I get a TypeScript error when I'm using the  `UserRegistrationPayloadType` type:
```text
TS2345: Argument of type  unknown  is not assignable to parameter of type  {} & { email: string; } 
Property  email  is missing in type  {}  but required in type  { email: string; }
```

How can I remove this empty object into the `allOf` array ?

**Comment by sinclairzx81** [comment]
@simon-tannai Hi,

You can try using Type.Composite() instead of Type.Intersect(). This type is similar to Intersect, except it merges the intersected objects into a singular object type. Because the object is merged, using Pick will select from the merged object (not the intersected object on allOf)

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZGcZFhwSEdi3gATDFQIBXLjAAiI3CQAWGEATgBeFMIB0AeREArDCRgAKBLLhwAJJGAFwOmI74UBwA5t4AlFj+KlAYRBiaAIIwYWgRAHJ6ICIYUAlJMgF6YJrpWTnhGI6FxaXlsuTx8orQ8Krq8HospSZmltZ2jY4AwnSQbDAY3gDacPz8KuYE7DEYcJapcNuaKmosEFxNXBAxcDDmwCxwLBZWBMnaugbGpq-WFQE8k1XB4vL5kgE3sAuLknFFYu1KgFqHwNPkCCAMLCIs4wMQ1AQuN4gZEYNEdr44CAOAAZDA7e5hACMOGs4jpDPMzIArAAGCjxRIQuA8NEYrFTXH49iE4lwskIpDU9gcmKMuAsqkEdn0tVcjV8gVCpGdWQAXS6chkCiUfTOg2GUAAShgYo8yURgGoAAoEVDXAiaMZvSYk72kADW3iGI1+4wIOGWDChXAYFtk3Vtd2EcAAqo6XW6NFBPT6-QHNEDJvhPSQADxCTAQKhwGPO13ukvS33+iCB4PWAB8AG4MzJ1qcBq2Cx3i6X2D2KwObPY-OONgEAESNjCbsKbiDuTwwTcVCdbsC0TCwYAYFh7xCyc-Izcph9r5-IuDb4QPzfF2JNyfDdkXIYDQLPEDN1SABHPQ+AyB9lnAr9X2saEgPXZEzXA8ggA)

```typescript
export const defaultDbSchema = Type.Object({
  ID: Type.String(),
  createdAt: Type.Number(),
  updatedAt: Type.Number(),
})
export const userDbSchema = Type.Composite([ // change here and console.log this schema
  defaultDbSchema,
  Type.Object({
    email: Type.String(),
    firstName: Type.Optional(Type.String({ minLength: 1, maxLength: 150 })),
    lastName: Type.Optional(Type.String({ minLength: 1, maxLength: 150 })),
  })
])

export const userRegistrationPayloadSchema = Type.Pick(userDbSchema, ['email'])

export type UserRegistrationPayloadType = Static<typeof userRegistrationPayloadSchema>;

// const userRegistrationPayloadSchema = {
//   "type": "object",
//   "properties": {
//     "email": {
//       "type": "string"
//     }
//   },
//   "required": [
//     "email"
//   ]
// }
```
If you need to retain the intersection (`allOf`), you can also do this.

```typescript
export const userDbSchema = Type.Intersect([ // retain Intersect for allOf representation
  defaultDbSchema,
  Type.Object({
    email: Type.String(),
    firstName: Type.Optional(Type.String({ minLength: 1, maxLength: 150 })),
    lastName: Type.Optional(Type.String({ minLength: 1, maxLength: 150 })),
  })
])

// First combine intersected types via Composite then Pick
export const userRegistrationPayloadSchema = Type.Pick(Type.Composite(userDbSchema.allOf), ['email'])

export type UserRegistrationPayloadType = Static<typeof userRegistrationPayloadSchema>;
```
I think there might be case here to update Pick and Omit to ensure they always return an object type. I'll make a note of this for the next round of updates, but for now this should provide the functionality you need.

Hope this helps
S

**Comment by simon-tannai** [comment]
That's perfect, thank you @sinclairzx81 ! 🙏
