### ISSUE TITLE
Type.Recursive causes "Type instantiation is excessively deep and possibly infinite."

### ISSUE THREAD

**Issue by arnmishra** [sinclairzx81/typebox#627]
I have the following type:

```
const TestType = Type.Object({
  field1: Type.Array(Type.String()),
  field2: Type.Optional(Type.Boolean(),
  field3: Type.Enum(EnumValue),
  recursiveField: Type.Recursive((Test) => Type.Array(Test)),
})
```

However, it gives the error "Type instantiation is excessively deep and possibly infinite."

What's interesting is that this doesn't given an error:

```
const TestType = Type.Recursive((Test) => Type.Array(Test))
```

I'm not sure what the practical difference is since both are possibly infinite. I need to do something like the first option in order to make my system work. Any suggestions on what the issue may be?

**Comment by sinclairzx81** [comment]
@arnmishra Hi,

The problem is that the `Type.Recursive((Test) => Type.Array(Test))` type produces an infinitely expansive array which evaluates to something like the following.

```typescript
const TestType = Type.Recursive((Test) => Type.Array(Test))

// evaluates as an infinitely expansive nested array.
type TestType = [[[[[[[[[[[...inf]]]]]]]]]], ...inf]
```

---

### Limitations

There isn't really a way to define a recursive array type using TB's default factory types, but you can create recursive object types (which would typically have access to a `this` context)

```typescript
enum EnumValue { A, B, C }

const T = Type.Recursive(This => Type.Object({
  field1: Type.Array(Type.String()),
  field2: Type.Optional(Type.Boolean()),
  field3: Type.Enum(EnumValue),
  recursiveField: Type.Array(This)
}))

```
Which is equivalent to the following TS interface
```typescript
enum EnumValue { A, B, C }
interface T {
  field1: string[]
  field2?: boolean
  field3: EnumValue
  recursiveField: this[]
}
```

---

### Workaround

If you need the type structured like the one in your example, you can implement this manually using TypeBox's Unsafe type.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZQzHABKcALzKA2gF04-fnBgALYCzgmDhjHCgYSAVyhsAblYUZZsjOzv0Aot5AANQIuOyskAEEcACEcAGEKDxkSCHYWeGQMdLRFdRyMADoAVTSCKgwAHiQ9OAxxMC5SYBguVDgAEwwqDitkXANhWThqYAwudoBGAC44dKgOAHNtIZGx9oAmAH4ZsQguDAJ2Fe61gGYZ-x9g0PcZYZt7R2AXADFR8ZmVYe+f4Zq7FhWB4OZyuYRwSw2WTkAB8AAokL8kciUTU6g0mi02p1uuwrAApFipPAkSwgAgDTArNwzBgQEQAK1sMAYWBWYFomFgoxYMwQK2GJ3G00QlIwtIIUCgBFQrLMMAwIF5oppjDmiwYFAobLu3yFGz5Ytpu32h015B1P3151Fh1QAHkqDMNEgUmkYLSIuacK7UuladFvaK3f7GHFzToLQLrLYQc8MG81nzo8MACTAdq0pSslNGxiS6Wyy2-ZqK5VIVM2J2MbOJXXDcgrKO6mwARzsfAwmbgGmjDH1EzlfetQ-rjH1ABZpLqtNCAJRJNwoLIwfJqPCEYgkCpuCBUZfZYQwoA)

```typescript
import { Type, Static } from '@sinclair/typebox'

type R = R[] // this is the recursive type

enum EnumValue { A, B, C }

const TestType = Type.Unsafe<{ // explicitly define TS type
  field1: string[]
  field2?: boolean
  field3: EnumValue
  recursiveField: R            // use recursive type here
}>({                           // explicitly define Json Schema type
  type: 'object',
  properties: {
    field1: { type: 'array', items: { type: 'string' } },
    field2: { type: 'boolean' },
    field3: { anyOf: [{ const: 'A' }, { const: 'B' }, { const: 'C' }] },
    recursiveField: {
      $id: 'R',
      type: 'array',
      items: { $ref: 'R' }
    }
  },
  required: [
    'field1', 
    'field3', 
    'field4'
  ]
})

type TestType = Static<typeof TestType>
```
Note, you will likely need to use a validator like Ajv to validate this type. Alternatively, you can try use the [TypeRegistry](https://github.com/sinclairzx81/typebox#typeregistry-type) to manually register and implement the check logic for this type.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@arnmishra Hiya,

Will close off this issue as TypeBox generally doesn't support recursive top level array types (only objects).

Side note though, there has actually been some consideration given to potentially renaming `Type.Recursive` to `Type.Interface` as the primary distinction between `type` and `interface` in TS is that `interface` provides access to a `this` context. There are still some things to consider around this, but the following would make it more clear the instances where recursive types are supported (drawing direct analogy to TS interfaces and access to `this`)

```typescript
interface Node {
  id: string
  nodes: this[] // accessible in interface definitions only
}

const Node = Type.Interface(This => Type.Object({ // TypeBox needs to pass in the This context.
  id: Type.String(),
  nodes: Type.Array(This)
})
```
Will close up this issue for now, but if you have any questions on any of the above, happy to answer them on this thread.
All the best!
S

**Comment by arnmishra** [comment]
Ahh ok, thanks for the clarification
