### ISSUE TITLE
Slash symbol in error path filed

### ISSUE THREAD

**Issue by dennation** [sinclairzx81/typebox#643]
```
const schema = Type.Object({
    "topLevel": Type.Object({
       "field": Type.Boolean()
    }),
    "topLevel/field": Type.String()
})

const errors = Value.Errors(schema, {})

for (const error of errors) {
    console.log(error)
}
```
![image](https://github.com/sinclairzx81/typebox/assets/44858312/1a04db06-a699-42b7-92eb-c682931dfe20)

Due to using slash in the path field, there is no way to identify the field based on the error. Any chance to get errors with a path as string array for ex? (it would be `["topLevel", "field"]` for the first one and `["topLevel/field"]` for the second)

**Comment by sinclairzx81** [comment]
@dennation Hi,

Have actually just pushed a update for this which should allow you to differentiate between keys. This was actually an oversight in the error path generation where it should have been generating escaped RFC6901 Json Pointer strings (you can read the specification https://datatracker.ietf.org/doc/html/rfc6901). The fix is published on TypeBox `0.31.19`

> Due to using slash in the path field, there is no way to identify the field based on the error. Any chance to get errors with a path as string array for ex? (it would be ["topLevel", "field"] for the first one and ["topLevel/field"] for the second)

I won't be able to add array based pathing here as the Json Pointer specification should be enough to differentiate the keys. TypeBox actually provides some utilities to read and write values via these pointers (called ValuePointer), You can use this to get at the values via pointer string.

### Example

```typescript
import { Value, ValuePointer } from '@sinclair/typebox/value'
import { Type } from '@sinclair/typebox'

const schema = Type.Object({
  "topLevel": Type.Object({
     "field": Type.Boolean()
  }),
  "topLevel/field": Type.String()
})

const value = {
  topLevel: { field: 1 },
  'topLevel/field': 2
}

const errors = Value.Errors(schema, value)

for (const error of errors) {
  console.log(error.path, '->', ValuePointer.Get(value, error.path))
}

// outputs:
// /topLevel/field -> 1
// /topLevel~1field -> 2
```
Note: Json Pointer will escape the `/` with `~1` (and also escapes `~` with `~0`). You can manually decode the path to it's original form with the following

```typescript
const decoded = '/root~1hello~0world'.replace(/~1/g, '/').replace(/~0/g, '~')

console.log(decoded) // -> /root/hello~world
```
Hope this helps
S
