### ISSUE TITLE
Fastify schema serialization fails for responses containing Type.Uint8Array() or Type.Undefined() from version >=0.30.0

### ISSUE THREAD

**Issue by rconjaerts** [sinclairzx81/typebox#648]
First of all, thank you for so quickly following up and fixing my previous issue (#646).

I found another issue. Fastify has trouble serializing my schema that was build with typebox. I'm not sure if this is a problem of typebox or fastify, but it occurred after upgrading typebox to a version >=0.30.0. Could still be an issue of fastify of course.

There were two problems with the serialization of the schema.

**First issue**
For an endpoint in my API I return a Uint8Array, and my response is created as follows:
`export const getGeneralLedgerBookingAttachmentByIdResponse = Type.Uint8Array();`

So nothing really special, but it appears that fastify isn't able to handle this anymore because I get the following error: `Failed building the serialization schema for GET: /entities/:entityId/general-ledgers/booking/:generalLedgerId/attachments/:attachmentId, due to error schema is invalid: data/type must be equal to one of the allowed values`.

**Second issue**
For another endpoint in my API I return something that also uses `Type.Undefined()` that suddenly throws an error.

```
export const entitiesRelationsResponse = Type.Object({
  matchedEntities: Type.Record(
    Type.String(),
    Type.Record(Type.String(), Type.Union([Type.String(), Type.Undefined()])),
  ),
});
```

With a similar error I'm getting: `Failed building the serialization schema for GET: /organisations/:orgId/entities/relations, due to error schema is invalid: data/properties/matchedEntities/patternProperties/^(.*)$/patternProperties/^(.*)$/anyOf/1/type must be equal to one of the allowed values.`

**Comment by sinclairzx81** [comment]
@rconjaerts Hiya,

This issue is likely to do with the use of Undefined(). This type is actually an extended [JavaScript Type](https://github.com/sinclairzx81/typebox#types-javascript) and isn't supported by the Json Schema specification; which in turn isn't supported by [Ajv](https://ajv.js.org/) (the validator for Fastify). Note that TypeBox does support an extended superset of Json Schema used specifically for expressing JavaScript (not Json) values, but when working strictly with Json Schema, you should avoid using the extended JavaScript type set.

You can differentiate between Json and JavaScript types by checking for a `[Json]` or `[JavaScript]` prefix on each types doc comment.

---

### Solution

You can try update the Record value to use Null(). This is supported by the specification and should be fine with Fastify.

```ts
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

export const entitiesRelationsResponse = Type.Object({
  matchedEntities: Type.Record(
    Type.String(),
    Type.Record(Type.String(), Type.Union([Type.String(), Type.Null()])), // Updated
  ),
});

Value.Check(entitiesRelationsResponse, {
  matchedEntities: {
    E1: { A: 'A', B: 'B', C: null }, // pass null for C
    E2: { A: 'A', B: 'B' }           // pass omit C (same as undefined)
  }
}) // true
```
Also note, there has been some changes in TypeBox in the recent versions to remove certain extended representations for Ajv (which would likely implicate Undefined()). The recommendation going forward is to only use types compatible with the specification (everything with the `[Json]` prefix) when using Ajv, and for extended types, manual configuration via Unsafe() types + `ajv.addKeyword()` is required.

You can read more about this change at the following URL

https://github.com/sinclairzx81/typebox/blob/master/changelog/0.30.0.md#Extended-Type-Representation-Change

Let me know if this helps
Cheers
S
