### ISSUE TITLE
Date in ajv

### ISSUE THREAD

**Issue by TheNoim** [sinclairzx81/typebox#653]
I currently try to use ajv and type-box together. 

However, it looks like there is some kind of case sensitivity mismatch for the validation of dates. It looks like ajv expects the type to be `date` but typebox uses `Date` as type. 

Here is a minimal example:

```typescript
import { Type }   from '@sinclair/typebox'
import addFormats from 'ajv-formats'
import Ajv        from 'ajv'

const ajv = addFormats(new Ajv({}), [
  'date-time',
  'time',
  'date',
  'email',
  'hostname',
  'ipv4',
  'ipv6',
  'uri',
  'uri-reference',
  'uuid',
  'uri-template',
  'json-pointer',
  'relative-json-pointer',
  'regex'
])

const validate = ajv.compile(Type.Object({
  date: Type.Date()
}))
```

This should work, right? I mean, it is basically the example from type-box's readme. But it fails with:

```
Error: schema is invalid: data/properties/date/type must be equal to one of the allowed values, data/properties/date/type must be array, data/properties/date/type must match a schema in anyOf
```

Maybe it is an unrelated issue and has nothing to do with `Date` vs `date`. But this is what I currently suspect to be the issue.

**Comment by sinclairzx81** [comment]
@TheNoim Hi,

TypeBox supports two kinds for types:

- [Json](https://github.com/sinclairzx81/typebox#types-json) serializable types (prefixed with the `[Json]` doc comment) 
- [JavaScript](https://github.com/sinclairzx81/typebox#javascript-types) native types (prefixed with the `[JavaScript]` doc comment). 

Unfortunately, the Type.Date type falls into the latter category and cannot be used with Ajv (or other Json Schema validator). The problem is that JavaScript Date objects are not directly serializable to Json, and because they cannot be defaultly serialized (and there is no specification for auto Date serialization), Json Schema validators can't reasonably check for them.

### Solution

Typically when dealing with Dates and Json, you will need to find someway to encode the Date into something representable in the Json format. There are are usually two options for this.

- number - representing a timestamp
- string - representing a iso8601 value.

In this regard, you wouldn't use Type.Date here, rather (and perhaps unintuitively) you would use Type.String and Type.Number.

```typescript
const T = Type.Number() // for a timestamp

const T = Type.String({ format: 'date-time' }) // for a is8601 string
```
Generally when representing types to be transmitted over the wire (for example in Json), you will only want use types that can be represented in the transmission format (Json in this case). If it's helpful, just check the jsdoc comment for `[Json]` for each type to know if you're using Json compatible types.

### Transforms

TypeBox has some options to automatically decode and encode from `encoded > Date` and `Date > encoded`. The use of the transform encoders is a bit of a complex thing (usually requiring some work to setup a validation pipeline in your application) but you can find some documentation on how to use it at the following link.

https://github.com/sinclairzx81/typebox#transform-types

Transforms help smooth over some of the issues relating to Date (and other structure) encodings in Json.

Hope this helps
S

**Comment by TheNoim** [comment]
This helped. Thank you!
