### ISSUE TITLE
Exported variable 'X' has or is using name 'Optional' from external module 'typebox' but cannot be named

### ISSUE THREAD

**Issue by thdk** [sinclairzx81/typebox#661]
The issue occurs with latest version: 0.31.23 (typescript version:  5.2.2)

However, it starts in 0.29.0 with the following similar error:

> Exported variable 'X' has or is using name 'Modifier' from external module ".../node_modules/@sinclair/typebox/typebox" but cannot be named.

From 0.30.0 the same code gives:

> Exported variable 'X' has or is using name 'Optional' from external module ".../node_modules/@sinclair/typebox/typebox" but cannot be named.

I was able to reduce the repro code to the following snippet using the latest typebox version:

```ts
export const createFoobar = (isString: boolean) =>
  Type.Composite([
    Type.Object({
      foo: Type.Optional(isString ? Type.String() : Type.Boolean()),
    }),
    Type.Object({
      bar: Type.Any(),
    }),
  ]);

```

**Workaround:**

```ts
export const createFoobar = (isString: boolean) =>
  Type.Composite([
    Type.Object({
     //  foo: Type.Optional(isString ? Type.String() : Type.Boolean()), 
      foo: isString ?  Type.Optional(Type.String()) : Type.Optional(Type.Boolean()),
    }),
    Type.Object({
      bar: Type.Any(),
    }),
  ]);
```

**Comment by sinclairzx81** [comment]
@thdk Hi,

Unfortunately, this is likely a no fix as the ternary argument passed to Type.Optional(...) is automatically interpreted to be a union of `TString | TBoolean` by the TypeScript type system. However TS unions are generally not understood by TypeBox to be a singular type it's able to reason about (not without exhaustive testing for each possible variant). For supported usage, the Type.Optional modifier should only take an exact TSchema argument (as per your workaround).

---

### Problem

The actual issue here relates to a combination of TypeBox's implementation of Type.Index (which Type.Composite uses internally to index and infer key properties) and TypeScript union/intersect normalization. 

```typescript
// This is the foo property
foo: Type.Optional(isString ? Type.String() : Type.Boolean())

// This is the non-normalized form of this property
foo: ( (TString | TBoolean) & [Optional]: "Optional" ); // TOptional<TString | TBoolean>

// This is the normalized form of this property (error)
foo: (TString & {
    [Optional]: "Optional";  // TOptional<TString>
}) | (TBoolean & {           // or
    [Optional]: "Optional";  // TOptional<TBoolean>
});
```
During a mapped distribution on Index, TypeScript will automatically normalize into the third form, which is causing the "'Optional' from external module" error. I don't fully understand why this would be a problem to TypeScript (as the type is actually known) but do assume it relates to the inverted duplication of the Optional symbol post normalization. This may be a good enquiry to ask on the TypeScript GitHub repository (this error doesn't seem quite right, but there may be a reason for it)

---

### Workaround

The code given for this issue looks to be a very good candidate for generic types. With these, you can prove to the compiler in advance exactly what the parameter is for Type.Optional.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUGUZTAB2A5jsgEIQQA2GAhkXAL5wBmUEIcA5AAIBnYgGMa9YFAD0MdBgBGEAB48AUCsmS4AYSgMYGdtQr0ocegLgkMRDIWFwZmOMIhEBBcTYAmDiHAzAMAAWtngExCRwAD4oVLQMRCoYipCwzq7uzrr0+gBi1HImcAC8cAA8yP6K+kReFsj4hKTRsdR0jAB8ABQCwiEg9ABcKACUJR0osgB0WlyQQvpdANoqcJOYUwDycgBWGMIwXQira4YQw2gbm2AwwK70ND19GAMjJ8wjWCeXGFu7+4djqdToUoBdpgBBIioLqfd5wgC6IwA3GoNHBdGAxMIMAJhsABI0IiViqUCABXDBJFLQeAuNzwCElLJ6DD5CCgro-KZE0iwt7qTSY7G4-GE8LNUmlNgPARU5KpOkZeAUZnCbJ5AomLnTOLtIj8lRAA)

```typescript
// Create fooBar as generic type constrained to either TString | TBoolean
export const createFoobar = <T extends TString | TBoolean>(schema: T) => Type.Composite([
  Type.Object({
    foo: Type.Optional(schema)
  }),
  Type.Object({
      bar: Type.Any(),
  }),
]);

// replaces: isString === true
export const A = createFoobar(Type.String())

// replaces: isString === false
export const B = createFoobar(Type.Boolean())
```

I might close off this issue as the generics example above is generally the way to go, noting TypeBox can't appropriately reason about TS unions (as per ternary expression). I may investigate better strategies for modifiers in future as this issue has popped up [before](https://github.com/sinclairzx81/typebox/issues/655), however updates to modifiers need to be based on implementation constraints (and TS unions of TSchema may not be feasible to support, will investigate at a later time)

Hope this helps
S

**Comment by thdk** [comment]
Thanks for the detailed answer. We have updated the code to use the workaround. As the code from my example here is just a very minimal reproduction of the issue and in reality our `createSomeSchema` is much more complex and would require drilling the generic types to other helper functions. I just wanted to report this ticket in case it went unnoticed. 

Your answer will certainly help us in the future when we stumble upon this again. Thanks a lot!
