### ISSUE TITLE
How to infer typeVars?

### ISSUE THREAD

**Issue by ExpandOcean** [sinclairzx81/typebox#667]
Hi, I am trying to  describe typeVars with Type.Ref in a simple generic type system.

```js
// a simple demo
const typeVar = Type.Object(
  {
    foo: Type.String(),
  },
  { $id: 'T' }
);

const requiredSchema = Type.Array(Type.Ref('T'));

const schema = Type.Array(
  Type.Object({
    foo: Type.String(),
    bar: Type.Number(),
  })
);

const valid = Type.Extends(
  schema,
  requiredSchema,
  Type.Literal(true),
  Type.Literal(false)
);
// Type.Literal(true)
```
In this demo, the inferred typeVar should be Type.Object({foo: Type.String(),bar: Type.Number()}).
Can you show me how to infer typeVars programmatically if an input schema satisfies the required schema?

Thanks!

**Comment by sinclairzx81** [comment]
@ExpandOcean Hi,

Unfortunately, Ref types are not directly supported with the utility types Extends, Extract, Exclude, Partial, Required, Pick, Omit and KeyOf. The reason is because TypeBox is currently stateless and does not internally track `$id` specifiers for types. Because TypeBox doesn't track the `$id`, it has no way to deference the `$ref` when applied to utility types (such as Extends), noting TypeBox needs the target schematic to correctly apply the utility.

---

### Workaround

The simple workaround is just to pass the JavaScript reference directly. 

```typescript
// a simple demo
const typeVar = Type.Object(
  {
    foo: Type.String(),
  },
  { $id: 'T' }
);

const requiredSchema = Type.Array(typeVar); // update: pass schema here.

const schema = Type.Array(
  Type.Object({
    foo: Type.String(),
    bar: Type.Number(),
  })
);

const valid = Type.Extends(
  schema,
  requiredSchema,
  Type.Literal(true),
  Type.Literal(false)
);
// Type.Literal(true)
```
---

### Reference Container

If you need interior dereferencing (as per your original example), it is possible to implement a Reference container that tracks the `$id` and can recursively dereference interior types. The implementation of such a container is moderately complex (so I've included the implementation in the expandable section below).

<details>
<summary>References Implementation</summary>

```typescript
import * as Types from '@sinclair/typebox'

export class References {
  private TArray(schema: Types.TArray) {
    return Types.Type.Array(this.Visit(schema.items), { ...schema })
  }
  private TAsyncIterator(schema: Types.TAsyncIterator) {
    return Types.Type.AsyncIterator(this.Visit(schema.items), { ...schema })
  }
  private TConstructor(schema: Types.TConstructor) {
    const parameters = schema.parameters.map(schema => this.Visit(schema))
    const returns = this.Visit(schema.returns)
    return Types.Type.Constructor(parameters, returns, { ...schema })
  }
  private TFunction(schema: Types.TFunction) {
    const parameters = schema.parameters.map(schema => this.Visit(schema))
    const returns = this.Visit(schema.returns)
    return Types.Type.Function(parameters, returns, { ...schema })
  }
  private TIntersect(schema: Types.TIntersect) {
    const allOf = schema.allOf.map(schema => this.Visit(schema))
    return Types.Type.Intersect(allOf, { ...schema })
  }
  private TIterator(schema: Types.TIterator) {
    return Types.Type.Iterator(this.Visit(schema.items), { ...schema })
  }
  private TNot(schema: Types.TNot) {
    return Type.Not(this.Visit(schema), { ...schema })
  }
  private TObject(schema: Types.TObject) {
    const properties = Object.keys(schema.properties).reduce((acc, key) => {
      return { ...acc, [key]: this.Visit(schema.properties[key]) }
    }, {} as Types.TProperties)
    return Types.Type.Object(properties, { ...schema })
  }
  private TPromise(schema: Types.TPromise) {
    return Types.Type.Promise(this.Visit(schema.item), { ...schema })
  }
  private TRef(schema: Types.TRef<any>) {
    if(!this.map.has(schema.$ref)) throw Error(`Cannot dereference schema with $id ${schema.$ref}`)
    return this.map.get(schema.$ref)!
  }
  private TTuple(schema: Types.TTuple<any[]>) {
    if(schema.items === undefined) return schema
    const items = schema.items.map(schema => this.Visit(schema))
    return Types.Type.Tuple(items, { ...schema })
  }
  private TUnion(schema: Types.TUnion) {
    const anyOf = schema.anyOf.map(schema => this.Visit(schema))
    return Types.Type.Union(anyOf, { ...schema })
  }
  private Visit(schema: Types.TSchema): TSchema {
    const _schema: any = schema
    switch (schema[Types.Kind]) {
      case 'Array':
        return this.TArray(_schema)
      case 'AsyncIterator':
        return this.TAsyncIterator(_schema)
      case 'Constructor':
        return this.TConstructor(_schema)
      case 'Function':
        return this.TFunction(_schema)
      case 'Intersect':
        return this.TIntersect(_schema)
      case 'Iterator':
        return this.TIterator(_schema)
      case 'Not':
        return this.TNot(_schema)
      case 'Object':
        return this.TObject(_schema)
      case 'Promise':
        return this.TPromise(_schema)
      case 'Ref':
        return this.TRef(_schema)
      case 'Tuple':
        return this.TTuple(_schema)
      case 'Union':
        return this.TUnion(_schema)
      default:
        return _schema
    }
  }
  readonly map = new Map<string, TSchema>()
  public Add<T extends TSchema> (schema: T) : T {
    if(typeof schema.$id !== 'string') return schema
    this.map.set(schema.$id!, schema)
    return schema
  }
  public Deref<T extends TSchema>(schema: T): T {
    return this.Visit(schema) as T
  }
}
```
</details>

The implementation of which would look as follows.

```typescript
// a simple demo
const typeVar = Type.Object(
  {
    foo: Type.String(),
  },
  { $id: 'T' }
)

const requiredSchema = Type.Array(Type.Ref('T'));

const schema = Type.Array(
  Type.Object({
    foo: Type.String(),
    bar: Type.Number(),
  })
);

const container = new References()  // Add typeVar to references container
container.Add(typeVar)              

const valid = Type.Extends(
  container.Deref(schema),          // explicit deref schema 
  container.Deref(requiredSchema),  // explicit deref schema 
  Type.Literal(true),
  Type.Literal(false)
);
```

---

### Status

TypeBox is currently awaiting a viable design for auto-dereferencing. An attempt was made in a previous revision of the library which proved unsuccessful (and quite error prone). The primary challenge is that TypeBox needs to monitor the state of identifiers across multiple modules, potentially resulting in unpredictable and order-dependent referential behaviors. At present, the recommended approach is to utilize JavaScript references during mapping and advocate for explicit dereferencing (as per the container implementation above). This stance will likely need to persist until a well-defined design for auto-dereferencing becomes more apparent.

Hope this helps
S

**Comment by sinclairzx81** [comment]
@ExpandOcean Hi,

I'm not sure I fully understand the context of this question, but based on 

> Both input schemas extend the required schema, but the inferred T should not have the same shape.
My question is how to get the infered typeVars(T) from the given input schemas based on the required schemas

You might be able to use Pick to select only the keys defined on the `required` schemas, and use this to infer the correct type (both statically and at runtime)

```typescript
import { Type } from '@sinclair/typebox'

const requiredP0Schema = Type.Array(Type.Object({ foo: Type.String() }))
const requiredP1Schema = Type.Object({ foo: Type.String() })

const inputP0Schema = Type.Array(Type.Object({ foo: Type.String(), bar: Type.String() }))
const inputP1Schema = Type.Object({ foo: Type.String(), dummy: Type.String() })

// typeVar (inferred type - picking keys from required type)
const typeVar0 = Type.Array(Type.Pick(inputP0Schema['items'], Type.KeyOf(requiredP0Schema['items'])))
const typeVar1 = Type.Pick(inputP1Schema, Type.KeyOf(requiredP1Schema))
```
You can try to make this generic to fit your use case, and there are other ways you can approach this (including custom mapping types), but give this a try and let me know how you go.

Cheers
S

**Comment by sinclairzx81** [comment]
@ExpandOcean Heya, 

Might close off this issue as this may be better for a [GH discussion thread](https://github.com/sinclairzx81/typebox/discussions). Quite a lot of this issue seems to relate to application specific details outside of TypeBox (and would likely require custom inference and mapping logic to achieve (although not entirely sure what to recommend based on the information so far)). 

As this would fall outside typical TypeBox usage, it's going to be better to discuss outside issue threads (as this doesn't appear to be a TypeBox issue). Discussion threads are usually a better place to discuss advanced usage patterns and application specific requirements. Hope you understand.

Cheers!
S
