### ISSUE TITLE
assignment of a schema to a function parameter of type `TSchema`originating from another module complains of missing unique symbol properties.

### ISSUE THREAD

**Issue by Gnuxie** [sinclairzx81/typebox#679]
I don't understand what is happening here myself, it's very likely that I am doing something wrong. So apologies in advance if this is not a bug, nevertheless it is concerning. 

To start I have a [library](https://github.com/Gnuxie/matrix-protection-suite/) `matrix-protection-suite` that depends on typebox that wraps the schema compiler and provides a nice utility to use it here https://github.com/Gnuxie/matrix-protection-suite/blob/main/src/Interface/Value.ts#L46-L63. 

I have another [library](https://github.com/Gnuxie/matrix-protection-suite-for-matrix-bot-sdk/) `matrix-protection-suite-for-matrix-bot-sdk` to extend the first. Creating any schema with `TSchema` within `matrix-protection-suite-for-matrix-bot-sdk`  and then trying to use the `Value` wrapper from `matrix-protection-suite` causes the following error 

```
src/SynapseAdmin/SynapseAdminClient.ts:72:7 - error TS2345: Argument of type 'TObject<{ admin: TOptional<TUnion<[TNull, TBoolean]>>; }>' is not assignable to parameter of type 'TSchema'.
  Property '[Kind]' is missing in type 'TObject<{ admin: TOptional<TUnion<[TNull, TBoolean]>>; }>' but required in type 'TSchema'.

72       SynapseAdminGetUserAdminBody,
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../matrix-protection-suite/node_modules/@sinclair/typebox/typebox.d.ts:66:5
    66     [Kind]: string;
           ~~~~~~
    '[Kind]' is declared here.

```

I suspected to begin with that this was because of some funky issue where jest/expect (which is a dev dependency of both projects) was depending on an older version of TypeBox and somehow the two dependencies were getting confused. But even after messing around with [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) in both libraries the issue persists. I don't know how file loading/module loading for typescript works, but I now suspect that somehow the same type definitions are being loaded in isolation, so that the unique symbol for `Kind` is created twice and so there is a mismatch between the `TSchema` loaded for typebox in `matrix-protection-suite-for-matrix-bot-sdk` and the one loaded  required by in the interface for `Value`'s methods within `matrix-protection-suite`. But again, that's just a theory. Wondering if you can make sense of this and whether this is a limitation with typescript or I'm just blatantly doing something silly. Thanks

And to be specific, here's the code I was using within `matrix-protection-suite-for-matrix-bot-sdk`, though any Schema would cause this problem:
  
```
export type SynapseAdminGetUserAdminBody = StaticDecode<
  typeof SynapseAdminGetUserAdminBody
>;
export const SynapseAdminGetUserAdminBody = Type.Object({
  admin: Type.Optional(Type.Union([Type.Null(), Type.Boolean()])),
});
```

```
    const decodedResult = Value.Decode(
      SynapseAdminGetUserAdminBody,
      response.ok
    );
```

**Comment by tuxado** [comment]
no ?

```
Type.Object({
    admin: Type.Optional(Type.Boolean()]),
});
```

**Comment by sinclairzx81** [comment]
@Gnuxie Hi, Sorry for the delay on this. 

It's difficult to know what to suggest here that would be specific to your libraries, however as a general rule, if you have two libraries that use TypeBox (and one library depends on the other), then both libraries will need the same version of TypeBox to avoid conflicts on `Kind`. The `Kind` is a unique symbol in TypeBox, and one where TS may interpret it as 2 distinct incompatible types if found in multiple installed versions of TypeBox.

One thing you can try is rather than taking TypeBox on as a `dependency`, you can take it on as a `peerDependency` (which decouples the exact version from each of your libraries, and allows TypeBox to be upgraded independently). Another approach is simply to ensure both of your libraries are using the `exact` version of TypeBox.

Let me know if this helps. Alternatively, if you can produce a repro of the issue (simple repository highlighting only the issue), I'd be happy to take a deeper look.

Again, sorry for the delay
S

**Comment by Gnuxie** [comment]
For context for the people getting here from search results, I had used someone else's typescript project template which gave me `rollup`. And I hadn't spent long enough reading the documentation to understand how to configure peer dependencies https://rollupjs.org/tools/#peer-dependencies. So people who encounter this issue likely are using a bundler that requires distinct configuration for peer deps to work.
