### ISSUE TITLE
No way to define custom types with proper validation

### ISSUE THREAD

**Issue by vanya2h** [sinclairzx81/typebox#681]
Hi! First of all thank you for this awesome project, I really love how it works!

I was trying to implement my own types using typebox and faced a problem with error messages generation. For example, I want to create a type that will handle values that cames from user's input e.g. `NumberInput` of Mantine UI which is returning `string | number` value. I've decided to make special type which is:

## Attempt 1:

```typescript
export type StringNumberNominal<T extends string> = (string | number) & {
  __IS_STRING_NUMBER_NOMINAL__: true
  __DISCRIMINTANT__: T
}

function BigNumber() {
  const base = Type.Union([Type.Number(), Type.String({ pattern: "^-?d+(.d+)?$" })])
  return Type.Unsafe<StringNumberNominal<typeof BigNumberFormat>>({
    ...base,
    description: "String representation of bignumber",
  })
}
```

Problems here:
- The error when validation fails is just: "Must be valid Union type"
- No way to override error message with this approach since I'm not using TypeRegistry or TypeSystem

## Attempt 2:
```typescript
const BigNumber = TypeSystem.Type<StringNumberNominal<"big-number">, NumericOptions<number>>(
  "BigNumber",
  (options, x) => {
    if (typeof x === "string" || typeof x === "number") {
      const parsed = toBn(x)
      if (!parsed.isNaN()) return true
    }
    return false
  },
)
```

Problems here:
- There's a way to define custom error message via TypeRegistry BUT with limitation that is only one error message is possible
- Does not extend any functionality from Type.String or Type.Number classes but it's clear that I want to have validation by max and min values, is integer and etc. Yes, it's possible to implement it by myself but if I will have a lot of custom types it will be a big pain

## Suggestion:
Attempt 2 is good, BUT I know how to improve it from DX perspective:
1. Centralized `TypeSystemErrorFunction` is something that brings a lot of pain.
2. Make it possible to THROW errors right inside the validation function and hoist it up. This will give you possibility to define custom error messages without any centralized thing such as `TypeSystemErrorFunction`

I'm not sure is it possible or not from the architecture perspective of typebox, but would love to chat about it with the author. 

Thank you!

**Comment by sinclairzx81** [comment]
@vanya2h Hi, thanks for the feedback,

I'll try cover off things in the sections below.

---

### Reference Implementation 

As you mentioned, it is possible to override the error message using the TypeSystemErrorFunction. This is generally achieved by introspecting the schema during error message generation (where .Errors() calls to TypeSystemErrorFunction when the value fails to check)

```typescript
import { TypeSystemErrorFunction, DefaultErrorFunction } from "@sinclair/typebox/system"
import { Type, SchemaOptions } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// ------------------------------------------------------------------
// TypeSystemErrorFunction Override
// ------------------------------------------------------------------
TypeSystemErrorFunction.Set((schema, errorType) => {
  if(schema.errorMessage) return schema.errorMessage // ... intercept errorMessage here
  return DefaultErrorFunction(schema, errorType)     // ... or just return default
})

// ------------------------------------------------------------------
// BigNumber
// ------------------------------------------------------------------
export type BigNumberFormat = string // unknown
export type StringNumberNominal<T extends string> = (string | number) & {
  __IS_STRING_NUMBER_NOMINAL__: true
  __DISCRIMINTANT__: T
}
export const BigNumber = (options: SchemaOptions = {}) => {
  const base = Type.Union([Type.Number(), Type.String({ pattern: "^-?d+(.d+)?$" })])
  const errorMessage = 'Failed to Validate BigNumber' 
  return Type.Unsafe<StringNumberNominal<BigNumberFormat>>({ errorMessage, ...options, ...base })
}

// ------------------------------------------------------------------
// BigNumber
// ------------------------------------------------------------------

const T = BigNumber()

const R = Value.Errors(T, 'foobar').First() // const R = {
                                            //   type: 61,
                                            //   schema: {
                                            //     errorMessage: 'Failed to Validate BigNumber',
                                            //     anyOf: [ [Object], [Object] ],
                                            //     [Symbol(TypeBox.Kind)]: 'Union'
                                            //   },
                                            //   path: '',
                                            //   value: 'foobar',
                                            //   message: 'Failed to Validate BigNumber'
                                            // }

console.log(R)
```

---

### Responses

> Centralized TypeSystemErrorFunction is something that brings a lot of pain.

Yes, I do agree. However keep in mind that TypeBox is a bit more orientated towards the following aspects:

- Keep Schematics, Validation and Error Generation Logic separated
- Provide hooks for framework integrators to configure validation and errors at a application wide level
- Provide relatively low level functionality that can be composed into high level functionality.

It's really these three points that make TypeBox quite a lot more verbose than other libraries. Outside of `Type.*`, good DX isn't really a design goal for TypeBox submodules (compiler, errors, etc) as these are intended to be more low level "things" integrators can combine into more DX friendly interfaces. For example, TypeBox doesn't provide a built-in `parse` function, but it's possible to build one by composing TB submodules.

```typescript
// ------------------------------------------------------------
// Integrator / Framework Code
// ------------------------------------------------------------
TypeSystemErrorFunction.Set((schema, errorType) => {
  if(schema.errorMessage) return schema.errorMessage
  return DefaultErrorFunction(schema, errorType)
})

export function Parse<T extends TSchema>(schema: T, value: unknown): Static<T> {
  const check = Value.Check(schema, value)
  if(!check) throw new Error(Value.Errors(schema, value).First()!?.message)
  return value
}
// ------------------------------------------------------------
// User Code
// ------------------------------------------------------------
const R = Parse(Type.String({ errorMessage: 'oh no!' }), 12345) // throws 'oh no!'
```

From an architectural standpoint, TypeBox sub modules are very much orientated towards being a validation backend for much larger systems. This has the unfortunate consequence of leading to more verbose API design (which isn't much fun to use (and is even less fun for me to write :D)), however the design of these modules is informed and evolved by the requirements of framework integrators...specifically the following.

- https://github.com/sinclairzx81/sidewinder
- https://elysiajs.com/concept/schema.html#local-schema
- https://feathersjs.com/api/schema/typebox.html

With this said, I think there is room to improve "how" TypeBox provides low level functionality. Historically, it's been unclear how best to improve it (due to all the different ways users need to consume the library). Because of this, the project has taken a very evolutionary approach to design based on integrator feedback, implementing necessary functionality while expending minimal efforts to make it "DX friendly". Every now and then I'll spend a bit of time consolidating new functionality (which has been dropped into the `TypeSystem` submodule (which may be partially deprecated in future)), but mostly, I feel the best strategy at this stage is to let integrators abstract TB submodules into more elegant interfaces, and just to keep design "raw" and "verbose" as this generally keeps things more flexible.

Hope this brings some insights! Happy to discuss more.
Cheers
S

**Comment by sinclairzx81** [comment]
@vanya2h Hiya,

Might close off this issue as discussions on design aspects and general DX might be better discussed on the [Discussion](https://github.com/sinclairzx81/typebox/discussions) forum. For custom type validation, just have a go with the example provided. If you have any issues there, ping on this thread and I can take a look. 

All the best!
S

**Comment by tomwidmer** [comment]
If the validation function was permitted to return any value instead of a boolean (i.e. `true | any`) then one could return the error message directly, or an error code/object that could be interpreted by a custom `TypeSystemErrorFunction`. Existing code for type registry Unsafe types would have to check for `const succeeded = checkResult === true`, but that doesn't seem like a huge deal (though thinking about it, it could cause issues for existing code that returns non-boolean values). Alternative is to return a specific object structure for an error, which can include arbitrary data for consumption by TypeSystemErrorFunction and a tag to identify that it is an error, avoiding any backwards compatibility issues with existing TypeRegistry functions.

Anyway, possible food for thought.

**Comment by sinclairzx81** [comment]
@tomwidmer Hi,

Getting a design together that solves all the use cases around custom types has been very challenging. The following is the current design (as of 0.32.0)

```typescript
import { DefaultErrorFunction, SetErrorFunction } from '@sinclair/typebox/errors'
import { Type, Kind, TypeRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// --- type and error registration
TypeRegistry.Set('Foo', (schema, value) => value === 'Foo')
TypeRegistry.Set('Bar', (schema, value) => value === 'Bar')
TypeRegistry.Set('Baz', (schema, value) => value === 'Baz')

SetErrorFunction((param) => {
  return (
    param.schema[Kind] === 'Foo' ? 'Not a Foo' : 
    param.schema[Kind] === 'Bar' ? 'Not a Bar' : 
    param.schema[Kind] === 'Baz' ? 'Not a Baz' : 
    DefaultErrorFunction(param)
  )
})

// ---

const T = Type.Unsafe({ [Kind]: 'Foo' })

console.log(Value.Errors(T, 'Bar').First()) // {
                                            //   type: 31,
                                            //   schema: { [Symbol(TypeBox.Kind)]: 'Foo' },
                                            //   path: '',
                                            //   value: 'Bar',
                                            //   message: 'Not a Foo'
                                            // }
```
There is still a requirement to register types via `[Kind]` such that they can be intercepted during error generation. The SetErrorFunction has been updated to make configuring custom types slightly more tenable, however an elegant API for custom types still proves elusive.

**Comment by tomwidmer** [comment]
AJV has a pretty powerful user defined keywords system: https://ajv.js.org/keywords.html - users have to define the code generation function as well, so user defined types are just as fast as built-in ones. I imagine you've already looked at that, and probably it's overkill!

My suggestion was just:

```typescript
import { DefaultErrorFunction, SetErrorFunction, CustomError } from '@sinclair/typebox/errors'
import { Type, Kind, TypeRegistry } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

// --- type and error registration
TypeRegistry.Set('Foo', (schema, value) => value === 'Foo' ? true : value === 'foo' ? CustomError(2) : CustomError(1))

SetErrorFunction((param) => {
  return
    param.schema[Kind] === 'Foo' ? 
      param.customError === 2 ? 
        'Foo must be capitalized' : 
        'Not a Foo' :
    DefaultErrorFunction(param)
})
```

`CustomError` would take type `any` or `unknown` as the parameter. i.e.

```typescript

export interface TCustomError {
  [Kind]: 'CustomError' // or some other way of tagging it so you can check for the type at runtime, 
                                       // could use an actual class instead to use instanceof
  error: unknown;
}

export const CustomError = (error: unknown) => {
   [Kind]: 'CustomError',
   error,
}
```
Then your code that uses TypeRegistry just needs to check 'truthy' values returned from the custom validator to see if they are CustomError values (you could use a class and use instanceof instead of  I guess).

It's up to the SetErrorFunction param to handle custom errors, if it wants to (DefaultErrorFunction would ignore them). One option for users is just to pass the required error message string directly to CustomError and just return customError directly from their SetErrorFunction, but they can pass anything, such as an i18n structure, say, with a key and param values.

Anyway, just a thought - configurable errors for UDTs would be of some use to me.
