### ISSUE TITLE
Add support for the decoder function in a transform to reject its input and return an error

### ISSUE THREAD

**Issue by redneb** [sinclairzx81/typebox#693]
Hi! Unless I am misunderstanding something, I think `Type.Transform` does not provide a way to return an error. This would have made `Type.Transform`  significantly more useful.

I think the canonical example here would be the handling of dates. Suppose you want to create a schema for handling ISO 8601 dates, i.e. dates formatted as `YYYY-MM-DD`. I would really like to be able to do something like this:
```
const ISODate =
	Type.Transform(Type.String())
		.Decode((str) => {
			const t = /^\d\d\d\d-\d\d-\d\d$/.test(str) ? Date.parse(str) : NaN;
			if (isNaN(t))
				throw Type.DecodeError("Not a valid date");
			return new Date(t);
		})
		.Encode(date => date.toISOString().substring(0, 10));
```
A workaround that I found for this case is to create a custom format with `TypeSystem.Format` that rejects invalid dates, but this is inelegant for multiple reasons:
1. You have to parse the date twice, once in the `TypeSystem.Format`'s check function and once in the decode function.
2. Only works for transforms whose the source value is of type string.

I think it is very common pattern to want to reject a value right when you try to decode it.

**Comment by sinclairzx81** [comment]
@redneb Hi,

> Unless I am misunderstanding something, I think Type.Transform does not provide a way to return an error. This would have made Type.Transform significantly more useful.

This is correct, the Encode and Decode functions will either return a valid encoded or decoded value or throw. To obtain the error you can wrap in a `try/catch`. A SafeDecode would be implemented similar to the following.

```typescript
try {
  return Value.Decode(T, value)
} catch(error) {
  return error
}
```

> A workaround that I found for this case is to create a custom format with TypeSystem.Format that rejects invalid dates, but this is inelegant for multiple reasons:

The Transform Encode and Decode functions do support throwing exceptions inside them, however the general recommendation is to try and catch structural or format problems as part of the schematic such that the functions can "trust" the value being passed to them is valid.


### Recommended

<details>
  <summary>IsDate Implementation</summary>
  
```typescript
  // https://github.com/sinclairzx81/typebox/blob/master/examples/formats/date.ts
const DAYS = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
const DATE = /^(\d\d\d\d)-(\d\d)-(\d\d)$/
function IsLeapYear(year: number): boolean {
  return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0)
}
export function IsDate(value: string): boolean {
  const matches: string[] | null = DATE.exec(value)
  if (!matches) return false
  const year: number = +matches[1]
  const month: number = +matches[2]
  const day: number = +matches[3]
  return month >= 1 && month <= 12 && day >= 1 && day <= (month === 2 && IsLeapYear(year) ? 29 : DAYS[month])
}
```
  
</details>


The following is the recommended way to transform a iso date string into a Date (see IsDate implementation above)

```typescript
import { FormatRegistry } from '@sinclair/typebox'

FormatRegistry.Set('date', IsDate)

const ISODate =
  Type.Transform(Type.String({ format: 'date' })) // only allow iso8601 date components
    .Decode(value => new Date(value)) // only executed if value is valid
    .Encode(value => value.toISOString().substring(0, 10))

Value.Decode(ISODate, '2023-12-18')  // ok: 2023-12-18T00:00:00.000Z
Value.Decode(ISODate, '2023-12-99')  // throw: "Expected string to match 'date' format"
```

### ...But Sometimes Required

There are cases where you may legitimately need to throw in the Transform. These cases will typically occur when there is no reasonable way to check the prior to decode. An example of which might be decoding a Uin8Array into a PNG data structure.

```typescript
const PNG =
  Type.Transform(Type.Uint8Array())
    .Decode(value => PNGLib.decode(value)) // expect throw if invalid
    .Encode(value => PNGLib.encode(value)) // expect throw if invalid
```
In both cases however, TypeBox will check and narrow the input based on the schema type, providing "some" assurances the value being passed in is what the decoder expects. As a general rule of thumb, the more you can narrow the input (via checks or formats, etc on the type), the less you need to rely on complex logic inside the Decode function.

Hope this brings some insights into the design of Transform types, but did you have any suggestions on how to improve the current setup? Happy to discuss more, but may be better to move to a discussion thread.

Cheers!
S

**Comment by sinclairzx81** [comment]
@redneb Hi, 

Might close off this issue as things are generally working as expected here. Again, the general rule of thumb is to detect that a value can be decoded in the schematic / format first, then just trust decoder to decode correctly based on that validated value, this generally keeps things nice and clean from an implementation standpoint. 

In the case of PNG or other non-immediately verifiable type, throwing inside the Decode (or Encode) is supported, but should only really be used for special cases, and perhaps balanced between the cost of handling decoding outside a transform entirely. The approaches to implementation can vary, but it's a call best left to developers. 

Happy to continue discussing this on the [discussion](https://github.com/sinclairzx81/typebox/discussions) thread. But will close off this issue for now.

All the best
S

**Comment by redneb** [comment]
Hi @sinclairzx81 

Thanks for the detailed answer. I think I did not explain my point clearly. My post was not a question about how do handle dates in typebox. I understand how do that. My post was a feature request because I think that typebox doesn't let me do that in the way that I  think is the best. Let me explain.

Your example with date contains complicated code to determine how many days a month has and whether a year is leap or not. My point is that this is a wrong approach. I am going to call `Date.parse` inside the encode function anyway and `Date.parse` knows how to check those things. I don't want to do those check in my code, I want to rely on `Date.parse`! Here's how I do that in zod:
```
z.string().transform((value, ctx) => {
	const date = /^\d\d\d\d-\d\d-\d\d$/.test(value) ? Date.parse(value) : NaN;
	if (isNaN(date)) {
		ctx.addIssue({
			code: z.ZodIssueCode.custom,
			message: "Not a date",
		});
		return z.NEVER;
	}
	return new Date(date);
});
```
As you can see in this code snippet, the transform function can reject its input an return an error. I think this is the right approach. You only have to parse the date once. I have not been able to that with typebox. My workaround is do this:
```
const ISODateFormat = TypeSystem.Format("date", str => /^\d\d\d\d-\d\d-\d\d$/.test(str) ? !isNaN(Date.parse(str)) : false);

Type.Transform(Type.String({format: ISODateFormat}))
	.Decode(str => new Date(str))
	.Encode(date => date.toISOString().substring(0, 10)),
```
This works, but it has 2 downsides:
1. I am parsing the date twice: once in the format function and once in the encode. On the other hand, the zod code does it once. Now you might say that is not a big deal, but dates is just a contrived example. In real life applications, parsing might be expensive and I would definitely not want to do it twice.
2. Formats only work with strings. The zod solution works regardless that the transformed type is, it doesn't have to be a string.

> In the case of PNG or other non-immediately verifiable type, throwing inside the Decode (or Encode) is supported, but should only really be used for special cases, and perhaps balanced between the cost of handling decoding outside a transform entirely. The approaches to implementation can vary, but it's a call best left to developers.

I tried throwing an error but it doesn't work as expected: if the encoder function throws an error, then when I call `Value.Errors` I don't get a standard list of error as I would have expected. Instead the `ValueErrorIterator` returned contains 0 errors.

I hope that makes sense.

So (respectfully!), I think this is a valid request and deserves to be reopened. Thanks!

**Comment by redneb** [comment]
Here's a self-contained minimal example where throwing an error inside an the decoder part of a transform does not work:
```
const TestSchema = Type.Transform(Type.String())
	.Decode(() => {throw new Error("Invalid value")})
	.Encode(() => "dummy value");

const errors = Value.Errors(TestSchema, "");
console.log([...errors].length);
```
If you run this, you will see it prints `0`.

**Comment by sinclairzx81** [comment]
@redneb Thanks for the follow up and clarification. Let me try and expand a bit further on Transform types.

```typescript
const TestSchema = Type.Transform(Type.String())
  .Decode(() => {throw new Error("Invalid value")})
  .Encode(() => "dummy value");

const errors = Value.Errors(TestSchema, "")
console.log([...errors].length)
```
This is expected. Transforms are not tied to schema error generation (so they don't report diagnostic errors derived from schematics), rather they are latent "runtime only" operations applied to values and only run after successful validation, and whose errors can only reasonably be caught via try/catch.

As suggested previously, in best cases, if a schema validation phase passes with 0 errors, the subsequent Transform Decode function is expected to succeed with 0 errors thrown. This is a core basis for Transforms in TypeBox where schematics should encode (as best as possible), the structure and format of data provided as an input to a transform function. By encoding information in the schematic, you can both obtain diagnostic errors as well as potentially mitigate expensive "parse" operations. 

As noted however, you can still throw exceptions inside Transform types. Both Decode and Encode will throw on either schema validator or transform error, meaning you can catch both kinds of error using standard `try/catch` blocks. The implementation of both TB and Zod are largely equivalent in this regard.

The following implements the reference Date transform using `Date.parse()` for Zod and TypeBox

---

### Zod

```typescript
import * as z from 'zod'

const T = z.string()
  .transform(value => {
    const timestamp = /^\d\d\d\d-\d\d-\d\d$/.test(value) ? Date.parse(value) : NaN;
    if(Number.isNaN(timestamp)) throw Error('Not a date')
    return new Date(timestamp)
  })

try {
  T.parse('2020-10-foo')
} catch(error) {
 console.log(error) // Error: Not a date
}

```
---

### TypeBox
```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const T = Type.Transform(Type.String())
  .Decode(value => {
    const timestamp = /^\d\d\d\d-\d\d-\d\d$/.test(value) ? Date.parse(value) : NaN;
    if(Number.isNaN(timestamp)) throw Error('Not a date')
    return new Date(timestamp)
  }).Encode(value => value.toISOString().slice(0, 10))

try {
  Value.Decode(T, '2020-10-foo')
} catch(error) {
  console.log(error) // TransformDecodeError: Not a date
}
```

---

### Revision 0.32.0

In addition to the above, Revision 0.32.0 exposes the internal `TransformDecodeError` as an import, meaning you can use this error to differentiate between schema validation phase and transform phase errors.

```typescript
import { Type, TypeBoxError } from '@sinclair/typebox'
import { Value, TransformDecodeError } from '@sinclair/typebox/value'

// TypeBox
const T = Type.Transform(Type.String())
  .Decode(value => {
    const timestamp = /^\d\d\d\d-\d\d-\d\d$/.test(value) ? Date.parse(value) : NaN;
    if(Number.isNaN(timestamp)) throw Error('Not a date')
    return new Date(timestamp)
  }).Encode(value => value.toISOString().slice(0, 10))

try {
  Value.Decode(T, value)
} catch(error) {
  if(error instanceof TransformDecodeError) {
    console.log('was a transform phase error')
  } else if(error instanceof TypeBoxError) {
    console.log('was a schema phase error')
    const E = [...Value.Errors(T, value)] // length greater than 0
  } else {
    console.log('unknown error')
  }
}
```

---

### Summary

I do certainly appreciate the desire to get both schema and transform errors out of `[...Errors()]` in a uniform way. The issue is, TypeBox decouples schematics from logic by design and treats Transforms as auxiliary functions far removed from Json Schema. This is different to Zod which couples logic and schematics together, making parsing values more "intuitive" at a library level, but comes at the expense of being less tied to a formal specification.

For now at least, I'm going to keep on with the current decoupled architecture (and the 0.32.0 update to expose specific errors) as the preference is still to encourage schema level validation prior to Decode. I may revisit at a later time, but note the updates required to include Transform errors in Errors() would be vast, and would extend all the way to Check() and would likely implicate performance. Noting most of the inefficiencies in Zod can largely be attributed to it's coupled "all in" architecture.

https://moltar.github.io/typescript-runtime-type-benchmarks/

I hope this brings more insights, happy to discuss more (although it's best discussed in GH discussion threads rather than issues). Will mark as "consideration" for now, but feel the issue is best closed as the reference Date type is representable under the current architecture.

Cheers
S
