### ISSUE TITLE
Discriminated union

### ISSUE THREAD

**Issue by thibauds** [sinclairzx81/typebox#704]
The following TS code is valid:

```ts
export enum Disc {
  USER = 'user',
  PONEY = 'poney',
  ROCK = 'rock',
}

type Moving = {
  id: string
  disc: Disc.USER | Disc.PONEY
}

type Inert = {
  disc: Disc.ROCK
}

export type Item = {
  name: string
}  & (Moving | Inert)


const getIdsFromItems = (items: Item[]) => {
  return items.reduce((ids: string[], current) => {
    if (current.disc !== Disc.ROCK) {
      if (!current.id) throw Error('missing id')
      if (!ids.includes(current.id)) ids.push(current.id)
    }
    return ids
  }, [])
}
```

Using the [typebox workbench](https://sinclairzx81.github.io/typebox-workbench/) I replaced type definitions with the following:

```ts
import { Type, Static } from '@sinclair/typebox'

export enum EnumDisc {
  USER = 'user',
  PONEY = 'poney',
  ROCK = 'rock'
}

export type Disc = Static<typeof Disc>
export const Disc = Type.Enum(EnumDisc)

type Moving = Static<typeof Moving>
const Moving = Type.Object({
  id: Type.String(),
  disc: Type.Union([Disc.USER, Disc.PONEY])
})

type Inert = Static<typeof Inert>
const Inert = Type.Object({
  disc: Disc.ROCK
})

export type Item = Static<typeof Item>
export const Item = Type.Intersect([
  Type.Object({
    name: Type.String()
  }),
  Type.Union([Moving, Inert])
])
```

Unfortunately the TS compiler is raising the following error on the `getIdsFromItems` function:
```
Property 'id' does not exist on type '{ name: string; } & ({ id: string; disc: any; } | { readonly disc?: any; })'.
```

Do you have any idea on how to use discriminated union with typebox to help the TS compiler distinguish the different types?

**Comment by sinclairzx81** [comment]
@thibauds Hi,

Unfortunately, this is a known limitation with TS enums. The problem is that TypeScript treats enum values as opaque, meaning they're invisible to the type system. Because they're invisible to the type system, they are also invisible to TypeBox (which is why you're seeing `any` inferred). 

There's been a few attempts to try an get constant values from TS enums in the past, unfortunately each attempt has lead to type scalability issues (and very slow inference performance for large enums). Because of this, using enum discriminators is generally not recommended (for now)

This said, you can get around this issue by not using enums, and instead using string literal values. These are observable to TypeBox, and generally are a better way to represent as discriminator properties (as they're directly encodable in Json Schema and don't require auxiliary knowledge of the enum data structure)

[Workbench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=dHlwZSBNb3ZpbmcgPSB7CiAgaWQ6IHN0cmluZwogIGRpc2M6ICd1c2VyJyB8ICdwb25leScKfQp0eXBlIEluZXJ0ID0gewogIGRpc2M6ICdyb2NrJwp9CmV4cG9ydCB0eXBlIEl0ZW0gPSB7CiAgbmFtZTogc3RyaW5nCn0gJiAoTW92aW5nIHwgSW5lcnQpCg%3D%3D)

```typescript
type Moving = {
  id: string
  disc: 'user' | 'poney'
}
type Inert = {
  disc: 'rock'
}
export type Item = {
  name: string
} & (Moving | Inert)
```
As a general rule of thumb, Enum are usually more useful for representing options, and less so for discriminator properties. For discriminators, always preference literal values if possible.

Hope this helps
S

**Comment by thibauds** [comment]
Thank you for this detailed answer :pray:
