### ISSUE TITLE
No implicit defaults on Value.Create()

### ISSUE THREAD

**Issue by pterrien** [sinclairzx81/typebox#742]
Hello,

First, please let me thank you for this excellent library. I find it quite impressive, it makes working with TS types and runtime such a breeze...

I'm facing a situation for which I may need your guidance. In my use case, I have schema definitions, that can be anything (`Type.Object()`, `Type.String()`, ...), and want to validate inputs against them.
Inputs may be partials (then I use `Value.Default()`), or `undefined` (then I use `Value.Create()`)

Here is an example:
```typescript
const T = Type.Object({
	max: Type.Number({ default: 5 }),
	per: Type.Number(),
})

const invalid1 = Value.Decode(T, Value.Default(T, { max: 2 })) // correctly throws an error, with message='Required property` and path='/per'
const invalid2 = Value.Decode(T, Value.Create(T)) // no error, because Value.Create(T) implicitly defaults to { max: 5, per: 0 }
```

Problem: As [described in the README](https://github.com/sinclairzx81/typebox#create), `Value.Create()` applies implicit defaults: 0 for `Type.Number()`, '' for `Type.String()`, ...

Question: Is there a way to **not apply** these implicit defaults? Something like a `Value.CreateStrict()`, that would ultimately fail on `Value.Decode()`, similarly to `Value.Default()`?

Thanks in advance for your help!

**Comment by sinclairzx81** [comment]
@pterrien Hi,

> Question: Is there a way to not apply these implicit defaults? Something like a Value.CreateStrict(), that would ultimately fail on Value.Decode(), similarly to Value.Default()?

The Create function is intended to instantiate a value that matches the given type, so it does need to initialize implicit defaults. The same is true for Cast. Keep in mind that Create and Cast are usually not very helpful for validation (they are more intended for data migration scenarios where you may need to instance (and fix) values due to schematic changes; this is particularly true for Cast)

The Default function however is intended for use in validation so would recommend using this if the goal is to validate. The Default function can pre-process a value prior to validation (Decode) by applying defaults for any `default` annotated type,; a lot of server frameworks use it for this purpose. The function actually replicates the Ajv `useDefaults` https://ajv.js.org/options.html#usedefaults configuration if you're familiar with it.

Um, I'm not too sure what to suggest here except perhaps consider avoiding Create, Cast during validation passes (as Default, Clean and Convert are typically the functions to use for pre-processing values). Any additional processing above Default, Clean and Convert would likely need to be custom....

```typescript
export function Parse<T extends TSchema>(schema: T, value: unknown) {
  const converted = Value.Convert(T, value)
  const defaulted = Value.Default(T, converted)
  const cleaned = Value.Clean(T, defaulted)
  // todo: additional custom processing of the value here.
  return Value.Decode(schema, cleaned)
}
```
The above is the intended usage for these functions and will error if the value is incorrect by the time it reaches the Decode call. It should be possible to apply custom logic prior to the Decode call if you need it.

Hope this helps
S

**Comment by pterrien** [comment]
> TypeBox can't really assume anything, but you should be able to get some use out of Default based on the above.

This totally makes sense, and using `default` on the object is indeed far more rigorous and elegant than my ugly workaround... :)

> if you do need something specific, you can implement functions from scratch (just check the way TB implements the current Value.* functions for an example on how to approach that (most are written using visitor patterns))

I will definitely have a look, even though using `default` will probably cover my needs.

> Again, hope this helps!

A lot, I sincerely thank you for your kind help!

**Comment by sinclairzx81** [comment]
@pterrien All good :)

Will go ahead and close up this issue for now.

All the best!
S
