### ISSUE TITLE
Support for discriminator

### ISSUE THREAD

**Issue by Baptiste-Garcin** [sinclairzx81/typebox#760]
Hi there !

I haven't found any information about a possible support for discriminator in Union types although it is [now supported by AJV](https://ajv.js.org/json-schema.html#discriminator).

Did I miss something ?
I understand that it's OpenAPI feature and not a JSON schema one but do you think, it's a possible evolution for TypeBox ?

Cheers

**Comment by sinclairzx81** [comment]
@Baptiste-Garcin Hi,

TypeBox won't support a DiscrimatedUnion type because it's not part of the Json Schema specification. Ajv does provide support for it, but it needs to be enabled to use (and it's still outside the specification). Note also that TypeScript doesn't have a representation of DiscriminatedUnion either. As it has a structural type system, it has features to deduce a union variant through control flow checks.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeAEE4AXhTCAdAHkRAKwwkYACgRS4FoZgBcGzJoAywGBigEuxhkoYBKHP344ABFgFhIoUA4iaHMLADd3AFcMWzR7ADlEkBFXYx8pcny5BXgAITU7DB19QxMzCzgrFMrHZ1d3T1Lff0CQsIiQKJgYhoSuZNStfAj2AHM8gqL5RTgAYQq0qt0DI1NYxuFJ+ycXNw8GVe64AODQ8Mj2aKh9sYmW0ogILgwCdgXCmTFFYAVQ2WmB7GA8mMAG0lDhSjhVgBdfJSKiJTjEeSNDCKYyYqHsWz4IikAA8TQgVDgwIAfD5EPs4MAqATIfJNE01Kp1AwuoykNdAuSALRreQwWhcOAAMS4EAA7msABaGADWMga2rghM5rwwOqNNzFcAAaklDaE8FKOLNmeQCkA)

```typescript
import { Type, Static } from '@sinclair/typebox'

const A = Type.Object({
   type: Type.Literal('A'), // Discriminator
   value: Type.Number()
})
const B = Type.Object({
   type: Type.Literal('B'), // Discriminator
   value: Type.String()
})
const C = Type.Object({
   type: Type.Literal('C'), // Discriminator
   value: Type.Boolean()
})

const U = Type.Union([A, B, C])

function test(union: Static<typeof U>) {
    if(union.type === 'B') {  // <- Control Flow Check

        union.value           // <- Value is String
    }
}
```
If you need to represent a property in the schematic that indicates "which" property of the union variants should be used for discrimination, you can optionally add this metadata in with.

```typescript
const U = Type.Union([A, B, C], { discriminator: 'type' })
```
However, this is not required for validation (it's only usually helpful for tools that might transform a schema into code for nominal type systems)

Will close off this issue for now as this functionality is largely out of scope.
Cheers
S
