### ISSUE TITLE
[Improvement] Usage of CHANGELOG

### ISSUE THREAD

**Issue by Divlo** [sinclairzx81/typebox#79]
Hey :wave:,

Thank you for this awesome `npm` package! :smile: 
To ease the update of the dependency and clarify what changed between release, there should be a `CHANGELOG.md` file **OR** usage of GitHub releases with notable changes as description, this could be auto-generated, with strong commit convention.

See: https://keepachangelog.com/

**Comment by sinclairzx81** [comment]
@Divlo Hey thank you for the suggestion. I will look into this for future releases!

**Comment by sinclairzx81** [comment]
@Divlo Hi, have added a changelog.md to the project which you can find here https://github.com/sinclairzx81/typebox/blob/master/changelog.md

Current logs document the changes from `0.17.1` onwards (as a starter, and because there has been some note worthy updates between `0.16.x` and `0.17.x` which would otherwise have been missed), Will reduce the frequency of updates to the changelog to occur only on `minor` revisions and standardize on that (starting from `0.18.0`). 

Thanks for this suggestion, It should help communicate things going forward (which has been somewhat difficult to do in the past).

Many Thanks!
S
