### ISSUE TITLE
Cannot use .map() inside Union with Literal

### ISSUE THREAD

**Issue by EvHaus** [sinclairzx81/typebox#885]
I'm trying to figure out why I don't get literal types when using a `.map()` inside `T.Union()`. Consider this code:

```ts
const DATA = [{value: 'Bob'}, {value: 'Stella'}] as const;

const thing = t.Union([
	t.Literal(DATA[0].value),
	t.Literal(DATA[1].value),
])

// ✅ This gives me the correct type:
// => "Bob" | "Stella"
```

However, this doesn't work:

```ts
const DATA = [{value: 'Bob'}, {value: 'Stella'}] as const;

const thing = t.Union(
	DATA.map(({ value }) => t.Literal(value))
)

// ❌ This gives me the wrong type:
// => never
```

Is this a bug, or a limitation of typebox?

**Comment by sinclairzx81** [comment]
@EvHaus Hi,

> Is this a bug, or a limitation of typebox?

It's neither. The issue is that DATA.map returns an array but where TypeBox expects a fixed size tuple for Union (and other types). Your first example works because you have explicitly passed an array with a known size (which TypeScript can observe as a tuple), the second example does not as the .map() function returns an array where interior elements are taken as a union. Consider.

```typescript
const A = [1, 2, 3, 4] as const   // type A = readonly [1, 2, 3, 4]

const B = A.map(value => value)   // type B = (1 | 2 | 3 | 4)[]  - (no longer a tuple)
```
Here is the equivalent when mapping for TLiteral types. 

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFJIR2LeABEAgshVwAvHADaCAG4EuAVwwAuRgCEIIhuRwGjpiw3wYuPOwF04BFnDkFGABuGUDFOAA1FQAlAEkVADlkXC04VXUAOhACMAAKPKRDEwwKAEotAD4UYUyAGWAYDCgjPOLTMor+fjgACwh9ZqjYhOTcKW6JnuQGppauAB4AImsRJbgAHzgltw8CJcqdHzgAWhO4OM5oKAwSGCmp3RnG5qMFhlWGSpxnubfXJp7L4+M5wADC11uMCAA)

```typescript
const DATA = [{value: 'Bob'}, {value: 'Stella'}] as const;

const VARIANTS = DATA.map(({ value }) => Type.Literal(value)) // hover VARIANTS
//
// TLiteral<"Bob" | "Stella">[]  -- Incorrect
//
// [TLiteral<'Bob'>, TLiteral<'Stella'>] -- Correct
```

---

TypeBox does not support the `TLiteral<"Bob" | "Stella">[]` form as it's very expensive to derive the constituents of `"Bob" | "Stella"` within the type system. The solution instead is to write a little bit of type level programming that maps each element of DATA 1 by 1 which proves the compiler both the mapping and size of the array (making it a tuple). The following achieves this.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUBlgwZQCGANnAL5wBmUEIcA5AAIDOwAdgManHBQB6GOgwAjCAA9GAKGkCBcALTKVqteo2at2nbuVyFAEWIxiyCPkIlSyAK5hSGA0r2u37j6tnDMcAKKOIBgc8AC8iHAAbmS2GABccKwwUJwA5pSy8igAFsCscHlwxHAAdCDEYAAUAJRwEJgkMMAQHAWtMNkYcD5drKhJGCDSPSjGpuaWRGR2DhgAPGPFGBKEHAAm+QGDwTAA2gC6OABKGKy2pPDLqxt4BFOkB3DhBwB8T3CV0nBwi3BXwTddpxqEQ4Lg-isAZtAjscCV4cDQUcIddodsQgd9l9vnAAPyjExmCx3awzRxzI44XbwkonM4XHDISbWOa4XaMaKkWKMfYvXnY74JOnnGDSarSai2bhNFo-QkTEnTezk37-dZooIY3mVDAwkKsBJQDDENYtUioODU+GLfbVBLIRYKqxK2YLQlvBDYo0wWxQVq69EwVhlCo6vVhN5oTAlZlkMOBkqc2LVWrEfIO+XE502ZXzRZvaQUTIKTylsvl-RZPwSYjgRzOCuNps6WRcFpJH4AQWQnfeuwQSfiTAAQhBRIwKDgBzEh4wAMqEUi8Cf7Ir5NscJIAblb7fgHTS7yjGBKAFUOM0OJVHVn7mSMNfu52U0A)

```typescript
import { Type, TLiteral } from '@sinclair/typebox'

// --------------------------------------------------------------------------------
// DataToLiteralTuple
// --------------------------------------------------------------------------------

type Element = { value: string }

// This is a .map() operation in the type system
type TDataToLiteralTuple<Data extends Element[], Result extends TLiteral[] = []> = (
  Data extends [infer L extends Element, ...infer R extends Element[]]
    ? TDataToLiteralTuple<R, [...Result, TLiteral<L['value']>]>
    : Result
)
function DataToLiteralTuple<Data extends Element[]>(elements: readonly [...Data]): TDataToLiteralTuple<Data> {
  return elements.map(element => Type.Literal(element.value)) as TDataToLiteralTuple<Data> 
}

// --------------------------------------------------------------------------------
// Example
// --------------------------------------------------------------------------------

const DATA = [{value: 'Bob'}, {value: 'Stella'}] as const;

const thing = Type.Union(DataToLiteralTuple(DATA))
```

Above, you would use `DataToLiteralTuple` instead of `DATA.map` as this function returns the correct computed tuple. The above pattern is fairly common when mapping external data structures to TypeBox types, but does require a little bit of type level programming to implement correctly.

Hope this helps
S

**Comment by EvHaus** [comment]
Came to report a bug. Got an amazing TypeScript lesson instead. Thanks so much for the super fast response and detailed answer @sinclairzx81!
