### ISSUE TITLE
Should `IsValueType` guard consider `Date`?

### ISSUE THREAD

**Issue by petrkozorezov** [sinclairzx81/typebox#899]
Currently, diff for objects with dates crashed with error 'Unable to create diff edits for unknown value'.

**Comment by sinclairzx81** [comment]
@petrkozorezov Hi, sorry for the delay in reply.

Unfortunately, built in JavaScript containers (such as Map, Set) as well as Date objects are not supported by the Diff/Patch functions. The reason is because it's not possible to patch class instances. However, there may be potential to support Map and Set in future, but as of now the Diff and Patch functions are limited to only values that can be serialized as Json.

Will close up this issue as being out of scope. But happy to discuss things further if you have any follow up comments.
Cheers
S
