### ISSUE TITLE
Error when using Composite with Ref (Unable to dereference schema with $id 'undefined')

### ISSUE THREAD

**Issue by jpenna** [sinclairzx81/typebox#917]
I'm trying to create a Composite type from an Object and a Ref type, but it is returning an error.

You can check the console logs [here in this sandbox](https://codesandbox.io/p/sandbox/typebox-playground-forked-ll5wlz).

# Expectation

I think the expected behavior is for it to merge the 2 types into one.

**Comment by sinclairzx81** [comment]
@jpenna Hi,

When using Type.Ref, the schematics only hold a `$ref: '<id>'` to the target schema. What this means is when you try to Decode the associated value, the Decode function has no way to locate the target schema. Because TypeBox does not track identifiers internally, you will need to track the reference type and pass it to Decode.

```typescript
export const Composited = Type.Composite([
  Type.Object({ token: Type.String() }),
  Type.Object({ user: Type.Ref(UserPublicSchema) }),
]);

const R = Value.Decode(Composited, [UserPublicSchema], {})
//                                  ^ pass interior referenced type here
```
Many of the TypeBox functions provide a secondary overload to pass references (including Encode, Decode, Check, Default, Clean, etc). It is possible to implement mechanisms to help keep track of references (if you are making heavy use of them), but TypeBox generally leaves this as a implementation detail for users.

Looking at your types though, you may not need a Type.Ref in this case, a JavaScript reference (or variable assignment) may work better and avoids the need to track a reference.

```typescript
export const Composited = Type.Composite([
  Type.Object({ token: Type.String() }),
  Type.Object({ user: UserPublicSchema }), // using JS references may be better
]);
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
@jpenna Hiya,

Might close off this issue as things are generally working as expected here. Just be mindful that Ref types don't store the actual schema (only references to them) and that you will need to keep track of the target schemas when passing them to functions (like Decode). In most cases, it's usually going to be easier to not use Ref (and just use JS references), and where Ref is mostly used to normalize schemas, usually for publishing them.

Will close off for now, but if you have any follow up questions, feel free to ping on this thread.
All the best
S

**Comment by jpenna** [comment]
Hi @sinclairzx81

Thanks for the quick response! I understand what you are saying. The validation was done by Fastify, so I guess it wasn't passing the references over.

I changed it to use references instead. I preferred it the other way, so I'd have the "schema component" when I generated the API's client code, but that's OK.

Thanks you!
