### ISSUE TITLE
How to use Type.Partial with Type.Intersect

### ISSUE THREAD

**Issue by domsen123** [sinclairzx81/typebox#95]
Hi,

is it possible to make an Type.Partital out of an Type.Intersect?

**Comment by sinclairzx81** [comment]
@domsen123 Hi. `Type.Partial(...)` and `Type.Required(...)` are constrained to accept instances of `TObject<TProperties>` only. This constraint is there primarily due to how JSON Schema deals with intersection via `allOf` as well as some architectural design principles around compositing JSON schema.

As such, the following is disallowed is TypeBox
```typescript
const A = Type.Object({ a: Type.Number() })
const B = Type.Object({ b: Type.Number() })
const I = Type.Intersect([A, B])
const P = Type.Partial(I) // not allowed (constrained to object only)
```
But you can express `P` with the following. Example [Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAsAChZJCOxbwAgnAC8KYQDoA8iIBWGEjAAUSAgC4tmbQDkAriBEYopgJQV38xcrgAhDRsMPUNjMyQRazRbR2dXDy8fJXgABSCYkIBJdhhXFnDTAG1M7VSCWGACLlMVdxxS8srq0393AF1vORkqB05iRTg85VMAN2qHDGt8IlIAHiFMCCo4VIA+TwRZOB24fn4hjD9xrkm4AAtXDFlyWSA)
```typescript
const A = Type.Object({ a: Type.Number() })
const B = Type.Object({ b: Type.Number() })
const I = Type.Intersect([A, B])
const P = Type.Intersect([Type.Partial(A), Type.Partial(B)])
```
There are quite a few subtle reasons around this. But mostly it comes down to a JSON schema principle where composited schema constraints should be additive, never subtractive. To handle the former case, TypeBox would need to removed constraints (`required` in this case) on each intersected sub schema. In the latter, the intersection is comprised of already `partial` objects, so there's no subtraction of constraints.

Hope that help!
S

**Comment by sinclairzx81** [comment]
Closing off this issue. Feel free to reply if you have any other questions though.

Cheers
S
