### ISSUE TITLE
Possible TypeBuilder.Parse support?

### ISSUE THREAD

**Issue by dested** [sinclairzx81/typebox#96]
Is it possible to serialize a type so they may be consumed somewhere else? For example: 

```
const jsonTypeObject = {/* json version of a type */} as const;
type Type = Static<typeof jsonTypeObject>
```

The issue I am running into now is I lose the symbol upon stringify so it isn't being picked up by static properly. I believe using a string enum instead of a symbol would allow it to be picked up faithfully. Is there any desire around this usecase? Possibly solved by adding a TypeBuilder.Parse that infers the type field and adds the symbol appropriately so it can be used as a regular type?

Thoughts?

**Comment by sinclairzx81** [comment]
@dested Hi. Yes, I have considered changing the property types `kind` and `modifier` from `Symbol` to `string` in the past, but have held off primarily due to `kind` and `modifier` being non-strict schema properties (these are trivially made to vanish via `JSON.stringify(...)`). This is actually what `Type.Strict(...)` does currently. 

I'd always imagined the primary usecase for making these `string` types was not specifically to allow for remote TS codebases to statically infer from the TypeBox output schematic (encoded in JSON), but rather for the remote codebase to manually parse the schema (during a codegen pass) to build out the types in the remote language (be it TS or C# or Rust, etc). I hadn't envisioned a `Type.Parse(...)` but it is an interesting idea that is in tune with other JSON schema to TS type projects.

Happy to discuss this more if you have some thoughts around this.

**Comment by sinclairzx81** [comment]
@dested Will close off this issue as I don't think I'll be able to support direct JSON parsing in TypeBox (given TS 4.5 compiler changes). I would recommend the `json-schema-to-ts` library for type inference directly from json schema. It may be possible to unify `typebox` and `json-schema-to-ts` under a common codebase, but that codebase would need to take either project as dependencies.

Possibly something like the following.

```typescript
import { TSchema, Static } from '@sinclair/typebox'
import { JSONSchema, FromSchema } from 'json-schema-to-ts'

// Unified Static Inference
export type UnifiedStatic<T> = 
    T extends TSchema        ? Static<T> :
    T extends JSONSchema ? FromSchema<T> :
    never
```
Many Thanks
S
