### ISSUE TITLE
ts(7056) when you try to export a big union type

### ISSUE THREAD

**Issue by eugeneduda** [sinclairzx81/typebox#960]
Hi there

I tried to create a quite big union type like this:

```ts
const value = Type.Union([
  Type.Number(),
  Type.TemplateLiteral([Type.Number(), Type.Literal("%")]),
  Type.TemplateLiteral([Type.Number(), Type.Literal("vw")]),
  Type.TemplateLiteral([Type.Number(), Type.Literal("vh")]),
  Type.TemplateLiteral([Type.Number(), Type.Literal("px")]),
  Type.TemplateLiteral([Type.Literal("-"), Type.Number(), Type.Literal("%")]),
  Type.TemplateLiteral([Type.Literal("-"), Type.Number(), Type.Literal("vw")]),
  Type.TemplateLiteral([Type.Literal("-"), Type.Number(), Type.Literal("vh")]),
  Type.TemplateLiteral([Type.Literal("-"), Type.Number(), Type.Literal("px")]),
]);

const props = Type.Partial(
  Type.Object({
    v1: value,
    v2: value,
    ...
    v20: value,
  }),
);

const test1 = Type.Union([
  Type.Object({
    type: Type.Literal("t1"),
    props,
  }),
  Type.Object({
    type: Type.Literal("t2"),
    props,
  }),
  ...
  Type.Object({
    type: Type.Literal("t37"),
    props,
  }),
]);

const test1 = Type.Union([
  Type.Object({
    type: Type.Literal("l1"),
    props,
  }),
  Type.Object({
    type: Type.Literal("l2"),
    props,
  }),
  ...
  Type.Object({
    type: Type.Literal("l37"),
    props,
  }),
]);

const test = Type.Union([test1, test2]);

type Test = Static<typeof test>;
```

The `Test` type works well in this file below. 

When I add `export` before the `Test` or `test`, an error for the `test` schema is created:

`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.ts(7056) `

It can be fixed by this way:

```ts
const test: TUnion<[typeof test1, typeof test2]> = Type.Union([
  test1,
  test2,
]);
```

Is there a way to avoid explicit type notation for this case?

**Comment by sinclairzx81** [comment]
@eugeneduda Hi,

I believe the issue may be related to TS declaration generation for `.d.ts` files. When you export a TB static type without annotation, the compiler will automatically generate the type annotation for you inside the output `.d.ts` file (where the compiler generates a bunch of `import('@sinclair/typebox').TSchema` definitions matching the exported computed type(s)). 

The issue here is probably due to the computed type being excessively large, so much so it is busting through the limits of what TypeScript is willing to serialize to the `.d.ts` declaration. When you explicitly add an annotation, this should mitigate the generation of the type in the declaration, and the compiler will use your explicit type instead.

There isn't much TypeBox can do to resolve this issue, and the explicit annotation should be a reasonable fallback for exceptionally large types. Keep in mind, TemplateLiteral types can result in extremely large schematics. It may be helpful to console.log the types to inspect the generated schematics to give you an indication of how large the type is (where there is parallels between the generated schematics and the generated declarations). 

You can also use the TypeBox Workbench to generate similar large types and inspect the runtime overhead for them.

[WorkBench Link Here](https://sinclairzx81.github.io/typebox-workbench/?share=Ly8gdmlldyB0cmFuc2Zvcm0gb3B0aW9ucyBvbiB0aGUgcmlnaHQgdG8gaW5zcGVjdCBnZW5lcmF0ZWQgdHlwZQoKZXhwb3J0IHR5cGUgQnl0ZSA9IGAkezB8MX0kezB8MX0kezB8MX0kezB8MX0kezB8MX0kezB8MX0kezB8MX0kezB8MX1gCgpleHBvcnQgdHlwZSBMYXJnZSA9IHsgW0sgaW4gQnl0ZV06IEsgfQo%3D)


Will close off this issue for now as there isn't much actionable here. But if you have any follow up questions, feel free to ping on this thread.

Cheers!
S
