### ISSUE TITLE
Unable to use a union of literal as record key type after upgrading version

### ISSUE THREAD

**Issue by nivnahmias** [sinclairzx81/typebox#966]
First of all i'd like to thank the maintainers of this package, it's amazing and we use it everyday.

I've recently tried upgrading from version `0.25.20` to the latest `0.33.7` and discovered some of my records no longer worked.
These records used a union of literals as its key type in order to tightly limit the values allowed in the schema/type.

for example:
```
const allowedKeys = ['A', 'B', 'C'] as const;
const allowedKeysSchema = Type.Union(allowedKeys.map((s) => Type.Literal(s)));

const recordSchema = Type.Record(allowedKeysSchema, Type.String());
```

This works beautifully in the older version but evaluates to a `TObject<{}>` in the latest version:
<img width="627" alt="image" src="https://github.com/user-attachments/assets/ffce5740-8e59-4798-a5ad-c75fb7302897">

I was wondering if this schema is no longer possible in typebox or am I doing something wrong here?

Thank you!

**Comment by sinclairzx81** [comment]
@nivnahmias Hi,

> I was wondering if this schema is no longer possible in typebox or am I doing something wrong here?

Yes, this is still possible, however you will need to be specific on how you map from `readonly string[]` into `TLiteral[]`. The following should work on modern versions.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUBlgwZQCGANjsgKoB2wE1cAvnAGZQQhwDkAAgM7BqAY1LFgUAPQx0GAEYQAHlwBQyiRLgBabTt179Bw0ePG1GmnWoAxdiADSGVHzNaTb9x4+qMCyLDjSmCgW9DYcDk4APADKcD6E1AAmfHB8MFCCAOYA2gC6OACCQkJxCgnJeAREZHlwALxweQB89XAAFMpwcLHxGEkp2YIsRHC4peUpaRnUmTgAdAtDIwBK430VU1l5uZ1dcAD8wbShthF8kcs42QtzRUIU+IQkpJG4TblNu10AXEeWkXdPgBKZQ+PzwFgAV2EMEscBC1lOjnOPTK60m6S2HzaAGtkb8oBhiIl6KRUI0btFckDflRjojwsiYi0ELtCTBIVAGGhMHMEbjkXMQMQwG0BaggfUWjyMHNHtVSOKgcq4MQUtQMAA3IjKRiqdSuTxG42eFwAUQUxHApAwLhN9odhlUQnoaVVpFIEAA7hhEmdWtkuAUuDguAAhEPcADCXFyqpSLuoaQA3M7XfAyJ6fX7kdEhAALDDC1oIsL2ZFtTPe31nEHKRNuwkuqCJPOF4sNGVzZYYZuJSse6s5pxtovECgyObRTEzNrKoA)

```typescript
import { Type, TLiteral, TUnion } from '@sinclair/typebox'

// -----------------------------------------------------------------
// UnionFromKeys
// -----------------------------------------------------------------

export type TUnionFromKeys<S extends string[], Acc extends TLiteral[] = []> = (
  S extends [infer L extends string, ...infer R extends string[]]
    ? TUnionFromKeys<R, [...Acc, TLiteral<L>]>
    : TUnion<Acc>
)
export function UnionFromKeys<S extends string[]>(keys: readonly [...S]): TUnionFromKeys<S> {
  return Type.Union(keys.map((key) => Type.Literal(key))) as never
}

// -----------------------------------------------------------------
// Example
// -----------------------------------------------------------------

const allowedKeys = ['A', 'B', 'C'] as const;

const allowedKeysSchema = UnionFromKeys(allowedKeys)

const recordSchema = Type.Record(allowedKeysSchema, Type.String())
```

The above gets around the problem where `.map()` does not return a fixed sized tuple, consider the following.

```typescript
const allowedKeysSchema = Type.Union(allowedKeys.map((s) => Type.Literal(s)));

// where allowedKeysSchema is:
//
//    TUnion<TLiteral<"A" | "B" | "C">[]>
//
// but we need the return type to be:
//
//    TUnion<[TLiteral<'A'>, TLiteral<'B'>, TLiteral<'C'>]>
```

The `TUnionFromKeys` type/function above ensures the union variants are distributed as a tuple.

---

Previous versions of TypeBox may have been accommodating of literal values containing embedded unions. In more recent versions, this internal handling will likely have been removed due to scalability problems deriving the constituents `A`, `B` and `C` from union `A | B | C`. This had generally been a problem for very large unions, where instantiation depth limits were often being reached.

If upgrading from 0.25.20, you will either need to implement an explicit mapping type (i.e. TUnionFromKeys) or just apply a explicit annotation. The following will also work.

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBoUFUB2wE+OyAMsDBlAIYA2cAvnAGZQQhwDkAAgM7B8AYzo1gUAPQx0GAEYQAHlwBQyocT7x6dCAHcMAEwDSGVHzgBeOAG0uAQS44uAIUfcAwlwC6cGufX4mgDcqgGavnQ6+samfADKQgAWGCA0AFx4hMQAPNZwEhJwGApgdMBClL74+BAwNDBE+HDJUBjKcCgUVLR02fZcAHxY7Z2U1PR9rkMj5GM9fZ7TXgOWKDIAdASNABTaeoYmZuupYNvbfACUlitomOtd43TnFy++5vgYAG7UoRrwreooAYEslUqtbhh1gAlDCAgy7SL7GJmEEpGikDZxGBQQQAc22LyCQA)

```typescript
import { Type, TUnion, TLiteral } from '@sinclair/typebox'

const allowedKeys = ['A', 'B', 'C'] as const;

const allowedKeysSchema: TUnion<[ // explicit annotation here
  TLiteral<'A'>,
  TLiteral<'B'>,
  TLiteral<'C'>,
]> = Type.Union(allowedKeys.map((s) => Type.Literal(s))) as never

const recordSchema = Type.Record(allowedKeysSchema, Type.String());
```

Hope this helps.
S

**Comment by nivnahmias** [comment]
thank you very much for the quick and informative response!
