### ISSUE TITLE
Uncaught Error: Cannot access 'Object' before initialization

### ISSUE THREAD

**Issue by itsyoboieltr** [sinclairzx81/typebox#968]
I am trying to use typebox in my react native (expo) app. I think the error I am seeing has something to do with bundling/esm, but I am not sure.

```
Uncaught Error
Cannot access 'Object' before initialization

Source
> 1 | export * from './object.mjs';
    | ^
  2 |

node_modules/@sinclair/typebox/build/esm/type/object/index.mjs (1:1)
```

Minimal reproduction steps:

1. Clone the repository of the minimal reproduction
```sh
git clone https://github.com/itsyoboieltr/bender-stack.git --branch typebox-minimal-reprod
```
2. Change directory to the repository
```sh
cd bender-stack
```
3. Install dependencies using bun
```sh
bun i
```
4. Run the development server
```sh
bun dev
```
5. Open http://localhost:3000 in your browser to see the error message from typebox

To prove that typebox is introducing the error, I also made a branch were I commented out typebox from the code, and used manual validation instead:

1. Clone the repository of the minimal reproduction
```sh
git clone https://github.com/itsyoboieltr/bender-stack.git --branch without-typebox-working
```
2. Change directory to the repository
```sh
cd bender-stack
```
3. Install dependencies using bun
```sh
bun i
```
4. Run the development server
```sh
bun dev
```
5. Open http://localhost:3000 in your browser and see the app working without typebox

**Comment by sinclairzx81** [comment]
@itsyoboieltr Hi,

This issue is may be tied to something happening in react native tool chains. Here is the `object.mjs` code in it's entirety.

```typescript
import { CreateType } from '../create/type.mjs';
import { Kind } from '../symbols/index.mjs';
// ------------------------------------------------------------------
// TypeGuard
// ------------------------------------------------------------------
import { IsOptional } from '../guard/kind.mjs';
function RequiredKeys(properties) {
    const keys = [];
    for (let key in properties) {
        if (!IsOptional(properties[key]))
            keys.push(key);
    }
    return keys;
}
/** `[Json]` Creates an Object type */
function _Object(properties, options) {
    const required = RequiredKeys(properties);
    const schematic = required.length > 0 ? { [Kind]: 'Object', type: 'object', properties, required } : { [Kind]: 'Object', type: 'object', properties };
    return CreateType(schematic, options);
}
/** `[Json]` Creates an Object type */
export const Object = _Object; // < ---- possible problem here
```
It is possible that the creation of a `const Object = ...` may be confusing the tooling where it may be interpreting the Object variable with `globalThis.Object` (which may or may not be polyfilled for the react native environment on build, I don't know). You should be able to repo the issue without by creating a `Object` variable (uppercase) and seeing if that triggers the error. I have seen similar behaviors before, but mostly they are related to something misbehaving in a tool or plugin somewhere.

I don't think there is much TypeBox can do to resolve this (other than renaming Object to something else, which is untennable) but if there is a workaround for the tooling you use, I'd be happy to explore incorporating it into TypeBox.

Keep me posted.
S

**Comment by sinclairzx81** [comment]
@itsyoboieltr Hi!

Hey, thanks for submitting those. I am quite curious to hear what comes back on either issues/projects. Have subscribed to both and will keep an eye out. 

Will close out this issue for now as I don't think there is anything I can action in TypeBox for this, but feel free to ping on this thread if you would like me to follow up / contribute to those remote issue threads. Would be good to see TypeBox working well in React Native.

Cheers!
S
