### ISSUE TITLE
Support for conditional optional based on other value

### ISSUE THREAD

**Issue by patilanz** [sinclairzx81/typebox#969]
Hey, 

Is it possible to define property as optional based on other boolean value? Example:

```ts
export const Billing = Type.Object({
  want_billing: Type.Boolean(),
  name: Type.String(),
  surname: Type.String(),
  document: Document,
  address: Type.String(),
  email: Type.Optional(Type.String({format: 'email'})),
  phone: Type.Optional(Type.String()),
}, {additionalProperties: false});
```

all other properties should be optional or excluded if want_billing is false.

**Comment by sinclairzx81** [comment]
@patilanz Hiya,

Might close off this issue for now as the above example should do what you need. However, If you do require additional conditional schematics, have a read over that link. As mentioned, TypeBox doesn't provide validation support for conditionally schemas (mostly due to inference challenges), but they can still be constructed by passing conditional keywords as options (so long as you use a validation backend like Ajv). If you have any questions on that, feel free to ping on this thread (can probably provide a few examples if you need)

Cheers!
S

**Comment by gotenxds** [comment]
@sinclairzx81 hya, I came here for the same reason I figured out I could use a union but that does not seem enoguh for my use case as I need the generated json-schema to use if/then, you mention briefly in your answer that it would be possible to pass that into the TObject, could you elaborate?
