### ISSUE TITLE
Add changelog or create a new release for each tag

### ISSUE THREAD

**Issue by DavideViolante** [sinclairzx81/typebox#972]
Apart from changelog folder that is not updated since 8 months, I can't find any changelog for this project...

I would
- update the current changelog folder or
- create a changelog.md file or
- create a new release for each tag and add the list of changes

**Comment by robcresswell** [comment]
Came here to ask for the same thing. Its kinda problematic for such a core part of a system. Is there a way I could help here?

**Comment by sinclairzx81** [comment]
@DavideViolante @robcresswell Hiya,


> Apart from changelog folder that is not updated since 8 months, I can't find any changelog for this project... I would

Yes, option 1 works. The current change log folder has been updated with a log details all the updates for 0.32.0 and 0.33.0. You can find all the latest updates since 0.32.0 at the following URL.

https://github.com/sinclairzx81/typebox/blob/master/changelog/latest.md

The information there-in isn't particularity exciting but does detail work done on the library since 0.32.0. I've added links to the associated PR's so you can read a bit more information about the changes, and preview what's changed code wise.  Keep in mind, there hasn't been any significant changes to the library since 0.32.0 with most of the work focusing on stabilizing and optimizing the revision (which is largely why the library isn't advertising huge new features in updated changelogs). There was a very minor breaking change on 0.33.0 with respect to schema initialization, but much of 0.33.0 can be seen as a continuation of 0.32.0.

> create a new release for each tag and add the list of changes

I am planning to do this once the library reaches a 1.0 state. For now I'm very happy tracking the revision updates via PR. As I am pretty much the sole maintainer for this library, and the current setup it works for me, but do appreciate better communication with users could be better.

Have a read over what's there. I would be interested to learn of better approaches to automate the current process, so if you have any thoughts on that, would be keen to hear.

Cheers!
S

**Comment by DavideViolante** [comment]
Thanks for adding the latest changelog.
Usually the standard practice and the easiest one is to create a release on github (and a new tag will be automatically created). While creating the release, you can click the "Generate release notes" button that will automatically fill the changes for you.
The automatically text that is generated there depends on the PR you create. Usually each PR should be a single feature or single fix. Everytime you merge on main use squash and merge (I think you are already using it), so 1 commit will be created with the title of the PR. Now, if you also use conventional commits in the PR titles, the release notes will be very clear already (because they are prefixed by feat, fix, refactor, etc), and will be similar to [these](https://github.com/Automattic/mongoose/releases).

It's important to use releases or changelog in a standard way because bots like dependabot, in the opened PR, will tell you inside the PR what's changed. If the bot cannot find anything, it might be a problem for the people and companies using that library to update safely.
