### ISSUE TITLE
Feature request: functions as defaults

### ISSUE THREAD

**Issue by StephenHaney** [sinclairzx81/typebox#975]
I'd like to be able to use functions as defaults so that they can run when `Value.Create` is used.

```
// Desired syntax:
export const FileSchema = Type.Object({
  id: Type.String({ default: () => ulid() }), // arrow func
  createdDate: Type.Number({ default: Date.now }), // non-invoked function reference
});

// Later
Value.Create(FileSchema) // the defaults evaluate now
```

Desired behavior: defaults are evaluated at Value.Create time if they're a function
Actual behavior: fields with a function as default are dropped from the created object with no error or warning

**Comment by sinclairzx81** [comment]
@StephenHaney Hi, thanks for the suggestion.

Yeah, historically I had been a bit reluctant to apply non-serializable data structures (such as functions) on schematics, as well as being a bit wary of defaults potentially causing side effects. But given the usefulness (especially for identifiers and dates), tagged with TypeBox having enough internal infrastructure to support the feature, I'm going to give it test run.

I have implemented this functionality on 0.33.8. The following is now supported for Create, Default and Parse.

```typescript
// If default is a function, it is invoked on Create, Default and Parse

const T = Type.Number({ default: () => Math.random() })

const A = Value.Create(T)              // A is random

const B = Value.Default(T, undefined)  // B is random

const C = Value.Parse(T, undefined)    // C is random

console.log(A, B, C)

// Function and Constructors Do result interior closures for defaults

const F1 = Type.Function([], Type.Void(), {
  default: () => () => console.log('hello')
})

const F2 = Type.Constructor([], Type.Void(), {
  default: () => class {}
})
```

The Function and Constructor defaults are a bit unusual, but not too bad given that they would otherwise need to be assigned non-serializable schematics. 

---

Will close up this issue for now, but if you run into any issues, feel free to ping on this thread.

All the best!
S

**Comment by StephenHaney** [comment]
That's great! Thank you.

If it does turn out to be an issue to include non-serializable info in the schema, an alternative would be to at least console warn if someone attempts to use a function as a default. Because it previously silently did nothing to pass a function, I didn't notice until I saw some unexpected data in my DB.

**Comment by sinclairzx81** [comment]
@StephenHaney Hiya,

> If it does turn out to be an issue to include non-serializable info in the schema, an alternative would be to at least console warn if someone attempts to use a function as a default. Because it previously silently did nothing to pass a function, I didn't notice until I saw some unexpected data in my DB.

I wouldn't expect it to be too much of an issue. My main reservations were mostly around keeping schematics publishable (and functions applied to `default` can't be published JS functions can't serialize to Json). However on the inverse of this, there are many developers attempting to use TypeBox for much more than just schema construction and publishing, and providing features like `default` functions can help with various workloads.

The update is relatively low impact, and I am somewhat interested in finding ways to open up TypeBox a bit more to allow developers make trade-offs around non-serializable schematics. Similar considerations were had for Transform types (also non-serializable). So it's all good.

So new features like this will usually sit in the wild for a few months while I keep an eye out for any reported issues. Should any issues pop up around the feature I'll likely need to re-evaluate it, but I think this one is probably good for the long term :) (people have been asking for this functionality for a while)

All good :)
S
