### ISSUE TITLE
Composite doesn't check additionalProperties

### ISSUE THREAD

**Issue by SaltyAom** [sinclairzx81/typebox#976]
From https://github.com/elysiajs/elysia/issues/482

The following (simplified) code should have thrown an error:
```ts
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const Resource = Type.Object({
	name: Type.String()
})

const Scope = Type.Object({
	id: Type.String()
})

const model = Type.Composite([
	Type.Pick(Resource, ['name']),
	Type.Object(
		{
			associatedScopes: Type.Optional(
				Type.Array(Type.Pick(Scope, ['id']))
			)
		},
		{
			additionalProperties: false
		}
	)
])

const value = {
	name: 'string',
	associatedScopes: [
		{
			id: 'a9f10990-2593-45cf-9876-95d75649afc6',
			blahhh: 'adawdwad' // Should be invalid
		}
	]
}

// Should be false but composite doesn't check additionalProperties
console.log(Value.Check(model, value))
```

If we add the following code:
```ts
import { TypeCompiler } from '@sinclair/typebox/compiler'
console.log(TypeCompiler.Code(model))
```

We can see that composite doesn't check for additionalProperties:
```js
return function check(value) {
  return (
    (typeof value === 'object' && value !== null && !Array.isArray(value)) &&
    (typeof value.name === 'string') &&
    (value.associatedScopes !== undefined ? (Array.isArray(value.associatedScopes) && value.associatedScopes.every((value) => ((typeof value === 'object' && value !== null && !Array.isArray(value)) && (typeof value.id === 'string')))) : true)
  )
}
```

If this is not in the roadmap, feel free to close the issue. Thanks.

**Comment by sinclairzx81** [comment]
Hi @SaltyAom ! :)

So, this issue is partially related to a design aspect of TypeBox. The mapping functions Pick, Omit, Mapped, and Composite will only copy the properties from source types, but not the constraints (such as additionalProperties). The return value from these functions will always be a new TObject type with no constraints (by default). You can think of these functions in a similar way to Type.Object({...}) where constraints (i.e. options) will need to be assigned on type creation.

There's a couple of reasons why TypeBox doesn't copy over the constraints from the source object; but the main one is to try and ensure the returned JSON schematic is non-closed and ready for additional composition. Note that copying constraints can lead to some problems in some compositions (specifically allOf (Intersect)). There is some high-level info on this at the link below which largely informed the no-copy-constraint design.

https://json-schema.org/understanding-json-schema/reference/object#extending

---

Here is a fix for the reproduction code. The update was just to ensure the `AssociatedScope` had an additionalProperties constraint applied to it on Pick, the other was to apply additionalProperties to the Composite options (and not the interior Object)

```typescript
import { Type } from '@sinclair/typebox'
import { Value } from '@sinclair/typebox/value'

const Resource = Type.Object({
  name: Type.String()
})

const Scope = Type.Object({
  id: Type.String()
})

// Object mapping types such as Pick, Omit and Mapped will only copy properties from the 
// source object, but do not copy constraints (such as additionalProperties). The type 
// returned from these functions will always be a new TObject. They can be thought of
// as aliases for Type.Object({...}) where constaints are applied via options on the
// last argument. 
const AssociatedScope = Type.Pick(Scope, ['id'], {
  additionalProperties: false
})

// Composite works similar to Pick, Omit and Mapped in that it doesn't copy the
// constaints from the source objects. This type can also be thought of as an
// Type.Object({...}) where constaints are applied via options.
const model = Type.Composite([
  Type.Pick(Resource, ['name']),
  Type.Object({
    associatedScopes: Type.Optional(Type.Array(AssociatedScope))
  })
], {
  additionalProperties: false
})


const value = {
  name: 'string',
  associatedScopes: [
    {
      id: 'a9f10990-2593-45cf-9876-95d75649afc6',
      blahhh: 'adawdwad' // Should be invalid
    }
  ]
}

console.log(Value.Check(model, value))  // false
```
Hope this helps
S

**Comment by sinclairzx81** [comment]
> If this is not in the roadmap, feel free to close the issue. Thanks.

Will close off this issue for now as things should largely be working to design; but very happy to field any additional follow-up questions on this thread. I do actually think the mapping types could benefit from some better documentation. I'll see about getting a little bit of extra documentation up over the next couple of revisions.

All the best!
S
