### ISSUE TITLE
Overriding Schema Title

### ISSUE THREAD

**Issue by chuck-flowers** [sinclairzx81/typebox#980]
I've discovered an interesting issue. It seems that once the `title` for a schema is set, it can't be overridden through composition function like `Omit`.

## Steps to Reproduce

```typescript
import { Type } from  '@sinclair/typebox';

const a = Type.Object({
  x: Type.Integer(),
  y: Type.Integer(),
  z: Type.Integer()
}, {
  title: 'A'
});

const b = Type.Omit(a, ['z'], {
  title: 'B'
});

console.log({ a, b });
```

## Expected Result

```
{
  a: {
    title: 'A',
    type: 'object',
    properties: { x: [Object], y: [Object], z: [Object] },
    required: [ 'x', 'y', 'z' ],
    [Symbol(TypeBox.Kind)]: 'Object'
  },
  b: {
    title: 'B',
    type: 'object',
    properties: { x: [Object], y: [Object] },
    required: [ 'x', 'y' ],
    [Symbol(TypeBox.Kind)]: 'Object'
  }
}
```

## Actual Result

```
{
  a: {
    title: 'A',
    type: 'object',
    properties: { x: [Object], y: [Object], z: [Object] },
    required: [ 'x', 'y', 'z' ],
    [Symbol(TypeBox.Kind)]: 'Object'
  },
  b: {
    title: 'A',
    type: 'object',
    properties: { x: [Object], y: [Object] },
    required: [ 'x', 'y' ],
    [Symbol(TypeBox.Kind)]: 'Object'
  }
}
```

## Potential Root Cause

I suspect that the root cause is the ordering of `schema` and `options` on [this
line](https://github.com/sinclairzx81/typebox/blob/1aee5c0863943369c0fc07e7b9c8744c15f077ba/src/type/create/type.ts#L36)

If the ordering of the spread was reversed, I think the expected behavior would occur.

**Comment by sinclairzx81** [comment]
@chuck-flowers Hi, Thanks for reporting. I have published a fix for this on 0.33.8. 

The fix was applied to Pick, Omit, Partial and Required. I note the mapping behaviors of these types is a little unusual and may be revised in future revisions. This fix should resolve the immediate issue, however future revisions may stop mapping unknown user defined properties such as `title`, and limit the mapping to the `properties` from the source types only. That isn't the current behavior of on 0.33.x, but may be on 0.34.x. 

Will close up this issue for now, but if you run into any problems, feel free to ping on this thread.

All the best
S
