### ISSUE TITLE
StaticDecode cannot handle union of literals, while Static can

### ISSUE THREAD

**Issue by wasd171** [sinclairzx81/typebox#986]
See [this playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzjAnmApnAyjAhjYAYwBpk1Md8iARdQiAE3VNQ2zwMIFEA7epluTgAVLIQAW6ELlLChAXzgAzKBBBwA5AAEAzsD4AbXMCgB6VugBGEAB4aAUPYtwAwgFcdMNXLYBeTbgacAA+mpYO9DyecABuuAZu6DoA8ko+mP4A2hqBpBrhALpwuDquHl4g6ZkFjpHRYpLScP7pAHTJlgBWdDAAFAj2cHAA1ugoAFwi5K0AqjzAEDy9cQlJqW3SYMvxic0AfFMYrQAywDDoUPHbqwCUd-byN46mpmRslJwNUrjNiPYvQ0BowmZU83nIAG5-q95E4hB8iF8mv4EYQADwWCBKbASb57Z6vZyo2j8dBIn7+AYAwEjMaTHjoGIXKEA2FEjg0OiMMm45HsKiEEncjHkLE4xq4fFAA)

**Comment by sinclairzx81** [comment]
@wasd171 Hi,

The problem here is due to `[].map()` transforming `['a', 'b']` to `('a' | 'b')[]` (losing information about the length and sequence of elements). The problem occurs on the parameter to Union. 

```typescript
const Schema = Type.Object({
  key: Type.Union(valuesOfType.map(value => Type.Literal(value)))
  //
  //             ^ Union expects [Literal<'a'>, TLiteral<'b'>]
  //
  //               ... but map is giving (Literal<'a'>, TLiteral<'b'>)[]
})
```
Because .map() loses information about the order/sequence/length of the array, you will need to explicitly tell TypeScript how it should transform a `['a', 'b']` into `[TLiteral<'a'>, TLiteral<'b'>]`. This can be achieved with a small amount of type level programming (note the type mapping mirrors the functionality of .map)

[TypeScript Link Here](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzjAnmApnAyjAhjYAYwBpk1Md8iARdQiAE3VNQ2zwMIFEA7epluTgAVLIQAW6ELlLDysgKo9gEHrIAywGOii4ANnAC+cAGZQIIOAHIAAgGdgfPbmBQA9K3QAjCAA8rAFABbm5wALQRkVHRMbFx8QmJ0cGhSio8AGLmIDhQjgDmdgBcIkK4PAxwGQCufASqcLhQFCggIOgweYQp4Ul9-QODAZ4iaapZFrkFdgA8wnDovtoVdnB2nQUA2gC6pABK6HbVevCLywyrohJSuDtwALxwOwB8D3AAFAFwIgtL6CtPRwmHRwdS-c6rdZ5Hj5UgAOgRQJBe3B-wuaw2MJ22y+3zgAH5RspxtkpjDZntSJsEXCDkcThotDp9DN1M9ts9cd8SsIxjwZnTjjBOQBKAImWqEeo8OB8iY5TGFOaogFQrYc94AN301UOJWauAYqj0KCeNOE2xFPLlpMVs2ErwQuOaMGqUBlcgwcL5Wp1hzh0jAvr0uoer096Dhmm0uj0wd1IsTjVWPHQmp0AUMPUGOdzebCPQUdlw+Uw2fzFcrsSC9B46zg2pDhwA8iYI29NlZcFZSFYvFZtsm4LX1kEQsPVPWxJJpDzm14AFZ0GAzJ3jvFwADW6BQ1uJ-M2wmjzL0MwARLgz89GTGWWevFeOQBuHqGTkj+DTm5vCNw+dLqV3idb5t13WV93lMlCnjFs23IMVDDFHoRkoTgv2kN411CDdQJKC8zzgAAfOB7zPF9xyzFCOCIdDcDeVCiBmTwIBMbBrmkTlkKEBjCFofh0FozCehwnc8MvIiSIfcjQko7jqN4uhGAE9i6MeHi+KUpjyBYtiZ1wTkgA)

```typescript
// -----------------------------------------------------------------------
// UnionFromStrings: Type and Function are Symmetric
// -----------------------------------------------------------------------
type TUnionFromStrings<T extends string[], Result extends TSchema[] = []> = (
  T extends [infer L extends string, ...infer R extends string[]]
    ? TUnionFromStrings<R, [...Result, TLiteral<L>]>
    : TUnion<Result>
)
function UnionFromStrings<T extends string[]>(values: readonly [...T]): TUnionFromStrings<T> {
  return Type.Union(values.map(value => Type.Literal(value))) as never
}
// -----------------------------------------------------------------------
// Usage 
// -----------------------------------------------------------------------

const valuesOfType = ['a', 'b'] as const

// const Schema: TObject<{
//     key: TUnion<[TLiteral<"a">, TLiteral<"b">]>;
// }>
const Schema = Type.Object({
  key: UnionFromStrings(valuesOfType)
})

// type StaticSchema = {
//     key: "a" | "b";
// }
type StaticSchema = Static<typeof Schema>

// type StaticDecodeSchema = {
//     key: "a" | "b";
// }
type StaticDecodeSchema = StaticDecode<typeof Schema>
```
The difference you see for Static and StaticDecode is due to StaticDecode having a slightly different evaluation path internally, but the incorrect static type in either case is due to .map(), the example update resolves things for either case.

Will close off things off for now as this isn't a bug, but happy to answer any questions related to the code above on this thread. 

Cheers
S
