### ISSUE TITLE
How to validate raw json schema

### ISSUE THREAD

**Issue by woody146** [sinclairzx81/typebox#987]
I save json schema in database to validate later (because my application creates dynamic form)

When I validate with typebox, it throws error `ValueErrorsUnknownTypeError: Unknown type`

```ts
Value.Errors(
  {
    type: 'object',
    properties: {
      user: {
        type: 'string',
        minLength: 4,
      },
    },
    required: ['user'],
  },
  { user: 'abc', pass: '123' }
).First();
```
Please guide me how to fix it

**Comment by sinclairzx81** [comment]
@woody146 Hi,

TypeBox requires that all types to contain a `[Kind]` symbol property that is used to describe each type. This property is used for composition, compiler optimizations, validation optimizations and is used to assert that a type conforms to the [json schema subset](https://github.com/sinclairzx81/typebox?types-json) supported by TypeBox (the error you see is this latter assertion)

The `[Kind]` property descriptor is defined as a `symbol` to ensure the descriptor is omitted on serialization (for example by JSON.stringify). Because of this, when you save a TypeBox type to a database (or share over a network), the symbol property is lost in the process and TypeBox will be unable to identify the type when you load it back (resulting in `ValueErrorsUnknownTypeError: Unknown type`)

Here's a few options

---

### Option A: Use Ajv

Rather than using TypeCompiler or Value to validate the type, you can use Ajv instead. This works because Ajv is a full implementation of the json schema specification and does not depend on intrinsic TypeBox type descriptors.

```typescript
import Ajv from 'ajv'

// here is the type when you create it
//
const T = Type.String()                    // T = { [Kind]: 'String', type: 'string' }

// simulate serializing / deserializing from a database
//
const S = JSON.parse(JSON.stringify(T))    // { type: 'string' }

const ajv = new Ajv()

// Ajv can validate with raw schematic
//
const R = ajv.validate(S, 'hello')         // const R = true
```

---

### Option B: Use FromSchema Prototype

https://github.com/sinclairzx81/typebox/blob/master/example/prototypes/from-schema.ts

You can use the above prototype type which will parse JSON schema back into TypeBox compatible types.

```typescript
import { FromSchema } from './from-schema'

// here is the type when you create it
//
const T = Type.String()                       // const T = { [Kind]: 'String', type: 'string' }

// simulate serializing / deserializing from a database
//
const S = JSON.parse(JSON.stringify(T))       // const S = { type: 'string' }

// parse schema back into typebox type
//
const P = FromSchema(S)                       // const T = { [Kind]: 'String', type: 'string' }

// validate
//
const R = Value.Check(P, 'hello')             // const R = true
```

You will need to copy and paste the above module into your code to use it, but can be accompanied with the code you use to read schematics from the underlying database. This type is being considered for inclusion in TypeBox at a later date.

---

Just note that in both cases, if you are loading schematics from a database, you won't be able to get type inference for those types as the schematics are dynamically loaded and unseen to the TypeScript type system. In the FromSchema case above, passing dynamically loaded values will always result in `TUnknown` (even if the function is correctly parsing into the required structure). This behavior is demonstrated below.

```typescript

// Dynamic

const T = FromSchema({ type: 'string' }) // TUnknown

// Static

const T = FromSchema({ type: 'string' } as const) // TString
```

Hope this helps
S

**Comment by woody146** [comment]
Thank you so much
