### ISSUE TITLE
Avoid losing precision when converting to bigints

### ISSUE THREAD

**Issue by hpeebles** [sinclairzx81/typebox#998]
Hey!

Currently, `tryConvertBigInt` uses `BigInt(parseInt(value))` (see [here](https://github.com/sinclairzx81/typebox/blob/master/src/value/convert/convert.ts#L122)). But the `parseInt` step loses precision for large numbers.
Eg. `parseInt("12345678901234567890")` gives `12345678901234567000`, whereas BigInt("12345678901234567890") works correctly.

`parseInt` is being used because the bigint constructor doesn't work if you pass in a fractional string, eg. `BigInt("123.123")` throws an error whereas `BigInt(parseInt("123.123"))` does not.

So in order to avoid losing precision but also avoid throwing errors for fractional strings, we could skip the `parseInt` step if we know for sure that the value isn't fractional.

We could use something like `/\.|,/i.test(value)` to check if the input string may be fractional. This simply returns true if the input contains a '.' or a ','. There may well be "nicer" ways of performing this check though!

**Comment by hpeebles** [comment]
I've pushed a commit containing this change to my fork - https://github.com/hpeebles/typebox/commit/2ad051744c22b1d42690e2cd8d99724f81b5db92

I've also included 2 new tests which fail when using 0.33.11.

**Comment by sinclairzx81** [comment]
@hpeebles Hi, thanks for reporting!

Yeah, this is clearly a bug (excellent spotting). Not sure why parseInt() was being used there but this needs fixing. I have pushed an update to the `bigint` branch which updates the logic there (essentially just using a `str.split(.)[0]`) to truncate everything after the first decimal point. I also included those two tests (thanks for writing those) and these pass.

Can view updates at the link below.

https://github.com/sinclairzx81/typebox/compare/master...bigint

```typescript
function TryConvertBigInt(value: unknown) {
  const truncateInteger = (value: string) => value.split('.')[0] // replaces parseInt()
  return IsStringNumeric(value) ? globalThis.BigInt(truncateInteger(value)) : IsNumber(value) ? BigInt(value | 0) : IsValueFalse(value) ? BigInt(0) : IsValueTrue(value) ? BigInt(1) : value
}
```
Keen to merge this one in asap, but if you wanted to submit a PR that replicates the logic on the bigint branch (or implements something faster!) happy to review and merge that instead. Will leave the branch there for a day, so feel free to submit a PR if you wish, otherwise will merge the bigint branch sometime tomorrow afternoon. 

Also open to reviewing the current logic for bigint conversion (not sure the `IsStringNumeric` is ideal for the initial BigInt test, but seems to work, I'm tempted to implement a simple numeric regex specifically for BigInt)

```typescript
function IsStringBigIntLike(value: string) {
  return /^-?(0|[1-9]\d*)$/.test(value)
}
```
Again, open to thoughts!

Many thanks!
S

**Comment by hpeebles** [comment]
Thanks for the quick response!

Using split rather than `parseInt` sounds good. But I'd suggest trimming at the first instance of either '.' or ',' since some locales using ',' as their decimal separator. This is why `parseInt("123,123") returns 123.

**Comment by sinclairzx81** [comment]
> But I'd suggest trimming at the first instance of either '.' or ',' since some locales using ',' as their decimal separator. This is why parseInt("123,123") returns 123.

Yeah, this sounds good. I guess partially replicating parseInt (but for large numbers, and truncating at the string level only) would be way to go. Would you like to submit a PR for this?

**Comment by hpeebles** [comment]
Yup, I can sort that. I'll likely have it done tomorrow as I doubt I'll have time today.

**Comment by hpeebles** [comment]
I've just created the PR (#999).

Turns out the JSON spec mandates that the decimal separator must be a dot, so I think there's no need to over complicate it by also trying to support numbers that use the comma separator.
